INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('waveform-lab','basic','What is a sine wave?',ARRAY['Smooth periodic oscillation','Square wave','Sawtooth wave','Pulse wave'],0,'Sine wave: smooth, described by A·sin(2πft).',10),
('waveform-lab','basic','What is the frequency of a wave?',ARRAY['Number of cycles per second','Time for one cycle','Maximum amplitude','Phase angle'],0,'Frequency = cycles/second, measured in Hz.',10),
('waveform-lab','basic','What is the period of a wave?',ARRAY['Time for one complete cycle','Number of cycles per second','Maximum displacement','Phase difference'],0,'Period T = 1/f.',10),
('waveform-lab','basic','What is the unit of frequency?',ARRAY['Hertz (Hz)','Seconds (s)','Volts (V)','Radians (rad)'],0,'Frequency is measured in Hz.',10),
('waveform-lab','basic','What is the amplitude of a wave?',ARRAY['Maximum displacement from zero','Time for one cycle','Number of cycles','Phase angle'],0,'Amplitude = peak value.',10),
('waveform-lab','basic','What is the relationship between frequency and period?',ARRAY['f = 1/T','f = T','f = T²','f = 1/T²'],0,'Frequency and period are reciprocals.',10),
('waveform-lab','basic','What is the phase of a wave?',ARRAY['Angular position in cycle','Maximum amplitude','Frequency','Period'],0,'Phase measured in degrees or radians.',10),
('waveform-lab','basic','What is a square wave?',ARRAY['Alternates between two levels','Smooth oscillation','Linear ramp','Single pulse'],0,'Square wave: 50% duty cycle by default.',10),
('waveform-lab','basic','What is a triangular wave?',ARRAY['Linear rise and fall','Two-level alternation','Smooth curve','Single spike'],0,'Triangular wave: linear ramps up and down.',10),
('waveform-lab','basic','What is a sawtooth wave?',ARRAY['Linear rise then sharp drop','Smooth oscillation','Two levels','Symmetric ramp'],0,'Sawtooth: slow rise, fast fall (or vice versa).',10),
('waveform-lab','basic','What is the RMS value of a sine wave with amplitude A?',ARRAY['A/√2','A','A√2','A/2'],0,'RMS = A/√2 ≈ 0.707A.',10),
('waveform-lab','basic','What is the peak-to-peak value of a sine wave with amplitude A?',ARRAY['2A','A','A√2','A/2'],0,'Peak-to-peak = 2 × amplitude.',10),
('waveform-lab','basic','What is the average value of a full sine wave over one cycle?',ARRAY['0','A','A/√2','A/2'],0,'Sine wave averages to zero over a full cycle.',10),
('waveform-lab','basic','What is the average value of a half-wave rectified sine?',ARRAY['A/π','A','A/√2','A/2'],0,'Half-wave average = A/π ≈ 0.318A.',10),
('waveform-lab','basic','What is the average value of a full-wave rectified sine?',ARRAY['2A/π','A/π','A','A/√2'],0,'Full-wave average = 2A/π ≈ 0.637A.',10),
('waveform-lab','basic','What is the RMS value of a square wave with amplitude A?',ARRAY['A','A/√2','A√2','A/2'],0,'Square wave RMS = A (same as peak).',10),
('waveform-lab','basic','What is the RMS value of a triangular wave with peak A?',ARRAY['A/√3','A/√2','A','A/2'],0,'Triangular wave RMS = A/√3.',10),
('waveform-lab','basic','What is the duty cycle of a square wave?',ARRAY['Percentage of high time in one period','Frequency','Amplitude','Phase'],0,'Duty cycle = high time / period × 100%.',10),
('waveform-lab','basic','What is a pulse wave?',ARRAY['Brief excursion from a baseline','Continuous oscillation','Smooth curve','Linear ramp'],0,'Pulse: short duration high state.',10),
('waveform-lab','basic','What is the fundamental frequency?',ARRAY['Lowest frequency in a waveform','Highest frequency','Average frequency','Zero frequency'],0,'Fundamental = first harmonic.',10),
('waveform-lab','basic','What is a harmonic?',ARRAY['Integer multiple of fundamental frequency','Half the fundamental','Same as fundamental','Random frequency'],0,'Harmonics: 2f, 3f, 4f, etc.',10),
('waveform-lab','basic','What is the 2nd harmonic of 100 Hz?',ARRAY['200 Hz','50 Hz','100 Hz','300 Hz'],0,'2nd harmonic = 2 × 100 = 200 Hz.',10),
('waveform-lab','basic','What is the 3rd harmonic of 60 Hz?',ARRAY['180 Hz','30 Hz','60 Hz','120 Hz'],0,'3rd harmonic = 3 × 60 = 180 Hz.',10),
('waveform-lab','basic','What is DC offset?',ARRAY['Non-zero average value','Zero average','Maximum value','Minimum value'],0,'DC offset shifts the waveform vertically.',10),
('waveform-lab','basic','What is the frequency of a 1 ms period wave?',ARRAY['1000 Hz','100 Hz','1 Hz','10 Hz'],0,'f = 1/T = 1/0.001 = 1000 Hz.',10),
('waveform-lab','basic','What is the period of a 50 Hz wave?',ARRAY['20 ms','10 ms','50 ms','5 ms'],0,'T = 1/f = 1/50 = 20 ms.',10),
('waveform-lab','basic','What is the period of a 1 kHz wave?',ARRAY['1 ms','10 ms','0.1 ms','100 ms'],0,'T = 1/1000 = 1 ms.',10),
('waveform-lab','basic','What is the angular frequency?',ARRAY['ω = 2πf','ω = f','ω = 1/f','ω = 2π/f'],0,'Angular frequency ω = 2πf rad/s.',10),
('waveform-lab','basic','What is the phase difference between two waves?',ARRAY['Angular displacement between them','Frequency difference','Amplitude difference','Period difference'],0,'Phase difference measured in degrees/radians.',10),
('waveform-lab','basic','What does ''in phase'' mean?',ARRAY['Zero phase difference','180° phase difference','90° phase difference','360° phase difference'],0,'In phase: peaks and troughs align.',10),
('waveform-lab','basic','What does ''out of phase'' mean?',ARRAY['Non-zero phase difference','Zero phase difference','Same frequency','Same amplitude'],0,'Out of phase: peaks don''t align.',10),
('waveform-lab','basic','What is a 180° phase shift?',ARRAY['Complete inversion','No change','90° rotation','360° rotation'],0,'180° shift = inverted waveform.',10),
('waveform-lab','basic','What is a 90° phase shift?',ARRAY['Quarter cycle offset','Half cycle offset','Full cycle offset','No offset'],0,'90° = quarter wavelength displacement.',10),
('waveform-lab','basic','What is wavelength?',ARRAY['Distance for one complete cycle','Time for one cycle','Maximum amplitude','Phase angle'],0,'Wavelength λ = v/f.',10),
('waveform-lab','basic','What is the unit of wavelength?',ARRAY['Meter (m)','Hertz (Hz)','Second (s)','Volt (V)'],0,'Wavelength measured in meters.',10),
('waveform-lab','basic','What is a waveform?',ARRAY['Visual representation of signal vs time','Frequency spectrum','Phase diagram','Circuit diagram'],0,'Waveform shows amplitude over time.',10),
('waveform-lab','basic','What is a cosine wave?',ARRAY['Sine wave shifted 90° ahead','Inverted sine','Half-frequency sine','Double-frequency sine'],0,'cos(θ) = sin(θ + 90°).',10),
('waveform-lab','basic','What is the relationship between sine and cosine?',ARRAY['90° phase difference','180° phase difference','Same wave','Opposite wave'],0,'Cosine leads sine by 90°.',10),
('waveform-lab','basic','What is a composite waveform?',ARRAY['Sum of multiple sine waves','Single sine wave','Square wave only','DC signal'],0,'Any periodic wave = sum of harmonics (Fourier).',10),
('waveform-lab','basic','What is the crest factor of a sine wave?',ARRAY['√2 ≈ 1.414','1','2','0.707'],0,'Crest factor = peak/RMS = A/(A/√2) = √2.',10),
('waveform-lab','basic','What is the crest factor of a square wave?',ARRAY['1','√2','2','0.707'],0,'Square: peak = RMS, so crest factor = 1.',10),
('waveform-lab','basic','What is the form factor of a sine wave?',ARRAY['π/(2√2) ≈ 1.11','1','√2','0.707'],0,'Form factor = RMS/Average = (A/√2)/(2A/π).',10),
('waveform-lab','basic','What is noise in a signal?',ARRAY['Unwanted random fluctuations','Desired signal','DC component','Harmonic'],0,'Noise degrades signal quality.',10),
('waveform-lab','basic','What is white noise?',ARRAY['Equal power across all frequencies','Single frequency noise','Low-frequency noise','High-frequency noise'],0,'White noise: flat power spectral density.',10),
('waveform-lab','basic','What is pink noise?',ARRAY['Equal power per octave','Equal power per Hz','Single frequency','No low frequencies'],0,'Pink noise: 1/f power spectrum.',10),
('waveform-lab','basic','What is SNR?',ARRAY['Signal-to-Noise Ratio','Signal Noise Reduction','System Noise Rate','Signal Null Ratio'],0,'SNR = signal power / noise power.',10),
('waveform-lab','basic','What is the unit of SNR?',ARRAY['dB','Hz','V','W'],0,'SNR typically expressed in dB.',10),
('waveform-lab','basic','What is a carrier wave?',ARRAY['High-frequency wave modulated by signal','Low-frequency wave','DC signal','Noise signal'],0,'Carrier is modulated by information signal.',10),
('waveform-lab','basic','What is modulation?',ARRAY['Varying carrier properties with signal','Amplifying a signal','Filtering a signal','Generating noise'],0,'Modulation encodes information onto carrier.',10),
('waveform-lab','basic','What is demodulation?',ARRAY['Extracting signal from carrier','Adding carrier to signal','Filtering noise','Amplifying carrier'],0,'Demodulation recovers original signal.',10);INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('waveform-lab','intermediate','What is Fourier''s theorem?',ARRAY['Any periodic signal = sum of sinusoids','Signals are always sinusoidal','All signals are square waves','Signals have no harmonics'],0,'Fourier: periodic signals decompose into harmonics.',15),
('waveform-lab','intermediate','What is the Fourier series of a square wave?',ARRAY['Odd harmonics with 1/n amplitude','Even harmonics','All harmonics equal','No harmonics'],0,'Square wave: Σ(1/n)·sin(nωt) for odd n.',15),
('waveform-lab','intermediate','What is the Fourier series of a triangular wave?',ARRAY['Odd harmonics with 1/n² amplitude','Even harmonics','1/n amplitude','1/n³ amplitude'],0,'Triangle: Σ(1/n²)·cos(nωt) for odd n.',15),
('waveform-lab','intermediate','What is the Fourier series of a sawtooth wave?',ARRAY['All harmonics with 1/n amplitude','Odd harmonics only','1/n² amplitude','1/n³ amplitude'],0,'Sawtooth: Σ(1/n)·sin(nωt) for all n.',15),
('waveform-lab','intermediate','What is the difference between Fourier series and Fourier transform?',ARRAY['Series for periodic, transform for aperiodic','Series is faster','Transform is for DC','No difference'],0,'Fourier series: periodic signals; FT: any signal.',15),
('waveform-lab','intermediate','What is the FFT?',ARRAY['Fast algorithm to compute DFT','Fast Fourier Theorem','Frequency Filter Transform','Full Fourier Transform'],0,'FFT computes DFT in O(n log n).',15),
('waveform-lab','intermediate','What is the DFT?',ARRAY['Discrete Fourier Transform','Digital Fourier Transform','Direct Fourier Transform','Dynamic Fourier Transform'],0,'DFT: discrete version of Fourier transform.',15),
('waveform-lab','intermediate','What is the Nyquist frequency?',ARRAY['Half the sampling rate','Same as sampling rate','Twice the sampling rate','Quarter the sampling rate'],0,'Nyquist frequency = fs/2.',15),
('waveform-lab','intermediate','What is the sampling theorem?',ARRAY['Sample at ≥ 2× highest frequency','Sample at same frequency','Sample at half frequency','Sample at any rate'],0,'Nyquist-Shannon: fs ≥ 2 × fmax.',15),
('waveform-lab','intermediate','What is quantization?',ARRAY['Converting continuous values to discrete levels','Sampling a signal','Filtering a signal','Amplifying a signal'],0,'Quantization maps continuous amplitude to discrete levels.',15),
('waveform-lab','intermediate','What is the SNR of an ideal n-bit ADC?',ARRAY['6.02n + 1.76 dB','6n dB','12n dB','3n dB'],0,'Ideal ADC SNR = 6.02n + 1.76 dB.',15),
('waveform-lab','intermediate','What is THD?',ARRAY['Total Harmonic Distortion','Total Harmonic Device','True Harmonic Distortion','Total High Distortion'],0,'THD measures harmonic content relative to fundamental.',15),
('waveform-lab','intermediate','What is amplitude modulation (AM)?',ARRAY['Carrier amplitude varies with signal','Carrier frequency varies','Carrier phase varies','Carrier is suppressed'],0,'AM: amplitude of carrier modulated by signal.',15),
('waveform-lab','intermediate','What is frequency modulation (FM)?',ARRAY['Carrier frequency varies with signal','Carrier amplitude varies','Carrier phase varies','Carrier is suppressed'],0,'FM: frequency of carrier modulated by signal.',15),
('waveform-lab','intermediate','What is phase modulation (PM)?',ARRAY['Carrier phase varies with signal','Carrier amplitude varies','Carrier frequency is constant','Carrier is suppressed'],0,'PM: phase of carrier modulated by signal.',15),
('waveform-lab','intermediate','What is the modulation index in AM?',ARRAY['Ratio of signal amplitude to carrier amplitude','Ratio of frequencies','Ratio of phases','Ratio of powers'],0,'AM modulation index m = Am/Ac.',15),
('waveform-lab','intermediate','What happens when AM modulation index > 1?',ARRAY['Overmodulation causing distortion','No effect','Better signal','Lower bandwidth'],0,'Overmodulation creates envelope distortion.',15),
('waveform-lab','intermediate','What is the bandwidth of an AM signal?',ARRAY['2 × signal bandwidth','Signal bandwidth','Half signal bandwidth','4 × signal bandwidth'],0,'AM bandwidth = 2 × fm (sidebands).',15),
('waveform-lab','intermediate','What are sidebands in AM?',ARRAY['Frequencies above and below carrier','Only above carrier','Only below carrier','At carrier frequency'],0,'AM produces upper and lower sidebands.',15),
('waveform-lab','intermediate','What is DSB-SC?',ARRAY['Double Sideband Suppressed Carrier','Double Sideband Single Carrier','Direct Sideband Suppressed Carrier','Dual Sideband System Carrier'],0,'DSB-SC suppresses carrier for efficiency.',15),
('waveform-lab','intermediate','What is SSB?',ARRAY['Single Sideband','Double Sideband','Suppressed Sideband','Standard Sideband'],0,'SSB transmits one sideband only, saving bandwidth.',15),
('waveform-lab','intermediate','What is the bandwidth advantage of SSB over AM?',ARRAY['Half the bandwidth','Same bandwidth','Double bandwidth','No bandwidth'],0,'SSB uses half the bandwidth of AM.',15),
('waveform-lab','intermediate','What is the Carson''s rule for FM bandwidth?',ARRAY['BW = 2(Δf + fm)','BW = 2fm','BW = Δf','BW = fm'],0,'Carson: BW = 2(β+1)fm = 2(Δf + fm).',15),
('waveform-lab','intermediate','What is the modulation index in FM?',ARRAY['β = Δf/fm','β = Am/Ac','β = fm/fc','β = Ac/Am'],0,'FM modulation index β = frequency deviation / signal frequency.',15),
('waveform-lab','intermediate','What is frequency deviation in FM?',ARRAY['Maximum change in carrier frequency','Carrier frequency','Signal frequency','Bandwidth'],0,'Δf = peak deviation from carrier frequency.',15),
('waveform-lab','intermediate','What is the spectrum of an FM signal?',ARRAY['Bessel function sidebands','Two sidebands only','No sidebands','Single sideband'],0,'FM sideband amplitudes follow Bessel functions.',15),
('waveform-lab','intermediate','What is the bandwidth of a narrowband FM signal?',ARRAY['2 × fm (similar to AM)','2(Δf + fm)','Δf','fm'],0,'Narrowband FM (β < 0.5) has bandwidth ≈ 2fm.',15),
('waveform-lab','intermediate','What is the bandwidth of a wideband FM signal?',ARRAY['2(Δf + fm)','2fm','fm','Δf'],0,'Wideband FM follows Carson''s rule.',15),
('waveform-lab','intermediate','What is pre-emphasis in FM?',ARRAY['Boosting high frequencies before modulation','Boosting low frequencies','Reducing high frequencies','Reducing low frequencies'],0,'Pre-emphasis improves SNR for high frequencies.',15),
('waveform-lab','intermediate','What is de-emphasis in FM?',ARRAY['Attenuating high frequencies after demodulation','Boosting high frequencies','Attenuating low frequencies','Boosting low frequencies'],0,'De-emphasis restores original spectrum + reduces noise.',15),
('waveform-lab','intermediate','What is FDM?',ARRAY['Frequency Division Multiplexing','Frequency Division Modulation','Full Duplex Multiplexing','Fast Division Multiplexing'],0,'FDM: multiple signals on different carrier frequencies.',15),
('waveform-lab','intermediate','What is TDM?',ARRAY['Time Division Multiplexing','Time Division Modulation','Total Division Multiplexing','Time Domain Multiplexing'],0,'TDM: multiple signals share time slots.',15),
('waveform-lab','intermediate','What is the difference between FDM and TDM?',ARRAY['FDM uses frequency, TDM uses time','FDM is faster','TDM is analog','No difference'],0,'FDM divides bandwidth, TDM divides time.',15),
('waveform-lab','intermediate','What is a spectrum?',ARRAY['Frequency content of a signal','Time-domain representation','Phase diagram','Amplitude plot'],0,'Spectrum shows signal''s frequency components.',15),
('waveform-lab','intermediate','What is a spectrogram?',ARRAY['Time-varying frequency spectrum','Single frequency plot','Phase plot','Amplitude plot'],0,'Spectrogram: frequency vs time, color = magnitude.',15),
('waveform-lab','intermediate','What is the power spectral density?',ARRAY['Power per unit frequency','Total power','Peak power','Average power'],0,'PSD describes power distribution across frequencies.',15),
('waveform-lab','intermediate','What is a window function in signal processing?',ARRAY['Tapers signal edges to reduce spectral leakage','Increases signal amplitude','Filters noise','Generates signal'],0,'Windowing reduces sidelobes in FFT.',15),
('waveform-lab','intermediate','What is spectral leakage?',ARRAY['Energy spreads to adjacent frequencies','Signal loses power','Frequencies disappear','Phase distortion'],0,'Leakage occurs when signal doesn''t fit exactly in FFT bins.',15),
('waveform-lab','intermediate','What is the Hamming window?',ARRAY['Window function reducing sidelobes','Filter type','Modulation scheme','Coding technique'],0,'Hamming window: w(n) = 0.54 - 0.46cos(2πn/N).',15),
('waveform-lab','intermediate','What is the Hanning window?',ARRAY['Raised cosine window','Rectangular window','No window','Kaiser window'],0,'Hanning: w(n) = 0.5 - 0.5cos(2πn/N).',15),
('waveform-lab','intermediate','What is convolution?',ARRAY['Operation combining two signals','Signal addition','Signal multiplication','Signal subtraction'],0,'Convolution: (f*g)(t) = ∫f(τ)g(t-τ)dτ.',15),
('waveform-lab','intermediate','What is correlation?',ARRAY['Measure of similarity between signals','Signal addition','Signal delay','Signal filtering'],0,'Correlation finds similarity vs time shift.',15),
('waveform-lab','intermediate','What is autocorrelation?',ARRAY['Correlation of a signal with itself','Correlation of two different signals','Signal filtering','Signal delay'],0,'Autocorrelation reveals periodicity.',15),
('waveform-lab','intermediate','What is cross-correlation?',ARRAY['Correlation between two different signals','Self-correlation','Signal addition','Signal multiplication'],0,'Cross-correlation finds time delay between signals.',15),
('waveform-lab','intermediate','What is the Wiener-Khinchin theorem?',ARRAY['PSD = Fourier transform of autocorrelation','PSD = autocorrelation','PSD = signal power','PSD = FFT of signal'],0,'Wiener-Khinchin links autocorrelation and PSD.',15),
('waveform-lab','intermediate','What is a filter?',ARRAY['Removes unwanted frequencies','Amplifies all frequencies','Adds frequencies','Generates frequencies'],0,'Filters pass desired frequencies, reject others.',15),
('waveform-lab','intermediate','What is an FIR filter?',ARRAY['Finite Impulse Response','Fast Impulse Response','Full Impulse Response','Filtered Impulse Response'],0,'FIR: output depends on finite number of inputs.',15),
('waveform-lab','intermediate','What is an IIR filter?',ARRAY['Infinite Impulse Response','Internal Impulse Response','Integrated Impulse Response','Inverse Impulse Response'],0,'IIR: output depends on infinite (feedback) samples.',15),
('waveform-lab','intermediate','What is the main advantage of FIR over IIR?',ARRAY['Linear phase and unconditional stability','Fewer coefficients','Higher speed','Lower power'],0,'FIR filters can have exact linear phase.',15),
('waveform-lab','intermediate','What is the main advantage of IIR over FIR?',ARRAY['Fewer coefficients for same spec','Linear phase','Always stable','No feedback'],0,'IIR needs fewer taps but may be unstable.',15);INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('waveform-lab','advanced','What is the Laplace transform of e^(-at)u(t)?',ARRAY['1/(s+a)','1/(s-a)','s/(s+a)','a/(s+a)'],0,'Laplace: L{e^(-at)} = 1/(s+a).',20),
('waveform-lab','advanced','What is the Laplace transform of a unit step u(t)?',ARRAY['1/s','s','1/(s+1)','s+1'],0,'L{u(t)} = 1/s.',20),
('waveform-lab','advanced','What is the Laplace transform of δ(t)?',ARRAY['1','1/s','s','0'],0,'L{δ(t)} = 1.',20),
('waveform-lab','advanced','What is the Laplace transform of sin(ωt)?',ARRAY['ω/(s²+ω²)','1/(s²+ω²)','s/(s²+ω²)','ω/s'],0,'L{sin(ωt)} = ω/(s²+ω²).',20),
('waveform-lab','advanced','What is the Laplace transform of cos(ωt)?',ARRAY['s/(s²+ω²)','ω/(s²+ω²)','1/(s²+ω²)','s/ω'],0,'L{cos(ωt)} = s/(s²+ω²).',20),
('waveform-lab','advanced','What is the region of convergence (ROC)?',ARRAY['Range of s where transform converges','Range of time','Range of frequency','Range of amplitude'],0,'ROC determines stability and causality.',20),
('waveform-lab','advanced','What is a pole in the s-plane?',ARRAY['Value of s where transfer function → ∞','Value where TF = 0','Value where TF = 1','Value where TF is real'],0,'Poles determine system dynamics.',20),
('waveform-lab','advanced','What is a zero in the s-plane?',ARRAY['Value of s where transfer function = 0','Value where TF → ∞','Value where TF = 1','Value where TF is imaginary'],0,'Zeros affect transient response shape.',20),
('waveform-lab','advanced','What does a pole in the right half s-plane indicate?',ARRAY['Unstable system','Stable system','Marginally stable','Oscillatory'],0,'RHP poles cause exponential growth (instability).',20),
('waveform-lab','advanced','What does a pole on the imaginary axis indicate?',ARRAY['Marginally stable (oscillatory)','Unstable','Stable','No dynamics'],0,'Imaginary axis poles: sustained oscillation.',20),
('waveform-lab','advanced','What is the damping ratio ζ?',ARRAY['Measure of oscillation decay rate','Gain margin','Phase margin','Natural frequency'],0,'ζ < 1: underdamped; ζ = 1: critical; ζ > 1: overdamped.',20),
('waveform-lab','advanced','What is the natural frequency ωn?',ARRAY['Oscillation frequency without damping','Damped frequency','Cutoff frequency','Resonant frequency'],0,'ωn is the undamped natural frequency.',20),
('waveform-lab','advanced','What is the damped frequency ωd?',ARRAY['ωn√(1-ζ²)','ωn','ωn/ζ','ωnζ'],0,'Damped frequency = ωn × √(1-ζ²).',20),
('waveform-lab','advanced','What is the settling time for a 2nd-order system?',ARRAY['~4/(ζωn)','~1/(ζωn)','~2/(ζωn)','~8/(ζωn)'],0,'Settling time ≈ 4 time constants = 4/(ζωn).',20),
('waveform-lab','advanced','What is the peak time for a 2nd-order system?',ARRAY['π/ωd','2π/ωd','π/ωn','1/ωd'],0,'Peak time = π/ωd.',20),
('waveform-lab','advanced','What is the percent overshoot for ζ=0.5?',ARRAY['~16.3%','~0%','~50%','~100%'],0,'%OS = 100·e^(-πζ/√(1-ζ²)) ≈ 16.3% for ζ=0.5.',20),
('waveform-lab','advanced','What is the steady-state error for a type 0 system with step input?',ARRAY['1/(1+Kp)','0','∞','Kp'],0,'Type 0: ess = 1/(1+Kp) for step input.',20),
('waveform-lab','advanced','What is the steady-state error for a type 1 system with step input?',ARRAY['0','1/(1+Kp)','∞','Kv'],0,'Type 1: zero error for step input.',20),
('waveform-lab','advanced','What is the steady-state error for a type 1 system with ramp input?',ARRAY['1/Kv','0','∞','Kp'],0,'Type 1: ess = 1/Kv for ramp input.',20),
('waveform-lab','advanced','What is the velocity error constant Kv?',ARRAY['lim(s→0) sG(s)','lim(s→0) G(s)','lim(s→∞) sG(s)','lim(s→0) s²G(s)'],0,'Kv = lim(s→0) s·G(s).',20),
('waveform-lab','advanced','What is the position error constant Kp?',ARRAY['lim(s→0) G(s)','lim(s→0) sG(s)','lim(s→∞) G(s)','lim(s→0) s²G(s)'],0,'Kp = lim(s→0) G(s).',20),
('waveform-lab','advanced','What is the acceleration error constant Ka?',ARRAY['lim(s→0) s²G(s)','lim(s→0) sG(s)','lim(s→0) G(s)','lim(s→∞) s²G(s)'],0,'Ka = lim(s→0) s²·G(s).',20),
('waveform-lab','advanced','What is a root locus?',ARRAY['Plot of closed-loop poles as gain varies','Open-loop poles','Nyquist plot','Bode plot'],0,'Root locus shows pole migration with gain.',20),
('waveform-lab','advanced','What is the Nyquist criterion?',ARRAY['Encirclements of -1 determine stability','Pole locations','Zero locations','Gain margin'],0,'N = Z - P (encirclements = RHP zeros - RHP poles).',20),
('waveform-lab','advanced','What is the gain margin from a Bode plot?',ARRAY['Gain at phase crossover frequency','Gain at unity frequency','Maximum gain','Minimum gain'],0,'GM = 1/|G(jω)| at phase = -180°.',20),
('waveform-lab','advanced','What is the phase margin?',ARRAY['180° + phase at unity gain crossover','Phase at zero gain','Maximum phase','Phase at resonance'],0,'PM = 180° + ∠G(jω) at |G| = 1.',20),
('waveform-lab','advanced','What is a lead compensator?',ARRAY['Improves transient response (adds phase lead)','Improves steady-state error','Reduces bandwidth','Adds poles'],0,'Lead compensator: zero closer to origin than pole.',20),
('waveform-lab','advanced','What is a lag compensator?',ARRAY['Improves steady-state error (adds gain at low f)','Improves transient response','Increases bandwidth','Adds zeros'],0,'Lag compensator: pole closer to origin than zero.',20),
('waveform-lab','advanced','What is a PID controller?',ARRAY['Proportional + Integral + Derivative','Proportional + Integral + Delay','Phase + Inverse + Derivative','Power + Input + Display'],0,'PID: Kp + Ki/s + Kd·s.',20),
('waveform-lab','advanced','What does the P term in PID do?',ARRAY['Reduces rise time','Eliminates steady-state error','Increases damping','Adds phase lead'],0,'Proportional gain speeds up response.',20),
('waveform-lab','advanced','What does the I term in PID do?',ARRAY['Eliminates steady-state error','Reduces rise time','Increases damping','Adds phase lead'],0,'Integral action removes steady-state error.',20),
('waveform-lab','advanced','What does the D term in PID do?',ARRAY['Improves stability and reduces overshoot','Eliminates steady-state error','Reduces rise time','Adds gain at low frequency'],0,'Derivative action damps oscillations.',20),
('waveform-lab','advanced','What is state-space representation?',ARRAY['Matrix form of dynamic systems','Frequency domain','Time domain only','Laplace domain'],0,'State-space: ẋ = Ax + Bu, y = Cx + Du.',20),
('waveform-lab','advanced','What is controllability?',ARRAY['Can drive system to any state with input','Can observe all states','System is stable','System is linear'],0,'Controllable if rank of [B AB A²B...] = n.',20),
('waveform-lab','advanced','What is observability?',ARRAY['Can determine all states from output','Can control all states','System is stable','System is linear'],0,'Observable if rank of [C; CA; CA²;...] = n.',20),
('waveform-lab','advanced','What is the Cayley-Hamilton theorem?',ARRAY['Matrix satisfies its own characteristic equation','Matrix is always invertible','Matrix is symmetric','Matrix is diagonal'],0,'Cayley-Hamilton: A satisfies det(λI-A)=0.',20),
('waveform-lab','advanced','What is the Lyapunov stability criterion?',ARRAY['Find V(x) > 0 with V̇(x) < 0','Check eigenvalues only','Check poles only','Check zeros only'],0,'Lyapunov: positive definite V with negative derivative.',20),
('waveform-lab','advanced','What is a Kalman filter?',ARRAY['Optimal state estimator','Analog filter','Low-pass filter','PID controller'],0,'Kalman filter: optimal recursive estimator.',20),
('waveform-lab','advanced','What is the difference between controllability and observability?',ARRAY['Controllability: input→states; Observability: output→states','Same concept','Controllability is about output','Observability is about input'],0,'Dual concepts in state-space.',20),
('waveform-lab','advanced','What is the z-transform of a unit delay?',ARRAY['z⁻¹','z','1','z²'],0,'Unit delay in z-domain: z⁻¹.',20),
('waveform-lab','advanced','What is the z-transform of a^n u[n]?',ARRAY['z/(z-a)','1/(z-a)','z-a','z(z-a)'],0,'Z{a^n u[n]} = z/(z-a), |z| > |a|.',20),
('waveform-lab','advanced','What is the z-transform of δ[n]?',ARRAY['1','z','z⁻¹','0'],0,'Z{δ[n]} = 1.',20),
('waveform-lab','advanced','What is the z-transform of u[n]?',ARRAY['z/(z-1)','1/(z-1)','z-1','z'],0,'Z{u[n]} = z/(z-1), |z| > 1.',20),
('waveform-lab','advanced','What is the chirp Z-transform?',ARRAY['Generalized ZT for arbitrary contour','Fast ZT','Inverse ZT','Discrete ZT'],0,'Chirp ZT evaluates ZT on a spiral contour.',20),
('waveform-lab','advanced','What is the DTFT?',ARRAY['Discrete-Time Fourier Transform','Digital Time Fourier Transform','Direct Time Fourier Transform','Discrete Transform Fourier Theorem'],0,'DTFT: Fourier transform of discrete signals.',20),
('waveform-lab','advanced','What is the relationship between DTFT and Z-transform?',ARRAY['ZT evaluated on unit circle','ZT evaluated on real axis','ZT evaluated at origin','ZT evaluated at infinity'],0,'DTFT = Z(e^jω), i.e., ZT on unit circle.',20),
('waveform-lab','advanced','What is the group delay of a filter?',ARRAY['Negative derivative of phase vs frequency','Time delay of amplitude','Filter bandwidth','Filter order'],0,'Group delay = -dφ/dω, ideally constant.',20),
('waveform-lab','advanced','What is a minimum-phase system?',ARRAY['All zeros in left half s-plane','All zeros in RHP','No zeros','All poles in RHP'],0,'Minimum phase: stable and causal with minimum delay.',20),
('waveform-lab','advanced','What is an all-pass filter?',ARRAY['Flat magnitude response, varying phase','Flat phase, varying magnitude','Passes all frequencies with no change','Blocks all frequencies'],0,'All-pass: |H(jω)| = 1, phase varies.',20),
('waveform-lab','advanced','What is the Hilbert transform?',ARRAY['90° phase shifter','Low-pass filter','High-pass filter','Amplifier'],0,'Hilbert transform shifts all frequencies by -90°.',20);