INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('circuit-builder','basic','What is Ohm''s Law?',ARRAY['V = IR','V = I/R','V = IR²','V = I²R'],0,'Ohm''s Law: Voltage = Current × Resistance.',10),
('circuit-builder','basic','What is the unit of resistance?',ARRAY['Ohm (Ω)','Volt (V)','Ampere (A)','Watt (W)'],0,'Resistance is measured in ohms.',10),
('circuit-builder','basic','What is the unit of current?',ARRAY['Ampere (A)','Volt (V)','Ohm (Ω)','Farad (F)'],0,'Current is measured in amperes.',10),
('circuit-builder','basic','What is the unit of voltage?',ARRAY['Volt (V)','Ampere (A)','Ohm (Ω)','Joule (J)'],0,'Voltage is measured in volts.',10),
('circuit-builder','basic','What is the unit of power?',ARRAY['Watt (W)','Volt (V)','Ampere (A)','Ohm (Ω)'],0,'Power is measured in watts.',10),
('circuit-builder','basic','What is the power formula?',ARRAY['P = VI','P = V/I','P = I/V','P = V+I'],0,'Power = Voltage × Current.',10),
('circuit-builder','basic','What is the resistance of two 10Ω resistors in series?',ARRAY['20Ω','5Ω','10Ω','100Ω'],0,'Series: R = R1 + R2 = 20Ω.',10),
('circuit-builder','basic','What is the resistance of two 10Ω resistors in parallel?',ARRAY['5Ω','20Ω','10Ω','100Ω'],0,'Parallel: R = (R1×R2)/(R1+R2) = 5Ω.',10),
('circuit-builder','basic','What happens to current in a series circuit?',ARRAY['Same at all points','Splits at each component','Increases','Decreases'],0,'Current is constant in a series circuit.',10),
('circuit-builder','basic','What happens to voltage in a parallel circuit?',ARRAY['Same across all branches','Splits across branches','Increases','Decreases'],0,'Voltage is equal across parallel branches.',10),
('circuit-builder','basic','What is Kirchhoff''s Voltage Law (KVL)?',ARRAY['Sum of voltages around a loop = 0','Sum of currents = 0','V = IR','P = VI'],0,'KVL: algebraic sum of voltages in a loop is zero.',10),
('circuit-builder','basic','What is Kirchhoff''s Current Law (KCL)?',ARRAY['Sum of currents at a node = 0','Sum of voltages = 0','I = V/R','P = I²R'],0,'KCL: sum of currents entering a node equals sum leaving.',10),
('circuit-builder','basic','What is a short circuit?',ARRAY['Zero resistance path','High resistance path','Open circuit','Normal circuit'],0,'Short circuit has near-zero resistance.',10),
('circuit-builder','basic','What is an open circuit?',ARRAY['Infinite resistance path','Zero resistance path','Low resistance path','Normal circuit'],0,'Open circuit has infinite resistance.',10),
('circuit-builder','basic','What is the equivalent resistance of 5Ω and 15Ω in series?',ARRAY['20Ω','3.75Ω','10Ω','75Ω'],0,'Series: 5 + 15 = 20Ω.',10),
('circuit-builder','basic','What is the equivalent resistance of 6Ω and 3Ω in parallel?',ARRAY['2Ω','9Ω','18Ω','3Ω'],0,'Parallel: (6×3)/(6+3) = 2Ω.',10),
('circuit-builder','basic','What does a capacitor do in a DC circuit?',ARRAY['Blocks DC after charging','Passes DC freely','Acts as a short','Acts as a resistor'],0,'Capacitor charges then blocks DC (open circuit).',10),
('circuit-builder','basic','What does an inductor do in a DC circuit?',ARRAY['Acts as a short after steady state','Blocks DC','Acts as open circuit','Acts as a capacitor'],0,'Inductor passes DC after transient (short circuit).',10),
('circuit-builder','basic','What is the unit of capacitance?',ARRAY['Farad (F)','Henry (H)','Ohm (Ω)','Volt (V)'],0,'Capacitance is measured in farads.',10),
('circuit-builder','basic','What is the unit of inductance?',ARRAY['Henry (H)','Farad (F)','Ohm (Ω)','Ampere (A)'],0,'Inductance is measured in henries.',10),
('circuit-builder','basic','What is the formula for capacitive reactance?',ARRAY['Xc = 1/(2πfC)','Xc = 2πfC','Xc = 1/(2πfL)','Xc = 2πfL'],0,'Capacitive reactance decreases with frequency.',10),
('circuit-builder','basic','What is the formula for inductive reactance?',ARRAY['Xl = 2πfL','Xl = 1/(2πfL)','Xl = 2πfC','Xl = 1/(2πfC)'],0,'Inductive reactance increases with frequency.',10),
('circuit-builder','basic','What happens to a capacitor''s reactance as frequency increases?',ARRAY['Decreases','Increases','Stays same','Becomes zero'],0,'Xc = 1/(2πfC) → decreases with f.',10),
('circuit-builder','basic','What happens to an inductor''s reactance as frequency increases?',ARRAY['Increases','Decreases','Stays same','Becomes zero'],0,'Xl = 2πfL → increases with f.',10),
('circuit-builder','basic','What is the time constant of an RC circuit?',ARRAY['τ = RC','τ = R/C','τ = C/R','τ = R+C'],0,'Time constant = R × C.',10),
('circuit-builder','basic','What is the time constant of an RL circuit?',ARRAY['τ = L/R','τ = R/L','τ = RL','τ = R+L'],0,'Time constant = L / R.',10),
('circuit-builder','basic','What is the voltage across a capacitor after one time constant during charging?',ARRAY['63.2% of V','37% of V','100% of V','50% of V'],0,'Capacitor charges to 63.2% after one τ.',10),
('circuit-builder','basic','What is the voltage across a capacitor after one time constant during discharging?',ARRAY['36.8% of V','63.2% of V','0% of V','50% of V'],0,'Capacitor discharges to 36.8% after one τ.',10),
('circuit-builder','basic','How many time constants to fully charge a capacitor?',ARRAY['5','3','1','10'],0,'~99.3% charged after 5 time constants.',10),
('circuit-builder','basic','What is a node in a circuit?',ARRAY['Junction of two or more elements','A single element','A loop','A battery'],0,'A node is a connection point.',10),
('circuit-builder','basic','What is a mesh in a circuit?',ARRAY['A loop with no inner loops','Any loop','A node','A branch'],0,'A mesh is the simplest loop.',10),
('circuit-builder','basic','What is a branch in a circuit?',ARRAY['A path between two nodes','A loop','A node','A source'],0,'A branch is a single path between nodes.',10),
('circuit-builder','basic','What is the current through a 10Ω resistor with 20V across it?',ARRAY['2A','0.5A','200A','10A'],0,'I = V/R = 20/10 = 2A.',10),
('circuit-builder','basic','What is the voltage across a 5Ω resistor with 3A through it?',ARRAY['15V','1.67V','8V','5V'],0,'V = IR = 3×5 = 15V.',10),
('circuit-builder','basic','What is the power dissipated by a 10Ω resistor with 2A through it?',ARRAY['40W','20W','10W','4W'],0,'P = I²R = 4×10 = 40W.',10),
('circuit-builder','basic','What is the power dissipated by a 10Ω resistor with 10V across it?',ARRAY['10W','1W','100W','0.1W'],0,'P = V²/R = 100/10 = 10W.',10),
('circuit-builder','basic','What is the equivalent capacitance of two 10µF caps in series?',ARRAY['5µF','20µF','10µF','100µF'],0,'Series caps: C = (C1×C2)/(C1+C2) = 5µF.',10),
('circuit-builder','basic','What is the equivalent capacitance of two 10µF caps in parallel?',ARRAY['20µF','5µF','10µF','100µF'],0,'Parallel caps: C = C1 + C2 = 20µF.',10),
('circuit-builder','basic','What is the equivalent inductance of two 10mH inductors in series?',ARRAY['20mH','5mH','10mH','100mH'],0,'Series inductors: L = L1 + L2 = 20mH.',10),
('circuit-builder','basic','What is the equivalent inductance of two 10mH inductors in parallel?',ARRAY['5mH','20mH','10mH','100mH'],0,'Parallel inductors: L = (L1×L2)/(L1+L2) = 5mH.',10),
('circuit-builder','basic','What is a voltage divider?',ARRAY['Two resistors splitting voltage','Two resistors combining voltage','A capacitor divider','An inductor divider'],0,'Voltage divider: Vout = Vin × R2/(R1+R2).',10),
('circuit-builder','basic','What is the output of a voltage divider with R1=R2=10Ω and Vin=12V?',ARRAY['6V','12V','3V','0V'],0,'Vout = 12 × 10/(10+10) = 6V.',10),
('circuit-builder','basic','What is a current divider?',ARRAY['Two parallel resistors splitting current','Two series resistors','A voltage divider','A transformer'],0,'Current divides inversely to resistance in parallel.',10),
('circuit-builder','basic','What is the current through R1=2Ω in parallel with R2=4Ω with total current 6A?',ARRAY['4A','2A','3A','6A'],0,'I1 = I × R2/(R1+R2) = 6 × 4/6 = 4A.',10),
('circuit-builder','basic','What does a diode do?',ARRAY['Allows current in one direction','Allows current both ways','Blocks all current','Amplifies current'],0,'Diode conducts when forward-biased.',10),
('circuit-builder','basic','What is the forward voltage drop of a silicon diode?',ARRAY['~0.7V','~0.3V','~1.2V','~0V'],0,'Silicon diode drops ~0.7V when conducting.',10),
('circuit-builder','basic','What is the forward voltage drop of a germanium diode?',ARRAY['~0.3V','~0.7V','~1.2V','~0V'],0,'Germanium diode drops ~0.3V.',10),
('circuit-builder','basic','What is a Zener diode used for?',ARRAY['Voltage regulation','Rectification','Amplification','Filtering'],0,'Zener diodes regulate voltage in reverse breakdown.',10),
('circuit-builder','basic','What is rectification?',ARRAY['Converting AC to DC','Converting DC to AC','Filtering signals','Amplifying signals'],0,'Rectifiers convert AC to pulsating DC.',10),
('circuit-builder','basic','What does a half-wave rectifier use?',ARRAY['One diode','Two diodes','Four diodes','No diode'],0,'Half-wave rectifier uses a single diode.',10);INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('circuit-builder','intermediate','What is Thevenin''s theorem?',ARRAY['Any linear network = voltage source + series resistance','Any network = current source + parallel resistance','V = IR','P = VI'],0,'Thevenin: Vth + Rth equivalent.',15),
('circuit-builder','intermediate','What is Norton''s theorem?',ARRAY['Any linear network = current source + parallel resistance','Voltage source + series resistance','V = IR','I = V/R'],0,'Norton: In || Rn equivalent.',15),
('circuit-builder','intermediate','How do you find Thevenin resistance?',ARRAY['Turn off all sources, find equivalent resistance','Measure voltage','Measure current','Short the output'],0,'Deactivate sources, then calculate Rth.',15),
('circuit-builder','intermediate','How do you find Thevenin voltage?',ARRAY['Open-circuit voltage at terminals','Short-circuit current','Equivalent resistance','Source voltage'],0,'Vth = open-circuit voltage.',15),
('circuit-builder','intermediate','How do you find Norton current?',ARRAY['Short-circuit current at terminals','Open-circuit voltage','Equivalent resistance','Source current'],0,'In = short-circuit current.',15),
('circuit-builder','intermediate','What is the relationship between Thevenin and Norton equivalents?',ARRAY['Rth = Rn, Vth = In × Rn','Rth = 2×Rn','Vth = In','In = Vth'],0,'Source transformation: Vth = In × Rn.',15),
('circuit-builder','intermediate','What is maximum power transfer?',ARRAY['Load R = source R for max power','Load R = 0','Load R = ∞','Load R = 2×source R'],0,'Max power when RL = Rth.',15),
('circuit-builder','intermediate','What is the efficiency at maximum power transfer?',ARRAY['50%','100%','25%','75%'],0,'Half the power is dissipated in source resistance.',15),
('circuit-builder','intermediate','What is superposition theorem?',ARRAY['Response = sum of responses from each source individually','Sum of all voltages','Sum of all currents','Sum of all powers'],0,'Analyze each source separately, then add.',15),
('circuit-builder','intermediate','When can you use superposition?',ARRAY['Only in linear circuits','In any circuit','Only in DC circuits','Only in AC circuits'],0,'Superposition requires linearity.',15),
('circuit-builder','intermediate','What is mesh analysis?',ARRAY['Using KVL around meshes','Using KCL at nodes','Using Ohm''s law','Using Thevenin'],0,'Mesh analysis applies KVL to each mesh.',15),
('circuit-builder','intermediate','What is nodal analysis?',ARRAY['Using KCL at nodes','Using KVL around meshes','Using Ohm''s law','Using Norton'],0,'Nodal analysis applies KCL at each node.',15),
('circuit-builder','intermediate','Which method is better for circuits with many nodes but few meshes?',ARRAY['Mesh analysis','Nodal analysis','Thevenin','Superposition'],0,'Fewer meshes = fewer mesh equations.',15),
('circuit-builder','intermediate','Which method is better for circuits with many meshes but few nodes?',ARRAY['Nodal analysis','Mesh analysis','Thevenin','Superposition'],0,'Fewer nodes = fewer nodal equations.',15),
('circuit-builder','intermediate','What is a dependent source?',ARRAY['Source controlled by another circuit variable','Independent voltage source','Battery','Current source'],0,'Dependent sources depend on voltage/current elsewhere.',15),
('circuit-builder','intermediate','What are the four types of dependent sources?',ARRAY['VCVS, VCCS, CCVS, CCCS','VCVS only','Voltage and current','AC and DC'],0,'Four types: voltage/current controlled voltage/current.',15),
('circuit-builder','intermediate','Can superposition be used with dependent sources?',ARRAY['Yes, but keep dependent sources active','No','Only with independent sources','Only with voltage sources'],0,'Dependent sources are never deactivated.',15),
('circuit-builder','intermediate','What is a transfer function?',ARRAY['Output/Input in s-domain','Output × Input','Output + Input','Output - Input'],0,'H(s) = Y(s)/X(s).',15),
('circuit-builder','intermediate','What is the impedance of a resistor?',ARRAY['R','1/(sC)','sL','1/R'],0,'Resistor impedance = R (frequency independent).',15),
('circuit-builder','intermediate','What is the impedance of a capacitor in s-domain?',ARRAY['1/(sC)','sC','sL','R'],0,'Capacitor: Z = 1/(sC).',15),
('circuit-builder','intermediate','What is the impedance of an inductor in s-domain?',ARRAY['sL','1/(sL)','1/(sC)','R'],0,'Inductor: Z = sL.',15),
('circuit-builder','intermediate','What is the impedance of a resistor at DC?',ARRAY['R','0','∞','1/R'],0,'Resistor impedance is always R.',15),
('circuit-builder','intermediate','What is the impedance of a capacitor at DC?',ARRAY['∞ (open)','0 (short)','R','1/(sC)'],0,'At DC (f=0), Xc → ∞.',15),
('circuit-builder','intermediate','What is the impedance of an inductor at DC?',ARRAY['0 (short)','∞ (open)','R','sL'],0,'At DC (f=0), Xl → 0.',15),
('circuit-builder','intermediate','What is the impedance of a capacitor at very high frequency?',ARRAY['0 (short)','∞ (open)','R','1/(sC)'],0,'At f→∞, Xc → 0.',15),
('circuit-builder','intermediate','What is the impedance of an inductor at very high frequency?',ARRAY['∞ (open)','0 (short)','R','sL'],0,'At f→∞, Xl → ∞.',15),
('circuit-builder','intermediate','What is a low-pass filter?',ARRAY['Passes low frequencies, attenuates high','Passes high, attenuates low','Passes all','Attenuates all'],0,'LPF cutoff: frequencies below fc pass.',15),
('circuit-builder','intermediate','What is a high-pass filter?',ARRAY['Passes high frequencies, attenuates low','Passes low, attenuates high','Passes all','Attenuates all'],0,'HPF cutoff: frequencies above fc pass.',15),
('circuit-builder','intermediate','What is a band-pass filter?',ARRAY['Passes a range of frequencies','Passes all frequencies','Blocks all frequencies','Passes DC only'],0,'BPF passes frequencies between f_low and f_high.',15),
('circuit-builder','intermediate','What is a band-stop filter?',ARRAY['Blocks a range of frequencies','Passes a range','Passes all','Blocks all'],0,'BSF (notch filter) rejects a band.',15),
('circuit-builder','intermediate','What is the cutoff frequency of an RC low-pass filter?',ARRAY['f = 1/(2πRC)','f = 2πRC','f = RC','f = 1/(RC)'],0,'Cutoff: fc = 1/(2πRC).',15),
('circuit-builder','intermediate','What is the cutoff frequency of an RL high-pass filter?',ARRAY['f = R/(2πL)','f = 2πL/R','f = L/R','f = RL'],0,'Cutoff: fc = R/(2πL).',15),
('circuit-builder','intermediate','What is the roll-off rate of a first-order filter?',ARRAY['-20 dB/decade','-40 dB/decade','-10 dB/decade','-60 dB/decade'],0,'First-order: -20 dB/decade or -6 dB/octave.',15),
('circuit-builder','intermediate','What is the roll-off rate of a second-order filter?',ARRAY['-40 dB/decade','-20 dB/decade','-60 dB/decade','-10 dB/decade'],0,'Second-order: -40 dB/decade.',15),
('circuit-builder','intermediate','What is the Q factor of a filter?',ARRAY['Measure of selectivity/resonance sharpness','Quality of components','Power factor','Efficiency'],0,'Q = fc/BW (center freq / bandwidth).',15),
('circuit-builder','intermediate','What is bandwidth?',ARRAY['Range of frequencies passed','Single frequency','Maximum frequency','Minimum frequency'],0,'BW = f_high - f_low.',15),
('circuit-builder','intermediate','What is resonance in an RLC circuit?',ARRAY['Xl = Xc, impedance is purely resistive','Maximum resistance','Minimum current','Maximum voltage'],0,'At resonance, Xl = Xc, Z = R.',15),
('circuit-builder','intermediate','What is the resonant frequency of an RLC circuit?',ARRAY['f = 1/(2π√(LC))','f = 2π√(LC)','f = LC','f = 1/(LC)'],0,'Resonance: fr = 1/(2π√(LC)).',15),
('circuit-builder','intermediate','What is the impedance at resonance in a series RLC circuit?',ARRAY['R (minimum)','∞','0','Xl'],0,'At resonance, Z = R (minimum impedance).',15),
('circuit-builder','intermediate','What is the impedance at resonance in a parallel RLC circuit?',ARRAY['R (maximum)','0','∞','Xc'],0,'At parallel resonance, Z = R (maximum).',15),
('circuit-builder','intermediate','What happens to current at series resonance?',ARRAY['Maximum','Minimum','Zero','Infinity'],0,'Z is minimum, so current is maximum.',15),
('circuit-builder','intermediate','What happens to current at parallel resonance?',ARRAY['Minimum','Maximum','Zero','Infinity'],0,'Z is maximum, so current is minimum.',15),
('circuit-builder','intermediate','What is a Bode plot?',ARRAY['Magnitude and phase vs frequency','Time vs voltage','Current vs voltage','Power vs time'],0,'Bode plots show frequency response.',15),
('circuit-builder','intermediate','What is the gain margin in a Bode plot?',ARRAY['How much gain can increase before instability','Phase shift','Cutoff frequency','Bandwidth'],0,'Gain margin measured at phase crossover.',15),
('circuit-builder','intermediate','What is the phase margin?',ARRAY['How much phase can change before instability','Gain at cutoff','Maximum phase','Minimum phase'],0,'Phase margin measured at unity gain.',15),
('circuit-builder','intermediate','What is a decibel (dB)?',ARRAY['20 log₁₀(ratio) for voltage','10 log₁₀(ratio)','Linear ratio','Power ratio'],0,'Voltage gain in dB: 20 log₁₀(Vout/Vin).',15),
('circuit-builder','intermediate','What is the dB formula for power ratio?',ARRAY['10 log₁₀(Pout/Pin)','20 log₁₀(Pout/Pin)','Pout/Pin','log₂(Pout/Pin)'],0,'Power gain in dB: 10 log₁₀(Pout/Pin).',15),
('circuit-builder','intermediate','What is a coupling capacitor used for?',ARRAY['Blocking DC, passing AC','Blocking AC','Passing DC','Storing charge'],0,'Coupling caps block DC between stages.',15),
('circuit-builder','intermediate','What is a bypass capacitor used for?',ARRAY['Shunting AC noise to ground','Blocking DC','Passing DC','Increasing voltage'],0,'Bypass caps short AC noise to ground.',15),
('circuit-builder','intermediate','What is the input impedance of an ideal op-amp?',ARRAY['∞','0','1Ω','100Ω'],0,'Ideal op-amp has infinite input impedance.',15);INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('circuit-builder','advanced','What is the Miller effect?',ARRAY['Input capacitance multiplied by (1+Av)','Output capacitance doubled','Input resistance halved','Gain bandwidth product'],0,'Miller: Cin_effective = Cin × (1 + |Av|).',20),
('circuit-builder','advanced','What is the gain-bandwidth product (GBW)?',ARRAY['Gain × Bandwidth = constant','Gain + Bandwidth','Gain / Bandwidth','Gain² × Bandwidth'],0,'GBW is constant for an op-amp.',20),
('circuit-builder','advanced','What is the slew rate of an op-amp?',ARRAY['Maximum rate of change of output voltage','Maximum gain','Maximum input voltage','Maximum frequency'],0,'Slew rate in V/µs limits large-signal bandwidth.',20),
('circuit-builder','advanced','What causes slew rate limiting?',ARRAY['Internal compensation capacitor charging','Input impedance','Power supply','Feedback resistor'],0,'Compensation cap limits dV/dt.',20),
('circuit-builder','advanced','What is the common-mode rejection ratio (CMRR)?',ARRAY['Differential gain / Common-mode gain','Open-loop gain','Slew rate','Input bias current'],0,'CMRR = Adm/Acm, ideally ∞.',20),
('circuit-builder','advanced','What is the input offset voltage?',ARRAY['Voltage needed to zero the output','Maximum input voltage','Minimum input voltage','Supply voltage'],0,'Offset voltage nulls output when inputs are equal.',20),
('circuit-builder','advanced','What is the input bias current?',ARRAY['DC current into op-amp inputs','AC input current','Output current','Supply current'],0,'Bias current flows into both inputs.',20),
('circuit-builder','advanced','What is the difference between inverting and non-inverting op-amp?',ARRAY['Non-inverting has positive gain and high input Z','Inverting has positive gain','No difference','Inverting has higher gain'],0,'Non-inverting: +gain, high Zin; inverting: -gain, Zin = Rin.',20),
('circuit-builder','advanced','Design a summing amplifier with 3 inputs. What is Vout?',ARRAY['-(Rf/R1·V1 + Rf/R2·V2 + Rf/R3·V3)','V1+V2+V3','Rf·(V1+V2+V3)','-(V1+V2+V3)'],0,'Inverting summer: Vout = -Σ(Rf/Ri·Vi).',20),
('circuit-builder','advanced','Design a difference amplifier. What is Vout?',ARRAY['(R2/R1)×(V2-V1)','V2-V1','R2×(V1+V2)','(V1-V2)/R1'],0,'Diff amp: Vout = (R2/R1)(V2-V1).',20),
('circuit-builder','advanced','What is an instrumentation amplifier?',ARRAY['High-precision differential amplifier with high CMRR','Buffer amplifier','Summing amplifier','Power amplifier'],0,'Instrumentation amps have high CMRR and gain.',20),
('circuit-builder','advanced','What is a Schmitt trigger using op-amp?',ARRAY['Comparator with hysteresis','Unity gain buffer','Integrator','Differentiator'],0,'Positive feedback creates hysteresis.',20),
('circuit-builder','advanced','Design an op-amp integrator. What component is in the feedback path?',ARRAY['Capacitor','Resistor','Inductor','Diode'],0,'Integrator: capacitor in feedback.',20),
('circuit-builder','advanced','Design an op-amp differentiator. What component is in the input path?',ARRAY['Capacitor','Resistor','Inductor','Diode'],0,'Differentiator: capacitor at input, resistor in feedback.',20),
('circuit-builder','advanced','What is a Wien bridge oscillator?',ARRAY['RC oscillator for sine waves','LC oscillator','Crystal oscillator','Relaxation oscillator'],0,'Wien bridge uses RC network for sine wave generation.',20),
('circuit-builder','advanced','What is the frequency of a Wien bridge oscillator?',ARRAY['f = 1/(2πRC)','f = 2πRC','f = RC','f = 1/(RC)'],0,'Wien bridge: f = 1/(2πRC).',20),
('circuit-builder','advanced','What is the Barkhausen criterion for oscillation?',ARRAY['Loop gain ≥ 1 and phase shift = 360°','Gain > 0','Phase = 0','Gain = 0'],0,'|Aβ| ≥ 1 and ∠Aβ = 2nπ.',20),
('circuit-builder','advanced','What is a phase-shift oscillator?',ARRAY['RC network providing 180° phase shift','LC oscillator','Crystal oscillator','Wien bridge'],0,'Three RC stages give 180°, plus op-amp inversion = 360°.',20),
('circuit-builder','advanced','What is a Colpitts oscillator?',ARRAY['LC oscillator with capacitive divider','RC oscillator','Crystal oscillator','Relaxation oscillator'],0,'Colpitts uses a capacitive voltage divider in the tank.',20),
('circuit-builder','advanced','What is a Hartley oscillator?',ARRAY['LC oscillator with tapped inductor','RC oscillator','Crystal oscillator','Colpitts variant'],0,'Hartley uses a tapped inductor in the tank circuit.',20),
('circuit-builder','advanced','What is a crystal oscillator?',ARRAY['Uses piezoelectric crystal for high stability','Uses RC network','Uses LC tank','Uses op-amp'],0,'Crystal oscillators are very stable (ppm range).',20),
('circuit-builder','advanced','What is the equivalent circuit of a crystal?',ARRAY['Series RLC with parallel C','Just a capacitor','Just an inductor','Just a resistor'],0,'Crystal: series RLC branch with parallel capacitance.',20),
('circuit-builder','advanced','What is a relaxation oscillator?',ARRAY['Uses charging/discharging of RC','Uses LC tank','Uses crystal','Uses op-amp integrator'],0,'Relaxation oscillators use comparators + RC.',20),
('circuit-builder','advanced','What is a multivibrator?',ARRAY['Two-state circuit generating square waves','Single amplifier','Filter circuit','Oscillator with crystal'],0,'Astable, monostable, bistable multivibrators.',20),
('circuit-builder','advanced','What is an astable multivibrator?',ARRAY['Free-running oscillator (no stable state)','One stable state','Two stable states','No output'],0,'Astable continuously oscillates.',20),
('circuit-builder','advanced','What is a monostable multivibrator?',ARRAY['One stable state, triggered to quasi-stable','No stable state','Two stable states','Free-running'],0,'Monostable produces one pulse per trigger.',20),
('circuit-builder','advanced','What is a bistable multivibrator?',ARRAY['Two stable states (flip-flop)','No stable state','One stable state','Free-running'],0,'Bistable = SR flip-flop.',20),
('circuit-builder','advanced','What is a 555 timer?',ARRAY['Versatile IC for timing and oscillation','Op-amp','Comparator','Logic gate'],0,'555 timer: astable, monostable, PWM applications.',20),
('circuit-builder','advanced','What is the output frequency of a 555 astable?',ARRAY['f = 1.44/((RA+2RB)C)','f = RC','f = 1/(RC)','f = RA+RB'],0,'555 astable: f = 1.44/((RA+2RB)×C).',20),
('circuit-builder','advanced','What is the duty cycle of a 555 astable?',ARRAY['(RA+RB)/(RA+2RB) × 100%','50%','100%','RB/RA'],0,'Duty cycle depends on RA and RB ratio.',20),
('circuit-builder','advanced','What is a PLL (Phase-Locked Loop)?',ARRAY['Locks output phase to input reference','Phase shifter','Frequency multiplier only','Filter'],0,'PLL: phase detector + VCO + loop filter.',20),
('circuit-builder','advanced','What are the main blocks of a PLL?',ARRAY['Phase detector, VCO, loop filter','Op-amp, resistor, capacitor','Mixer, filter, amplifier','Counter, register, decoder'],0,'PLL = PD + LPF + VCO.',20),
('circuit-builder','advanced','What is the capture range of a PLL?',ARRAY['Range of frequencies PLL can lock onto','Output frequency range','Input voltage range','Loop bandwidth'],0,'Capture range ⊆ lock range.',20),
('circuit-builder','advanced','What is the lock range of a PLL?',ARRAY['Range of frequencies PLL can maintain lock','Capture range','VCO range','Filter bandwidth'],0,'Lock range ≥ capture range.',20),
('circuit-builder','advanced','What is a VCO?',ARRAY['Voltage-Controlled Oscillator','Voltage Comparator','Variable Current Output','Voltage Controlled Op-amp'],0,'VCO frequency controlled by input voltage.',20),
('circuit-builder','advanced','What is a sample-and-hold circuit?',ARRAY['Captures and holds analog voltage','Amplifies signal','Filters signal','Converts digital to analog'],0,'S/H uses a capacitor to hold sampled voltage.',20),
('circuit-builder','advanced','What is a DAC?',ARRAY['Digital-to-Analog Converter','Data Acquisition Circuit','Direct Current Amplifier','Digital Arithmetic Circuit'],0,'DAC converts digital codes to analog voltage.',20),
('circuit-builder','advanced','What is an ADC?',ARRAY['Analog-to-Digital Converter','Amplifier with Digital Control','Active Differential Comparator','Analog Data Converter'],0,'ADC converts analog voltage to digital code.',20),
('circuit-builder','advanced','What is the resolution of an 8-bit ADC?',ARRAY['256 levels','128 levels','64 levels','512 levels'],0,'2^8 = 256 levels.',20),
('circuit-builder','advanced','What is the quantization error of an n-bit ADC?',ARRAY['±(1/2) LSB','±1 LSB','±2 LSB','±(1/4) LSB'],0,'Quantization error is ±½ LSB.',20),
('circuit-builder','advanced','What is a flash ADC?',ARRAY['Fastest ADC using 2^n-1 comparators','Slowest ADC','Uses a single comparator','Uses a DAC'],0,'Flash ADC: parallel comparison, 1 clock cycle.',20),
('circuit-builder','advanced','What is a successive approximation ADC?',ARRAY['Uses binary search with DAC','Uses parallel comparators','Uses single slope','Uses dual slope'],0,'SAR ADC: binary search, n clock cycles.',20),
('circuit-builder','advanced','What is a dual-slope ADC?',ARRAY['Integrates signal for fixed time, then deintegrates','Uses parallel comparators','Uses binary search','Fastest ADC'],0,'Dual-slope: high accuracy, slow speed.',20),
('circuit-builder','advanced','What is a sigma-delta ADC?',ARRAY['Oversampling + noise shaping + decimation','Parallel conversion','Binary search','Dual slope'],0,'Σ-Δ ADC: high resolution, moderate speed.',20),
('circuit-builder','advanced','What is the Nyquist rate?',ARRAY['Minimum sampling rate = 2 × signal bandwidth','Sampling rate = signal bandwidth','Sampling rate = 4 × bandwidth','Sampling rate = bandwidth/2'],0,'Nyquist: fs ≥ 2 × fmax to avoid aliasing.',20),
('circuit-builder','advanced','What is aliasing?',ARRAY['High frequencies fold back as low frequencies','Signal attenuation','Signal amplification','Phase distortion'],0,'Aliasing occurs when fs < 2 × fmax.',20),
('circuit-builder','advanced','What is an anti-aliasing filter?',ARRAY['Low-pass filter before ADC','High-pass filter after ADC','Band-pass filter','Notch filter'],0,'Anti-aliasing filter limits bandwidth before sampling.',20),
('circuit-builder','advanced','What is oversampling?',ARRAY['Sampling at much higher than Nyquist rate','Sampling at Nyquist rate','Sampling below Nyquist','Sampling once'],0,'Oversampling improves SNR and resolution.',20),
('circuit-builder','advanced','What is a switched-capacitor filter?',ARRAY['Uses capacitors and switches to simulate resistors','Uses op-amps only','Uses inductors','Uses crystals'],0,'SC filters: R = 1/(fC), tunable by clock frequency.',20),
('circuit-builder','advanced','What is the advantage of active filters over passive filters?',ARRAY['Can provide gain, no inductors needed','Cheaper','Smaller size','Higher frequency'],0,'Active filters use op-amps, avoid bulky inductors.',20);