INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','Problem: D flip-flop with D=0, clock=no edge. What is Q_next?',ARRAY['Q (hold)','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=0, clock=rising edge. What is Q_next?',ARRAY['0','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=no edge. What is Q_next?',ARRAY['Q (hold)','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=rising edge. What is Q_next?',ARRAY['1','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: A state machine has 2 states. How many flip-flops are needed?',ARRAY['1','2','1','4'],0,'Need ⌈log2(2)⌉ = 1 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 3 states. How many flip-flops are needed?',ARRAY['2','3','1.5','6'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 5 states. How many flip-flops are needed?',ARRAY['3','5','2.5','10'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 6 states. How many flip-flops are needed?',ARRAY['3','6','3','12'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 8 states. How many flip-flops are needed?',ARRAY['3','8','4','16'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10);