INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 4 states using 2 flip-flops. How many unused states exist?',ARRAY['0','0','4','2'],0,'2^2 = 4 total, 4 - 4 = 0 unused.',20),
('state-machine','advanced','A state machine has 5 states using 3 flip-flops. How many unused states exist?',ARRAY['3','0','5','3'],0,'2^3 = 8 total, 8 - 5 = 3 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 15 states using 4 flip-flops. How many unused states exist?',ARRAY['1','0','15','4'],0,'2^4 = 16 total, 16 - 15 = 1 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 7 states using 3 flip-flops. How many unused states exist?',ARRAY['1','0','7','3'],0,'2^3 = 8 total, 8 - 7 = 1 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 13 states using 4 flip-flops. How many unused states exist?',ARRAY['3','0','13','4'],0,'2^4 = 16 total, 16 - 13 = 3 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A state machine has 4 states using 2 flip-flops. How many unused states exist?',ARRAY['0','0','4','2'],0,'2^2 = 4 total, 4 - 4 = 0 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A Petri net has 10 places and 9 transitions. What is the minimum number of arcs?',ARRAY['9','0','10','90'],0,'Each transition needs at least one input and one output arc, minimum 9 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 8 transitions. What is the minimum number of arcs?',ARRAY['8','0','5','40'],0,'Each transition needs at least one input and one output arc, minimum 8 arcs.',20),
('state-machine','advanced','A Petri net has 7 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','7','28'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','8','48'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 10 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','10','50'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 9 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','9','36'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 10 transitions. What is the minimum number of arcs?',ARRAY['10','0','3','30'],0,'Each transition needs at least one input and one output arc, minimum 10 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','3','12'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 3 transitions. What is the minimum number of arcs?',ARRAY['3','0','8','24'],0,'Each transition needs at least one input and one output arc, minimum 3 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 8 transitions. What is the minimum number of arcs?',ARRAY['8','0','8','64'],0,'Each transition needs at least one input and one output arc, minimum 8 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','5','20'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','3','18'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 7 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','7','42'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 6 places and 3 transitions. What is the minimum number of arcs?',ARRAY['3','0','6','18'],0,'Each transition needs at least one input and one output arc, minimum 3 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 2 transitions. What is the minimum number of arcs?',ARRAY['2','0','3','6'],0,'Each transition needs at least one input and one output arc, minimum 2 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','8','48'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 7 transitions. What is the minimum number of arcs?',ARRAY['7','0','3','21'],0,'Each transition needs at least one input and one output arc, minimum 7 arcs.',20),
('state-machine','advanced','A 8-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['64','8','16','256'],0,'For 8 states, sequences of length 2: 8×8 = 64 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 7-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['49','7','14','128'],0,'For 7 states, sequences of length 2: 7×7 = 49 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 3-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['9','3','6','8'],0,'For 3 states, sequences of length 2: 3×3 = 9 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 8-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['64','8','16','256'],0,'For 8 states, sequences of length 2: 8×8 = 64 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 3-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['9','3','6','8'],0,'For 3 states, sequences of length 2: 3×3 = 9 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A one-hot encoded FSM with 4 states needs how many flip-flops?',ARRAY['4','2','5','3'],0,'One-hot: 1 flip-flop per state = 4 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 18 states needs how many flip-flops?',ARRAY['18','5','19','17'],0,'One-hot: 1 flip-flop per state = 18 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 12 states needs how many flip-flops?',ARRAY['12','4','13','11'],0,'One-hot: 1 flip-flop per state = 12 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 8 states needs how many flip-flops?',ARRAY['8','3','9','7'],0,'One-hot: 1 flip-flop per state = 8 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 18 states needs how many flip-flops?',ARRAY['18','5','19','17'],0,'One-hot: 1 flip-flop per state = 18 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 14 states needs how many flip-flops?',ARRAY['14','4','15','13'],0,'One-hot: 1 flip-flop per state = 14 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 4 states needs how many flip-flops?',ARRAY['4','2','5','3'],0,'One-hot: 1 flip-flop per state = 4 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 10 states needs how many flip-flops?',ARRAY['10','4','11','9'],0,'One-hot: 1 flip-flop per state = 10 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 19 states needs how many flip-flops?',ARRAY['19','5','20','18'],0,'One-hot: 1 flip-flop per state = 19 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 11 states needs how many flip-flops?',ARRAY['11','4','12','10'],0,'One-hot: 1 flip-flop per state = 11 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 5 states needs how many flip-flops?',ARRAY['5','3','6','4'],0,'One-hot: 1 flip-flop per state = 5 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 19 states needs how many flip-flops?',ARRAY['5','19','20','6'],0,'Binary encoding: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 5 states needs how many flip-flops?',ARRAY['3','5','6','4'],0,'Binary encoding: ⌈log2(5)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 10 states needs how many flip-flops?',ARRAY['4','10','11','5'],0,'Binary encoding: ⌈log2(10)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 18 states needs how many flip-flops?',ARRAY['5','18','19','6'],0,'Binary encoding: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 19 states needs how many flip-flops?',ARRAY['5','19','20','6'],0,'Binary encoding: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 15 states needs how many flip-flops?',ARRAY['4','15','16','5'],0,'Binary encoding: ⌈log2(15)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 18 states needs how many flip-flops?',ARRAY['5','18','19','6'],0,'Binary encoding: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 9 states needs how many flip-flops?',ARRAY['4','9','10','5'],0,'Binary encoding: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 9 states needs how many flip-flops?',ARRAY['4','9','10','5'],0,'Binary encoding: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 15 states needs how many flip-flops?',ARRAY['4','15','16','5'],0,'Binary encoding: ⌈log2(15)⌉ = 4 flip-flops.',20);;