INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1 OR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1 OR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10);