INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: AB + A''B',ARRAY['B','A','AB','A''+B'],0,'AB+A''B = B(A+A'') = B.',15),
('gate-puzzler','intermediate','Simplify: AB + AB''',ARRAY['A','B','AB','A+B'],0,'AB+AB'' = A(B+B'') = A.',15),
('gate-puzzler','intermediate','Simplify: A + A''B',ARRAY['A+B','A','B','AB'],0,'A+A''B = (A+A'')(A+B) = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)'' + (A''+B'')''',ARRAY['0','1','A','B'],0,'De Morgan: (A+B)''=A''B'', (A''+B'')''=AB. Sum = A''B''+AB = 0 only if... actually = A XNOR B.',15),
('gate-puzzler','intermediate','Simplify: A(A+B'')',ARRAY['A','AB''','A+B''','AB'],0,'A(A+B'') = A+AB'' = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A''+B)',ARRAY['B','A','A+B','AB'],0,'(A+B)(A''+B) = AB+B = B.',15),
('gate-puzzler','intermediate','Simplify: AB''C + ABC',ARRAY['AC','AB','BC','ABC'],0,'AB''C+ABC = AC(B''+B) = AC.',15),
('gate-puzzler','intermediate','Simplify: (AB)'' · A',ARRAY['A·(A''+B'')','AB','A+B','A'''],0,'(AB)''·A = (A''+B'')·A = AB''.',15),
('gate-puzzler','intermediate','Simplify: A⊕B⊕A',ARRAY['B','A','0','1'],0,'A⊕B⊕A = B (A cancels out).',15),
('gate-puzzler','intermediate','Simplify: A⊙B⊙A',ARRAY['B''','A''','1','0'],0,'A⊙B⊙A = B'' (XNOR with A cancels to NOT B).',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 1kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+1 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 2kΩ are in series. What is R_eq?',ARRAY['4kΩ','1.00kΩ','4kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 2+2 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 3kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+3 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 4kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 2+4 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 5kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 2+5 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 1kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+1 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 2kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+2 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 3kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.50kΩ','9kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 3+3 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 4kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+4 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 5kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+5 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 1kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+1 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 2kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+2 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 3kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+3 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 4kΩ are in series. What is R_eq?',ARRAY['8kΩ','2.00kΩ','16kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 4+4 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 5kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+5 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 1kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+1 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 2kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+2 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 3kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+3 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 4kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+4 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 5kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.50kΩ','25kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 5+5 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 1kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+1 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 2kΩ are in series. What is R_eq?',ARRAY['4kΩ','1.00kΩ','4kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 2+2 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 3kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+3 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 4kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 2+4 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 5kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 2+5 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 1kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+1 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 2kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+2 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 3kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.50kΩ','9kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 3+3 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 4kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+4 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 5kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+5 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 1kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+1 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 2kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+2 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 3kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+3 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 4kΩ are in series. What is R_eq?',ARRAY['8kΩ','2.00kΩ','16kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 4+4 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 5kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+5 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 1kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+1 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 2kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+2 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 3kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+3 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 4kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+4 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 5kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.50kΩ','25kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 5+5 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 1kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+1 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 2kΩ are in series. What is R_eq?',ARRAY['4kΩ','1.00kΩ','4kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 2+2 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 3kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+3 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 4kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 2+4 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 5kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 2+5 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 1kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+1 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 2kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+2 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 3kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.50kΩ','9kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 3+3 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 4kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+4 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 5kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+5 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 1kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+1 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 2kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+2 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 3kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+3 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 4kΩ are in series. What is R_eq?',ARRAY['8kΩ','2.00kΩ','16kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 4+4 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 5kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+5 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 1kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+1 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 2kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+2 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 3kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+3 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 4kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+4 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 5kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.50kΩ','25kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 5+5 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15);