INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15);