INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input AND(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=0. What does the buffer output?',ARRAY['0','1','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 0.',10),
('gate-puzzler','basic','Problem: A buffer gate receives A=1. What does the buffer output?',ARRAY['1','0','High-Z','Undefined'],0,'Buffer passes input unchanged: output = 1.',10);