INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 12 states. How many flip-flops are needed?',ARRAY['4','12','6','24'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 5 states. How many flip-flops are needed?',ARRAY['3','5','2.5','10'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 6 states. How many flip-flops are needed?',ARRAY['3','6','3','12'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 14 states. How many flip-flops are needed?',ARRAY['4','14','7','28'],0,'Need ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 8 states. How many flip-flops are needed?',ARRAY['3','8','4','16'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 3 states. How many flip-flops are needed?',ARRAY['2','3','1.5','6'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 15 states. How many flip-flops are needed?',ARRAY['4','15','7.5','30'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10);