INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells.',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells.',20),
('gate-puzzler','advanced','A 5-variable K-map has how many cells?',ARRAY['32','16','64','128'],0,'2^5 = 32 cells.',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Gray code ordering: adjacent cells differ by 1 variable.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'All 16 cells = function = 1.',20),
('gate-puzzler','advanced','K-map groups must be of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups of 1, 2, 4, 8, 16...',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','What is a prime implicant in K-map simplification?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group.',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['Covers a cell no other PI covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one unique minterm.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,7)?',ARRAY['2','1','3','8'],0,'Two minterms: m0, m7.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,2,3) simplifies to what?',ARRAY['A''','A','B','C'],0,'m0-m3 = A''(B''+B)(C''+C) = A''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(4,5,6,7) simplifies to what?',ARRAY['A','A''','B','C'],0,'m4-m7 = A(B''+B)(C''+C) = A.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,2,4,6) simplifies to what?',ARRAY['C''','C','A','B'],0,'Even minterms = C''.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','A 4:1 MUX needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, n = 2.',20),
('gate-puzzler','advanced','An 8:1 MUX needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, n = 3.',20),
('gate-puzzler','advanced','A 16:1 MUX needs how many select lines?',ARRAY['4','3','5','16'],0,'2^n = 16, n = 4.',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs → 8 outputs.',20),
('gate-puzzler','advanced','A 4-to-16 decoder has how many outputs?',ARRAY['16','4','8','32'],0,'4 inputs → 16 outputs.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'2^3 = 8.',20),
('gate-puzzler','advanced','How many NAND gates to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both NAND inputs together.',20),
('gate-puzzler','advanced','How many NAND gates to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT.',20),
('gate-puzzler','advanced','How many NAND gates to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs.',20),
('gate-puzzler','advanced','How many NAND gates to build an XOR gate?',ARRAY['4','2','3','6'],0,'XOR from NAND needs 4 gates.',20),
('gate-puzzler','advanced','How many NOR gates to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT.',20),
('gate-puzzler','advanced','How many NOR gates to build an AND gate?',ARRAY['3','2','4','1'],0,'AND = NOR(A'') NOR NOR(B'') = 3 NORs.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what?',ARRAY['A','A''','1','0'],0,'Output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what?',ARRAY['A''','A','1','0'],0,'Output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=0, S=A outputs what?',ARRAY['0','A','A''','1'],0,'Both inputs are 0, so output = 0.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=1, S=A outputs what?',ARRAY['1','A','A''','0'],0,'Both inputs are 1, so output = 1.',20),
('gate-puzzler','advanced','If F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A.',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'0+0 = 0.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'A''B''·AB = 0.',20),
('gate-puzzler','advanced','Hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC.',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates needed?',ARRAY['4','2','8','1'],0,'4 XNORs ANDed.',20),
('gate-puzzler','advanced','What is a static-1 hazard?',ARRAY['Output momentarily goes to 0 when it should stay 1','Output stays 1','Output oscillates','Output is undefined'],0,'Static-1 hazard: brief 0 glitch on a 1 output.',20),
('gate-puzzler','advanced','What is a static-0 hazard?',ARRAY['Output momentarily goes to 1 when it should stay 0','Output stays 0','Output oscillates','Output is undefined'],0,'Static-0 hazard: brief 1 glitch on a 0 output.',20),
('gate-puzzler','advanced','How do you eliminate static hazards?',ARRAY['Add consensus terms','Remove gates','Increase clock speed','Add buffers'],0,'Consensus terms cover transitions.',20),
('gate-puzzler','advanced','What is a dynamic hazard?',ARRAY['Output changes multiple times during a transition','Output doesn''t change','Output oscillates continuously','Output is stuck'],0,'Dynamic hazard: multiple transitions for a single input change.',20),
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells.',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells.',20),
('gate-puzzler','advanced','A 5-variable K-map has how many cells?',ARRAY['32','16','64','128'],0,'2^5 = 32 cells.',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Gray code ordering: adjacent cells differ by 1 variable.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'All 16 cells = function = 1.',20),
('gate-puzzler','advanced','K-map groups must be of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups of 1, 2, 4, 8, 16...',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','What is a prime implicant in K-map simplification?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group.',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['Covers a cell no other PI covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one unique minterm.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,7)?',ARRAY['2','1','3','8'],0,'Two minterms: m0, m7.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,2,3) simplifies to what?',ARRAY['A''','A','B','C'],0,'m0-m3 = A''(B''+B)(C''+C) = A''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(4,5,6,7) simplifies to what?',ARRAY['A','A''','B','C'],0,'m4-m7 = A(B''+B)(C''+C) = A.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,2,4,6) simplifies to what?',ARRAY['C''','C','A','B'],0,'Even minterms = C''.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','A 4:1 MUX needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, n = 2.',20),
('gate-puzzler','advanced','An 8:1 MUX needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, n = 3.',20),
('gate-puzzler','advanced','A 16:1 MUX needs how many select lines?',ARRAY['4','3','5','16'],0,'2^n = 16, n = 4.',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs → 8 outputs.',20),
('gate-puzzler','advanced','A 4-to-16 decoder has how many outputs?',ARRAY['16','4','8','32'],0,'4 inputs → 16 outputs.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'2^3 = 8.',20),
('gate-puzzler','advanced','How many NAND gates to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both NAND inputs together.',20),
('gate-puzzler','advanced','How many NAND gates to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT.',20),
('gate-puzzler','advanced','How many NAND gates to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs.',20),
('gate-puzzler','advanced','How many NAND gates to build an XOR gate?',ARRAY['4','2','3','6'],0,'XOR from NAND needs 4 gates.',20),
('gate-puzzler','advanced','How many NOR gates to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT.',20),
('gate-puzzler','advanced','How many NOR gates to build an AND gate?',ARRAY['3','2','4','1'],0,'AND = NOR(A'') NOR NOR(B'') = 3 NORs.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what?',ARRAY['A','A''','1','0'],0,'Output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what?',ARRAY['A''','A','1','0'],0,'Output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=0, S=A outputs what?',ARRAY['0','A','A''','1'],0,'Both inputs are 0, so output = 0.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=1, S=A outputs what?',ARRAY['1','A','A''','0'],0,'Both inputs are 1, so output = 1.',20),
('gate-puzzler','advanced','If F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A.',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'0+0 = 0.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'A''B''·AB = 0.',20),
('gate-puzzler','advanced','Hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC.',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates needed?',ARRAY['4','2','8','1'],0,'4 XNORs ANDed.',20),
('gate-puzzler','advanced','What is a static-1 hazard?',ARRAY['Output momentarily goes to 0 when it should stay 1','Output stays 1','Output oscillates','Output is undefined'],0,'Static-1 hazard: brief 0 glitch on a 1 output.',20),
('gate-puzzler','advanced','What is a static-0 hazard?',ARRAY['Output momentarily goes to 1 when it should stay 0','Output stays 0','Output oscillates','Output is undefined'],0,'Static-0 hazard: brief 1 glitch on a 0 output.',20),
('gate-puzzler','advanced','How do you eliminate static hazards?',ARRAY['Add consensus terms','Remove gates','Increase clock speed','Add buffers'],0,'Consensus terms cover transitions.',20),
('gate-puzzler','advanced','What is a dynamic hazard?',ARRAY['Output changes multiple times during a transition','Output doesn''t change','Output oscillates continuously','Output is stuck'],0,'Dynamic hazard: multiple transitions for a single input change.',20),
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells.',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells.',20),
('gate-puzzler','advanced','A 5-variable K-map has how many cells?',ARRAY['32','16','64','128'],0,'2^5 = 32 cells.',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Gray code ordering: adjacent cells differ by 1 variable.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'All 16 cells = function = 1.',20),
('gate-puzzler','advanced','K-map groups must be of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups of 1, 2, 4, 8, 16...',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','What is a prime implicant in K-map simplification?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group.',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['Covers a cell no other PI covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one unique minterm.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,7)?',ARRAY['2','1','3','8'],0,'Two minterms: m0, m7.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,2,3) simplifies to what?',ARRAY['A''','A','B','C'],0,'m0-m3 = A''(B''+B)(C''+C) = A''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(4,5,6,7) simplifies to what?',ARRAY['A','A''','B','C'],0,'m4-m7 = A(B''+B)(C''+C) = A.',20);;