INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input AND(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input OR(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=0, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(0,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(0,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=1, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(0,1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=0, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(1,0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(1,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(1,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','Problem: What is NOT(AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,0)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0)=0.',10),
('gate-puzzler','basic','Problem: What is XOR(AND(1,1), OR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, OR(0,1)=1, XOR(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NAND(OR(1,0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, AND(1,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(AND(0,1), OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(0,1)=0, OR(0,0)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(XOR(1,0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,0)=1, AND(1,1)=1, XNOR(1,1)=1. Wait, XNOR(1,1)=1, but the answer is 1. Correct answer is 1.',10),
('gate-puzzler','basic','Problem: What is NOT(NAND(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(0,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(NOR(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(1,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is AND(OR(1,0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, NOT(1)=0, AND(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is OR(AND(0,1), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(0,1)=0, NOT(0)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, XOR(1,0)=1. Wait, XOR(1,0)=1. Answer is 1.',10),
('gate-puzzler','basic','Problem: What is NAND(NOT(0), NOT(0))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(0)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(NOT(1), NOT(1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, NOT(1)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(NOT(0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, XNOR(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is AND(XOR(1,1), OR(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1)=0, OR(1,0)=1, AND(0,1)=0.',10),
('gate-puzzler','basic','Problem: What is OR(NAND(0,0), NOR(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(0,0)=1, NOR(0,0)=1, OR(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is NOT(XOR(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(XNOR(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,1)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is AND(1, OR(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0)=0, AND(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is OR(0, AND(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(1, XOR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(0, XNOR(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(1,0)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(AND(1,0), OR(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,0)=0, OR(1,1)=1, XOR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(NAND(1,1), NOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,1)=0, NOR(0,1)=0, XNOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(AND(NOT(0), NOT(1)))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, AND(1,0)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(AND(0,0)), NOT(OR(1,1)))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0)=0, NOT(0)=1, OR(1,1)=1, NOT(1)=0, OR(1,0)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), NOT(1), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0,0)=0.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, XOR(1,1,1)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(1,1,1)?',ARRAY['0','1','High-Z','Undefined'],0,'3-input NAND(1,1,1)=NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(0,0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'3-input NOR(0,0,0)=NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(1,1,1)?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XNOR(1,1,1)=1 (odd parity check).',10),
('gate-puzzler','basic','Problem: What is XNOR(1,0,1)?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XNOR(1,0,1)=0 (not all same).',10),
('gate-puzzler','basic','Problem: What is NOT(OR(AND(1,1), AND(0,0)))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, AND(0,0)=0, OR(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), OR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, OR(0,1)=1, AND(1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), AND(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, AND(1,1)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), AND(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,0)=0, XOR(1,0)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(NOT(1), OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0)=0, NAND(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOR(NOT(0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1)=1, NOR(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is XNOR(XOR(0,1), NOT(0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,1)=1, NOT(0)=1, XNOR(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is AND(XNOR(1,1), XOR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,1)=1, XOR(0,1)=1, AND(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is OR(NAND(0,1), NOR(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1)=1, NOR(1,0)=0, OR(1,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(NAND(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(NOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(XNOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(0,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: Evaluate AND(OR(1,0), NOR(0,0)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, NOR(0,0)=1, AND(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: Evaluate NAND(AND(1,1), XOR(0,1)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, XOR(0,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: Evaluate NOR(OR(1,1), AND(0,1)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,1)=1, AND(0,1)=0, NOR(1,0)=0.',10);