INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','advanced','Problem: FSM with 4 states using 2 flip-flops (binary). How many unused states?',ARRAY['0','0','4','2'],0,'2^2 = 4, minus 4 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 5 states using 3 flip-flops (binary). How many unused states?',ARRAY['3','0','5','3'],0,'2^3 = 8, minus 5 used = 3 unused.',20),
('state-machine','advanced','Problem: FSM with 6 states using 3 flip-flops (binary). How many unused states?',ARRAY['2','0','6','3'],0,'2^3 = 8, minus 6 used = 2 unused.',20),
('state-machine','advanced','Problem: FSM with 7 states using 3 flip-flops (binary). How many unused states?',ARRAY['1','0','7','3'],0,'2^3 = 8, minus 7 used = 1 unused.',20),
('state-machine','advanced','Problem: FSM with 8 states using 3 flip-flops (binary). How many unused states?',ARRAY['0','0','8','3'],0,'2^3 = 8, minus 8 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 9 states using 4 flip-flops (binary). How many unused states?',ARRAY['7','0','9','4'],0,'2^4 = 16, minus 9 used = 7 unused.',20),
('state-machine','advanced','Problem: FSM with 10 states using 4 flip-flops (binary). How many unused states?',ARRAY['6','0','10','4'],0,'2^4 = 16, minus 10 used = 6 unused.',20),
('state-machine','advanced','Problem: FSM with 11 states using 4 flip-flops (binary). How many unused states?',ARRAY['5','0','11','4'],0,'2^4 = 16, minus 11 used = 5 unused.',20),
('state-machine','advanced','Problem: FSM with 12 states using 4 flip-flops (binary). How many unused states?',ARRAY['4','0','12','4'],0,'2^4 = 16, minus 12 used = 4 unused.',20),
('state-machine','advanced','Problem: FSM with 13 states using 4 flip-flops (binary). How many unused states?',ARRAY['3','0','13','4'],0,'2^4 = 16, minus 13 used = 3 unused.',20),
('state-machine','advanced','Problem: FSM with 14 states using 4 flip-flops (binary). How many unused states?',ARRAY['2','0','14','4'],0,'2^4 = 16, minus 14 used = 2 unused.',20),
('state-machine','advanced','Problem: FSM with 15 states using 4 flip-flops (binary). How many unused states?',ARRAY['1','0','15','4'],0,'2^4 = 16, minus 15 used = 1 unused.',20),
('state-machine','advanced','Problem: FSM with 16 states using 4 flip-flops (binary). How many unused states?',ARRAY['0','0','16','4'],0,'2^4 = 16, minus 16 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 17 states using 5 flip-flops (binary). How many unused states?',ARRAY['15','0','17','5'],0,'2^5 = 32, minus 17 used = 15 unused.',20),
('state-machine','advanced','Problem: FSM with 18 states using 5 flip-flops (binary). How many unused states?',ARRAY['14','0','18','5'],0,'2^5 = 32, minus 18 used = 14 unused.',20),
('state-machine','advanced','Problem: FSM with 19 states using 5 flip-flops (binary). How many unused states?',ARRAY['13','0','19','5'],0,'2^5 = 32, minus 19 used = 13 unused.',20),
('state-machine','advanced','Problem: FSM with 20 states using 5 flip-flops (binary). How many unused states?',ARRAY['12','0','20','5'],0,'2^5 = 32, minus 20 used = 12 unused.',20),
('state-machine','advanced','Problem: FSM with 4 states using one-hot encoding. How many flip-flops needed?',ARRAY['4','2','5','3'],0,'One-hot: 1 FF per state = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 5 states using one-hot encoding. How many flip-flops needed?',ARRAY['5','3','6','4'],0,'One-hot: 1 FF per state = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 6 states using one-hot encoding. How many flip-flops needed?',ARRAY['6','3','7','5'],0,'One-hot: 1 FF per state = 6 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 7 states using one-hot encoding. How many flip-flops needed?',ARRAY['7','3','8','6'],0,'One-hot: 1 FF per state = 7 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 8 states using one-hot encoding. How many flip-flops needed?',ARRAY['8','3','9','7'],0,'One-hot: 1 FF per state = 8 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 9 states using one-hot encoding. How many flip-flops needed?',ARRAY['9','4','10','8'],0,'One-hot: 1 FF per state = 9 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 10 states using one-hot encoding. How many flip-flops needed?',ARRAY['10','4','11','9'],0,'One-hot: 1 FF per state = 10 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 11 states using one-hot encoding. How many flip-flops needed?',ARRAY['11','4','12','10'],0,'One-hot: 1 FF per state = 11 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 12 states using one-hot encoding. How many flip-flops needed?',ARRAY['12','4','13','11'],0,'One-hot: 1 FF per state = 12 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 13 states using one-hot encoding. How many flip-flops needed?',ARRAY['13','4','14','12'],0,'One-hot: 1 FF per state = 13 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 14 states using one-hot encoding. How many flip-flops needed?',ARRAY['14','4','15','13'],0,'One-hot: 1 FF per state = 14 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 15 states using one-hot encoding. How many flip-flops needed?',ARRAY['15','4','16','14'],0,'One-hot: 1 FF per state = 15 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 16 states using one-hot encoding. How many flip-flops needed?',ARRAY['16','4','17','15'],0,'One-hot: 1 FF per state = 16 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 17 states using one-hot encoding. How many flip-flops needed?',ARRAY['17','5','18','16'],0,'One-hot: 1 FF per state = 17 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 18 states using one-hot encoding. How many flip-flops needed?',ARRAY['18','5','19','17'],0,'One-hot: 1 FF per state = 18 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 19 states using one-hot encoding. How many flip-flops needed?',ARRAY['19','5','20','18'],0,'One-hot: 1 FF per state = 19 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 20 states using one-hot encoding. How many flip-flops needed?',ARRAY['20','5','21','19'],0,'One-hot: 1 FF per state = 20 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 4 states using binary encoding. How many flip-flops needed?',ARRAY['2','4','5','3'],0,'Binary: ⌈log2(4)⌉ = 2 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 5 states using binary encoding. How many flip-flops needed?',ARRAY['3','5','6','4'],0,'Binary: ⌈log2(5)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 6 states using binary encoding. How many flip-flops needed?',ARRAY['3','6','7','4'],0,'Binary: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 7 states using binary encoding. How many flip-flops needed?',ARRAY['3','7','8','4'],0,'Binary: ⌈log2(7)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 8 states using binary encoding. How many flip-flops needed?',ARRAY['3','8','9','4'],0,'Binary: ⌈log2(8)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 9 states using binary encoding. How many flip-flops needed?',ARRAY['4','9','10','5'],0,'Binary: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 10 states using binary encoding. How many flip-flops needed?',ARRAY['4','10','11','5'],0,'Binary: ⌈log2(10)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 11 states using binary encoding. How many flip-flops needed?',ARRAY['4','11','12','5'],0,'Binary: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 12 states using binary encoding. How many flip-flops needed?',ARRAY['4','12','13','5'],0,'Binary: ⌈log2(12)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 13 states using binary encoding. How many flip-flops needed?',ARRAY['4','13','14','5'],0,'Binary: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 14 states using binary encoding. How many flip-flops needed?',ARRAY['4','14','15','5'],0,'Binary: ⌈log2(14)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 15 states using binary encoding. How many flip-flops needed?',ARRAY['4','15','16','5'],0,'Binary: ⌈log2(15)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 16 states using binary encoding. How many flip-flops needed?',ARRAY['4','16','17','5'],0,'Binary: ⌈log2(16)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 17 states using binary encoding. How many flip-flops needed?',ARRAY['5','17','18','6'],0,'Binary: ⌈log2(17)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 18 states using binary encoding. How many flip-flops needed?',ARRAY['5','18','19','6'],0,'Binary: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 19 states using binary encoding. How many flip-flops needed?',ARRAY['5','19','20','6'],0,'Binary: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 20 states using binary encoding. How many flip-flops needed?',ARRAY['5','20','21','6'],0,'Binary: ⌈log2(20)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','3','6'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','3','9'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','3','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','3','15'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','3','18'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','3','21'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','3','24'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','3','27'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','3','30'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','4','8'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','4','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','4','16'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','4','20'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','4','24'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','4','28'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','4','32'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','4','36'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','4','40'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','5','10'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','5','15'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','5','20'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','5','25'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','5','30'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','5','35'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','5','40'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','5','45'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','5','50'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 6 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','6','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 6 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','6','18'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: 2-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['4','2','4','4'],0,'State pairs: 2×2 = 4 sequences.',20),
('state-machine','advanced','Problem: 3-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['9','3','6','8'],0,'State pairs: 3×3 = 9 sequences.',20),
('state-machine','advanced','Problem: 4-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['16','4','8','16'],0,'State pairs: 4×4 = 16 sequences.',20),
('state-machine','advanced','Problem: 5-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['25','5','10','32'],0,'State pairs: 5×5 = 25 sequences.',20),
('state-machine','advanced','Problem: 6-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['36','6','12','64'],0,'State pairs: 6×6 = 36 sequences.',20),
('state-machine','advanced','Problem: 7-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['49','7','14','128'],0,'State pairs: 7×7 = 49 sequences.',20),
('state-machine','advanced','Problem: 8-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['64','8','16','256'],0,'State pairs: 8×8 = 64 sequences.',20),
('state-machine','advanced','Problem: A Mealy machine with 3 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 4 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 5 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 6 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 7 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 8 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 9 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 10 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Moore machine with 3 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 4 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 5 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 6 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 7 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20);;