INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: AB + A''B',ARRAY['B','A','AB','A''+B'],0,'AB+A''B = B(A+A'') = B.',15),
('gate-puzzler','intermediate','Simplify: AB + AB''',ARRAY['A','B','AB','A+B'],0,'AB+AB'' = A(B+B'') = A.',15),
('gate-puzzler','intermediate','Simplify: A + A''B',ARRAY['A+B','A','B','AB'],0,'A+A''B = (A+A'')(A+B) = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)'' + (A''+B'')''',ARRAY['A XNOR B','0','1','A XOR B'],0,'De Morgan: (A+B)''=A''B'', (A''+B'')''=AB. Sum = A''B''+AB = A XNOR B.',15),
('gate-puzzler','intermediate','Simplify: A(A+B'')',ARRAY['A','AB''','A+B''','AB'],0,'A(A+B'') = A+AB'' = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A''+B)',ARRAY['B','A','A+B','AB'],0,'(A+B)(A''+B) = AB+B = B.',15),
('gate-puzzler','intermediate','Simplify: AB''C + ABC',ARRAY['AC','AB','BC','ABC'],0,'AB''C+ABC = AC(B''+B) = AC.',15),
('gate-puzzler','intermediate','Simplify: (AB)'' · A',ARRAY['AB''','AB','A+B','A'''],0,'(AB)''·A = (A''+B'')·A = AB''.',15),
('gate-puzzler','intermediate','Simplify: A⊕B⊕A',ARRAY['B','A','0','1'],0,'A⊕B⊕A = B (A cancels out).',15),
('gate-puzzler','intermediate','Simplify: A⊙B⊙A',ARRAY['B''','A''','1','0'],0,'A⊙B⊙A = B'' (XNOR with A cancels to NOT B).',15),
('gate-puzzler','intermediate','Simplify: A+B+A''',ARRAY['1','A','B','A+B'],0,'A+B+A'' = (A+A'')+B = 1+B = 1.',15),
('gate-puzzler','intermediate','Simplify: A·B·A''',ARRAY['0','A','B','AB'],0,'A·B·A'' = A·A''·B = 0·B = 0.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)·A''',ARRAY['B·A''+C·A''','A+B+C','0','A'''],0,'Distribute A'': A''B+A''C.',15),
('gate-puzzler','intermediate','Simplify: A·(A+B+C)',ARRAY['A','A+B+C','B+C','ABC'],0,'Absorption: A·(A+B+C) = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)''·(B+C)''',ARRAY['A''·B''','B''','A''+C''','0'],0,'De Morgan: (A+B)''=A''B'', (B+C)''=B''C''. Product = A''B''C'' = (A+B+C)''.',15),
('gate-puzzler','intermediate','Simplify: AB + BC + A''C',ARRAY['AB + A''C + BC','AB+BC','A''C','AB+A''C'],0,'Consensus theorem: AB+A''C+BC = AB+A''C.',15),
('gate-puzzler','intermediate','Simplify: (A⊕B)'' ',ARRAY['A XNOR B','A XOR B','A+B','A·B'],0,'(A⊕B)'' = A⊙B = A XNOR B.',15),
('gate-puzzler','intermediate','Simplify: A·1 + A·0',ARRAY['A','1','0','A'''],0,'A·1+A·0 = A+0 = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+B'')',ARRAY['A','B','A+B','AB'],0,'(A+B)(A+B'') = A+BB'' = A+0 = A.',15),
('gate-puzzler','intermediate','Simplify: A⊕0',ARRAY['A','0','1','A'''],0,'A⊕0 = A (XOR with 0 is identity).',15),
('gate-puzzler','intermediate','Simplify: A⊕1',ARRAY['A''','A','0','1'],0,'A⊕1 = A'' (XOR with 1 is NOT).',15),
('gate-puzzler','intermediate','Simplify: A⊙0',ARRAY['A''','A','0','1'],0,'A XNOR 0 = A'' (XNOR with 0 is NOT).',15),
('gate-puzzler','intermediate','Simplify: A⊙1',ARRAY['A','A''','0','1'],0,'A XNOR 1 = A (XNOR with 1 is identity).',15),
('gate-puzzler','intermediate','Simplify: A(A''+B)',ARRAY['AB','A','B','A+B'],0,'A(A''+B) = AA''+AB = 0+AB = AB.',15),
('gate-puzzler','intermediate','Simplify: A''+A·B',ARRAY['A''+B','A','B','AB'],0,'A''+AB = (A''+A)(A''+B) = A''+B.',15),
('gate-puzzler','intermediate','Simplify: (AB)''·(AB)',ARRAY['0','1','A','B'],0,'(AB)''·AB = (A''+B'')·AB = 0.',15),
('gate-puzzler','intermediate','Simplify: A·B + A·B''',ARRAY['A','B','AB','A'''],0,'A(B+B'') = A·1 = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A''+B'')',ARRAY['A⊕B','0','1','A XNOR B'],0,'(A+B)(A''+B'') = AB''+A''B = A⊕B.',15),
('gate-puzzler','intermediate','Simplify: ABC + AB''C + ABC'' + AB''C''',ARRAY['A','B','C','AB'],0,'A(BC+B''C+BC''+B''C'') = A(B+B'')(C+C'') = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)(A+B+C'')',ARRAY['A+B','A','B','C'],0,'(A+B+C)(A+B+C'') = (A+B)+CC'' = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(B+C)(A+C)',ARRAY['(A+B)(B+C)','A+B+C','AB+BC','ABC'],0,'Consensus: (A+B)(B+C)(A+C) = (A+B)(B+C).',15),
('gate-puzzler','intermediate','Simplify: A⊕B⊕B',ARRAY['A','B','0','1'],0,'A⊕B⊕B = A⊕0 = A.',15),
('gate-puzzler','intermediate','Simplify: A⊙B⊙B',ARRAY['A''','A','1','0'],0,'A⊙B⊙B = A XNOR 0 = A''.',15),
('gate-puzzler','intermediate','Simplify: (A·B·C)'' ',ARRAY['A''+B''+C''','A''B''C''','ABC''','A+B+C'],0,'De Morgan: (ABC)'' = A''+B''+C''.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)''',ARRAY['A''·B''·C''','A''B''+C''','A''+BC''','ABC'''],0,'De Morgan: (A+B+C)'' = A''B''C''.',15),
('gate-puzzler','intermediate','Simplify: A(B+C) + A''(B+C)',ARRAY['B+C','A','B','C'],0,'(A+A'')(B+C) = B+C.',15),
('gate-puzzler','intermediate','Simplify: AB(A+B)',ARRAY['AB','A+B','A','B'],0,'AB(A+B) = ABA+ABB = AB+AB = AB.',15),
('gate-puzzler','intermediate','Simplify: (A+B)'' + A',ARRAY['A+B''','1','A''','B'],0,'(A+B)''+A = A''B''+A = A+B'' (absorption).',15),
('gate-puzzler','intermediate','Simplify: A·B'' + A''·B + A·B',ARRAY['A+B','A⊕B','A XNOR B','AB'],0,'AB''+A''B+AB = A(B''+B)+A''B = A+A''B = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)''(A''+B'')''',ARRAY['0','1','A XNOR B','A⊕B'],0,'A''B''·AB = 0.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 6kΩ are in series. What is R_eq?',ARRAY['7kΩ','0.86kΩ','6kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 1+6 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 7kΩ are in series. What is R_eq?',ARRAY['8kΩ','0.88kΩ','7kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 1+7 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 8kΩ are in series. What is R_eq?',ARRAY['9kΩ','0.89kΩ','8kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 1+8 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 9kΩ are in series. What is R_eq?',ARRAY['10kΩ','0.90kΩ','9kΩ','8kΩ'],0,'Series: R_eq = R1+R2 = 1+9 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 10kΩ are in series. What is R_eq?',ARRAY['11kΩ','0.91kΩ','10kΩ','9kΩ'],0,'Series: R_eq = R1+R2 = 1+10 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 1kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+1 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 2kΩ are in series. What is R_eq?',ARRAY['4kΩ','1.00kΩ','4kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 2+2 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 3kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+3 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 4kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 2+4 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 5kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 2+5 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 6kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.50kΩ','12kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 2+6 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 7kΩ are in series. What is R_eq?',ARRAY['9kΩ','1.56kΩ','14kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 2+7 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 8kΩ are in series. What is R_eq?',ARRAY['10kΩ','1.60kΩ','16kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 2+8 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 9kΩ are in series. What is R_eq?',ARRAY['11kΩ','1.64kΩ','18kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 2+9 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 10kΩ are in series. What is R_eq?',ARRAY['12kΩ','1.67kΩ','20kΩ','8kΩ'],0,'Series: R_eq = R1+R2 = 2+10 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 1kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+1 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 2kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+2 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 3kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.50kΩ','9kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 3+3 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 4kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+4 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 5kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+5 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 6kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.00kΩ','18kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 3+6 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 7kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.10kΩ','21kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 3+7 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 8kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.18kΩ','24kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 3+8 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 9kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.25kΩ','27kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 3+9 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 10kΩ are in series. What is R_eq?',ARRAY['13kΩ','2.31kΩ','30kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 3+10 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 1kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+1 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 2kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+2 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 3kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+3 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 4kΩ are in series. What is R_eq?',ARRAY['8kΩ','2.00kΩ','16kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 4+4 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 5kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+5 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 6kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.40kΩ','24kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+6 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 7kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.55kΩ','28kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+7 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 8kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.67kΩ','32kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 4+8 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 9kΩ are in series. What is R_eq?',ARRAY['13kΩ','2.77kΩ','36kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 4+9 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 10kΩ are in series. What is R_eq?',ARRAY['14kΩ','2.86kΩ','40kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 4+10 = 14kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 1kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+1 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 2kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+2 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 3kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+3 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 4kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+4 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 5kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.50kΩ','25kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 5+5 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 6kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.73kΩ','30kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+6 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 7kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.92kΩ','35kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+7 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 8kΩ are in series. What is R_eq?',ARRAY['13kΩ','3.08kΩ','40kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+8 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 9kΩ are in series. What is R_eq?',ARRAY['14kΩ','3.21kΩ','45kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+9 = 14kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 10kΩ are in series. What is R_eq?',ARRAY['15kΩ','3.33kΩ','50kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 5+10 = 15kΩ.',15);