INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','Problem: D flip-flop with D=0, clock=no edge. What is Q_next?',ARRAY['Q (hold)','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=0, clock=rising edge. What is Q_next?',ARRAY['0','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=no edge. What is Q_next?',ARRAY['Q (hold)','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=rising edge. What is Q_next?',ARRAY['1','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: SR latch has S=0, R=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'S=0, R=0: Hold.',10),
('state-machine','basic','Problem: SR latch has S=0, R=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'S=0, R=1: Reset (0).',10),
('state-machine','basic','Problem: SR latch has S=1, R=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'S=1, R=0: Set (1).',10),
('state-machine','basic','Problem: SR latch has S=1, R=1. What is the next state?',ARRAY['Invalid','Hold','Reset','Set'],0,'S=1, R=1: Invalid.',10),
('state-machine','basic','Problem: A state machine has 2 states. How many flip-flops are needed?',ARRAY['1','2','1','4'],0,'Need ⌈log2(2)⌉ = 1 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 3 states. How many flip-flops are needed?',ARRAY['2','3','1.5','6'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 5 states. How many flip-flops are needed?',ARRAY['3','5','2.5','10'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 6 states. How many flip-flops are needed?',ARRAY['3','6','3','12'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 8 states. How many flip-flops are needed?',ARRAY['3','8','4','16'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 12 states. How many flip-flops are needed?',ARRAY['4','12','6','24'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 14 states. How many flip-flops are needed?',ARRAY['4','14','7','28'],0,'Need ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 15 states. How many flip-flops are needed?',ARRAY['4','15','7.5','30'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 17 states. How many flip-flops are needed?',ARRAY['5','17','8.5','34'],0,'Need ⌈log2(17)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 18 states. How many flip-flops are needed?',ARRAY['5','18','9','36'],0,'Need ⌈log2(18)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 19 states. How many flip-flops are needed?',ARRAY['5','19','9.5','38'],0,'Need ⌈log2(19)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 20 states. How many flip-flops are needed?',ARRAY['5','20','10','40'],0,'Need ⌈log2(20)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: D flip-flop has D=0, current Q=0. After clock edge, what is Q?',ARRAY['0','0','1','1'],0,'On clock edge, Q_next = D = 0 regardless of current Q=0.',10),
('state-machine','basic','Problem: D flip-flop has D=0, current Q=1. After clock edge, what is Q?',ARRAY['0','1','1','0'],0,'On clock edge, Q_next = D = 0 regardless of current Q=1.',10),
('state-machine','basic','Problem: D flip-flop has D=1, current Q=0. After clock edge, what is Q?',ARRAY['1','0','0','1'],0,'On clock edge, Q_next = D = 1 regardless of current Q=0.',10),
('state-machine','basic','Problem: D flip-flop has D=1, current Q=1. After clock edge, what is Q?',ARRAY['1','1','0','0'],0,'On clock edge, Q_next = D = 1 regardless of current Q=1.',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=0, current Q=0. What is Q_next?',ARRAY['Q (stays 0)','0','1','Toggle'],0,'J=0, K=0, Q=0: Q (stays 0).',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=0, current Q=1. What is Q_next?',ARRAY['Q (stays 1)','0','1','Toggle'],0,'J=0, K=0, Q=1: Q (stays 1).',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=1, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=0, K=1, Q=0: 0.',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=0, K=1, Q=1: 0.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=0, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=0, Q=0: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=0, Q=1: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=1, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=1, Q=0: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=1, K=1, Q=1: 0.',10),
('state-machine','basic','Problem: T flip-flop T=0, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'T=0, Q=0: Q_next = 0.',10),
('state-machine','basic','Problem: T flip-flop T=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'T=0, Q=1: Q_next = 1.',10),
('state-machine','basic','Problem: T flip-flop T=1, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'T=1, Q=0: Q_next = 1.',10),
('state-machine','basic','Problem: T flip-flop T=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'T=1, Q=1: Q_next = 0.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 2. How many flip-flops needed?',ARRAY['1','2','1','3'],0,'Divide by 2 needs ⌈log2(2)⌉ = 1 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 3. How many flip-flops needed?',ARRAY['2','3','2','4'],0,'Divide by 3 needs ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 4. How many flip-flops needed?',ARRAY['2','4','3','5'],0,'Divide by 4 needs ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 5. How many flip-flops needed?',ARRAY['3','5','4','6'],0,'Divide by 5 needs ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 6. How many flip-flops needed?',ARRAY['3','6','5','7'],0,'Divide by 6 needs ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 7. How many flip-flops needed?',ARRAY['3','7','6','8'],0,'Divide by 7 needs ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 8. How many flip-flops needed?',ARRAY['3','8','7','9'],0,'Divide by 8 needs ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 9. How many flip-flops needed?',ARRAY['4','9','8','10'],0,'Divide by 9 needs ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 10. How many flip-flops needed?',ARRAY['4','10','9','11'],0,'Divide by 10 needs ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 11. How many flip-flops needed?',ARRAY['4','11','10','12'],0,'Divide by 11 needs ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 12. How many flip-flops needed?',ARRAY['4','12','11','13'],0,'Divide by 12 needs ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 13. How many flip-flops needed?',ARRAY['4','13','12','14'],0,'Divide by 13 needs ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 14. How many flip-flops needed?',ARRAY['4','14','13','15'],0,'Divide by 14 needs ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 15. How many flip-flops needed?',ARRAY['4','15','14','16'],0,'Divide by 15 needs ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 16. How many flip-flops needed?',ARRAY['4','16','15','17'],0,'Divide by 16 needs ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-3 counter needs how many flip-flops?',ARRAY['2','3','2','4'],0,'Mod-3 needs ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Mod-4 needs ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A mod-5 counter needs how many flip-flops?',ARRAY['3','5','4','6'],0,'Mod-5 needs ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Mod-6 needs ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-7 counter needs how many flip-flops?',ARRAY['3','7','6','8'],0,'Mod-7 needs ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-8 counter needs how many flip-flops?',ARRAY['3','8','7','9'],0,'Mod-8 needs ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Mod-9 needs ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Mod-10 needs ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-11 counter needs how many flip-flops?',ARRAY['4','11','10','12'],0,'Mod-11 needs ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Mod-12 needs ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Mod-13 needs ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-14 counter needs how many flip-flops?',ARRAY['4','14','13','15'],0,'Mod-14 needs ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-15 counter needs how many flip-flops?',ARRAY['4','15','14','16'],0,'Mod-15 needs ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-16 counter needs how many flip-flops?',ARRAY['4','16','15','17'],0,'Mod-16 needs ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-17 counter needs how many flip-flops?',ARRAY['5','17','16','18'],0,'Mod-17 needs ⌈log2(17)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-18 counter needs how many flip-flops?',ARRAY['5','18','17','19'],0,'Mod-18 needs ⌈log2(18)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-19 counter needs how many flip-flops?',ARRAY['5','19','18','20'],0,'Mod-19 needs ⌈log2(19)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-20 counter needs how many flip-flops?',ARRAY['5','20','19','21'],0,'Mod-20 needs ⌈log2(20)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A truth table with 2 inputs has how many rows?',ARRAY['4','2','4','3'],0,'2^2 = 4 rows.',10),
('state-machine','basic','Problem: A truth table with 3 inputs has how many rows?',ARRAY['8','3','6','4'],0,'2^3 = 8 rows.',10),
('state-machine','basic','Problem: A truth table with 4 inputs has how many rows?',ARRAY['16','4','8','5'],0,'2^4 = 16 rows.',10),
('state-machine','basic','Problem: A truth table with 5 inputs has how many rows?',ARRAY['32','5','10','6'],0,'2^5 = 32 rows.',10),
('state-machine','basic','Problem: A truth table with 6 inputs has how many rows?',ARRAY['64','6','12','7'],0,'2^6 = 64 rows.',10),
('state-machine','basic','Problem: A truth table with 7 inputs has how many rows?',ARRAY['128','7','14','8'],0,'2^7 = 128 rows.',10),
('state-machine','basic','Problem: A truth table with 8 inputs has how many rows?',ARRAY['256','8','16','9'],0,'2^8 = 256 rows.',10),
('state-machine','basic','Problem: A truth table with 9 inputs has how many rows?',ARRAY['512','9','18','10'],0,'2^9 = 512 rows.',10),
('state-machine','basic','Problem: A truth table with 10 inputs has how many rows?',ARRAY['1024','10','20','11'],0,'2^10 = 1024 rows.',10),
('state-machine','basic','Problem: A D flip-flop has D=0. What is Q'' (complement output) after clock?',ARRAY['1','0','High-Z','Undefined'],0,'Q_next = D = 0, so Q'' = 1.',10),
('state-machine','basic','Problem: A D flip-flop has D=1. What is Q'' (complement output) after clock?',ARRAY['0','1','High-Z','Undefined'],0,'Q_next = D = 1, so Q'' = 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=0, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=0, Q=0: 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=0, R=0, Q=1: 1.',10),
('state-machine','basic','Problem: SR latch S=0, R=1, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=1, Q=0: 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=1, Q=1: 0.',10),
('state-machine','basic','Problem: SR latch S=1, R=0, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=1, R=0, Q=0: 1.',10),
('state-machine','basic','Problem: SR latch S=1, R=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=1, R=0, Q=1: 1.',10),
('state-machine','basic','Problem: SR latch S=1, R=1, current Q=0. What is Q_next?',ARRAY['Invalid','0','1','Toggle'],0,'S=1, R=1, Q=0: Invalid.',10);