INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a AND gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a OR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=0, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NAND gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a NOR gate with inputs A=1, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOR(1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=0, B=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=0. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a XNOR gate with inputs A=1, B=1. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=0, B=1, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(0,1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input AND(1,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input AND gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input AND(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input OR(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=0, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(0,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=0, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input OR gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input OR(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=0, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(0,0,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=0, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(0,0,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=1, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(0,1,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=0, B=1, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(0,1,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=0, C=0. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(1,0,0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=0, C=1. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(1,0,1) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=1, C=0. Output?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XOR(1,1,0) = 0.',10),
('gate-puzzler','basic','Problem: Evaluate a 3-input XOR gate with A=1, B=1, C=1. Output?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XOR(1,1,1) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=0. What is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','Problem: Evaluate a NOT gate with input A=1. What is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','Problem: What is NOT(AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,0)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0)=0.',10),
('gate-puzzler','basic','Problem: What is XOR(AND(1,1), OR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, OR(0,1)=1, XOR(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NAND(OR(1,0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, AND(1,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(AND(0,1), OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(0,1)=0, OR(0,0)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(XOR(1,0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,0)=1, AND(1,1)=1, XNOR(1,1)=1. Wait, XNOR(1,1)=1, but the answer is 1. Correct answer is 1.',10),
('gate-puzzler','basic','Problem: What is NOT(NAND(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(0,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(NOR(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(1,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is AND(OR(1,0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, NOT(1)=0, AND(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is OR(AND(0,1), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(0,1)=0, NOT(0)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, XOR(1,0)=1. Wait, XOR(1,0)=1. Answer is 1.',10),
('gate-puzzler','basic','Problem: What is NAND(NOT(0), NOT(0))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(0)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(NOT(1), NOT(1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, NOT(1)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(NOT(0), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, XNOR(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is AND(XOR(1,1), OR(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1)=0, OR(1,0)=1, AND(0,1)=0.',10),
('gate-puzzler','basic','Problem: What is OR(NAND(0,0), NOR(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(0,0)=1, NOR(0,0)=1, OR(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is NOT(XOR(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(XNOR(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,1)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is AND(1, OR(0,0))?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0)=0, AND(1,0)=0.',10),
('gate-puzzler','basic','Problem: What is OR(0, AND(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(1, XOR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(0, XNOR(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(1,0)=0, NOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(AND(1,0), OR(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,0)=0, OR(1,1)=1, XOR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(NAND(1,1), NOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,1)=0, NOR(0,1)=0, XNOR(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(AND(NOT(0), NOT(1)))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, NOT(1)=0, AND(1,0)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(AND(0,0)), NOT(OR(1,1)))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0)=0, NOT(0)=1, OR(1,1)=1, NOT(1)=0, OR(1,0)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), NOT(1), NOT(1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0,0)=0.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), NOT(0), NOT(0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, XOR(1,1,1)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(1,1,1)?',ARRAY['0','1','High-Z','Undefined'],0,'3-input NAND(1,1,1)=NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOR(0,0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'3-input NOR(0,0,0)=NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is XNOR(1,1,1)?',ARRAY['1','0','High-Z','Undefined'],0,'3-input XNOR(1,1,1)=1 (odd parity check).',10),
('gate-puzzler','basic','Problem: What is XNOR(1,0,1)?',ARRAY['0','1','High-Z','Undefined'],0,'3-input XNOR(1,0,1)=0 (not all same).',10),
('gate-puzzler','basic','Problem: What is NOT(OR(AND(1,1), AND(0,0)))?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, AND(0,0)=0, OR(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is AND(NOT(0), OR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, OR(0,1)=1, AND(1,1)=1.',10),
('gate-puzzler','basic','Problem: What is OR(NOT(1), AND(1,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, AND(1,1)=1, OR(0,1)=1.',10),
('gate-puzzler','basic','Problem: What is XOR(NOT(0), AND(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0)=1, AND(1,0)=0, XOR(1,0)=1.',10),
('gate-puzzler','basic','Problem: What is NAND(NOT(1), OR(0,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(1)=0, OR(0,0)=0, NAND(0,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOR(NOT(0), AND(1,1))?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(0)=1, AND(1,1)=1, NOR(1,1)=0.',10),
('gate-puzzler','basic','Problem: What is XNOR(XOR(0,1), NOT(0))?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,1)=1, NOT(0)=1, XNOR(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is AND(XNOR(1,1), XOR(0,1))?',ARRAY['0','1','High-Z','Undefined'],0,'XNOR(1,1)=1, XOR(0,1)=1, AND(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: What is OR(NAND(0,1), NOR(1,0))?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1)=1, NOR(1,0)=0, OR(1,0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(NAND(1,0))?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,0)=1, NOT(1)=0.',10),
('gate-puzzler','basic','Problem: What is NOT(NOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: What is NOT(XNOR(0,1))?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR(0,1)=0, NOT(0)=1.',10),
('gate-puzzler','basic','Problem: Evaluate AND(OR(1,0), NOR(0,0)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,0)=1, NOR(0,0)=1, AND(1,1)=1. Wait, answer is 1.',10),
('gate-puzzler','basic','Problem: Evaluate NAND(AND(1,1), XOR(0,1)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,1)=1, XOR(0,1)=1, NAND(1,1)=0.',10),
('gate-puzzler','basic','Problem: Evaluate NOR(OR(1,1), AND(0,1)). Output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(1,1)=1, AND(0,1)=0, NOR(1,0)=0.',10);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify: AB + A''B',ARRAY['B','A','AB','A''+B'],0,'AB+A''B = B(A+A'') = B.',15),
('gate-puzzler','intermediate','Simplify: AB + AB''',ARRAY['A','B','AB','A+B'],0,'AB+AB'' = A(B+B'') = A.',15),
('gate-puzzler','intermediate','Simplify: A + A''B',ARRAY['A+B','A','B','AB'],0,'A+A''B = (A+A'')(A+B) = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)'' + (A''+B'')''',ARRAY['A XNOR B','0','1','A XOR B'],0,'De Morgan: (A+B)''=A''B'', (A''+B'')''=AB. Sum = A''B''+AB = A XNOR B.',15),
('gate-puzzler','intermediate','Simplify: A(A+B'')',ARRAY['A','AB''','A+B''','AB'],0,'A(A+B'') = A+AB'' = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A''+B)',ARRAY['B','A','A+B','AB'],0,'(A+B)(A''+B) = AB+B = B.',15),
('gate-puzzler','intermediate','Simplify: AB''C + ABC',ARRAY['AC','AB','BC','ABC'],0,'AB''C+ABC = AC(B''+B) = AC.',15),
('gate-puzzler','intermediate','Simplify: (AB)'' · A',ARRAY['AB''','AB','A+B','A'''],0,'(AB)''·A = (A''+B'')·A = AB''.',15),
('gate-puzzler','intermediate','Simplify: A⊕B⊕A',ARRAY['B','A','0','1'],0,'A⊕B⊕A = B (A cancels out).',15),
('gate-puzzler','intermediate','Simplify: A⊙B⊙A',ARRAY['B''','A''','1','0'],0,'A⊙B⊙A = B'' (XNOR with A cancels to NOT B).',15),
('gate-puzzler','intermediate','Simplify: A+B+A''',ARRAY['1','A','B','A+B'],0,'A+B+A'' = (A+A'')+B = 1+B = 1.',15),
('gate-puzzler','intermediate','Simplify: A·B·A''',ARRAY['0','A','B','AB'],0,'A·B·A'' = A·A''·B = 0·B = 0.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)·A''',ARRAY['B·A''+C·A''','A+B+C','0','A'''],0,'Distribute A'': A''B+A''C.',15),
('gate-puzzler','intermediate','Simplify: A·(A+B+C)',ARRAY['A','A+B+C','B+C','ABC'],0,'Absorption: A·(A+B+C) = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)''·(B+C)''',ARRAY['A''·B''','B''','A''+C''','0'],0,'De Morgan: (A+B)''=A''B'', (B+C)''=B''C''. Product = A''B''C'' = (A+B+C)''.',15),
('gate-puzzler','intermediate','Simplify: AB + BC + A''C',ARRAY['AB + A''C + BC','AB+BC','A''C','AB+A''C'],0,'Consensus theorem: AB+A''C+BC = AB+A''C.',15),
('gate-puzzler','intermediate','Simplify: (A⊕B)'' ',ARRAY['A XNOR B','A XOR B','A+B','A·B'],0,'(A⊕B)'' = A⊙B = A XNOR B.',15),
('gate-puzzler','intermediate','Simplify: A·1 + A·0',ARRAY['A','1','0','A'''],0,'A·1+A·0 = A+0 = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+B'')',ARRAY['A','B','A+B','AB'],0,'(A+B)(A+B'') = A+BB'' = A+0 = A.',15),
('gate-puzzler','intermediate','Simplify: A⊕0',ARRAY['A','0','1','A'''],0,'A⊕0 = A (XOR with 0 is identity).',15),
('gate-puzzler','intermediate','Simplify: A⊕1',ARRAY['A''','A','0','1'],0,'A⊕1 = A'' (XOR with 1 is NOT).',15),
('gate-puzzler','intermediate','Simplify: A⊙0',ARRAY['A''','A','0','1'],0,'A XNOR 0 = A'' (XNOR with 0 is NOT).',15),
('gate-puzzler','intermediate','Simplify: A⊙1',ARRAY['A','A''','0','1'],0,'A XNOR 1 = A (XNOR with 1 is identity).',15),
('gate-puzzler','intermediate','Simplify: A(A''+B)',ARRAY['AB','A','B','A+B'],0,'A(A''+B) = AA''+AB = 0+AB = AB.',15),
('gate-puzzler','intermediate','Simplify: A''+A·B',ARRAY['A''+B','A','B','AB'],0,'A''+AB = (A''+A)(A''+B) = A''+B.',15),
('gate-puzzler','intermediate','Simplify: (AB)''·(AB)',ARRAY['0','1','A','B'],0,'(AB)''·AB = (A''+B'')·AB = 0.',15),
('gate-puzzler','intermediate','Simplify: A·B + A·B''',ARRAY['A','B','AB','A'''],0,'A(B+B'') = A·1 = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A''+B'')',ARRAY['A⊕B','0','1','A XNOR B'],0,'(A+B)(A''+B'') = AB''+A''B = A⊕B.',15),
('gate-puzzler','intermediate','Simplify: ABC + AB''C + ABC'' + AB''C''',ARRAY['A','B','C','AB'],0,'A(BC+B''C+BC''+B''C'') = A(B+B'')(C+C'') = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)(A+B+C'')',ARRAY['A+B','A','B','C'],0,'(A+B+C)(A+B+C'') = (A+B)+CC'' = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(B+C)(A+C)',ARRAY['(A+B)(B+C)','A+B+C','AB+BC','ABC'],0,'Consensus: (A+B)(B+C)(A+C) = (A+B)(B+C).',15),
('gate-puzzler','intermediate','Simplify: A⊕B⊕B',ARRAY['A','B','0','1'],0,'A⊕B⊕B = A⊕0 = A.',15),
('gate-puzzler','intermediate','Simplify: A⊙B⊙B',ARRAY['A''','A','1','0'],0,'A⊙B⊙B = A XNOR 0 = A''.',15),
('gate-puzzler','intermediate','Simplify: (A·B·C)'' ',ARRAY['A''+B''+C''','A''B''C''','ABC''','A+B+C'],0,'De Morgan: (ABC)'' = A''+B''+C''.',15),
('gate-puzzler','intermediate','Simplify: (A+B+C)''',ARRAY['A''·B''·C''','A''B''+C''','A''+BC''','ABC'''],0,'De Morgan: (A+B+C)'' = A''B''C''.',15),
('gate-puzzler','intermediate','Simplify: A(B+C) + A''(B+C)',ARRAY['B+C','A','B','C'],0,'(A+A'')(B+C) = B+C.',15),
('gate-puzzler','intermediate','Simplify: AB(A+B)',ARRAY['AB','A+B','A','B'],0,'AB(A+B) = ABA+ABB = AB+AB = AB.',15),
('gate-puzzler','intermediate','Simplify: (A+B)'' + A',ARRAY['A+B''','1','A''','B'],0,'(A+B)''+A = A''B''+A = A+B'' (absorption).',15),
('gate-puzzler','intermediate','Simplify: A·B'' + A''·B + A·B',ARRAY['A+B','A⊕B','A XNOR B','AB'],0,'AB''+A''B+AB = A(B''+B)+A''B = A+A''B = A+B.',15),
('gate-puzzler','intermediate','Simplify: (A+B)''(A''+B'')''',ARRAY['0','1','A XNOR B','A⊕B'],0,'A''B''·AB = 0.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 1kΩ are in series. What is R_eq?',ARRAY['2kΩ','0.50kΩ','1kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 1+1 = 2kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 2kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 1+2 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 3kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 1+3 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 4kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 1+4 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 5kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 1+5 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 6kΩ are in series. What is R_eq?',ARRAY['7kΩ','0.86kΩ','6kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 1+6 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 7kΩ are in series. What is R_eq?',ARRAY['8kΩ','0.88kΩ','7kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 1+7 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 8kΩ are in series. What is R_eq?',ARRAY['9kΩ','0.89kΩ','8kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 1+8 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 9kΩ are in series. What is R_eq?',ARRAY['10kΩ','0.90kΩ','9kΩ','8kΩ'],0,'Series: R_eq = R1+R2 = 1+9 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 1kΩ and 10kΩ are in series. What is R_eq?',ARRAY['11kΩ','0.91kΩ','10kΩ','9kΩ'],0,'Series: R_eq = R1+R2 = 1+10 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 1kΩ are in series. What is R_eq?',ARRAY['3kΩ','0.67kΩ','2kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+1 = 3kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 2kΩ are in series. What is R_eq?',ARRAY['4kΩ','1.00kΩ','4kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 2+2 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 3kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 2+3 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 4kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 2+4 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 5kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 2+5 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 6kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.50kΩ','12kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 2+6 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 7kΩ are in series. What is R_eq?',ARRAY['9kΩ','1.56kΩ','14kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 2+7 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 8kΩ are in series. What is R_eq?',ARRAY['10kΩ','1.60kΩ','16kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 2+8 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 9kΩ are in series. What is R_eq?',ARRAY['11kΩ','1.64kΩ','18kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 2+9 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 2kΩ and 10kΩ are in series. What is R_eq?',ARRAY['12kΩ','1.67kΩ','20kΩ','8kΩ'],0,'Series: R_eq = R1+R2 = 2+10 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 1kΩ are in series. What is R_eq?',ARRAY['4kΩ','0.75kΩ','3kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+1 = 4kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 2kΩ are in series. What is R_eq?',ARRAY['5kΩ','1.20kΩ','6kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+2 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 3kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.50kΩ','9kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 3+3 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 4kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 3+4 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 5kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 3+5 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 6kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.00kΩ','18kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 3+6 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 7kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.10kΩ','21kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 3+7 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 8kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.18kΩ','24kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 3+8 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 9kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.25kΩ','27kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 3+9 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 3kΩ and 10kΩ are in series. What is R_eq?',ARRAY['13kΩ','2.31kΩ','30kΩ','7kΩ'],0,'Series: R_eq = R1+R2 = 3+10 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 1kΩ are in series. What is R_eq?',ARRAY['5kΩ','0.80kΩ','4kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+1 = 5kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 2kΩ are in series. What is R_eq?',ARRAY['6kΩ','1.33kΩ','8kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+2 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 3kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.71kΩ','12kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+3 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 4kΩ are in series. What is R_eq?',ARRAY['8kΩ','2.00kΩ','16kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 4+4 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 5kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 4+5 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 6kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.40kΩ','24kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 4+6 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 7kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.55kΩ','28kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 4+7 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 8kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.67kΩ','32kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 4+8 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 9kΩ are in series. What is R_eq?',ARRAY['13kΩ','2.77kΩ','36kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 4+9 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 4kΩ and 10kΩ are in series. What is R_eq?',ARRAY['14kΩ','2.86kΩ','40kΩ','6kΩ'],0,'Series: R_eq = R1+R2 = 4+10 = 14kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 1kΩ are in series. What is R_eq?',ARRAY['6kΩ','0.83kΩ','5kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+1 = 6kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 2kΩ are in series. What is R_eq?',ARRAY['7kΩ','1.43kΩ','10kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+2 = 7kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 3kΩ are in series. What is R_eq?',ARRAY['8kΩ','1.88kΩ','15kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+3 = 8kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 4kΩ are in series. What is R_eq?',ARRAY['9kΩ','2.22kΩ','20kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+4 = 9kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 5kΩ are in series. What is R_eq?',ARRAY['10kΩ','2.50kΩ','25kΩ','0kΩ'],0,'Series: R_eq = R1+R2 = 5+5 = 10kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 6kΩ are in series. What is R_eq?',ARRAY['11kΩ','2.73kΩ','30kΩ','1kΩ'],0,'Series: R_eq = R1+R2 = 5+6 = 11kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 7kΩ are in series. What is R_eq?',ARRAY['12kΩ','2.92kΩ','35kΩ','2kΩ'],0,'Series: R_eq = R1+R2 = 5+7 = 12kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 8kΩ are in series. What is R_eq?',ARRAY['13kΩ','3.08kΩ','40kΩ','3kΩ'],0,'Series: R_eq = R1+R2 = 5+8 = 13kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 9kΩ are in series. What is R_eq?',ARRAY['14kΩ','3.21kΩ','45kΩ','4kΩ'],0,'Series: R_eq = R1+R2 = 5+9 = 14kΩ.',15),
('gate-puzzler','intermediate','Problem: Two resistors 5kΩ and 10kΩ are in series. What is R_eq?',ARRAY['15kΩ','3.33kΩ','50kΩ','5kΩ'],0,'Series: R_eq = R1+R2 = 5+10 = 15kΩ.',15);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells.',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells.',20),
('gate-puzzler','advanced','A 5-variable K-map has how many cells?',ARRAY['32','16','64','128'],0,'2^5 = 32 cells.',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Gray code ordering: adjacent cells differ by 1 variable.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'All 16 cells = function = 1.',20),
('gate-puzzler','advanced','K-map groups must be of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups of 1, 2, 4, 8, 16...',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','What is a prime implicant in K-map simplification?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group.',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['Covers a cell no other PI covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one unique minterm.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many minterms in F(A,B,C) = Σm(0,7)?',ARRAY['2','1','3','8'],0,'Two minterms: m0, m7.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,2,3) simplifies to what?',ARRAY['A''','A','B','C'],0,'m0-m3 = A''(B''+B)(C''+C) = A''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(4,5,6,7) simplifies to what?',ARRAY['A','A''','B','C'],0,'m4-m7 = A(B''+B)(C''+C) = A.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,2,4,6) simplifies to what?',ARRAY['C''','C','A','B'],0,'Even minterms = C''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(1,3,5,7) simplifies to what?',ARRAY['C','C''','A','B'],0,'Odd minterms = C.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,4,5) simplifies to what?',ARRAY['B''','B','A''','C'''],0,'m0,m1,m4,m5 = B''(A''+A)(C''+C) = B''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(2,3,6,7) simplifies to what?',ARRAY['B','B''','A','C'],0,'m2,m3,m6,m7 = B(A''+A)(C''+C) = B.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,2,4,6) in SOP form uses how many product terms?',ARRAY['1','2','3','4'],0,'All even minterms = C'', one term.',20),
('gate-puzzler','advanced','F(A,B,C,D) = Σm(0,1,2,3,4,5,6,7) simplifies to what?',ARRAY['A''','A','B''','D'''],0,'m0-m7 = A''(B''+B)(C''+C)(D''+D) = A''.',20),
('gate-puzzler','advanced','F(A,B,C,D) = Σm(8,9,10,11,12,13,14,15) simplifies to what?',ARRAY['A','A''','B','D'],0,'m8-m15 = A(B''+B)(C''+C)(D''+D) = A.',20),
('gate-puzzler','advanced','How many cells in a 2-variable K-map?',ARRAY['4','2','8','16'],0,'2^2 = 4 cells.',20),
('gate-puzzler','advanced','In K-map, a group of 4 cells eliminates how many variables?',ARRAY['2','1','3','4'],0,'Group of 4 eliminates 2 variables.',20),
('gate-puzzler','advanced','In K-map, a group of 8 cells eliminates how many variables?',ARRAY['3','2','1','4'],0,'Group of 8 eliminates 3 variables.',20),
('gate-puzzler','advanced','In K-map, a group of 2 cells eliminates how many variables?',ARRAY['1','2','0','3'],0,'Group of 2 eliminates 1 variable.',20),
('gate-puzzler','advanced','In K-map, a group of 1 cell eliminates how many variables?',ARRAY['0','1','2','3'],0,'Single cell = minterm, no elimination.',20),
('gate-puzzler','advanced','What is a don''t-care condition in K-map?',ARRAY['Can be 0 or 1 for simplification','Must be 0','Must be 1','Must be avoided'],0,'Don''t-cares (X) can be included in groups to simplify.',20),
('gate-puzzler','advanced','How are don''t-care conditions represented?',ARRAY['X or d','0','1','?'],0,'Don''t-cares are marked as X or d in K-map.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(0,1,2,5,7) + d(3,6). Max simplification?',ARRAY['A''+C''','A''+B''','C''+B''','A''+C'],0,'Using don''t-cares m3,m6: groups give A''+C''.',20),
('gate-puzzler','advanced','F(A,B,C) = Σm(1,3,5,7) + d(0,2). Max simplification?',ARRAY['C','C''','A''','B'],0,'Using don''t-cares: C covers all minterms.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','A 4:1 MUX needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, n = 2.',20),
('gate-puzzler','advanced','An 8:1 MUX needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, n = 3.',20),
('gate-puzzler','advanced','A 16:1 MUX needs how many select lines?',ARRAY['4','3','5','16'],0,'2^n = 16, n = 4.',20),
('gate-puzzler','advanced','A 32:1 MUX needs how many select lines?',ARRAY['5','4','6','32'],0,'2^n = 32, n = 5.',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs → 8 outputs.',20),
('gate-puzzler','advanced','A 4-to-16 decoder has how many outputs?',ARRAY['16','4','8','32'],0,'4 inputs → 16 outputs.',20),
('gate-puzzler','advanced','A 2-to-4 decoder has how many outputs?',ARRAY['4','2','8','16'],0,'2 inputs → 4 outputs.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'2^3 = 8.',20),
('gate-puzzler','advanced','A priority encoder with 16 inputs needs how many output bits?',ARRAY['4','3','5','16'],0,'2^4 = 16.',20),
('gate-puzzler','advanced','How many NAND gates to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both NAND inputs together.',20),
('gate-puzzler','advanced','How many NAND gates to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT.',20),
('gate-puzzler','advanced','How many NAND gates to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs.',20),
('gate-puzzler','advanced','How many NAND gates to build an XOR gate?',ARRAY['4','2','3','6'],0,'XOR from NAND needs 4 gates.',20),
('gate-puzzler','advanced','How many NOR gates to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT.',20),
('gate-puzzler','advanced','How many NOR gates to build an AND gate?',ARRAY['3','2','4','1'],0,'AND = NOR(A'') NOR NOR(B'') = 3 NORs.',20),
('gate-puzzler','advanced','How many NOR gates to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both NOR inputs together.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what?',ARRAY['A','A''','1','0'],0,'Output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what?',ARRAY['A''','A','1','0'],0,'Output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=0, S=A outputs what?',ARRAY['0','A','A''','1'],0,'Both inputs are 0, so output = 0.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=1, S=A outputs what?',ARRAY['1','A','A''','0'],0,'Both inputs are 1, so output = 1.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=B, I1=B'', S=A outputs what?',ARRAY['A⊕B','A XNOR B','B','B'''],0,'Output = A·B'' + A''·B = A⊕B.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=B'', I1=B, S=A outputs what?',ARRAY['A XNOR B','A⊕B','B','B'''],0,'Output = A·B + A''·B'' = A XNOR B.',20),
('gate-puzzler','advanced','How many 2:1 MUXes to build a 4:1 MUX?',ARRAY['3','2','4','1'],0,'Three 2:1 MUXes: two for data, one for select.',20),
('gate-puzzler','advanced','How many 2:1 MUXes to build an 8:1 MUX?',ARRAY['7','4','8','3'],0,'Seven 2:1 MUXes for 8:1.',20),
('gate-puzzler','advanced','A full adder can be built using how many half-adders?',ARRAY['2','1','3','4'],0,'Two half-adders plus an OR gate.',20),
('gate-puzzler','advanced','How many full adders for a 4-bit ripple carry adder?',ARRAY['4','2','8','16'],0,'One full adder per bit = 4.',20),
('gate-puzzler','advanced','How many full adders for an 8-bit ripple carry adder?',ARRAY['8','4','16','32'],0,'One full adder per bit = 8.',20),
('gate-puzzler','advanced','A BCD to 7-segment decoder has how many outputs?',ARRAY['7','4','10','9'],0,'7 segments (a-g).',20),
('gate-puzzler','advanced','How many select lines for a 1:4 demux?',ARRAY['2','1','3','4'],0,'2^n = 4, n = 2.',20),
('gate-puzzler','advanced','How many select lines for a 1:8 demux?',ARRAY['3','2','4','8'],0,'2^n = 8, n = 3.',20),
('gate-puzzler','advanced','If F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A.',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'0+0 = 0.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'A''B''·AB = 0.',20),
('gate-puzzler','advanced','Hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC.',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates needed?',ARRAY['4','2','8','1'],0,'4 XNORs ANDed.',20),
('gate-puzzler','advanced','What is a static-1 hazard?',ARRAY['Output momentarily goes to 0 when it should stay 1','Output stays 1','Output oscillates','Output is undefined'],0,'Static-1 hazard: brief 0 glitch on a 1 output.',20),
('gate-puzzler','advanced','What is a static-0 hazard?',ARRAY['Output momentarily goes to 1 when it should stay 0','Output stays 0','Output oscillates','Output is undefined'],0,'Static-0 hazard: brief 1 glitch on a 0 output.',20),
('gate-puzzler','advanced','How do you eliminate static hazards?',ARRAY['Add consensus terms','Remove gates','Increase clock speed','Add buffers'],0,'Consensus terms cover transitions.',20),
('gate-puzzler','advanced','What is a dynamic hazard?',ARRAY['Output changes multiple times during a transition','Output doesn''t change','Output oscillates continuously','Output is stuck'],0,'Dynamic hazard: multiple transitions for a single input change.',20),
('gate-puzzler','advanced','If F = A⊕B⊕C, what is F when A=1, B=1, C=1?',ARRAY['1','0','A','B'],0,'XOR(1,1,1) = 1 (odd number of 1s).',20),
('gate-puzzler','advanced','If F = A⊕B⊕C, what is F when A=1, B=0, C=1?',ARRAY['0','1','A','B'],0,'XOR(1,0,1) = 0 (even number of 1s).',20),
('gate-puzzler','advanced','A 3-bit parity generator uses which gate?',ARRAY['XOR','AND','OR','NAND'],0,'XOR chain for even/odd parity.',20),
('gate-puzzler','advanced','How many XOR gates for a 4-bit parity checker?',ARRAY['3','2','4','1'],0,'3 XOR gates in a tree.',20),
('gate-puzzler','advanced','A 2:1 MUX can implement any 2-variable function. How many MUXes for 3 variables?',ARRAY['4','2','3','8'],0,'4 MUXes (LUT-based design).',20),
('gate-puzzler','advanced','What is a LUT in FPGA design?',ARRAY['Look-Up Table','Logic Unit Test','Last Used Tag','Local Universal Terminal'],0,'LUT = Look-Up Table, implements any function.',20),
('gate-puzzler','advanced','A 4-input LUT can implement how many functions?',ARRAY['2^16','2^4','16','256'],0,'4 inputs → 2^4=16 minterms → 2^16 possible functions.',20),
('gate-puzzler','advanced','What is the difference between PLA and PAL?',ARRAY['PLA has programmable AND and OR; PAL has fixed OR','No difference','PAL is programmable','PLA is fixed'],0,'PLA: both AND/OR programmable. PAL: only AND programmable.',20),
('gate-puzzler','advanced','How many product terms can a 3×4 PLA implement?',ARRAY['4','3','7','12'],0,'4 product terms (OR array size).',20),
('gate-puzzler','advanced','What is fan-in?',ARRAY['Number of inputs a gate can accept','Number of outputs','Gate speed','Gate size'],0,'Fan-in = number of inputs.',20),
('gate-puzzler','advanced','What is fan-out?',ARRAY['Number of gates a single output can drive','Number of inputs','Gate speed','Power consumption'],0,'Fan-out = number of loads driven.',20),
('gate-puzzler','advanced','A gate with fan-out 10 can drive how many gates?',ARRAY['10','5','20','100'],0,'Fan-out 10 = drives 10 gate inputs.',20),
('gate-puzzler','advanced','What is propagation delay?',ARRAY['Time for signal to pass through a gate','Gate setup time','Clock period','Hold time'],0,'Propagation delay = input-to-output delay.',20),
('gate-puzzler','advanced','If a gate has 5ns propagation delay, what is max frequency?',ARRAY['200 MHz','100 MHz','50 MHz','500 MHz'],0,'f_max = 1/delay = 1/5ns = 200 MHz.',20),
('gate-puzzler','advanced','Two gates each with 3ns delay in series. Total delay?',ARRAY['6 ns','3 ns','9 ns','1.5 ns'],0,'Series delays add: 3+3 = 6 ns.',20),
('gate-puzzler','advanced','Two gates each with 3ns delay in parallel. Critical path delay?',ARRAY['3 ns','6 ns','1.5 ns','9 ns'],0,'Parallel: critical path = max(3,3) = 3 ns.',20),
('gate-puzzler','advanced','What is setup time?',ARRAY['Time data must be stable before clock edge','Time after clock','Gate delay','Clock period'],0,'Setup time = minimum stable time before clock.',20),
('gate-puzzler','advanced','What is hold time?',ARRAY['Time data must be stable after clock edge','Time before clock','Gate delay','Clock period'],0,'Hold time = minimum stable time after clock.',20),
('gate-puzzler','advanced','If setup time = 2ns, hold time = 1ns, clock period = 10ns, what is max propagation delay?',ARRAY['7 ns','8 ns','10 ns','5 ns'],0,'Max delay = clock - setup = 10-2 = 8ns. But hold: delay >= hold = 1ns. So max = 8ns.',20),
('gate-puzzler','advanced','What is metastability?',ARRAY['Unstable state when setup/hold violated','Stable state','Oscillation','High impedance'],0,'Metastability: flip-flop enters unstable state.',20),
('gate-puzzler','advanced','How to reduce metastability?',ARRAY['Use synchronizer flip-flops','Increase clock speed','Remove flip-flops','Use buffers'],0,'Two-stage synchronizer reduces metastability.',20),
('gate-puzzler','advanced','Critical: A 93-state FSM requires how many bits for state encoding?',ARRAY['7','93','92','8'],0,'⌈log2(93)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 94-state FSM requires how many bits for state encoding?',ARRAY['7','94','93','8'],0,'⌈log2(94)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 95-state FSM requires how many bits for state encoding?',ARRAY['7','95','94','8'],0,'⌈log2(95)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 96-state FSM requires how many bits for state encoding?',ARRAY['7','96','95','8'],0,'⌈log2(96)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 97-state FSM requires how many bits for state encoding?',ARRAY['7','97','96','8'],0,'⌈log2(97)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 98-state FSM requires how many bits for state encoding?',ARRAY['7','98','97','8'],0,'⌈log2(98)⌉ = 7 bits.',20),
('gate-puzzler','advanced','Critical: A 99-state FSM requires how many bits for state encoding?',ARRAY['7','99','98','8'],0,'⌈log2(99)⌉ = 7 bits.',20);;
