INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','Problem: D flip-flop with D=0, clock=no edge. What is Q_next?',ARRAY['Q (hold)','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=0, clock=rising edge. What is Q_next?',ARRAY['0','1','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 0. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=no edge. What is Q_next?',ARRAY['Q (hold)','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: D flip-flop with D=1, clock=rising edge. What is Q_next?',ARRAY['1','0','0','1'],0,'D flip-flop: on clock edge, Q_next = D = 1. Without edge, Q holds.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'J=0, K=0: Hold.',10),
('state-machine','basic','Problem: JK flip-flop has J=0, K=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'J=0, K=1: Reset (0).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'J=1, K=0: Set (1).',10),
('state-machine','basic','Problem: JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','Reset','Set'],0,'J=1, K=1: Toggle.',10),
('state-machine','basic','Problem: T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold.',10),
('state-machine','basic','Problem: T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle.',10),
('state-machine','basic','Problem: SR latch has S=0, R=0. What is the next state?',ARRAY['Hold','Hold','Reset','Set'],0,'S=0, R=0: Hold.',10),
('state-machine','basic','Problem: SR latch has S=0, R=1. What is the next state?',ARRAY['Reset (0)','Hold','Reset','Set'],0,'S=0, R=1: Reset (0).',10),
('state-machine','basic','Problem: SR latch has S=1, R=0. What is the next state?',ARRAY['Set (1)','Hold','Reset','Set'],0,'S=1, R=0: Set (1).',10),
('state-machine','basic','Problem: SR latch has S=1, R=1. What is the next state?',ARRAY['Invalid','Hold','Reset','Set'],0,'S=1, R=1: Invalid.',10),
('state-machine','basic','Problem: A state machine has 2 states. How many flip-flops are needed?',ARRAY['1','2','1','4'],0,'Need ⌈log2(2)⌉ = 1 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 3 states. How many flip-flops are needed?',ARRAY['2','3','1.5','6'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 5 states. How many flip-flops are needed?',ARRAY['3','5','2.5','10'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 6 states. How many flip-flops are needed?',ARRAY['3','6','3','12'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 8 states. How many flip-flops are needed?',ARRAY['3','8','4','16'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 12 states. How many flip-flops are needed?',ARRAY['4','12','6','24'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 14 states. How many flip-flops are needed?',ARRAY['4','14','7','28'],0,'Need ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 15 states. How many flip-flops are needed?',ARRAY['4','15','7.5','30'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 17 states. How many flip-flops are needed?',ARRAY['5','17','8.5','34'],0,'Need ⌈log2(17)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 18 states. How many flip-flops are needed?',ARRAY['5','18','9','36'],0,'Need ⌈log2(18)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 19 states. How many flip-flops are needed?',ARRAY['5','19','9.5','38'],0,'Need ⌈log2(19)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A state machine has 20 states. How many flip-flops are needed?',ARRAY['5','20','10','40'],0,'Need ⌈log2(20)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: D flip-flop has D=0, current Q=0. After clock edge, what is Q?',ARRAY['0','0','1','1'],0,'On clock edge, Q_next = D = 0 regardless of current Q=0.',10),
('state-machine','basic','Problem: D flip-flop has D=0, current Q=1. After clock edge, what is Q?',ARRAY['0','1','1','0'],0,'On clock edge, Q_next = D = 0 regardless of current Q=1.',10),
('state-machine','basic','Problem: D flip-flop has D=1, current Q=0. After clock edge, what is Q?',ARRAY['1','0','0','1'],0,'On clock edge, Q_next = D = 1 regardless of current Q=0.',10),
('state-machine','basic','Problem: D flip-flop has D=1, current Q=1. After clock edge, what is Q?',ARRAY['1','1','0','0'],0,'On clock edge, Q_next = D = 1 regardless of current Q=1.',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=0, current Q=0. What is Q_next?',ARRAY['Q (stays 0)','0','1','Toggle'],0,'J=0, K=0, Q=0: Q (stays 0).',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=0, current Q=1. What is Q_next?',ARRAY['Q (stays 1)','0','1','Toggle'],0,'J=0, K=0, Q=1: Q (stays 1).',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=1, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=0, K=1, Q=0: 0.',10),
('state-machine','basic','Problem: JK flip-flop J=0, K=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=0, K=1, Q=1: 0.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=0, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=0, Q=0: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=0, Q=1: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=1, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'J=1, K=1, Q=0: 1.',10),
('state-machine','basic','Problem: JK flip-flop J=1, K=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'J=1, K=1, Q=1: 0.',10),
('state-machine','basic','Problem: T flip-flop T=0, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'T=0, Q=0: Q_next = 0.',10),
('state-machine','basic','Problem: T flip-flop T=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'T=0, Q=1: Q_next = 1.',10),
('state-machine','basic','Problem: T flip-flop T=1, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'T=1, Q=0: Q_next = 1.',10),
('state-machine','basic','Problem: T flip-flop T=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'T=1, Q=1: Q_next = 0.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 2. How many flip-flops needed?',ARRAY['1','2','1','3'],0,'Divide by 2 needs ⌈log2(2)⌉ = 1 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 3. How many flip-flops needed?',ARRAY['2','3','2','4'],0,'Divide by 3 needs ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 4. How many flip-flops needed?',ARRAY['2','4','3','5'],0,'Divide by 4 needs ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 5. How many flip-flops needed?',ARRAY['3','5','4','6'],0,'Divide by 5 needs ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 6. How many flip-flops needed?',ARRAY['3','6','5','7'],0,'Divide by 6 needs ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 7. How many flip-flops needed?',ARRAY['3','7','6','8'],0,'Divide by 7 needs ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 8. How many flip-flops needed?',ARRAY['3','8','7','9'],0,'Divide by 8 needs ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 9. How many flip-flops needed?',ARRAY['4','9','8','10'],0,'Divide by 9 needs ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 10. How many flip-flops needed?',ARRAY['4','10','9','11'],0,'Divide by 10 needs ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 11. How many flip-flops needed?',ARRAY['4','11','10','12'],0,'Divide by 11 needs ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 12. How many flip-flops needed?',ARRAY['4','12','11','13'],0,'Divide by 12 needs ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 13. How many flip-flops needed?',ARRAY['4','13','12','14'],0,'Divide by 13 needs ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 14. How many flip-flops needed?',ARRAY['4','14','13','15'],0,'Divide by 14 needs ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 15. How many flip-flops needed?',ARRAY['4','15','14','16'],0,'Divide by 15 needs ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A ripple counter divides clock by 16. How many flip-flops needed?',ARRAY['4','16','15','17'],0,'Divide by 16 needs ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-3 counter needs how many flip-flops?',ARRAY['2','3','2','4'],0,'Mod-3 needs ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Mod-4 needs ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','Problem: A mod-5 counter needs how many flip-flops?',ARRAY['3','5','4','6'],0,'Mod-5 needs ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Mod-6 needs ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-7 counter needs how many flip-flops?',ARRAY['3','7','6','8'],0,'Mod-7 needs ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-8 counter needs how many flip-flops?',ARRAY['3','8','7','9'],0,'Mod-8 needs ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','Problem: A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Mod-9 needs ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Mod-10 needs ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-11 counter needs how many flip-flops?',ARRAY['4','11','10','12'],0,'Mod-11 needs ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Mod-12 needs ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Mod-13 needs ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-14 counter needs how many flip-flops?',ARRAY['4','14','13','15'],0,'Mod-14 needs ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-15 counter needs how many flip-flops?',ARRAY['4','15','14','16'],0,'Mod-15 needs ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-16 counter needs how many flip-flops?',ARRAY['4','16','15','17'],0,'Mod-16 needs ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','Problem: A mod-17 counter needs how many flip-flops?',ARRAY['5','17','16','18'],0,'Mod-17 needs ⌈log2(17)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-18 counter needs how many flip-flops?',ARRAY['5','18','17','19'],0,'Mod-18 needs ⌈log2(18)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-19 counter needs how many flip-flops?',ARRAY['5','19','18','20'],0,'Mod-19 needs ⌈log2(19)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A mod-20 counter needs how many flip-flops?',ARRAY['5','20','19','21'],0,'Mod-20 needs ⌈log2(20)⌉ = 5 flip-flops.',10),
('state-machine','basic','Problem: A truth table with 2 inputs has how many rows?',ARRAY['4','2','4','3'],0,'2^2 = 4 rows.',10),
('state-machine','basic','Problem: A truth table with 3 inputs has how many rows?',ARRAY['8','3','6','4'],0,'2^3 = 8 rows.',10),
('state-machine','basic','Problem: A truth table with 4 inputs has how many rows?',ARRAY['16','4','8','5'],0,'2^4 = 16 rows.',10),
('state-machine','basic','Problem: A truth table with 5 inputs has how many rows?',ARRAY['32','5','10','6'],0,'2^5 = 32 rows.',10),
('state-machine','basic','Problem: A truth table with 6 inputs has how many rows?',ARRAY['64','6','12','7'],0,'2^6 = 64 rows.',10),
('state-machine','basic','Problem: A truth table with 7 inputs has how many rows?',ARRAY['128','7','14','8'],0,'2^7 = 128 rows.',10),
('state-machine','basic','Problem: A truth table with 8 inputs has how many rows?',ARRAY['256','8','16','9'],0,'2^8 = 256 rows.',10),
('state-machine','basic','Problem: A truth table with 9 inputs has how many rows?',ARRAY['512','9','18','10'],0,'2^9 = 512 rows.',10),
('state-machine','basic','Problem: A truth table with 10 inputs has how many rows?',ARRAY['1024','10','20','11'],0,'2^10 = 1024 rows.',10),
('state-machine','basic','Problem: A D flip-flop has D=0. What is Q'' (complement output) after clock?',ARRAY['1','0','High-Z','Undefined'],0,'Q_next = D = 0, so Q'' = 1.',10),
('state-machine','basic','Problem: A D flip-flop has D=1. What is Q'' (complement output) after clock?',ARRAY['0','1','High-Z','Undefined'],0,'Q_next = D = 1, so Q'' = 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=0, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=0, Q=0: 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=0, R=0, Q=1: 1.',10),
('state-machine','basic','Problem: SR latch S=0, R=1, current Q=0. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=1, Q=0: 0.',10),
('state-machine','basic','Problem: SR latch S=0, R=1, current Q=1. What is Q_next?',ARRAY['0','0','1','Toggle'],0,'S=0, R=1, Q=1: 0.',10),
('state-machine','basic','Problem: SR latch S=1, R=0, current Q=0. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=1, R=0, Q=0: 1.',10),
('state-machine','basic','Problem: SR latch S=1, R=0, current Q=1. What is Q_next?',ARRAY['1','0','1','Toggle'],0,'S=1, R=0, Q=1: 1.',10),
('state-machine','basic','Problem: SR latch S=1, R=1, current Q=0. What is Q_next?',ARRAY['Invalid','0','1','Toggle'],0,'S=1, R=1, Q=0: Invalid.',10);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','intermediate','Problem: A 2-bit ripple counter has how many states?',ARRAY['4','2','3','4'],0,'2-bit counter: 2^2 = 4 states.',15),
('state-machine','intermediate','Problem: A 3-bit ripple counter has how many states?',ARRAY['8','3','4','6'],0,'3-bit counter: 2^3 = 8 states.',15),
('state-machine','intermediate','Problem: A 4-bit ripple counter has how many states?',ARRAY['16','4','5','8'],0,'4-bit counter: 2^4 = 16 states.',15),
('state-machine','intermediate','Problem: A 5-bit ripple counter has how many states?',ARRAY['32','5','6','10'],0,'5-bit counter: 2^5 = 32 states.',15),
('state-machine','intermediate','Problem: A 6-bit ripple counter has how many states?',ARRAY['64','6','7','12'],0,'6-bit counter: 2^6 = 64 states.',15),
('state-machine','intermediate','Problem: A 7-bit ripple counter has how many states?',ARRAY['128','7','8','14'],0,'7-bit counter: 2^7 = 128 states.',15),
('state-machine','intermediate','Problem: A 8-bit ripple counter has how many states?',ARRAY['256','8','9','16'],0,'8-bit counter: 2^8 = 256 states.',15),
('state-machine','intermediate','Problem: A 9-bit ripple counter has how many states?',ARRAY['512','9','10','18'],0,'9-bit counter: 2^9 = 512 states.',15),
('state-machine','intermediate','Problem: A 10-bit ripple counter has how many states?',ARRAY['1024','10','11','20'],0,'10-bit counter: 2^10 = 1024 states.',15),
('state-machine','intermediate','Problem: A 11-bit ripple counter has how many states?',ARRAY['2048','11','12','22'],0,'11-bit counter: 2^11 = 2048 states.',15),
('state-machine','intermediate','Problem: A 12-bit ripple counter has how many states?',ARRAY['4096','12','13','24'],0,'12-bit counter: 2^12 = 4096 states.',15),
('state-machine','intermediate','Problem: A 13-bit ripple counter has how many states?',ARRAY['8192','13','14','26'],0,'13-bit counter: 2^13 = 8192 states.',15),
('state-machine','intermediate','Problem: A 14-bit ripple counter has how many states?',ARRAY['16384','14','15','28'],0,'14-bit counter: 2^14 = 16384 states.',15),
('state-machine','intermediate','Problem: A 15-bit ripple counter has how many states?',ARRAY['32768','15','16','30'],0,'15-bit counter: 2^15 = 32768 states.',15),
('state-machine','intermediate','Problem: A 16-bit ripple counter has how many states?',ARRAY['65536','16','17','32'],0,'16-bit counter: 2^16 = 65536 states.',15),
('state-machine','intermediate','Problem: A mod-3 counter needs how many flip-flops?',ARRAY['2','3','2','4'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-5 counter needs how many flip-flops?',ARRAY['3','5','4','6'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-7 counter needs how many flip-flops?',ARRAY['3','7','6','8'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-8 counter needs how many flip-flops?',ARRAY['3','8','7','9'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-11 counter needs how many flip-flops?',ARRAY['4','11','10','12'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-14 counter needs how many flip-flops?',ARRAY['4','14','13','15'],0,'Need ⌈log2(14)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-15 counter needs how many flip-flops?',ARRAY['4','15','14','16'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A mod-16 counter needs how many flip-flops?',ARRAY['4','16','15','17'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: 2-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['250 Hz','1000 Hz','500 Hz','4000 Hz'],0,'2-bit counter divides by 2^2=4: 1000/4 = 250 Hz.',15),
('state-machine','intermediate','Problem: 3-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['125 Hz','1000 Hz','250 Hz','8000 Hz'],0,'3-bit counter divides by 2^3=8: 1000/8 = 125 Hz.',15),
('state-machine','intermediate','Problem: 4-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['63 Hz','1000 Hz','125 Hz','16000 Hz'],0,'4-bit counter divides by 2^4=16: 1000/16 = 63 Hz.',15),
('state-machine','intermediate','Problem: 5-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['31 Hz','1000 Hz','63 Hz','32000 Hz'],0,'5-bit counter divides by 2^5=32: 1000/32 = 31 Hz.',15),
('state-machine','intermediate','Problem: 6-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['16 Hz','1000 Hz','31 Hz','64000 Hz'],0,'6-bit counter divides by 2^6=64: 1000/64 = 16 Hz.',15),
('state-machine','intermediate','Problem: 7-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['8 Hz','1000 Hz','16 Hz','128000 Hz'],0,'7-bit counter divides by 2^7=128: 1000/128 = 8 Hz.',15),
('state-machine','intermediate','Problem: 8-bit ripple counter clocked at 1000 Hz. Find MSB output frequency.',ARRAY['4 Hz','1000 Hz','8 Hz','256000 Hz'],0,'8-bit counter divides by 2^8=256: 1000/256 = 4 Hz.',15),
('state-machine','intermediate','Problem: 2-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['2500 Hz','10000 Hz','5000 Hz','40000 Hz'],0,'2-bit counter divides by 2^2=4: 10000/4 = 2500 Hz.',15),
('state-machine','intermediate','Problem: 3-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['1250 Hz','10000 Hz','2500 Hz','80000 Hz'],0,'3-bit counter divides by 2^3=8: 10000/8 = 1250 Hz.',15),
('state-machine','intermediate','Problem: 4-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['625 Hz','10000 Hz','1250 Hz','160000 Hz'],0,'4-bit counter divides by 2^4=16: 10000/16 = 625 Hz.',15),
('state-machine','intermediate','Problem: 5-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['313 Hz','10000 Hz','625 Hz','320000 Hz'],0,'5-bit counter divides by 2^5=32: 10000/32 = 313 Hz.',15),
('state-machine','intermediate','Problem: 6-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['156 Hz','10000 Hz','313 Hz','640000 Hz'],0,'6-bit counter divides by 2^6=64: 10000/64 = 156 Hz.',15),
('state-machine','intermediate','Problem: 7-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['78 Hz','10000 Hz','156 Hz','1280000 Hz'],0,'7-bit counter divides by 2^7=128: 10000/128 = 78 Hz.',15),
('state-machine','intermediate','Problem: 8-bit ripple counter clocked at 10000 Hz. Find MSB output frequency.',ARRAY['39 Hz','10000 Hz','78 Hz','2560000 Hz'],0,'8-bit counter divides by 2^8=256: 10000/256 = 39 Hz.',15),
('state-machine','intermediate','Problem: 2-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['25000 Hz','100000 Hz','50000 Hz','400000 Hz'],0,'2-bit counter divides by 2^2=4: 100000/4 = 25000 Hz.',15),
('state-machine','intermediate','Problem: 3-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['12500 Hz','100000 Hz','25000 Hz','800000 Hz'],0,'3-bit counter divides by 2^3=8: 100000/8 = 12500 Hz.',15),
('state-machine','intermediate','Problem: 4-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['6250 Hz','100000 Hz','12500 Hz','1600000 Hz'],0,'4-bit counter divides by 2^4=16: 100000/16 = 6250 Hz.',15),
('state-machine','intermediate','Problem: 5-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['3125 Hz','100000 Hz','6250 Hz','3200000 Hz'],0,'5-bit counter divides by 2^5=32: 100000/32 = 3125 Hz.',15),
('state-machine','intermediate','Problem: 6-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['1563 Hz','100000 Hz','3125 Hz','6400000 Hz'],0,'6-bit counter divides by 2^6=64: 100000/64 = 1563 Hz.',15),
('state-machine','intermediate','Problem: 7-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['781 Hz','100000 Hz','1563 Hz','12800000 Hz'],0,'7-bit counter divides by 2^7=128: 100000/128 = 781 Hz.',15),
('state-machine','intermediate','Problem: 8-bit ripple counter clocked at 100000 Hz. Find MSB output frequency.',ARRAY['391 Hz','100000 Hz','781 Hz','25600000 Hz'],0,'8-bit counter divides by 2^8=256: 100000/256 = 391 Hz.',15),
('state-machine','intermediate','Problem: 2-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['250000 Hz','1000000 Hz','500000 Hz','4000000 Hz'],0,'2-bit counter divides by 2^2=4: 1000000/4 = 250000 Hz.',15),
('state-machine','intermediate','Problem: 3-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['125000 Hz','1000000 Hz','250000 Hz','8000000 Hz'],0,'3-bit counter divides by 2^3=8: 1000000/8 = 125000 Hz.',15),
('state-machine','intermediate','Problem: 4-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['62500 Hz','1000000 Hz','125000 Hz','16000000 Hz'],0,'4-bit counter divides by 2^4=16: 1000000/16 = 62500 Hz.',15),
('state-machine','intermediate','Problem: 5-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['31250 Hz','1000000 Hz','62500 Hz','32000000 Hz'],0,'5-bit counter divides by 2^5=32: 1000000/32 = 31250 Hz.',15),
('state-machine','intermediate','Problem: 6-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['15625 Hz','1000000 Hz','31250 Hz','64000000 Hz'],0,'6-bit counter divides by 2^6=64: 1000000/64 = 15625 Hz.',15),
('state-machine','intermediate','Problem: 7-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['7813 Hz','1000000 Hz','15625 Hz','128000000 Hz'],0,'7-bit counter divides by 2^7=128: 1000000/128 = 7813 Hz.',15),
('state-machine','intermediate','Problem: 8-bit ripple counter clocked at 1000000 Hz. Find MSB output frequency.',ARRAY['3906 Hz','1000000 Hz','7813 Hz','256000000 Hz'],0,'8-bit counter divides by 2^8=256: 1000000/256 = 3906 Hz.',15),
('state-machine','intermediate','Problem: A Moore machine with 2 states. How many flip-flops for binary encoding?',ARRAY['1','2','1','2'],0,'Binary encoding: ⌈log2(2)⌉ = 1 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 3 states. How many flip-flops for binary encoding?',ARRAY['2','3','2','3'],0,'Binary encoding: ⌈log2(3)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 4 states. How many flip-flops for binary encoding?',ARRAY['2','4','3','3'],0,'Binary encoding: ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 5 states. How many flip-flops for binary encoding?',ARRAY['3','5','4','4'],0,'Binary encoding: ⌈log2(5)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 6 states. How many flip-flops for binary encoding?',ARRAY['3','6','5','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 7 states. How many flip-flops for binary encoding?',ARRAY['3','7','6','4'],0,'Binary encoding: ⌈log2(7)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 8 states. How many flip-flops for binary encoding?',ARRAY['3','8','7','4'],0,'Binary encoding: ⌈log2(8)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 9 states. How many flip-flops for binary encoding?',ARRAY['4','9','8','5'],0,'Binary encoding: ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 10 states. How many flip-flops for binary encoding?',ARRAY['4','10','9','5'],0,'Binary encoding: ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 11 states. How many flip-flops for binary encoding?',ARRAY['4','11','10','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 12 states. How many flip-flops for binary encoding?',ARRAY['4','12','11','5'],0,'Binary encoding: ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 13 states. How many flip-flops for binary encoding?',ARRAY['4','13','12','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 14 states. How many flip-flops for binary encoding?',ARRAY['4','14','13','5'],0,'Binary encoding: ⌈log2(14)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 15 states. How many flip-flops for binary encoding?',ARRAY['4','15','14','5'],0,'Binary encoding: ⌈log2(15)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A Moore machine with 16 states. How many flip-flops for binary encoding?',ARRAY['4','16','15','5'],0,'Binary encoding: ⌈log2(16)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 2, how many flip-flops are needed in a ripple counter?',ARRAY['1','2','1','3'],0,'Divide by 2 needs ⌈log2(2)⌉ = 1 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 3, how many flip-flops are needed in a ripple counter?',ARRAY['2','3','2','4'],0,'Divide by 3 needs ⌈log2(3)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 4, how many flip-flops are needed in a ripple counter?',ARRAY['2','4','3','5'],0,'Divide by 4 needs ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 5, how many flip-flops are needed in a ripple counter?',ARRAY['3','5','4','6'],0,'Divide by 5 needs ⌈log2(5)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 6, how many flip-flops are needed in a ripple counter?',ARRAY['3','6','5','7'],0,'Divide by 6 needs ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 7, how many flip-flops are needed in a ripple counter?',ARRAY['3','7','6','8'],0,'Divide by 7 needs ⌈log2(7)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 8, how many flip-flops are needed in a ripple counter?',ARRAY['3','8','7','9'],0,'Divide by 8 needs ⌈log2(8)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 9, how many flip-flops are needed in a ripple counter?',ARRAY['4','9','8','10'],0,'Divide by 9 needs ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 10, how many flip-flops are needed in a ripple counter?',ARRAY['4','10','9','11'],0,'Divide by 10 needs ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 11, how many flip-flops are needed in a ripple counter?',ARRAY['4','11','10','12'],0,'Divide by 11 needs ⌈log2(11)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 12, how many flip-flops are needed in a ripple counter?',ARRAY['4','12','11','13'],0,'Divide by 12 needs ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 13, how many flip-flops are needed in a ripple counter?',ARRAY['4','13','12','14'],0,'Divide by 13 needs ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 14, how many flip-flops are needed in a ripple counter?',ARRAY['4','14','13','15'],0,'Divide by 14 needs ⌈log2(14)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 15, how many flip-flops are needed in a ripple counter?',ARRAY['4','15','14','16'],0,'Divide by 15 needs ⌈log2(15)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: To divide a clock by 16, how many flip-flops are needed in a ripple counter?',ARRAY['4','16','15','17'],0,'Divide by 16 needs ⌈log2(16)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','Problem: A 4-bit ring counter has how many valid states?',ARRAY['4','16','3','5'],0,'Ring counter: 4 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 5-bit ring counter has how many valid states?',ARRAY['5','32','4','6'],0,'Ring counter: 5 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 6-bit ring counter has how many valid states?',ARRAY['6','64','5','7'],0,'Ring counter: 6 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 7-bit ring counter has how many valid states?',ARRAY['7','128','6','8'],0,'Ring counter: 7 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 8-bit ring counter has how many valid states?',ARRAY['8','256','7','9'],0,'Ring counter: 8 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 9-bit ring counter has how many valid states?',ARRAY['9','512','8','10'],0,'Ring counter: 9 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 10-bit ring counter has how many valid states?',ARRAY['10','1024','9','11'],0,'Ring counter: 10 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 11-bit ring counter has how many valid states?',ARRAY['11','2048','10','12'],0,'Ring counter: 11 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 12-bit ring counter has how many valid states?',ARRAY['12','4096','11','13'],0,'Ring counter: 12 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 13-bit ring counter has how many valid states?',ARRAY['13','8192','12','14'],0,'Ring counter: 13 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 14-bit ring counter has how many valid states?',ARRAY['14','16384','13','15'],0,'Ring counter: 14 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 15-bit ring counter has how many valid states?',ARRAY['15','32768','14','16'],0,'Ring counter: 15 valid states (one-hot rotating).',15),
('state-machine','intermediate','Problem: A 16-bit ring counter has how many valid states?',ARRAY['16','65536','15','17'],0,'Ring counter: 16 valid states (one-hot rotating).',15);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','advanced','Problem: FSM with 4 states using 2 flip-flops (binary). How many unused states?',ARRAY['0','0','4','2'],0,'2^2 = 4, minus 4 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 5 states using 3 flip-flops (binary). How many unused states?',ARRAY['3','0','5','3'],0,'2^3 = 8, minus 5 used = 3 unused.',20),
('state-machine','advanced','Problem: FSM with 6 states using 3 flip-flops (binary). How many unused states?',ARRAY['2','0','6','3'],0,'2^3 = 8, minus 6 used = 2 unused.',20),
('state-machine','advanced','Problem: FSM with 7 states using 3 flip-flops (binary). How many unused states?',ARRAY['1','0','7','3'],0,'2^3 = 8, minus 7 used = 1 unused.',20),
('state-machine','advanced','Problem: FSM with 8 states using 3 flip-flops (binary). How many unused states?',ARRAY['0','0','8','3'],0,'2^3 = 8, minus 8 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 9 states using 4 flip-flops (binary). How many unused states?',ARRAY['7','0','9','4'],0,'2^4 = 16, minus 9 used = 7 unused.',20),
('state-machine','advanced','Problem: FSM with 10 states using 4 flip-flops (binary). How many unused states?',ARRAY['6','0','10','4'],0,'2^4 = 16, minus 10 used = 6 unused.',20),
('state-machine','advanced','Problem: FSM with 11 states using 4 flip-flops (binary). How many unused states?',ARRAY['5','0','11','4'],0,'2^4 = 16, minus 11 used = 5 unused.',20),
('state-machine','advanced','Problem: FSM with 12 states using 4 flip-flops (binary). How many unused states?',ARRAY['4','0','12','4'],0,'2^4 = 16, minus 12 used = 4 unused.',20),
('state-machine','advanced','Problem: FSM with 13 states using 4 flip-flops (binary). How many unused states?',ARRAY['3','0','13','4'],0,'2^4 = 16, minus 13 used = 3 unused.',20),
('state-machine','advanced','Problem: FSM with 14 states using 4 flip-flops (binary). How many unused states?',ARRAY['2','0','14','4'],0,'2^4 = 16, minus 14 used = 2 unused.',20),
('state-machine','advanced','Problem: FSM with 15 states using 4 flip-flops (binary). How many unused states?',ARRAY['1','0','15','4'],0,'2^4 = 16, minus 15 used = 1 unused.',20),
('state-machine','advanced','Problem: FSM with 16 states using 4 flip-flops (binary). How many unused states?',ARRAY['0','0','16','4'],0,'2^4 = 16, minus 16 used = 0 unused.',20),
('state-machine','advanced','Problem: FSM with 17 states using 5 flip-flops (binary). How many unused states?',ARRAY['15','0','17','5'],0,'2^5 = 32, minus 17 used = 15 unused.',20),
('state-machine','advanced','Problem: FSM with 18 states using 5 flip-flops (binary). How many unused states?',ARRAY['14','0','18','5'],0,'2^5 = 32, minus 18 used = 14 unused.',20),
('state-machine','advanced','Problem: FSM with 19 states using 5 flip-flops (binary). How many unused states?',ARRAY['13','0','19','5'],0,'2^5 = 32, minus 19 used = 13 unused.',20),
('state-machine','advanced','Problem: FSM with 20 states using 5 flip-flops (binary). How many unused states?',ARRAY['12','0','20','5'],0,'2^5 = 32, minus 20 used = 12 unused.',20),
('state-machine','advanced','Problem: FSM with 4 states using one-hot encoding. How many flip-flops needed?',ARRAY['4','2','5','3'],0,'One-hot: 1 FF per state = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 5 states using one-hot encoding. How many flip-flops needed?',ARRAY['5','3','6','4'],0,'One-hot: 1 FF per state = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 6 states using one-hot encoding. How many flip-flops needed?',ARRAY['6','3','7','5'],0,'One-hot: 1 FF per state = 6 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 7 states using one-hot encoding. How many flip-flops needed?',ARRAY['7','3','8','6'],0,'One-hot: 1 FF per state = 7 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 8 states using one-hot encoding. How many flip-flops needed?',ARRAY['8','3','9','7'],0,'One-hot: 1 FF per state = 8 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 9 states using one-hot encoding. How many flip-flops needed?',ARRAY['9','4','10','8'],0,'One-hot: 1 FF per state = 9 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 10 states using one-hot encoding. How many flip-flops needed?',ARRAY['10','4','11','9'],0,'One-hot: 1 FF per state = 10 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 11 states using one-hot encoding. How many flip-flops needed?',ARRAY['11','4','12','10'],0,'One-hot: 1 FF per state = 11 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 12 states using one-hot encoding. How many flip-flops needed?',ARRAY['12','4','13','11'],0,'One-hot: 1 FF per state = 12 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 13 states using one-hot encoding. How many flip-flops needed?',ARRAY['13','4','14','12'],0,'One-hot: 1 FF per state = 13 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 14 states using one-hot encoding. How many flip-flops needed?',ARRAY['14','4','15','13'],0,'One-hot: 1 FF per state = 14 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 15 states using one-hot encoding. How many flip-flops needed?',ARRAY['15','4','16','14'],0,'One-hot: 1 FF per state = 15 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 16 states using one-hot encoding. How many flip-flops needed?',ARRAY['16','4','17','15'],0,'One-hot: 1 FF per state = 16 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 17 states using one-hot encoding. How many flip-flops needed?',ARRAY['17','5','18','16'],0,'One-hot: 1 FF per state = 17 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 18 states using one-hot encoding. How many flip-flops needed?',ARRAY['18','5','19','17'],0,'One-hot: 1 FF per state = 18 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 19 states using one-hot encoding. How many flip-flops needed?',ARRAY['19','5','20','18'],0,'One-hot: 1 FF per state = 19 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 20 states using one-hot encoding. How many flip-flops needed?',ARRAY['20','5','21','19'],0,'One-hot: 1 FF per state = 20 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 4 states using binary encoding. How many flip-flops needed?',ARRAY['2','4','5','3'],0,'Binary: ⌈log2(4)⌉ = 2 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 5 states using binary encoding. How many flip-flops needed?',ARRAY['3','5','6','4'],0,'Binary: ⌈log2(5)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 6 states using binary encoding. How many flip-flops needed?',ARRAY['3','6','7','4'],0,'Binary: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 7 states using binary encoding. How many flip-flops needed?',ARRAY['3','7','8','4'],0,'Binary: ⌈log2(7)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 8 states using binary encoding. How many flip-flops needed?',ARRAY['3','8','9','4'],0,'Binary: ⌈log2(8)⌉ = 3 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 9 states using binary encoding. How many flip-flops needed?',ARRAY['4','9','10','5'],0,'Binary: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 10 states using binary encoding. How many flip-flops needed?',ARRAY['4','10','11','5'],0,'Binary: ⌈log2(10)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 11 states using binary encoding. How many flip-flops needed?',ARRAY['4','11','12','5'],0,'Binary: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 12 states using binary encoding. How many flip-flops needed?',ARRAY['4','12','13','5'],0,'Binary: ⌈log2(12)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 13 states using binary encoding. How many flip-flops needed?',ARRAY['4','13','14','5'],0,'Binary: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 14 states using binary encoding. How many flip-flops needed?',ARRAY['4','14','15','5'],0,'Binary: ⌈log2(14)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 15 states using binary encoding. How many flip-flops needed?',ARRAY['4','15','16','5'],0,'Binary: ⌈log2(15)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 16 states using binary encoding. How many flip-flops needed?',ARRAY['4','16','17','5'],0,'Binary: ⌈log2(16)⌉ = 4 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 17 states using binary encoding. How many flip-flops needed?',ARRAY['5','17','18','6'],0,'Binary: ⌈log2(17)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 18 states using binary encoding. How many flip-flops needed?',ARRAY['5','18','19','6'],0,'Binary: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 19 states using binary encoding. How many flip-flops needed?',ARRAY['5','19','20','6'],0,'Binary: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: FSM with 20 states using binary encoding. How many flip-flops needed?',ARRAY['5','20','21','6'],0,'Binary: ⌈log2(20)⌉ = 5 flip-flops.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','3','6'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','3','9'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','3','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','3','15'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','3','18'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','3','21'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','3','24'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','3','27'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 3 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','3','30'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','4','8'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','4','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','4','16'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','4','20'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','4','24'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','4','28'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','4','32'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','4','36'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 4 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','4','40'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','5','10'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','5','15'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 4 transitions. Min arcs for connectivity?',ARRAY['4','0','5','20'],0,'Each transition needs at least 1 input + 1 output arc, minimum 4 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 5 transitions. Min arcs for connectivity?',ARRAY['5','0','5','25'],0,'Each transition needs at least 1 input + 1 output arc, minimum 5 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 6 transitions. Min arcs for connectivity?',ARRAY['6','0','5','30'],0,'Each transition needs at least 1 input + 1 output arc, minimum 6 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 7 transitions. Min arcs for connectivity?',ARRAY['7','0','5','35'],0,'Each transition needs at least 1 input + 1 output arc, minimum 7 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 8 transitions. Min arcs for connectivity?',ARRAY['8','0','5','40'],0,'Each transition needs at least 1 input + 1 output arc, minimum 8 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 9 transitions. Min arcs for connectivity?',ARRAY['9','0','5','45'],0,'Each transition needs at least 1 input + 1 output arc, minimum 9 arcs.',20),
('state-machine','advanced','Problem: Petri net has 5 places, 10 transitions. Min arcs for connectivity?',ARRAY['10','0','5','50'],0,'Each transition needs at least 1 input + 1 output arc, minimum 10 arcs.',20),
('state-machine','advanced','Problem: Petri net has 6 places, 2 transitions. Min arcs for connectivity?',ARRAY['2','0','6','12'],0,'Each transition needs at least 1 input + 1 output arc, minimum 2 arcs.',20),
('state-machine','advanced','Problem: Petri net has 6 places, 3 transitions. Min arcs for connectivity?',ARRAY['3','0','6','18'],0,'Each transition needs at least 1 input + 1 output arc, minimum 3 arcs.',20),
('state-machine','advanced','Problem: 2-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['4','2','4','4'],0,'State pairs: 2×2 = 4 sequences.',20),
('state-machine','advanced','Problem: 3-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['9','3','6','8'],0,'State pairs: 3×3 = 9 sequences.',20),
('state-machine','advanced','Problem: 4-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['16','4','8','16'],0,'State pairs: 4×4 = 16 sequences.',20),
('state-machine','advanced','Problem: 5-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['25','5','10','32'],0,'State pairs: 5×5 = 25 sequences.',20),
('state-machine','advanced','Problem: 6-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['36','6','12','64'],0,'State pairs: 6×6 = 36 sequences.',20),
('state-machine','advanced','Problem: 7-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['49','7','14','128'],0,'State pairs: 7×7 = 49 sequences.',20),
('state-machine','advanced','Problem: 8-state FSM tested exhaustively. How many state sequences of length 2?',ARRAY['64','8','16','256'],0,'State pairs: 8×8 = 64 sequences.',20),
('state-machine','advanced','Problem: A Mealy machine with 3 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 4 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 5 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 6 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 7 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 8 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 9 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Mealy machine with 10 states has outputs that depend on what?',ARRAY['Current state and inputs','Current state only','Inputs only','Clock only'],0,'Mealy outputs depend on both current state and inputs.',20),
('state-machine','advanced','Problem: A Moore machine with 3 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 4 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 5 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 6 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20),
('state-machine','advanced','Problem: A Moore machine with 7 states has outputs that depend on what?',ARRAY['Current state only','Current state and inputs','Inputs only','Clock only'],0,'Moore outputs depend only on the current state.',20);
