INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A D flip-flop has D=0. After the clock edge, what is Q?',ARRAY['0','1','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 0.',10),
('state-machine','basic','A D flip-flop has D=1. After the clock edge, what is Q?',ARRAY['1','0','High-Z','Previous Q'],0,'D flip-flop: Q_next = D = 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=0, K=0. What is the next state?',ARRAY['Hold','Hold','0','1'],0,'J=0,K=0: Hold.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A JK flip-flop has J=0, K=1. What is the next state?',ARRAY['0','Hold','0','1'],1,'J=0,K=1: 0.',10),
('state-machine','basic','A JK flip-flop has J=1, K=0. What is the next state?',ARRAY['1','Hold','0','1'],2,'J=1,K=0: 1.',10),
('state-machine','basic','A JK flip-flop has J=1, K=1. What is the next state?',ARRAY['Toggle','Hold','0','1'],0,'J=1,K=1: Toggle.',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=0. What is the next state?',ARRAY['Hold','0','1','Reset'],0,'T=0: Hold (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A T flip-flop has T=1. What is the next state?',ARRAY['Toggle','0','1','Reset'],0,'T=1: Toggle (T=0 holds, T=1 toggles).',10),
('state-machine','basic','A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 16 states. How many flip-flops are needed?',ARRAY['4','16','8','32'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 12 states. How many flip-flops are needed?',ARRAY['4','12','6','24'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 5 states. How many flip-flops are needed?',ARRAY['3','5','2.5','10'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 6 states. How many flip-flops are needed?',ARRAY['3','6','3','12'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 14 states. How many flip-flops are needed?',ARRAY['4','14','7','28'],0,'Need ⌈log2(14)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 8 states. How many flip-flops are needed?',ARRAY['3','8','4','16'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 11 states. How many flip-flops are needed?',ARRAY['4','11','5.5','22'],0,'Need ⌈log2(11)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 4 states. How many flip-flops are needed?',ARRAY['2','4','2','8'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 3 states. How many flip-flops are needed?',ARRAY['2','3','1.5','6'],0,'Need ⌈log2(3)⌉ = 2 flip-flops.',10),
('state-machine','basic','A state machine has 13 states. How many flip-flops are needed?',ARRAY['4','13','6.5','26'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 15 states. How many flip-flops are needed?',ARRAY['4','15','7.5','30'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 7 states. How many flip-flops are needed?',ARRAY['3','7','3.5','14'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',10),
('state-machine','basic','A state machine has 9 states. How many flip-flops are needed?',ARRAY['4','9','4.5','18'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',10),
('state-machine','basic','A state machine has 10 states. How many flip-flops are needed?',ARRAY['4','10','5','20'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',10);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','intermediate','A 11-bit asynchronous (ripple) counter has how many states?',ARRAY['2048','11','12','22'],0,'n-bit counter has 2^n = 2048 states.',15),
('state-machine','intermediate','A 15-bit asynchronous (ripple) counter has how many states?',ARRAY['32768','15','16','30'],0,'n-bit counter has 2^n = 32768 states.',15),
('state-machine','intermediate','A 9-bit asynchronous (ripple) counter has how many states?',ARRAY['512','9','10','18'],0,'n-bit counter has 2^n = 512 states.',15),
('state-machine','intermediate','A 16-bit asynchronous (ripple) counter has how many states?',ARRAY['65536','16','17','32'],0,'n-bit counter has 2^n = 65536 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A 2-bit asynchronous (ripple) counter has how many states?',ARRAY['4','2','3','4'],0,'n-bit counter has 2^n = 4 states.',15),
('state-machine','intermediate','A 2-bit asynchronous (ripple) counter has how many states?',ARRAY['4','2','3','4'],0,'n-bit counter has 2^n = 4 states.',15),
('state-machine','intermediate','A 16-bit asynchronous (ripple) counter has how many states?',ARRAY['65536','16','17','32'],0,'n-bit counter has 2^n = 65536 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A 14-bit asynchronous (ripple) counter has how many states?',ARRAY['16384','14','15','28'],0,'n-bit counter has 2^n = 16384 states.',15),
('state-machine','intermediate','A 16-bit asynchronous (ripple) counter has how many states?',ARRAY['65536','16','17','32'],0,'n-bit counter has 2^n = 65536 states.',15),
('state-machine','intermediate','A 4-bit asynchronous (ripple) counter has how many states?',ARRAY['16','4','5','8'],0,'n-bit counter has 2^n = 16 states.',15),
('state-machine','intermediate','A 9-bit asynchronous (ripple) counter has how many states?',ARRAY['512','9','10','18'],0,'n-bit counter has 2^n = 512 states.',15),
('state-machine','intermediate','A 10-bit asynchronous (ripple) counter has how many states?',ARRAY['1024','10','11','20'],0,'n-bit counter has 2^n = 1024 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A 3-bit asynchronous (ripple) counter has how many states?',ARRAY['8','3','4','6'],0,'n-bit counter has 2^n = 8 states.',15),
('state-machine','intermediate','A 13-bit asynchronous (ripple) counter has how many states?',ARRAY['8192','13','14','26'],0,'n-bit counter has 2^n = 8192 states.',15),
('state-machine','intermediate','A 6-bit asynchronous (ripple) counter has how many states?',ARRAY['64','6','7','12'],0,'n-bit counter has 2^n = 64 states.',15),
('state-machine','intermediate','A 7-bit asynchronous (ripple) counter has how many states?',ARRAY['128','7','8','14'],0,'n-bit counter has 2^n = 128 states.',15),
('state-machine','intermediate','A 13-bit asynchronous (ripple) counter has how many states?',ARRAY['8192','13','14','26'],0,'n-bit counter has 2^n = 8192 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A 14-bit asynchronous (ripple) counter has how many states?',ARRAY['16384','14','15','28'],0,'n-bit counter has 2^n = 16384 states.',15),
('state-machine','intermediate','A 13-bit asynchronous (ripple) counter has how many states?',ARRAY['8192','13','14','26'],0,'n-bit counter has 2^n = 8192 states.',15),
('state-machine','intermediate','A 12-bit asynchronous (ripple) counter has how many states?',ARRAY['4096','12','13','24'],0,'n-bit counter has 2^n = 4096 states.',15),
('state-machine','intermediate','A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-16 counter needs how many flip-flops?',ARRAY['4','16','15','17'],0,'Need ⌈log2(16)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-8 counter needs how many flip-flops?',ARRAY['3','8','7','9'],0,'Need ⌈log2(8)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-12 counter needs how many flip-flops?',ARRAY['4','12','11','13'],0,'Need ⌈log2(12)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-15 counter needs how many flip-flops?',ARRAY['4','15','14','16'],0,'Need ⌈log2(15)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-13 counter needs how many flip-flops?',ARRAY['4','13','12','14'],0,'Need ⌈log2(13)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','A mod-10 counter needs how many flip-flops?',ARRAY['4','10','9','11'],0,'Need ⌈log2(10)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-5 counter needs how many flip-flops?',ARRAY['3','5','4','6'],0,'Need ⌈log2(5)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-9 counter needs how many flip-flops?',ARRAY['4','9','8','10'],0,'Need ⌈log2(9)⌉ = 4 flip-flops.',15),
('state-machine','intermediate','A mod-6 counter needs how many flip-flops?',ARRAY['3','6','5','7'],0,'Need ⌈log2(6)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A mod-4 counter needs how many flip-flops?',ARRAY['2','4','3','5'],0,'Need ⌈log2(4)⌉ = 2 flip-flops.',15),
('state-machine','intermediate','A mod-7 counter needs how many flip-flops?',ARRAY['3','7','6','8'],0,'Need ⌈log2(7)⌉ = 3 flip-flops.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 616381 Hz. What is the output frequency of the MSB?',ARRAY['38524 Hz','616381 Hz','154095 Hz','9862096 Hz'],0,'4-bit counter divides by 2^4=16: 616381/16 = 38524 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 725627 Hz. What is the output frequency of the MSB?',ARRAY['45352 Hz','725627 Hz','181407 Hz','11610032 Hz'],0,'4-bit counter divides by 2^4=16: 725627/16 = 45352 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 853022 Hz. What is the output frequency of the MSB?',ARRAY['53314 Hz','853022 Hz','213256 Hz','13648352 Hz'],0,'4-bit counter divides by 2^4=16: 853022/16 = 53314 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 900695 Hz. What is the output frequency of the MSB?',ARRAY['56293 Hz','900695 Hz','225174 Hz','14411120 Hz'],0,'4-bit counter divides by 2^4=16: 900695/16 = 56293 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 758209 Hz. What is the output frequency of the MSB?',ARRAY['47388 Hz','758209 Hz','189552 Hz','12131344 Hz'],0,'4-bit counter divides by 2^4=16: 758209/16 = 47388 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 562331 Hz. What is the output frequency of the MSB?',ARRAY['35146 Hz','562331 Hz','140583 Hz','8997296 Hz'],0,'4-bit counter divides by 2^4=16: 562331/16 = 35146 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 876097 Hz. What is the output frequency of the MSB?',ARRAY['54756 Hz','876097 Hz','219024 Hz','14017552 Hz'],0,'4-bit counter divides by 2^4=16: 876097/16 = 54756 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 575909 Hz. What is the output frequency of the MSB?',ARRAY['35994 Hz','575909 Hz','143977 Hz','9214544 Hz'],0,'4-bit counter divides by 2^4=16: 575909/16 = 35994 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 161607 Hz. What is the output frequency of the MSB?',ARRAY['10100 Hz','161607 Hz','40402 Hz','2585712 Hz'],0,'4-bit counter divides by 2^4=16: 161607/16 = 10100 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 995972 Hz. What is the output frequency of the MSB?',ARRAY['62248 Hz','995972 Hz','248993 Hz','15935552 Hz'],0,'4-bit counter divides by 2^4=16: 995972/16 = 62248 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 879340 Hz. What is the output frequency of the MSB?',ARRAY['54959 Hz','879340 Hz','219835 Hz','14069440 Hz'],0,'4-bit counter divides by 2^4=16: 879340/16 = 54959 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 912632 Hz. What is the output frequency of the MSB?',ARRAY['57040 Hz','912632 Hz','228158 Hz','14602112 Hz'],0,'4-bit counter divides by 2^4=16: 912632/16 = 57040 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 424286 Hz. What is the output frequency of the MSB?',ARRAY['26518 Hz','424286 Hz','106072 Hz','6788576 Hz'],0,'4-bit counter divides by 2^4=16: 424286/16 = 26518 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 44757 Hz. What is the output frequency of the MSB?',ARRAY['2797 Hz','44757 Hz','11189 Hz','716112 Hz'],0,'4-bit counter divides by 2^4=16: 44757/16 = 2797 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 876336 Hz. What is the output frequency of the MSB?',ARRAY['54771 Hz','876336 Hz','219084 Hz','14021376 Hz'],0,'4-bit counter divides by 2^4=16: 876336/16 = 54771 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 613110 Hz. What is the output frequency of the MSB?',ARRAY['38319 Hz','613110 Hz','153278 Hz','9809760 Hz'],0,'4-bit counter divides by 2^4=16: 613110/16 = 38319 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 309807 Hz. What is the output frequency of the MSB?',ARRAY['19363 Hz','309807 Hz','77452 Hz','4956912 Hz'],0,'4-bit counter divides by 2^4=16: 309807/16 = 19363 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 176068 Hz. What is the output frequency of the MSB?',ARRAY['11004 Hz','176068 Hz','44017 Hz','2817088 Hz'],0,'4-bit counter divides by 2^4=16: 176068/16 = 11004 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 631301 Hz. What is the output frequency of the MSB?',ARRAY['39456 Hz','631301 Hz','157825 Hz','10100816 Hz'],0,'4-bit counter divides by 2^4=16: 631301/16 = 39456 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 908795 Hz. What is the output frequency of the MSB?',ARRAY['56800 Hz','908795 Hz','227199 Hz','14540720 Hz'],0,'4-bit counter divides by 2^4=16: 908795/16 = 56800 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 983721 Hz. What is the output frequency of the MSB?',ARRAY['61483 Hz','983721 Hz','245930 Hz','15739536 Hz'],0,'4-bit counter divides by 2^4=16: 983721/16 = 61483 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 306084 Hz. What is the output frequency of the MSB?',ARRAY['19130 Hz','306084 Hz','76521 Hz','4897344 Hz'],0,'4-bit counter divides by 2^4=16: 306084/16 = 19130 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 475991 Hz. What is the output frequency of the MSB?',ARRAY['29749 Hz','475991 Hz','118998 Hz','7615856 Hz'],0,'4-bit counter divides by 2^4=16: 475991/16 = 29749 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 694285 Hz. What is the output frequency of the MSB?',ARRAY['43393 Hz','694285 Hz','173571 Hz','11108560 Hz'],0,'4-bit counter divides by 2^4=16: 694285/16 = 43393 Hz.',15),
('state-machine','intermediate','A 4-bit ripple counter is clocked at 737918 Hz. What is the output frequency of the MSB?',ARRAY['46120 Hz','737918 Hz','184480 Hz','11806688 Hz'],0,'4-bit counter divides by 2^4=16: 737918/16 = 46120 Hz.',15),
('state-machine','intermediate','A Mealy machine with 6 states and 2 inputs has how many possible transitions?',ARRAY['24','6','36','12'],0,'Transitions = states × 2^inputs = 6×4 = 24 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 10 states and 2 inputs has how many possible transitions?',ARRAY['40','10','100','20'],0,'Transitions = states × 2^inputs = 10×4 = 40 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 5 states and 2 inputs has how many possible transitions?',ARRAY['20','5','25','10'],0,'Transitions = states × 2^inputs = 5×4 = 20 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 4 states and 2 inputs has how many possible transitions?',ARRAY['16','4','16','8'],0,'Transitions = states × 2^inputs = 4×4 = 16 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 3 states and 2 inputs has how many possible transitions?',ARRAY['12','3','9','6'],0,'Transitions = states × 2^inputs = 3×4 = 12 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 7 states and 2 inputs has how many possible transitions?',ARRAY['28','7','49','14'],0,'Transitions = states × 2^inputs = 7×4 = 28 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 6 states and 2 inputs has how many possible transitions?',ARRAY['24','6','36','12'],0,'Transitions = states × 2^inputs = 6×4 = 24 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 9 states and 2 inputs has how many possible transitions?',ARRAY['36','9','81','18'],0,'Transitions = states × 2^inputs = 9×4 = 36 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 8 states and 2 inputs has how many possible transitions?',ARRAY['32','8','64','16'],0,'Transitions = states × 2^inputs = 8×4 = 32 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 6 states and 2 inputs has how many possible transitions?',ARRAY['24','6','36','12'],0,'Transitions = states × 2^inputs = 6×4 = 24 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 7 states and 2 inputs has how many possible transitions?',ARRAY['28','7','49','14'],0,'Transitions = states × 2^inputs = 7×4 = 28 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 7 states and 2 inputs has how many possible transitions?',ARRAY['28','7','49','14'],0,'Transitions = states × 2^inputs = 7×4 = 28 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 6 states and 2 inputs has how many possible transitions?',ARRAY['24','6','36','12'],0,'Transitions = states × 2^inputs = 6×4 = 24 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 9 states and 2 inputs has how many possible transitions?',ARRAY['36','9','81','18'],0,'Transitions = states × 2^inputs = 9×4 = 36 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 9 states and 2 inputs has how many possible transitions?',ARRAY['36','9','81','18'],0,'Transitions = states × 2^inputs = 9×4 = 36 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 7 states and 2 inputs has how many possible transitions?',ARRAY['28','7','49','14'],0,'Transitions = states × 2^inputs = 7×4 = 28 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 10 states and 2 inputs has how many possible transitions?',ARRAY['40','10','100','20'],0,'Transitions = states × 2^inputs = 10×4 = 40 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 4 states and 2 inputs has how many possible transitions?',ARRAY['16','4','16','8'],0,'Transitions = states × 2^inputs = 4×4 = 16 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 7 states and 2 inputs has how many possible transitions?',ARRAY['28','7','49','14'],0,'Transitions = states × 2^inputs = 7×4 = 28 (but Mealy outputs depend on inputs).',15),
('state-machine','intermediate','A Mealy machine with 4 states and 2 inputs has how many possible transitions?',ARRAY['16','4','16','8'],0,'Transitions = states × 2^inputs = 4×4 = 16 (but Mealy outputs depend on inputs).',15);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 4 states using 2 flip-flops. How many unused states exist?',ARRAY['0','0','4','2'],0,'2^2 = 4 total, 4 - 4 = 0 unused.',20),
('state-machine','advanced','A state machine has 5 states using 3 flip-flops. How many unused states exist?',ARRAY['3','0','5','3'],0,'2^3 = 8 total, 8 - 5 = 3 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 15 states using 4 flip-flops. How many unused states exist?',ARRAY['1','0','15','4'],0,'2^4 = 16 total, 16 - 15 = 1 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 7 states using 3 flip-flops. How many unused states exist?',ARRAY['1','0','7','3'],0,'2^3 = 8 total, 8 - 7 = 1 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A state machine has 10 states using 4 flip-flops. How many unused states exist?',ARRAY['6','0','10','4'],0,'2^4 = 16 total, 16 - 10 = 6 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 13 states using 4 flip-flops. How many unused states exist?',ARRAY['3','0','13','4'],0,'2^4 = 16 total, 16 - 13 = 3 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 11 states using 4 flip-flops. How many unused states exist?',ARRAY['5','0','11','4'],0,'2^4 = 16 total, 16 - 11 = 5 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A state machine has 4 states using 2 flip-flops. How many unused states exist?',ARRAY['0','0','4','2'],0,'2^2 = 4 total, 4 - 4 = 0 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 12 states using 4 flip-flops. How many unused states exist?',ARRAY['4','0','12','4'],0,'2^4 = 16 total, 16 - 12 = 4 unused.',20),
('state-machine','advanced','A state machine has 6 states using 3 flip-flops. How many unused states exist?',ARRAY['2','0','6','3'],0,'2^3 = 8 total, 8 - 6 = 2 unused.',20),
('state-machine','advanced','A Petri net has 10 places and 9 transitions. What is the minimum number of arcs?',ARRAY['9','0','10','90'],0,'Each transition needs at least one input and one output arc, minimum 9 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 8 transitions. What is the minimum number of arcs?',ARRAY['8','0','5','40'],0,'Each transition needs at least one input and one output arc, minimum 8 arcs.',20),
('state-machine','advanced','A Petri net has 7 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','7','28'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','8','48'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 10 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','10','50'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 9 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','9','36'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 10 transitions. What is the minimum number of arcs?',ARRAY['10','0','3','30'],0,'Each transition needs at least one input and one output arc, minimum 10 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','3','12'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 3 transitions. What is the minimum number of arcs?',ARRAY['3','0','8','24'],0,'Each transition needs at least one input and one output arc, minimum 3 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 8 transitions. What is the minimum number of arcs?',ARRAY['8','0','8','64'],0,'Each transition needs at least one input and one output arc, minimum 8 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 4 transitions. What is the minimum number of arcs?',ARRAY['4','0','5','20'],0,'Each transition needs at least one input and one output arc, minimum 4 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','3','18'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 7 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','7','42'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 6 places and 3 transitions. What is the minimum number of arcs?',ARRAY['3','0','6','18'],0,'Each transition needs at least one input and one output arc, minimum 3 arcs.',20),
('state-machine','advanced','A Petri net has 5 places and 5 transitions. What is the minimum number of arcs?',ARRAY['5','0','5','25'],0,'Each transition needs at least one input and one output arc, minimum 5 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 2 transitions. What is the minimum number of arcs?',ARRAY['2','0','3','6'],0,'Each transition needs at least one input and one output arc, minimum 2 arcs.',20),
('state-machine','advanced','A Petri net has 8 places and 6 transitions. What is the minimum number of arcs?',ARRAY['6','0','8','48'],0,'Each transition needs at least one input and one output arc, minimum 6 arcs.',20),
('state-machine','advanced','A Petri net has 3 places and 7 transitions. What is the minimum number of arcs?',ARRAY['7','0','3','21'],0,'Each transition needs at least one input and one output arc, minimum 7 arcs.',20),
('state-machine','advanced','A 8-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['64','8','16','256'],0,'For 8 states, sequences of length 2: 8×8 = 64 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 7-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['49','7','14','128'],0,'For 7 states, sequences of length 2: 7×7 = 49 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 3-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['9','3','6','8'],0,'For 3 states, sequences of length 2: 3×3 = 9 (state pairs).',20),
('state-machine','advanced','A 4-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['16','4','8','16'],0,'For 4 states, sequences of length 2: 4×4 = 16 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 8-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['64','8','16','256'],0,'For 8 states, sequences of length 2: 8×8 = 64 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 3-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['9','3','6','8'],0,'For 3 states, sequences of length 2: 3×3 = 9 (state pairs).',20),
('state-machine','advanced','A 5-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['25','5','10','32'],0,'For 5 states, sequences of length 2: 5×5 = 25 (state pairs).',20),
('state-machine','advanced','A 2-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['4','2','4','4'],0,'For 2 states, sequences of length 2: 2×2 = 4 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A 6-state FSM is tested exhaustively. How many input sequences of length 2 must be tested?',ARRAY['36','6','12','64'],0,'For 6 states, sequences of length 2: 6×6 = 36 (state pairs).',20),
('state-machine','advanced','A one-hot encoded FSM with 4 states needs how many flip-flops?',ARRAY['4','2','5','3'],0,'One-hot: 1 flip-flop per state = 4 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 18 states needs how many flip-flops?',ARRAY['18','5','19','17'],0,'One-hot: 1 flip-flop per state = 18 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 12 states needs how many flip-flops?',ARRAY['12','4','13','11'],0,'One-hot: 1 flip-flop per state = 12 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 8 states needs how many flip-flops?',ARRAY['8','3','9','7'],0,'One-hot: 1 flip-flop per state = 8 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 18 states needs how many flip-flops?',ARRAY['18','5','19','17'],0,'One-hot: 1 flip-flop per state = 18 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 14 states needs how many flip-flops?',ARRAY['14','4','15','13'],0,'One-hot: 1 flip-flop per state = 14 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 4 states needs how many flip-flops?',ARRAY['4','2','5','3'],0,'One-hot: 1 flip-flop per state = 4 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 10 states needs how many flip-flops?',ARRAY['10','4','11','9'],0,'One-hot: 1 flip-flop per state = 10 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 19 states needs how many flip-flops?',ARRAY['19','5','20','18'],0,'One-hot: 1 flip-flop per state = 19 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 11 states needs how many flip-flops?',ARRAY['11','4','12','10'],0,'One-hot: 1 flip-flop per state = 11 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 13 states needs how many flip-flops?',ARRAY['13','4','14','12'],0,'One-hot: 1 flip-flop per state = 13 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 5 states needs how many flip-flops?',ARRAY['5','3','6','4'],0,'One-hot: 1 flip-flop per state = 5 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A one-hot encoded FSM with 20 states needs how many flip-flops?',ARRAY['20','5','21','19'],0,'One-hot: 1 flip-flop per state = 20 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 19 states needs how many flip-flops?',ARRAY['5','19','20','6'],0,'Binary encoding: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 5 states needs how many flip-flops?',ARRAY['3','5','6','4'],0,'Binary encoding: ⌈log2(5)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 10 states needs how many flip-flops?',ARRAY['4','10','11','5'],0,'Binary encoding: ⌈log2(10)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 18 states needs how many flip-flops?',ARRAY['5','18','19','6'],0,'Binary encoding: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 11 states needs how many flip-flops?',ARRAY['4','11','12','5'],0,'Binary encoding: ⌈log2(11)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 19 states needs how many flip-flops?',ARRAY['5','19','20','6'],0,'Binary encoding: ⌈log2(19)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 15 states needs how many flip-flops?',ARRAY['4','15','16','5'],0,'Binary encoding: ⌈log2(15)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 6 states needs how many flip-flops?',ARRAY['3','6','7','4'],0,'Binary encoding: ⌈log2(6)⌉ = 3 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 18 states needs how many flip-flops?',ARRAY['5','18','19','6'],0,'Binary encoding: ⌈log2(18)⌉ = 5 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 13 states needs how many flip-flops?',ARRAY['4','13','14','5'],0,'Binary encoding: ⌈log2(13)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 9 states needs how many flip-flops?',ARRAY['4','9','10','5'],0,'Binary encoding: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 9 states needs how many flip-flops?',ARRAY['4','9','10','5'],0,'Binary encoding: ⌈log2(9)⌉ = 4 flip-flops.',20),
('state-machine','advanced','A binary-encoded FSM with 15 states needs how many flip-flops?',ARRAY['4','15','16','5'],0,'Binary encoding: ⌈log2(15)⌉ = 4 flip-flops.',20);
