INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 1 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,1) = 0 AND 1 = 0.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'AND(1,1) = 1 AND 1 = 1.',10),
('gate-puzzler','basic','For a 2-input AND gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'AND(0,0) = 0 AND 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1 OR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1 OR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=1 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,1) = 1 OR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'OR(0,0) = 0 OR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input OR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'OR(0,1) = 0 OR 1 = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NOT(0) = 1.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a NOT gate with input A=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(0,1) = 0 XOR 1 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1 XOR 0 = 1.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=0 and B=0, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(0,0) = 0 XOR 0 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input XOR gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'XOR(1,1) = 1 XOR 1 = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=0 and B=1, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,1) = NOT(0 AND 1) = 1.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=1, what is the output?',ARRAY['0','1','High-Z','Undefined'],0,'NAND(1,1) = NOT(1 AND 1) = 0.',10),
('gate-puzzler','basic','For a 2-input NAND gate with A=1 and B=0, what is the output?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(1,0) = NOT(1 AND 0) = 1.',10);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(B+C)',ARRAY['AB+AC','AB+BC','A+BC','ABC'],0,'Distributive law: A(B+C) = AB+AC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+AB',ARRAY['A','B','A+B','AB'],0,'Absorption: A+AB = A(1+B) = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A(A+B)',ARRAY['A','B','A+B','AB'],0,'Absorption: A(A+B) = A+AB = A.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: (A+B)(A+C)',ARRAY['A+BC','AB+AC','A+B+C','ABC'],0,'Consensus: (A+B)(A+C) = A+BC.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A+1',ARRAY['1','A','0','A'''],0,'Annulment: A+1 = 1.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A·0',ARRAY['0','A','1','A'''],0,'Annulment: A·0 = 0.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A·B)',ARRAY['A''+B''','A''+B','A·B''','A+B'],0,'De Morgan: NOT(A·B) = A''+B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: NOT(A+B)',ARRAY['A''·B''','A''·B','A+B''','A·B'],0,'De Morgan: NOT(A+B) = A''·B''.',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XOR A',ARRAY['0','1','A','A'''],0,'A XOR A = 0 (same inputs).',15),
('gate-puzzler','intermediate','Simplify the Boolean expression: A XNOR A',ARRAY['1','0','A','A'''],0,'A XNOR A = 1 (same inputs).',15);
INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells for 3 variables.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Half-adder: Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','If a circuit outputs F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A: F = A(B+C).',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells for 4 variables.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'Full-adder: A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B (equality detector).',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable (Gray code ordering).',20),
('gate-puzzler','advanced','A multiplexer with 4 data lines needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, so n = 2 select lines.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'A''B''+AB = 0+0 = 0 when A=1,B=0.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'Maximum group = all 16 cells (function = 1).',20),
('gate-puzzler','advanced','A multiplexer with 8 data lines needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, so n = 3 select lines.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'De Morgan: (A+B)'' = A''B'', (A''+B'')'' = AB. F = A''B''·AB = 0.',20),
('gate-puzzler','advanced','K-map grouping must use groups of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups must be 1, 2, 4, 8, 16 (powers of 2).',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs decode to 8 output lines.',20),
('gate-puzzler','advanced','What is the hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC to cover the transition.',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'8 inputs → 3 output bits (2^3=8).',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what function?',ARRAY['A','A''','1','0'],0,'S=A: output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both inputs of NAND together = NOT.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what function?',ARRAY['A''','A','1','0'],0,'S=A: output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','In K-map simplification, what is a prime implicant?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group of adjacent 1s.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT (which is NAND with tied inputs).',20),
('gate-puzzler','advanced','Using only NAND gates, how do you implement F = A·B?',ARRAY['2 NAND gates','1 NAND gate','3 NAND gates','4 NAND gates'],0,'AND = NAND followed by NOT (NAND with tied inputs).',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['A prime implicant covering a cell no other covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one minterm not covered by any other PI.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs (2 NOTs + 1 NAND).',20),
('gate-puzzler','advanced','What is the minimum number of gates for F = A XOR B using NAND?',ARRAY['4','2','3','6'],0,'XOR from NAND requires 4 gates.',20),
('gate-puzzler','advanced','How many minterms are in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many NOR gates are needed to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT (NOR with tied inputs = NOT).',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates are needed?',ARRAY['4','2','8','1'],0,'4 XNORs (one per bit) ANDed together.',20),
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells for 3 variables.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Half-adder: Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','If a circuit outputs F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A: F = A(B+C).',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells for 4 variables.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'Full-adder: A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B (equality detector).',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable (Gray code ordering).',20),
('gate-puzzler','advanced','A multiplexer with 4 data lines needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, so n = 2 select lines.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'A''B''+AB = 0+0 = 0 when A=1,B=0.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'Maximum group = all 16 cells (function = 1).',20),
('gate-puzzler','advanced','A multiplexer with 8 data lines needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, so n = 3 select lines.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'De Morgan: (A+B)'' = A''B'', (A''+B'')'' = AB. F = A''B''·AB = 0.',20),
('gate-puzzler','advanced','K-map grouping must use groups of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups must be 1, 2, 4, 8, 16 (powers of 2).',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs decode to 8 output lines.',20),
('gate-puzzler','advanced','What is the hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC to cover the transition.',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'8 inputs → 3 output bits (2^3=8).',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what function?',ARRAY['A','A''','1','0'],0,'S=A: output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both inputs of NAND together = NOT.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what function?',ARRAY['A''','A','1','0'],0,'S=A: output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','In K-map simplification, what is a prime implicant?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group of adjacent 1s.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT (which is NAND with tied inputs).',20),
('gate-puzzler','advanced','Using only NAND gates, how do you implement F = A·B?',ARRAY['2 NAND gates','1 NAND gate','3 NAND gates','4 NAND gates'],0,'AND = NAND followed by NOT (NAND with tied inputs).',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['A prime implicant covering a cell no other covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one minterm not covered by any other PI.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs (2 NOTs + 1 NAND).',20),
('gate-puzzler','advanced','What is the minimum number of gates for F = A XOR B using NAND?',ARRAY['4','2','3','6'],0,'XOR from NAND requires 4 gates.',20),
('gate-puzzler','advanced','How many minterms are in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many NOR gates are needed to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT (NOR with tied inputs = NOT).',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates are needed?',ARRAY['4','2','8','1'],0,'4 XNORs (one per bit) ANDed together.',20),
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells for 3 variables.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Half-adder: Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','If a circuit outputs F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A: F = A(B+C).',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells for 4 variables.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'Full-adder: A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B (equality detector).',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable (Gray code ordering).',20),
('gate-puzzler','advanced','A multiplexer with 4 data lines needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, so n = 2 select lines.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'A''B''+AB = 0+0 = 0 when A=1,B=0.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'Maximum group = all 16 cells (function = 1).',20),
('gate-puzzler','advanced','A multiplexer with 8 data lines needs how many select lines?',ARRAY['3','2','4','8'],0,'2^n = 8, so n = 3 select lines.',20),
('gate-puzzler','advanced','A circuit has F = (A+B)''·(A''+B'')''. What is F?',ARRAY['0','1','A','B'],0,'De Morgan: (A+B)'' = A''B'', (A''+B'')'' = AB. F = A''B''·AB = 0.',20),
('gate-puzzler','advanced','K-map grouping must use groups of what size?',ARRAY['Powers of 2','Any number','Odd numbers','Prime numbers'],0,'Groups must be 1, 2, 4, 8, 16 (powers of 2).',20),
('gate-puzzler','advanced','A 3-to-8 decoder has how many outputs?',ARRAY['8','3','6','4'],0,'3 inputs decode to 8 output lines.',20),
('gate-puzzler','advanced','What is the hazard-free expression for F = AB + A''C?',ARRAY['AB + A''C + BC','AB + A''C','AB + C','A''C + B'],0,'Add consensus term BC to cover the transition.',20),
('gate-puzzler','advanced','What does a K-map with all 1s simplify to?',ARRAY['1','0','A','A'''],0,'All 1s = constant 1.',20),
('gate-puzzler','advanced','A priority encoder with 8 inputs needs how many output bits?',ARRAY['3','2','4','8'],0,'8 inputs → 3 output bits (2^3=8).',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=0, I1=1, S=A outputs what function?',ARRAY['A','A''','1','0'],0,'S=A: output = A·1 + A''·0 = A.',20),
('gate-puzzler','advanced','What does a K-map with all 0s simplify to?',ARRAY['0','1','A','A'''],0,'All 0s = constant 0.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build a NOT gate?',ARRAY['1','2','3','4'],0,'Tie both inputs of NAND together = NOT.',20),
('gate-puzzler','advanced','A 2:1 MUX with I0=1, I1=0, S=A outputs what function?',ARRAY['A''','A','1','0'],0,'S=A: output = A·0 + A''·1 = A''.',20),
('gate-puzzler','advanced','In K-map simplification, what is a prime implicant?',ARRAY['A maximal group of 1s','Any group of 1s','A single cell','A group of 0s'],0,'Prime implicant = largest possible group of adjacent 1s.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an AND gate?',ARRAY['2','1','3','4'],0,'AND = NAND + NOT (which is NAND with tied inputs).',20),
('gate-puzzler','advanced','Using only NAND gates, how do you implement F = A·B?',ARRAY['2 NAND gates','1 NAND gate','3 NAND gates','4 NAND gates'],0,'AND = NAND followed by NOT (NAND with tied inputs).',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['A prime implicant covering a cell no other covers','The largest group','The smallest group','Any group'],0,'Essential PI covers at least one minterm not covered by any other PI.',20),
('gate-puzzler','advanced','How many NAND gates are needed to build an OR gate?',ARRAY['3','2','4','1'],0,'OR = NOT(A) NAND NOT(B) = 3 NANDs (2 NOTs + 1 NAND).',20),
('gate-puzzler','advanced','What is the minimum number of gates for F = A XOR B using NAND?',ARRAY['4','2','3','6'],0,'XOR from NAND requires 4 gates.',20),
('gate-puzzler','advanced','How many minterms are in F(A,B,C) = Σm(0,1,2,5)?',ARRAY['4','3','5','8'],0,'Four minterms: m0, m1, m2, m5.',20),
('gate-puzzler','advanced','How many NOR gates are needed to build an OR gate?',ARRAY['2','1','3','4'],0,'OR = NOR + NOT (NOR with tied inputs = NOT).',20),
('gate-puzzler','advanced','If a 4-bit comparator checks A=B, how many XNOR gates are needed?',ARRAY['4','2','8','1'],0,'4 XNORs (one per bit) ANDed together.',20),
('gate-puzzler','advanced','A 3-variable K-map has how many cells?',ARRAY['8','4','16','32'],0,'2^3 = 8 cells for 3 variables.',20),
('gate-puzzler','advanced','Design a half-adder. Which gates are needed?',ARRAY['XOR and AND','AND and OR','NAND and NOR','XOR and OR'],0,'Half-adder: Sum = A XOR B, Carry = A AND B.',20),
('gate-puzzler','advanced','If a circuit outputs F = AB + AC, what is the minimal form?',ARRAY['A(B+C)','ABC','A+B+C','AB+AC'],0,'Factor out A: F = A(B+C).',20),
('gate-puzzler','advanced','A 4-variable K-map has how many cells?',ARRAY['16','8','32','64'],0,'2^4 = 16 cells for 4 variables.',20),
('gate-puzzler','advanced','Design a full-adder. How many inputs?',ARRAY['3','2','4','5'],0,'Full-adder: A, B, Cin (3 inputs).',20),
('gate-puzzler','advanced','If F = A''B + AB, what function is this?',ARRAY['XNOR','XOR','AND','OR'],0,'A''B+AB = A XNOR B (equality detector).',20),
('gate-puzzler','advanced','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable (Gray code ordering).',20),
('gate-puzzler','advanced','A multiplexer with 4 data lines needs how many select lines?',ARRAY['2','1','3','4'],0,'2^n = 4, so n = 2 select lines.',20),
('gate-puzzler','advanced','If F = A''B'' + AB, what is F when A=1, B=0?',ARRAY['0','1','High-Z','Undefined'],0,'A''B''+AB = 0+0 = 0 when A=1,B=0.',20),
('gate-puzzler','advanced','What is the maximum group size in a 4-variable K-map?',ARRAY['16','8','4','2'],0,'Maximum group = all 16 cells (function = 1).',20);
