INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','What does a NOT gate do?',ARRAY['Inverts the input','Buffers the input','Adds two inputs','Multiplies inputs'],0,'A NOT gate outputs the inverse of its input.',10),
('gate-puzzler','basic','Which gate outputs 1 only when both inputs are 1?',ARRAY['AND','OR','XOR','NAND'],0,'AND requires both inputs high.',10),
('gate-puzzler','basic','How many inputs does a standard NOT gate have?',ARRAY['1','2','3','4'],0,'NOT is a single-input gate.',10),
('gate-puzzler','basic','What is the output of OR gate when both inputs are 0?',ARRAY['0','1','High impedance','Undefined'],0,'OR outputs 0 only when all inputs are 0.',10),
('gate-puzzler','basic','NAND gate is the combination of which two gates?',ARRAY['AND + NOT','OR + NOT','XOR + NOT','NOR + NOT'],0,'NAND is AND followed by NOT.',10),
('gate-puzzler','basic','Which gate outputs 0 only when both inputs are 1?',ARRAY['NAND','AND','OR','XOR'],0,'NAND outputs 0 only when all inputs are 1.',10),
('gate-puzzler','basic','What does XOR output when both inputs are the same?',ARRAY['0','1','High-Z','Depends on input'],0,'XOR outputs 0 when inputs are equal.',10),
('gate-puzzler','basic','How many input combinations does a 2-input truth table have?',ARRAY['4','2','8','16'],0,'2^2 = 4 combinations.',10),
('gate-puzzler','basic','Which symbol represents an AND gate?',ARRAY['D-shaped','Shield-shaped','Triangle','Oval'],0,'AND gates use a D-shaped symbol.',10),
('gate-puzzler','basic','What is the output of a NOR gate with inputs 1 and 0?',ARRAY['0','1','High-Z','Undefined'],0,'NOR outputs 0 if any input is 1.',10),
('gate-puzzler','basic','A buffer gate does what?',ARRAY['Passes input unchanged','Inverts input','ANDs inputs','ORs inputs'],0,'A buffer passes the signal through.',10),
('gate-puzzler','basic','Which gate is known as the universal gate?',ARRAY['NAND','XOR','OR','NOT'],0,'NAND can implement any logic function.',10),
('gate-puzzler','basic','What is the truth table output for AND(1,1)?',ARRAY['1','0','Both','Neither'],0,'AND(1,1) = 1.',10),
('gate-puzzler','basic','How many rows in a 3-input truth table?',ARRAY['8','4','16','32'],0,'2^3 = 8 rows.',10),
('gate-puzzler','basic','Which gate gives 1 when inputs differ?',ARRAY['XOR','AND','OR','NAND'],0,'XOR outputs 1 when inputs differ.',10),
('gate-puzzler','basic','What is De Morgan''s first law?',ARRAY['NOT(A AND B) = NOT A OR NOT B','A AND B = A OR B','NOT(A OR B) = A AND B','A XOR B = A NAND B'],0,'De Morgan: complement of AND equals OR of complements.',10),
('gate-puzzler','basic','Which gate has a bubble at its output?',ARRAY['NAND','AND','OR','XOR'],0,'The bubble indicates inversion.',10),
('gate-puzzler','basic','What does the bubble on a gate symbol represent?',ARRAY['Inversion','Amplification','Buffering','Ground'],0,'A bubble means logical NOT.',10),
('gate-puzzler','basic','Which gate is OR followed by NOT?',ARRAY['NOR','NAND','XOR','AND'],0,'NOR = OR + NOT.',10),
('gate-puzzler','basic','What is the output of NAND(0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = NOT(0) = 1.',10),
('gate-puzzler','basic','How many transistors does a basic CMOS NOT gate use?',ARRAY['2','4','6','8'],0,'CMOS NOT uses one PMOS and one NMOS.',10),
('gate-puzzler','basic','Which logic family uses complementary pairs?',ARRAY['CMOS','TTL','ECL','DTL'],0,'CMOS uses complementary MOSFET pairs.',10),
('gate-puzzler','basic','What is the output of NOT(1)?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','Which gate can be used to build any other gate?',ARRAY['NAND','XOR','OR','Buffer'],0,'NAND is functionally complete.',10),
('gate-puzzler','basic','What is the Boolean expression for OR gate?',ARRAY['A + B','A · B','A ⊕ B','A · B'''],0,'OR is represented by +.',10),
('gate-puzzler','basic','What is the Boolean expression for AND gate?',ARRAY['A · B','A + B','A ⊕ B','A'''],0,'AND is represented by ·.',10),
('gate-puzzler','basic','Which gate outputs 1 when at least one input is 1?',ARRAY['OR','AND','NAND','NOR'],0,'OR outputs 1 if any input is high.',10),
('gate-puzzler','basic','What is the dual of AND?',ARRAY['OR','NOT','XOR','NAND'],0,'The dual of AND is OR.',10),
('gate-puzzler','basic','In Boolean algebra, what is A + 1?',ARRAY['1','A','0','A'''],0,'A OR 1 = 1 (absorption).',10),
('gate-puzzler','basic','In Boolean algebra, what is A · 0?',ARRAY['0','A','1','A'''],0,'A AND 0 = 0.',10),
('gate-puzzler','basic','In Boolean algebra, what is A + 0?',ARRAY['A','0','1','A'''],0,'A OR 0 = A (identity).',10),
('gate-puzzler','basic','In Boolean algebra, what is A · 1?',ARRAY['A','0','1','A'''],0,'A AND 1 = A (identity).',10),
('gate-puzzler','basic','What is A + A in Boolean algebra?',ARRAY['A','0','1','A'''],0,'A OR A = A (idempotent).',10),
('gate-puzzler','basic','What is A · A in Boolean algebra?',ARRAY['A','0','1','A'''],0,'A AND A = A (idempotent).',10),
('gate-puzzler','basic','What is NOT(NOT A)?',ARRAY['A','0','1','A'''],0,'Double negation cancels out.',10),
('gate-puzzler','basic','Which gate has a truth table with only one 0 output?',ARRAY['NAND','AND','OR','XOR'],0,'NAND has one 0 row (both inputs 1).',10),
('gate-puzzler','basic','Which gate has a truth table with only one 1 output?',ARRAY['AND','NAND','NOR','XOR'],0,'AND has one 1 row (both inputs 1).',10),
('gate-puzzler','basic','What is the output of XOR(1,0)?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1.',10),
('gate-puzzler','basic','What is the output of XNOR(1,1)?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR outputs 1 when inputs are equal.',10),
('gate-puzzler','basic','How many 2-input gates are needed to build a NAND from NOR gates?',ARRAY['4','2','3','1'],0,'NAND from NOR requires 4 NOR gates.',10),
('gate-puzzler','basic','What does a logic 1 typically represent?',ARRAY['HIGH/True','LOW/False','Ground','High impedance'],0,'Logic 1 = HIGH = True.',10),
('gate-puzzler','basic','What does a logic 0 typically represent?',ARRAY['LOW/False','HIGH/True','VCC','High impedance'],0,'Logic 0 = LOW = False.',10),
('gate-puzzler','basic','Which gate is used for parity checking?',ARRAY['XOR','AND','OR','NAND'],0,'XOR is used for parity generation/checking.',10),
('gate-puzzler','basic','What is the output of NOR(0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,0) = NOT(0 OR 0) = NOT(0) = 1.',10),
('gate-puzzler','basic','Which gate''s output is the complement of XOR?',ARRAY['XNOR','NAND','NOR','AND'],0,'XNOR is the complement of XOR.',10),
('gate-puzzler','basic','What is A · A'' in Boolean algebra?',ARRAY['0','1','A','A'''],0,'A AND NOT A = 0 (complementarity).',10),
('gate-puzzler','basic','What is A + A'' in Boolean algebra?',ARRAY['1','0','A','A'''],0,'A OR NOT A = 1 (complementarity).',10),
('gate-puzzler','basic','Which two gates are called universal gates?',ARRAY['NAND and NOR','AND and OR','XOR and XNOR','NOT and Buffer'],0,'Both NAND and NOR are functionally complete.',10),
('gate-puzzler','basic','What is the output of AND(1,0)?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 0.',10),
('gate-puzzler','basic','What is the output of OR(1,0)?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1.',10);