INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','intermediate','Simplify: A + AB',ARRAY['A','B','A+B','AB'],0,'A + AB = A(1+B) = A (absorption).',15),
('gate-puzzler','intermediate','Simplify: A(A+B)',ARRAY['A','B','AB','A+B'],0,'A(A+B) = AA + AB = A + AB = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+B'')',ARRAY['A','B','A+B','AB'],0,'(A+B)(A+B'') = A + BB'' = A.',15),
('gate-puzzler','intermediate','What is the consensus theorem?',ARRAY['AB + A''C + BC = AB + A''C','AB + AC = AB','A+B = A','AB = A'],0,'Consensus: AB + A''C + BC = AB + A''C.',15),
('gate-puzzler','intermediate','Simplify: AB + AB''',ARRAY['A','B','A+B','0'],0,'AB + AB'' = A(B+B'') = A.',15),
('gate-puzzler','intermediate','How many minterms does a 3-variable function have?',ARRAY['8','4','16','6'],0,'2^3 = 8 minterms.',15),
('gate-puzzler','intermediate','How many maxterms does a 4-variable function have?',ARRAY['16','8','4','32'],0,'2^4 = 16 maxterms.',15),
('gate-puzzler','intermediate','What is the minterm for A=1, B=0, C=1?',ARRAY['m5','m2','m7','m3'],0,'101 binary = 5, so m5.',15),
('gate-puzzler','intermediate','What is the maxterm for A=0, B=1, C=0?',ARRAY['M2','M5','M4','M1'],0,'010 binary = 2, so M2.',15),
('gate-puzzler','intermediate','How many cells in a 4-variable K-map?',ARRAY['16','8','4','32'],0,'2^4 = 16 cells.',15),
('gate-puzzler','intermediate','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable.',15),
('gate-puzzler','intermediate','What is the minimum number of variables for a K-map to be useful?',ARRAY['2','1','3','4'],0,'K-maps work for 2-6 variables.',15),
('gate-puzzler','intermediate','What does SOP stand for?',ARRAY['Sum of Products','Set of Pairs','Standard Operating Procedure','Series of Products'],0,'SOP = Sum of Products.',15),
('gate-puzzler','intermediate','What does POS stand for?',ARRAY['Product of Sums','Position','Post-Operation Set','Pair of Sums'],0,'POS = Product of Sums.',15),
('gate-puzzler','intermediate','Which is the canonical form for minterms?',ARRAY['SOP','POS','Both','Neither'],0,'Minterms are expressed in SOP form.',15),
('gate-puzzler','intermediate','Which is the canonical form for maxterms?',ARRAY['POS','SOP','Both','Neither'],0,'Maxterms are expressed in POS form.',15),
('gate-puzzler','intermediate','What is a hazard in combinational logic?',ARRAY['A momentary false output','A permanent error','A short circuit','A power fault'],0,'Hazards cause brief glitches during transitions.',15),
('gate-puzzler','intermediate','What causes a static-1 hazard?',ARRAY['Single variable change causing a 1→0→1 glitch','Two variables changing','Clock skew','Power noise'],0,'A single input change can cause a brief 0 glitch.',15),
('gate-puzzler','intermediate','How do you eliminate a static hazard?',ARRAY['Add redundant consensus terms','Add more gates','Increase voltage','Add a clock'],0,'Consensus terms cover the hazard gap.',15),
('gate-puzzler','intermediate','What is a multiplexer?',ARRAY['A data selector','A data distributor','A counter','A register'],0,'A MUX selects one of many inputs.',15),
('gate-puzzler','intermediate','How many select lines does a 16:1 MUX need?',ARRAY['4','3','2','5'],0,'2^4 = 16 inputs need 4 select lines.',15),
('gate-puzzler','intermediate','How many inputs does a 4:1 MUX have?',ARRAY['4','2','8','16'],0,'4:1 means 4 data inputs.',15),
('gate-puzzler','intermediate','What is a demultiplexer?',ARRAY['Routes one input to many outputs','Combines many inputs','Counts pulses','Stores data'],0,'A DEMUX distributes one input to selected output.',15),
('gate-puzzler','intermediate','How many output lines does a 3-to-8 decoder have?',ARRAY['8','3','5','16'],0,'3 inputs decode to 8 outputs.',15),
('gate-puzzler','intermediate','What is an encoder?',ARRAY['Converts many inputs to fewer output lines','Converts few inputs to many','Amplifies signals','Buffers data'],0,'Encoder = opposite of decoder.',15),
('gate-puzzler','intermediate','How many output lines does an 8-to-3 priority encoder have?',ARRAY['3','8','5','4'],0,'8 inputs encode to 3-bit output.',15),
('gate-puzzler','intermediate','What does a priority encoder do?',ARRAY['Outputs the highest-priority active input','Outputs all active inputs','Counts inputs','Buffers data'],0,'Priority encoders handle multiple active inputs.',15),
('gate-puzzler','intermediate','What is a half adder?',ARRAY['Adds 2 bits, outputs sum and carry','Adds 4 bits','Adds 2 numbers','Subtracts bits'],0,'Half adder: 2 inputs, sum + carry outputs.',15),
('gate-puzzler','intermediate','What is a full adder?',ARRAY['Adds 3 bits including carry-in','Adds 2 bits','Adds 4 bits','Adds with overflow'],0,'Full adder includes carry-in.',15),
('gate-puzzler','intermediate','How many full adders are needed for a 4-bit ripple carry adder?',ARRAY['4','3','2','8'],0,'One per bit position.',15),
('gate-puzzler','intermediate','What is the main disadvantage of ripple carry?',ARRAY['Propagation delay','Power consumption','Area','Cost'],0,'Carry ripples through each stage sequentially.',15),
('gate-puzzler','intermediate','Which adder is fastest for large bit widths?',ARRAY['Carry-lookahead','Ripple carry','Serial adder','Half adder'],0,'CLA computes carries in advance.',15),
('gate-puzzler','intermediate','What does a comparator circuit do?',ARRAY['Compares two binary numbers','Compares voltages','Compares frequencies','Compares currents'],0,'Comparators output equality/inequality.',15),
('gate-puzzler','intermediate','How many outputs does a 4-bit magnitude comparator have?',ARRAY['3','2','4','1'],0,'A>B, A<B, A=B outputs.',15),
('gate-puzzler','intermediate','What is a parity generator?',ARRAY['Adds a parity bit for error detection','Generates clock signals','Generates random numbers','Generates addresses'],0,'Parity bits detect single-bit errors.',15),
('gate-puzzler','intermediate','What is even parity?',ARRAY['Total number of 1s is even','Total 1s is odd','All bits are 1','All bits are 0'],0,'Even parity means even count of 1s.',15),
('gate-puzzler','intermediate','What is odd parity?',ARRAY['Total number of 1s is odd','Total 1s is even','Half are 1','None are 1'],0,'Odd parity means odd count of 1s.',15),
('gate-puzzler','intermediate','Which gate is used in a parity checker?',ARRAY['XOR','AND','OR','NAND'],0,'XOR toggles for each 1, giving parity.',15),
('gate-puzzler','intermediate','What is a BCD to 7-segment decoder?',ARRAY['Converts BCD to segment signals','Converts binary to BCD','Converts hex to decimal','Converts analog to digital'],0,'Drives 7-segment displays from BCD input.',15),
('gate-puzzler','intermediate','How many segment outputs does a 7-segment decoder have?',ARRAY['7','4','8','10'],0,'7 segments: a-g.',15),
('gate-puzzler','intermediate','What is a tristate buffer?',ARRAY['Buffer with high-impedance state','Buffer with 3 inputs','Buffer with 3 outputs','Triple buffer'],0,'Tristate adds a high-Z (disable) state.',15),
('gate-puzzler','intermediate','What is the purpose of tristate buffers on a bus?',ARRAY['Allow multiple drivers to share a bus','Increase speed','Reduce power','Add inversion'],0,'Only one driver is active at a time.',15),
('gate-puzzler','intermediate','What is an open-collector output?',ARRAY['Output that can sink but not source current','Output with 3 states','Output with amplification','Output with inversion'],0,'Open-collector needs a pull-up resistor.',15),
('gate-puzzler','intermediate','What is wired-OR using open-collector?',ARRAY['Multiple open-collector outputs share a pull-up','OR gate with wires','Wired connection','Bus arbitration'],0,'Active-low outputs on shared line act as NOR.',15),
('gate-puzzler','intermediate','What does a Schmitt trigger do?',ARRAY['Provides hysteresis for noise immunity','Triggers on clock','Amplifies signals','Buffers data'],0,'Hysteresis prevents oscillation near threshold.',15),
('gate-puzzler','intermediate','What is the difference between latch and flip-flop?',ARRAY['Flip-flop is edge-triggered, latch is level-sensitive','Latch is faster','Flip-flop uses less power','No difference'],0,'Latches are transparent when enabled; FFs sample on edge.',15),
('gate-puzzler','intermediate','What is a setup time?',ARRAY['Time data must be stable before clock edge','Time after clock','Clock period','Propagation delay'],0,'Setup time ensures correct sampling.',15),
('gate-puzzler','intermediate','What is hold time?',ARRAY['Time data must be stable after clock edge','Time before clock','Clock high duration','Reset time'],0,'Hold time ensures data is captured correctly.',15),
('gate-puzzler','intermediate','What is metastability?',ARRAY['Flip-flop output is unstable between 0 and 1','Flip-flop is reset','Flip-flop is stuck at 1','Flip-flop is too fast'],0,'Caused by setup/hold violation.',15),
('gate-puzzler','intermediate','How do you reduce metastability?',ARRAY['Use synchronizer flip-flops','Increase clock speed','Add more gates','Reduce voltage'],0,'Two-stage synchronizers reduce failure rate.',15);