INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('circuit-builder','basic','What is Ohm''s Law?',ARRAY['V = IR','V = I/R','V = IR²','V = I²R'],0,'Ohm''s Law: Voltage = Current × Resistance.',10),
('circuit-builder','basic','What is the unit of resistance?',ARRAY['Ohm (Ω)','Volt (V)','Ampere (A)','Watt (W)'],0,'Resistance is measured in ohms.',10),
('circuit-builder','basic','What is the unit of current?',ARRAY['Ampere (A)','Volt (V)','Ohm (Ω)','Farad (F)'],0,'Current is measured in amperes.',10),
('circuit-builder','basic','What is the unit of voltage?',ARRAY['Volt (V)','Ampere (A)','Ohm (Ω)','Joule (J)'],0,'Voltage is measured in volts.',10),
('circuit-builder','basic','What is the unit of power?',ARRAY['Watt (W)','Volt (V)','Ampere (A)','Ohm (Ω)'],0,'Power is measured in watts.',10),
('circuit-builder','basic','What is the power formula?',ARRAY['P = VI','P = V/I','P = I/V','P = V+I'],0,'Power = Voltage × Current.',10),
('circuit-builder','basic','What is the resistance of two 10Ω resistors in series?',ARRAY['20Ω','5Ω','10Ω','100Ω'],0,'Series: R = R1 + R2 = 20Ω.',10),
('circuit-builder','basic','What is the resistance of two 10Ω resistors in parallel?',ARRAY['5Ω','20Ω','10Ω','100Ω'],0,'Parallel: R = (R1×R2)/(R1+R2) = 5Ω.',10),
('circuit-builder','basic','What happens to current in a series circuit?',ARRAY['Same at all points','Splits at each component','Increases','Decreases'],0,'Current is constant in a series circuit.',10),
('circuit-builder','basic','What happens to voltage in a parallel circuit?',ARRAY['Same across all branches','Splits across branches','Increases','Decreases'],0,'Voltage is equal across parallel branches.',10),
('circuit-builder','basic','What is Kirchhoff''s Voltage Law (KVL)?',ARRAY['Sum of voltages around a loop = 0','Sum of currents = 0','V = IR','P = VI'],0,'KVL: algebraic sum of voltages in a loop is zero.',10),
('circuit-builder','basic','What is Kirchhoff''s Current Law (KCL)?',ARRAY['Sum of currents at a node = 0','Sum of voltages = 0','I = V/R','P = I²R'],0,'KCL: sum of currents entering a node equals sum leaving.',10),
('circuit-builder','basic','What is a short circuit?',ARRAY['Zero resistance path','High resistance path','Open circuit','Normal circuit'],0,'Short circuit has near-zero resistance.',10),
('circuit-builder','basic','What is an open circuit?',ARRAY['Infinite resistance path','Zero resistance path','Low resistance path','Normal circuit'],0,'Open circuit has infinite resistance.',10),
('circuit-builder','basic','What is the equivalent resistance of 5Ω and 15Ω in series?',ARRAY['20Ω','3.75Ω','10Ω','75Ω'],0,'Series: 5 + 15 = 20Ω.',10),
('circuit-builder','basic','What is the equivalent resistance of 6Ω and 3Ω in parallel?',ARRAY['2Ω','9Ω','18Ω','3Ω'],0,'Parallel: (6×3)/(6+3) = 2Ω.',10),
('circuit-builder','basic','What does a capacitor do in a DC circuit?',ARRAY['Blocks DC after charging','Passes DC freely','Acts as a short','Acts as a resistor'],0,'Capacitor charges then blocks DC (open circuit).',10),
('circuit-builder','basic','What does an inductor do in a DC circuit?',ARRAY['Acts as a short after steady state','Blocks DC','Acts as open circuit','Acts as a capacitor'],0,'Inductor passes DC after transient (short circuit).',10),
('circuit-builder','basic','What is the unit of capacitance?',ARRAY['Farad (F)','Henry (H)','Ohm (Ω)','Volt (V)'],0,'Capacitance is measured in farads.',10),
('circuit-builder','basic','What is the unit of inductance?',ARRAY['Henry (H)','Farad (F)','Ohm (Ω)','Ampere (A)'],0,'Inductance is measured in henries.',10),
('circuit-builder','basic','What is the formula for capacitive reactance?',ARRAY['Xc = 1/(2πfC)','Xc = 2πfC','Xc = 1/(2πfL)','Xc = 2πfL'],0,'Capacitive reactance decreases with frequency.',10),
('circuit-builder','basic','What is the formula for inductive reactance?',ARRAY['Xl = 2πfL','Xl = 1/(2πfL)','Xl = 2πfC','Xl = 1/(2πfC)'],0,'Inductive reactance increases with frequency.',10),
('circuit-builder','basic','What happens to a capacitor''s reactance as frequency increases?',ARRAY['Decreases','Increases','Stays same','Becomes zero'],0,'Xc = 1/(2πfC) → decreases with f.',10),
('circuit-builder','basic','What happens to an inductor''s reactance as frequency increases?',ARRAY['Increases','Decreases','Stays same','Becomes zero'],0,'Xl = 2πfL → increases with f.',10),
('circuit-builder','basic','What is the time constant of an RC circuit?',ARRAY['τ = RC','τ = R/C','τ = C/R','τ = R+C'],0,'Time constant = R × C.',10),
('circuit-builder','basic','What is the time constant of an RL circuit?',ARRAY['τ = L/R','τ = R/L','τ = RL','τ = R+L'],0,'Time constant = L / R.',10),
('circuit-builder','basic','What is the voltage across a capacitor after one time constant during charging?',ARRAY['63.2% of V','37% of V','100% of V','50% of V'],0,'Capacitor charges to 63.2% after one τ.',10),
('circuit-builder','basic','What is the voltage across a capacitor after one time constant during discharging?',ARRAY['36.8% of V','63.2% of V','0% of V','50% of V'],0,'Capacitor discharges to 36.8% after one τ.',10),
('circuit-builder','basic','How many time constants to fully charge a capacitor?',ARRAY['5','3','1','10'],0,'~99.3% charged after 5 time constants.',10),
('circuit-builder','basic','What is a node in a circuit?',ARRAY['Junction of two or more elements','A single element','A loop','A battery'],0,'A node is a connection point.',10),
('circuit-builder','basic','What is a mesh in a circuit?',ARRAY['A loop with no inner loops','Any loop','A node','A branch'],0,'A mesh is the simplest loop.',10),
('circuit-builder','basic','What is a branch in a circuit?',ARRAY['A path between two nodes','A loop','A node','A source'],0,'A branch is a single path between nodes.',10),
('circuit-builder','basic','What is the current through a 10Ω resistor with 20V across it?',ARRAY['2A','0.5A','200A','10A'],0,'I = V/R = 20/10 = 2A.',10),
('circuit-builder','basic','What is the voltage across a 5Ω resistor with 3A through it?',ARRAY['15V','1.67V','8V','5V'],0,'V = IR = 3×5 = 15V.',10),
('circuit-builder','basic','What is the power dissipated by a 10Ω resistor with 2A through it?',ARRAY['40W','20W','10W','4W'],0,'P = I²R = 4×10 = 40W.',10),
('circuit-builder','basic','What is the power dissipated by a 10Ω resistor with 10V across it?',ARRAY['10W','1W','100W','0.1W'],0,'P = V²/R = 100/10 = 10W.',10),
('circuit-builder','basic','What is the equivalent capacitance of two 10µF caps in series?',ARRAY['5µF','20µF','10µF','100µF'],0,'Series caps: C = (C1×C2)/(C1+C2) = 5µF.',10),
('circuit-builder','basic','What is the equivalent capacitance of two 10µF caps in parallel?',ARRAY['20µF','5µF','10µF','100µF'],0,'Parallel caps: C = C1 + C2 = 20µF.',10),
('circuit-builder','basic','What is the equivalent inductance of two 10mH inductors in series?',ARRAY['20mH','5mH','10mH','100mH'],0,'Series inductors: L = L1 + L2 = 20mH.',10),
('circuit-builder','basic','What is the equivalent inductance of two 10mH inductors in parallel?',ARRAY['5mH','20mH','10mH','100mH'],0,'Parallel inductors: L = (L1×L2)/(L1+L2) = 5mH.',10),
('circuit-builder','basic','What is a voltage divider?',ARRAY['Two resistors splitting voltage','Two resistors combining voltage','A capacitor divider','An inductor divider'],0,'Voltage divider: Vout = Vin × R2/(R1+R2).',10),
('circuit-builder','basic','What is the output of a voltage divider with R1=R2=10Ω and Vin=12V?',ARRAY['6V','12V','3V','0V'],0,'Vout = 12 × 10/(10+10) = 6V.',10),
('circuit-builder','basic','What is a current divider?',ARRAY['Two parallel resistors splitting current','Two series resistors','A voltage divider','A transformer'],0,'Current divides inversely to resistance in parallel.',10),
('circuit-builder','basic','What is the current through R1=2Ω in parallel with R2=4Ω with total current 6A?',ARRAY['4A','2A','3A','6A'],0,'I1 = I × R2/(R1+R2) = 6 × 4/6 = 4A.',10),
('circuit-builder','basic','What does a diode do?',ARRAY['Allows current in one direction','Allows current both ways','Blocks all current','Amplifies current'],0,'Diode conducts when forward-biased.',10),
('circuit-builder','basic','What is the forward voltage drop of a silicon diode?',ARRAY['~0.7V','~0.3V','~1.2V','~0V'],0,'Silicon diode drops ~0.7V when conducting.',10),
('circuit-builder','basic','What is the forward voltage drop of a germanium diode?',ARRAY['~0.3V','~0.7V','~1.2V','~0V'],0,'Germanium diode drops ~0.3V.',10),
('circuit-builder','basic','What is a Zener diode used for?',ARRAY['Voltage regulation','Rectification','Amplification','Filtering'],0,'Zener diodes regulate voltage in reverse breakdown.',10),
('circuit-builder','basic','What is rectification?',ARRAY['Converting AC to DC','Converting DC to AC','Filtering signals','Amplifying signals'],0,'Rectifiers convert AC to pulsating DC.',10),
('circuit-builder','basic','What does a half-wave rectifier use?',ARRAY['One diode','Two diodes','Four diodes','No diode'],0,'Half-wave rectifier uses a single diode.',10);