INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('circuit-builder','intermediate','What is Thevenin''s theorem?',ARRAY['Any linear network = voltage source + series resistance','Any network = current source + parallel resistance','V = IR','P = VI'],0,'Thevenin: Vth + Rth equivalent.',15),
('circuit-builder','intermediate','What is Norton''s theorem?',ARRAY['Any linear network = current source + parallel resistance','Voltage source + series resistance','V = IR','I = V/R'],0,'Norton: In || Rn equivalent.',15),
('circuit-builder','intermediate','How do you find Thevenin resistance?',ARRAY['Turn off all sources, find equivalent resistance','Measure voltage','Measure current','Short the output'],0,'Deactivate sources, then calculate Rth.',15),
('circuit-builder','intermediate','How do you find Thevenin voltage?',ARRAY['Open-circuit voltage at terminals','Short-circuit current','Equivalent resistance','Source voltage'],0,'Vth = open-circuit voltage.',15),
('circuit-builder','intermediate','How do you find Norton current?',ARRAY['Short-circuit current at terminals','Open-circuit voltage','Equivalent resistance','Source current'],0,'In = short-circuit current.',15),
('circuit-builder','intermediate','What is the relationship between Thevenin and Norton equivalents?',ARRAY['Rth = Rn, Vth = In × Rn','Rth = 2×Rn','Vth = In','In = Vth'],0,'Source transformation: Vth = In × Rn.',15),
('circuit-builder','intermediate','What is maximum power transfer?',ARRAY['Load R = source R for max power','Load R = 0','Load R = ∞','Load R = 2×source R'],0,'Max power when RL = Rth.',15),
('circuit-builder','intermediate','What is the efficiency at maximum power transfer?',ARRAY['50%','100%','25%','75%'],0,'Half the power is dissipated in source resistance.',15),
('circuit-builder','intermediate','What is superposition theorem?',ARRAY['Response = sum of responses from each source individually','Sum of all voltages','Sum of all currents','Sum of all powers'],0,'Analyze each source separately, then add.',15),
('circuit-builder','intermediate','When can you use superposition?',ARRAY['Only in linear circuits','In any circuit','Only in DC circuits','Only in AC circuits'],0,'Superposition requires linearity.',15),
('circuit-builder','intermediate','What is mesh analysis?',ARRAY['Using KVL around meshes','Using KCL at nodes','Using Ohm''s law','Using Thevenin'],0,'Mesh analysis applies KVL to each mesh.',15),
('circuit-builder','intermediate','What is nodal analysis?',ARRAY['Using KCL at nodes','Using KVL around meshes','Using Ohm''s law','Using Norton'],0,'Nodal analysis applies KCL at each node.',15),
('circuit-builder','intermediate','Which method is better for circuits with many nodes but few meshes?',ARRAY['Mesh analysis','Nodal analysis','Thevenin','Superposition'],0,'Fewer meshes = fewer mesh equations.',15),
('circuit-builder','intermediate','Which method is better for circuits with many meshes but few nodes?',ARRAY['Nodal analysis','Mesh analysis','Thevenin','Superposition'],0,'Fewer nodes = fewer nodal equations.',15),
('circuit-builder','intermediate','What is a dependent source?',ARRAY['Source controlled by another circuit variable','Independent voltage source','Battery','Current source'],0,'Dependent sources depend on voltage/current elsewhere.',15),
('circuit-builder','intermediate','What are the four types of dependent sources?',ARRAY['VCVS, VCCS, CCVS, CCCS','VCVS only','Voltage and current','AC and DC'],0,'Four types: voltage/current controlled voltage/current.',15),
('circuit-builder','intermediate','Can superposition be used with dependent sources?',ARRAY['Yes, but keep dependent sources active','No','Only with independent sources','Only with voltage sources'],0,'Dependent sources are never deactivated.',15),
('circuit-builder','intermediate','What is a transfer function?',ARRAY['Output/Input in s-domain','Output × Input','Output + Input','Output - Input'],0,'H(s) = Y(s)/X(s).',15),
('circuit-builder','intermediate','What is the impedance of a resistor?',ARRAY['R','1/(sC)','sL','1/R'],0,'Resistor impedance = R (frequency independent).',15),
('circuit-builder','intermediate','What is the impedance of a capacitor in s-domain?',ARRAY['1/(sC)','sC','sL','R'],0,'Capacitor: Z = 1/(sC).',15),
('circuit-builder','intermediate','What is the impedance of an inductor in s-domain?',ARRAY['sL','1/(sL)','1/(sC)','R'],0,'Inductor: Z = sL.',15),
('circuit-builder','intermediate','What is the impedance of a resistor at DC?',ARRAY['R','0','∞','1/R'],0,'Resistor impedance is always R.',15),
('circuit-builder','intermediate','What is the impedance of a capacitor at DC?',ARRAY['∞ (open)','0 (short)','R','1/(sC)'],0,'At DC (f=0), Xc → ∞.',15),
('circuit-builder','intermediate','What is the impedance of an inductor at DC?',ARRAY['0 (short)','∞ (open)','R','sL'],0,'At DC (f=0), Xl → 0.',15),
('circuit-builder','intermediate','What is the impedance of a capacitor at very high frequency?',ARRAY['0 (short)','∞ (open)','R','1/(sC)'],0,'At f→∞, Xc → 0.',15),
('circuit-builder','intermediate','What is the impedance of an inductor at very high frequency?',ARRAY['∞ (open)','0 (short)','R','sL'],0,'At f→∞, Xl → ∞.',15),
('circuit-builder','intermediate','What is a low-pass filter?',ARRAY['Passes low frequencies, attenuates high','Passes high, attenuates low','Passes all','Attenuates all'],0,'LPF cutoff: frequencies below fc pass.',15),
('circuit-builder','intermediate','What is a high-pass filter?',ARRAY['Passes high frequencies, attenuates low','Passes low, attenuates high','Passes all','Attenuates all'],0,'HPF cutoff: frequencies above fc pass.',15),
('circuit-builder','intermediate','What is a band-pass filter?',ARRAY['Passes a range of frequencies','Passes all frequencies','Blocks all frequencies','Passes DC only'],0,'BPF passes frequencies between f_low and f_high.',15),
('circuit-builder','intermediate','What is a band-stop filter?',ARRAY['Blocks a range of frequencies','Passes a range','Passes all','Blocks all'],0,'BSF (notch filter) rejects a band.',15),
('circuit-builder','intermediate','What is the cutoff frequency of an RC low-pass filter?',ARRAY['f = 1/(2πRC)','f = 2πRC','f = RC','f = 1/(RC)'],0,'Cutoff: fc = 1/(2πRC).',15),
('circuit-builder','intermediate','What is the cutoff frequency of an RL high-pass filter?',ARRAY['f = R/(2πL)','f = 2πL/R','f = L/R','f = RL'],0,'Cutoff: fc = R/(2πL).',15),
('circuit-builder','intermediate','What is the roll-off rate of a first-order filter?',ARRAY['-20 dB/decade','-40 dB/decade','-10 dB/decade','-60 dB/decade'],0,'First-order: -20 dB/decade or -6 dB/octave.',15),
('circuit-builder','intermediate','What is the roll-off rate of a second-order filter?',ARRAY['-40 dB/decade','-20 dB/decade','-60 dB/decade','-10 dB/decade'],0,'Second-order: -40 dB/decade.',15),
('circuit-builder','intermediate','What is the Q factor of a filter?',ARRAY['Measure of selectivity/resonance sharpness','Quality of components','Power factor','Efficiency'],0,'Q = fc/BW (center freq / bandwidth).',15),
('circuit-builder','intermediate','What is bandwidth?',ARRAY['Range of frequencies passed','Single frequency','Maximum frequency','Minimum frequency'],0,'BW = f_high - f_low.',15),
('circuit-builder','intermediate','What is resonance in an RLC circuit?',ARRAY['Xl = Xc, impedance is purely resistive','Maximum resistance','Minimum current','Maximum voltage'],0,'At resonance, Xl = Xc, Z = R.',15),
('circuit-builder','intermediate','What is the resonant frequency of an RLC circuit?',ARRAY['f = 1/(2π√(LC))','f = 2π√(LC)','f = LC','f = 1/(LC)'],0,'Resonance: fr = 1/(2π√(LC)).',15),
('circuit-builder','intermediate','What is the impedance at resonance in a series RLC circuit?',ARRAY['R (minimum)','∞','0','Xl'],0,'At resonance, Z = R (minimum impedance).',15),
('circuit-builder','intermediate','What is the impedance at resonance in a parallel RLC circuit?',ARRAY['R (maximum)','0','∞','Xc'],0,'At parallel resonance, Z = R (maximum).',15),
('circuit-builder','intermediate','What happens to current at series resonance?',ARRAY['Maximum','Minimum','Zero','Infinity'],0,'Z is minimum, so current is maximum.',15),
('circuit-builder','intermediate','What happens to current at parallel resonance?',ARRAY['Minimum','Maximum','Zero','Infinity'],0,'Z is maximum, so current is minimum.',15),
('circuit-builder','intermediate','What is a Bode plot?',ARRAY['Magnitude and phase vs frequency','Time vs voltage','Current vs voltage','Power vs time'],0,'Bode plots show frequency response.',15),
('circuit-builder','intermediate','What is the gain margin in a Bode plot?',ARRAY['How much gain can increase before instability','Phase shift','Cutoff frequency','Bandwidth'],0,'Gain margin measured at phase crossover.',15),
('circuit-builder','intermediate','What is the phase margin?',ARRAY['How much phase can change before instability','Gain at cutoff','Maximum phase','Minimum phase'],0,'Phase margin measured at unity gain.',15),
('circuit-builder','intermediate','What is a decibel (dB)?',ARRAY['20 log₁₀(ratio) for voltage','10 log₁₀(ratio)','Linear ratio','Power ratio'],0,'Voltage gain in dB: 20 log₁₀(Vout/Vin).',15),
('circuit-builder','intermediate','What is the dB formula for power ratio?',ARRAY['10 log₁₀(Pout/Pin)','20 log₁₀(Pout/Pin)','Pout/Pin','log₂(Pout/Pin)'],0,'Power gain in dB: 10 log₁₀(Pout/Pin).',15),
('circuit-builder','intermediate','What is a coupling capacitor used for?',ARRAY['Blocking DC, passing AC','Blocking AC','Passing DC','Storing charge'],0,'Coupling caps block DC between stages.',15),
('circuit-builder','intermediate','What is a bypass capacitor used for?',ARRAY['Shunting AC noise to ground','Blocking DC','Passing DC','Increasing voltage'],0,'Bypass caps short AC noise to ground.',15),
('circuit-builder','intermediate','What is the input impedance of an ideal op-amp?',ARRAY['∞','0','1Ω','100Ω'],0,'Ideal op-amp has infinite input impedance.',15);