INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('waveform-lab','basic','What is a sine wave?',ARRAY['Smooth periodic oscillation','Square wave','Sawtooth wave','Pulse wave'],0,'Sine wave: smooth, described by A·sin(2πft).',10),
('waveform-lab','basic','What is the frequency of a wave?',ARRAY['Number of cycles per second','Time for one cycle','Maximum amplitude','Phase angle'],0,'Frequency = cycles/second, measured in Hz.',10),
('waveform-lab','basic','What is the period of a wave?',ARRAY['Time for one complete cycle','Number of cycles per second','Maximum displacement','Phase difference'],0,'Period T = 1/f.',10),
('waveform-lab','basic','What is the unit of frequency?',ARRAY['Hertz (Hz)','Seconds (s)','Volts (V)','Radians (rad)'],0,'Frequency is measured in Hz.',10),
('waveform-lab','basic','What is the amplitude of a wave?',ARRAY['Maximum displacement from zero','Time for one cycle','Number of cycles','Phase angle'],0,'Amplitude = peak value.',10),
('waveform-lab','basic','What is the relationship between frequency and period?',ARRAY['f = 1/T','f = T','f = T²','f = 1/T²'],0,'Frequency and period are reciprocals.',10),
('waveform-lab','basic','What is the phase of a wave?',ARRAY['Angular position in cycle','Maximum amplitude','Frequency','Period'],0,'Phase measured in degrees or radians.',10),
('waveform-lab','basic','What is a square wave?',ARRAY['Alternates between two levels','Smooth oscillation','Linear ramp','Single pulse'],0,'Square wave: 50% duty cycle by default.',10),
('waveform-lab','basic','What is a triangular wave?',ARRAY['Linear rise and fall','Two-level alternation','Smooth curve','Single spike'],0,'Triangular wave: linear ramps up and down.',10),
('waveform-lab','basic','What is a sawtooth wave?',ARRAY['Linear rise then sharp drop','Smooth oscillation','Two levels','Symmetric ramp'],0,'Sawtooth: slow rise, fast fall (or vice versa).',10),
('waveform-lab','basic','What is the RMS value of a sine wave with amplitude A?',ARRAY['A/√2','A','A√2','A/2'],0,'RMS = A/√2 ≈ 0.707A.',10),
('waveform-lab','basic','What is the peak-to-peak value of a sine wave with amplitude A?',ARRAY['2A','A','A√2','A/2'],0,'Peak-to-peak = 2 × amplitude.',10),
('waveform-lab','basic','What is the average value of a full sine wave over one cycle?',ARRAY['0','A','A/√2','A/2'],0,'Sine wave averages to zero over a full cycle.',10),
('waveform-lab','basic','What is the average value of a half-wave rectified sine?',ARRAY['A/π','A','A/√2','A/2'],0,'Half-wave average = A/π ≈ 0.318A.',10),
('waveform-lab','basic','What is the average value of a full-wave rectified sine?',ARRAY['2A/π','A/π','A','A/√2'],0,'Full-wave average = 2A/π ≈ 0.637A.',10),
('waveform-lab','basic','What is the RMS value of a square wave with amplitude A?',ARRAY['A','A/√2','A√2','A/2'],0,'Square wave RMS = A (same as peak).',10),
('waveform-lab','basic','What is the RMS value of a triangular wave with peak A?',ARRAY['A/√3','A/√2','A','A/2'],0,'Triangular wave RMS = A/√3.',10),
('waveform-lab','basic','What is the duty cycle of a square wave?',ARRAY['Percentage of high time in one period','Frequency','Amplitude','Phase'],0,'Duty cycle = high time / period × 100%.',10),
('waveform-lab','basic','What is a pulse wave?',ARRAY['Brief excursion from a baseline','Continuous oscillation','Smooth curve','Linear ramp'],0,'Pulse: short duration high state.',10),
('waveform-lab','basic','What is the fundamental frequency?',ARRAY['Lowest frequency in a waveform','Highest frequency','Average frequency','Zero frequency'],0,'Fundamental = first harmonic.',10),
('waveform-lab','basic','What is a harmonic?',ARRAY['Integer multiple of fundamental frequency','Half the fundamental','Same as fundamental','Random frequency'],0,'Harmonics: 2f, 3f, 4f, etc.',10),
('waveform-lab','basic','What is the 2nd harmonic of 100 Hz?',ARRAY['200 Hz','50 Hz','100 Hz','300 Hz'],0,'2nd harmonic = 2 × 100 = 200 Hz.',10),
('waveform-lab','basic','What is the 3rd harmonic of 60 Hz?',ARRAY['180 Hz','30 Hz','60 Hz','120 Hz'],0,'3rd harmonic = 3 × 60 = 180 Hz.',10),
('waveform-lab','basic','What is DC offset?',ARRAY['Non-zero average value','Zero average','Maximum value','Minimum value'],0,'DC offset shifts the waveform vertically.',10),
('waveform-lab','basic','What is the frequency of a 1 ms period wave?',ARRAY['1000 Hz','100 Hz','1 Hz','10 Hz'],0,'f = 1/T = 1/0.001 = 1000 Hz.',10),
('waveform-lab','basic','What is the period of a 50 Hz wave?',ARRAY['20 ms','10 ms','50 ms','5 ms'],0,'T = 1/f = 1/50 = 20 ms.',10),
('waveform-lab','basic','What is the period of a 1 kHz wave?',ARRAY['1 ms','10 ms','0.1 ms','100 ms'],0,'T = 1/1000 = 1 ms.',10),
('waveform-lab','basic','What is the angular frequency?',ARRAY['ω = 2πf','ω = f','ω = 1/f','ω = 2π/f'],0,'Angular frequency ω = 2πf rad/s.',10),
('waveform-lab','basic','What is the phase difference between two waves?',ARRAY['Angular displacement between them','Frequency difference','Amplitude difference','Period difference'],0,'Phase difference measured in degrees/radians.',10),
('waveform-lab','basic','What does ''in phase'' mean?',ARRAY['Zero phase difference','180° phase difference','90° phase difference','360° phase difference'],0,'In phase: peaks and troughs align.',10),
('waveform-lab','basic','What does ''out of phase'' mean?',ARRAY['Non-zero phase difference','Zero phase difference','Same frequency','Same amplitude'],0,'Out of phase: peaks don''t align.',10),
('waveform-lab','basic','What is a 180° phase shift?',ARRAY['Complete inversion','No change','90° rotation','360° rotation'],0,'180° shift = inverted waveform.',10),
('waveform-lab','basic','What is a 90° phase shift?',ARRAY['Quarter cycle offset','Half cycle offset','Full cycle offset','No offset'],0,'90° = quarter wavelength displacement.',10),
('waveform-lab','basic','What is wavelength?',ARRAY['Distance for one complete cycle','Time for one cycle','Maximum amplitude','Phase angle'],0,'Wavelength λ = v/f.',10),
('waveform-lab','basic','What is the unit of wavelength?',ARRAY['Meter (m)','Hertz (Hz)','Second (s)','Volt (V)'],0,'Wavelength measured in meters.',10),
('waveform-lab','basic','What is a waveform?',ARRAY['Visual representation of signal vs time','Frequency spectrum','Phase diagram','Circuit diagram'],0,'Waveform shows amplitude over time.',10),
('waveform-lab','basic','What is a cosine wave?',ARRAY['Sine wave shifted 90° ahead','Inverted sine','Half-frequency sine','Double-frequency sine'],0,'cos(θ) = sin(θ + 90°).',10),
('waveform-lab','basic','What is the relationship between sine and cosine?',ARRAY['90° phase difference','180° phase difference','Same wave','Opposite wave'],0,'Cosine leads sine by 90°.',10),
('waveform-lab','basic','What is a composite waveform?',ARRAY['Sum of multiple sine waves','Single sine wave','Square wave only','DC signal'],0,'Any periodic wave = sum of harmonics (Fourier).',10),
('waveform-lab','basic','What is the crest factor of a sine wave?',ARRAY['√2 ≈ 1.414','1','2','0.707'],0,'Crest factor = peak/RMS = A/(A/√2) = √2.',10),
('waveform-lab','basic','What is the crest factor of a square wave?',ARRAY['1','√2','2','0.707'],0,'Square: peak = RMS, so crest factor = 1.',10),
('waveform-lab','basic','What is the form factor of a sine wave?',ARRAY['π/(2√2) ≈ 1.11','1','√2','0.707'],0,'Form factor = RMS/Average = (A/√2)/(2A/π).',10),
('waveform-lab','basic','What is noise in a signal?',ARRAY['Unwanted random fluctuations','Desired signal','DC component','Harmonic'],0,'Noise degrades signal quality.',10),
('waveform-lab','basic','What is white noise?',ARRAY['Equal power across all frequencies','Single frequency noise','Low-frequency noise','High-frequency noise'],0,'White noise: flat power spectral density.',10),
('waveform-lab','basic','What is pink noise?',ARRAY['Equal power per octave','Equal power per Hz','Single frequency','No low frequencies'],0,'Pink noise: 1/f power spectrum.',10),
('waveform-lab','basic','What is SNR?',ARRAY['Signal-to-Noise Ratio','Signal Noise Reduction','System Noise Rate','Signal Null Ratio'],0,'SNR = signal power / noise power.',10),
('waveform-lab','basic','What is the unit of SNR?',ARRAY['dB','Hz','V','W'],0,'SNR typically expressed in dB.',10),
('waveform-lab','basic','What is a carrier wave?',ARRAY['High-frequency wave modulated by signal','Low-frequency wave','DC signal','Noise signal'],0,'Carrier is modulated by information signal.',10),
('waveform-lab','basic','What is modulation?',ARRAY['Varying carrier properties with signal','Amplifying a signal','Filtering a signal','Generating noise'],0,'Modulation encodes information onto carrier.',10),
('waveform-lab','basic','What is demodulation?',ARRAY['Extracting signal from carrier','Adding carrier to signal','Filtering noise','Amplifying carrier'],0,'Demodulation recovers original signal.',10);