INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('waveform-lab','advanced','What is the Laplace transform of e^(-at)u(t)?',ARRAY['1/(s+a)','1/(s-a)','s/(s+a)','a/(s+a)'],0,'Laplace: L{e^(-at)} = 1/(s+a).',20),
('waveform-lab','advanced','What is the Laplace transform of a unit step u(t)?',ARRAY['1/s','s','1/(s+1)','s+1'],0,'L{u(t)} = 1/s.',20),
('waveform-lab','advanced','What is the Laplace transform of δ(t)?',ARRAY['1','1/s','s','0'],0,'L{δ(t)} = 1.',20),
('waveform-lab','advanced','What is the Laplace transform of sin(ωt)?',ARRAY['ω/(s²+ω²)','1/(s²+ω²)','s/(s²+ω²)','ω/s'],0,'L{sin(ωt)} = ω/(s²+ω²).',20),
('waveform-lab','advanced','What is the Laplace transform of cos(ωt)?',ARRAY['s/(s²+ω²)','ω/(s²+ω²)','1/(s²+ω²)','s/ω'],0,'L{cos(ωt)} = s/(s²+ω²).',20),
('waveform-lab','advanced','What is the region of convergence (ROC)?',ARRAY['Range of s where transform converges','Range of time','Range of frequency','Range of amplitude'],0,'ROC determines stability and causality.',20),
('waveform-lab','advanced','What is a pole in the s-plane?',ARRAY['Value of s where transfer function → ∞','Value where TF = 0','Value where TF = 1','Value where TF is real'],0,'Poles determine system dynamics.',20),
('waveform-lab','advanced','What is a zero in the s-plane?',ARRAY['Value of s where transfer function = 0','Value where TF → ∞','Value where TF = 1','Value where TF is imaginary'],0,'Zeros affect transient response shape.',20),
('waveform-lab','advanced','What does a pole in the right half s-plane indicate?',ARRAY['Unstable system','Stable system','Marginally stable','Oscillatory'],0,'RHP poles cause exponential growth (instability).',20),
('waveform-lab','advanced','What does a pole on the imaginary axis indicate?',ARRAY['Marginally stable (oscillatory)','Unstable','Stable','No dynamics'],0,'Imaginary axis poles: sustained oscillation.',20),
('waveform-lab','advanced','What is the damping ratio ζ?',ARRAY['Measure of oscillation decay rate','Gain margin','Phase margin','Natural frequency'],0,'ζ < 1: underdamped; ζ = 1: critical; ζ > 1: overdamped.',20),
('waveform-lab','advanced','What is the natural frequency ωn?',ARRAY['Oscillation frequency without damping','Damped frequency','Cutoff frequency','Resonant frequency'],0,'ωn is the undamped natural frequency.',20),
('waveform-lab','advanced','What is the damped frequency ωd?',ARRAY['ωn√(1-ζ²)','ωn','ωn/ζ','ωnζ'],0,'Damped frequency = ωn × √(1-ζ²).',20),
('waveform-lab','advanced','What is the settling time for a 2nd-order system?',ARRAY['~4/(ζωn)','~1/(ζωn)','~2/(ζωn)','~8/(ζωn)'],0,'Settling time ≈ 4 time constants = 4/(ζωn).',20),
('waveform-lab','advanced','What is the peak time for a 2nd-order system?',ARRAY['π/ωd','2π/ωd','π/ωn','1/ωd'],0,'Peak time = π/ωd.',20),
('waveform-lab','advanced','What is the percent overshoot for ζ=0.5?',ARRAY['~16.3%','~0%','~50%','~100%'],0,'%OS = 100·e^(-πζ/√(1-ζ²)) ≈ 16.3% for ζ=0.5.',20),
('waveform-lab','advanced','What is the steady-state error for a type 0 system with step input?',ARRAY['1/(1+Kp)','0','∞','Kp'],0,'Type 0: ess = 1/(1+Kp) for step input.',20),
('waveform-lab','advanced','What is the steady-state error for a type 1 system with step input?',ARRAY['0','1/(1+Kp)','∞','Kv'],0,'Type 1: zero error for step input.',20),
('waveform-lab','advanced','What is the steady-state error for a type 1 system with ramp input?',ARRAY['1/Kv','0','∞','Kp'],0,'Type 1: ess = 1/Kv for ramp input.',20),
('waveform-lab','advanced','What is the velocity error constant Kv?',ARRAY['lim(s→0) sG(s)','lim(s→0) G(s)','lim(s→∞) sG(s)','lim(s→0) s²G(s)'],0,'Kv = lim(s→0) s·G(s).',20),
('waveform-lab','advanced','What is the position error constant Kp?',ARRAY['lim(s→0) G(s)','lim(s→0) sG(s)','lim(s→∞) G(s)','lim(s→0) s²G(s)'],0,'Kp = lim(s→0) G(s).',20),
('waveform-lab','advanced','What is the acceleration error constant Ka?',ARRAY['lim(s→0) s²G(s)','lim(s→0) sG(s)','lim(s→0) G(s)','lim(s→∞) s²G(s)'],0,'Ka = lim(s→0) s²·G(s).',20),
('waveform-lab','advanced','What is a root locus?',ARRAY['Plot of closed-loop poles as gain varies','Open-loop poles','Nyquist plot','Bode plot'],0,'Root locus shows pole migration with gain.',20),
('waveform-lab','advanced','What is the Nyquist criterion?',ARRAY['Encirclements of -1 determine stability','Pole locations','Zero locations','Gain margin'],0,'N = Z - P (encirclements = RHP zeros - RHP poles).',20),
('waveform-lab','advanced','What is the gain margin from a Bode plot?',ARRAY['Gain at phase crossover frequency','Gain at unity frequency','Maximum gain','Minimum gain'],0,'GM = 1/|G(jω)| at phase = -180°.',20),
('waveform-lab','advanced','What is the phase margin?',ARRAY['180° + phase at unity gain crossover','Phase at zero gain','Maximum phase','Phase at resonance'],0,'PM = 180° + ∠G(jω) at |G| = 1.',20),
('waveform-lab','advanced','What is a lead compensator?',ARRAY['Improves transient response (adds phase lead)','Improves steady-state error','Reduces bandwidth','Adds poles'],0,'Lead compensator: zero closer to origin than pole.',20),
('waveform-lab','advanced','What is a lag compensator?',ARRAY['Improves steady-state error (adds gain at low f)','Improves transient response','Increases bandwidth','Adds zeros'],0,'Lag compensator: pole closer to origin than zero.',20),
('waveform-lab','advanced','What is a PID controller?',ARRAY['Proportional + Integral + Derivative','Proportional + Integral + Delay','Phase + Inverse + Derivative','Power + Input + Display'],0,'PID: Kp + Ki/s + Kd·s.',20),
('waveform-lab','advanced','What does the P term in PID do?',ARRAY['Reduces rise time','Eliminates steady-state error','Increases damping','Adds phase lead'],0,'Proportional gain speeds up response.',20),
('waveform-lab','advanced','What does the I term in PID do?',ARRAY['Eliminates steady-state error','Reduces rise time','Increases damping','Adds phase lead'],0,'Integral action removes steady-state error.',20),
('waveform-lab','advanced','What does the D term in PID do?',ARRAY['Improves stability and reduces overshoot','Eliminates steady-state error','Reduces rise time','Adds gain at low frequency'],0,'Derivative action damps oscillations.',20),
('waveform-lab','advanced','What is state-space representation?',ARRAY['Matrix form of dynamic systems','Frequency domain','Time domain only','Laplace domain'],0,'State-space: ẋ = Ax + Bu, y = Cx + Du.',20),
('waveform-lab','advanced','What is controllability?',ARRAY['Can drive system to any state with input','Can observe all states','System is stable','System is linear'],0,'Controllable if rank of [B AB A²B...] = n.',20),
('waveform-lab','advanced','What is observability?',ARRAY['Can determine all states from output','Can control all states','System is stable','System is linear'],0,'Observable if rank of [C; CA; CA²;...] = n.',20),
('waveform-lab','advanced','What is the Cayley-Hamilton theorem?',ARRAY['Matrix satisfies its own characteristic equation','Matrix is always invertible','Matrix is symmetric','Matrix is diagonal'],0,'Cayley-Hamilton: A satisfies det(λI-A)=0.',20),
('waveform-lab','advanced','What is the Lyapunov stability criterion?',ARRAY['Find V(x) > 0 with V̇(x) < 0','Check eigenvalues only','Check poles only','Check zeros only'],0,'Lyapunov: positive definite V with negative derivative.',20),
('waveform-lab','advanced','What is a Kalman filter?',ARRAY['Optimal state estimator','Analog filter','Low-pass filter','PID controller'],0,'Kalman filter: optimal recursive estimator.',20),
('waveform-lab','advanced','What is the difference between controllability and observability?',ARRAY['Controllability: input→states; Observability: output→states','Same concept','Controllability is about output','Observability is about input'],0,'Dual concepts in state-space.',20),
('waveform-lab','advanced','What is the z-transform of a unit delay?',ARRAY['z⁻¹','z','1','z²'],0,'Unit delay in z-domain: z⁻¹.',20),
('waveform-lab','advanced','What is the z-transform of a^n u[n]?',ARRAY['z/(z-a)','1/(z-a)','z-a','z(z-a)'],0,'Z{a^n u[n]} = z/(z-a), |z| > |a|.',20),
('waveform-lab','advanced','What is the z-transform of δ[n]?',ARRAY['1','z','z⁻¹','0'],0,'Z{δ[n]} = 1.',20),
('waveform-lab','advanced','What is the z-transform of u[n]?',ARRAY['z/(z-1)','1/(z-1)','z-1','z'],0,'Z{u[n]} = z/(z-1), |z| > 1.',20),
('waveform-lab','advanced','What is the chirp Z-transform?',ARRAY['Generalized ZT for arbitrary contour','Fast ZT','Inverse ZT','Discrete ZT'],0,'Chirp ZT evaluates ZT on a spiral contour.',20),
('waveform-lab','advanced','What is the DTFT?',ARRAY['Discrete-Time Fourier Transform','Digital Time Fourier Transform','Direct Time Fourier Transform','Discrete Transform Fourier Theorem'],0,'DTFT: Fourier transform of discrete signals.',20),
('waveform-lab','advanced','What is the relationship between DTFT and Z-transform?',ARRAY['ZT evaluated on unit circle','ZT evaluated on real axis','ZT evaluated at origin','ZT evaluated at infinity'],0,'DTFT = Z(e^jω), i.e., ZT on unit circle.',20),
('waveform-lab','advanced','What is the group delay of a filter?',ARRAY['Negative derivative of phase vs frequency','Time delay of amplitude','Filter bandwidth','Filter order'],0,'Group delay = -dφ/dω, ideally constant.',20),
('waveform-lab','advanced','What is a minimum-phase system?',ARRAY['All zeros in left half s-plane','All zeros in RHP','No zeros','All poles in RHP'],0,'Minimum phase: stable and causal with minimum delay.',20),
('waveform-lab','advanced','What is an all-pass filter?',ARRAY['Flat magnitude response, varying phase','Flat phase, varying magnitude','Passes all frequencies with no change','Blocks all frequencies'],0,'All-pass: |H(jω)| = 1, phase varies.',20),
('waveform-lab','advanced','What is the Hilbert transform?',ARRAY['90° phase shifter','Low-pass filter','High-pass filter','Amplifier'],0,'Hilbert transform shifts all frequencies by -90°.',20);