INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('power-quest','basic','What is electrical power?',ARRAY['Rate of energy transfer','Amount of charge','Resistance to flow','Voltage level'],0,'Power = energy/time, measured in watts.',10),
('power-quest','basic','What is the formula for DC power?',ARRAY['P = VI','P = V/I','P = I/V','P = V+I'],0,'DC power = voltage × current.',10),
('power-quest','basic','What is the unit of electrical energy?',ARRAY['Joule (J)','Watt (W)','Volt (V)','Ampere (A)'],0,'Energy measured in joules (or watt-hours).',10),
('power-quest','basic','What is 1 kWh in joules?',ARRAY['3.6 MJ','3600 J','1 J','1000 J'],0,'1 kWh = 1000 × 3600 = 3.6 × 10⁶ J.',10),
('power-quest','basic','What is the efficiency of a system?',ARRAY['Output power / Input power × 100%','Input / Output × 100%','Output × Input','Output + Input'],0,'Efficiency = Pout/Pin × 100%.',10),
('power-quest','basic','What is power factor?',ARRAY['cos(φ) = R/Z','R/X','X/R','Z/R'],0,'Power factor = cos(phase angle) = R/Z.',10),
('power-quest','basic','What is the ideal power factor?',ARRAY['1','0','0.5','0.8'],0,'Unity power factor = 1 (purely resistive).',10),
('power-quest','basic','What does a power factor of 0.8 lagging mean?',ARRAY['Current lags voltage by 36.87°','Current leads voltage','Current in phase','No phase difference'],0,'cos⁻¹(0.8) = 36.87° lagging.',10),
('power-quest','basic','What is real power?',ARRAY['Power actually consumed','Power stored in reactive elements','Total apparent power','Power lost in wires'],0,'Real power P = VI cos(φ), measured in watts.',10),
('power-quest','basic','What is reactive power?',ARRAY['Power oscillating in reactive elements','Power consumed by resistors','Total power','Power lost'],0,'Reactive power Q = VI sin(φ), measured in VAR.',10),
('power-quest','basic','What is apparent power?',ARRAY['VI (total power)','VI cos(φ)','VI sin(φ)','V/I'],0,'Apparent power S = VI, measured in VA.',10),
('power-quest','basic','What is the unit of reactive power?',ARRAY['VAR','Watt','VA','Joule'],0,'Reactive power measured in VAR (volt-ampere reactive).',10),
('power-quest','basic','What is the unit of apparent power?',ARRAY['VA','Watt','VAR','Joule'],0,'Apparent power measured in VA (volt-ampere).',10),
('power-quest','basic','What is the power triangle?',ARRAY['P, Q, S relationship','Voltage triangle','Current triangle','Resistance triangle'],0,'S² = P² + Q², S = √(P²+Q²).',10),
('power-quest','basic','What is the relationship between P, Q, and S?',ARRAY['S² = P² + Q²','S = P + Q','S = P × Q','S = P - Q'],0,'Power triangle: S = √(P² + Q²).',10),
('power-quest','basic','What is a transformer?',ARRAY['Device that changes voltage levels','Device that generates power','Device that stores energy','Device that measures power'],0,'Transformer transfers AC power between voltage levels.',10),
('power-quest','basic','What does a step-up transformer do?',ARRAY['Increases voltage, decreases current','Decreases voltage, increases current','Increases both','Decreases both'],0,'Step-up: V₂ > V₁, I₂ < I₁.',10),
('power-quest','basic','What does a step-down transformer do?',ARRAY['Decreases voltage, increases current','Increases voltage, decreases current','Decreases both','Increases both'],0,'Step-down: V₂ < V₁, I₂ > I₁.',10),
('power-quest','basic','What is the turns ratio of a transformer?',ARRAY['N2/N1','N1/N2','N1+N2','N1×N2'],0,'Turns ratio a = N2/N1 = V2/V1 = I1/I2.',10),
('power-quest','basic','What is an ideal transformer''s power relationship?',ARRAY['V1I1 = V2I2','V1I2 = V2I1','V1 = V2','I1 = I2'],0,'Ideal: input power = output power.',10),
('power-quest','basic','What is the efficiency of an ideal transformer?',ARRAY['100%','50%','90%','99%'],0,'Ideal transformer has no losses.',10),
('power-quest','basic','What are transformer losses?',ARRAY['Copper losses + core losses','Only copper losses','Only core losses','No losses'],0,'Copper (I²R) + core (hysteresis + eddy current).',10),
('power-quest','basic','What are copper losses?',ARRAY['I²R losses in windings','Losses in the core','Losses in the air','Losses in insulation'],0,'Copper losses = current² × winding resistance.',10),
('power-quest','basic','What are core losses?',ARRAY['Hysteresis + eddy current losses','Copper losses','Friction losses','Windage losses'],0,'Core losses are constant (independent of load).',10),
('power-quest','basic','What is hysteresis loss?',ARRAY['Energy lost in magnetizing/demagnetizing core','Loss in windings','Loss in oil','Loss in insulation'],0,'Hysteresis: area of B-H loop × frequency × volume.',10),
('power-quest','basic','What is eddy current loss?',ARRAY['Loss from circulating currents in core','Loss in windings','Loss in air gap','Loss in connections'],0,'Eddy currents induced in core; reduced by laminations.',10),
('power-quest','basic','How are eddy currents reduced?',ARRAY['Using laminated cores','Using thicker wire','Using more turns','Using oil'],0,'Laminations break eddy current paths.',10),
('power-quest','basic','What is a rectifier?',ARRAY['Converts AC to DC','Converts DC to AC','Changes voltage','Stores energy'],0,'Rectifier converts AC to DC.',10),
('power-quest','basic','What is an inverter?',ARRAY['Converts DC to AC','Converts AC to DC','Changes voltage','Stores energy'],0,'Inverter converts DC to AC.',10),
('power-quest','basic','What is a converter?',ARRAY['Changes voltage/current form','Stores energy','Measures power','Generates power'],0,'Converters change electrical form (AC/DC, voltage).',10),
('power-quest','basic','What is a buck converter?',ARRAY['Step-down DC-DC converter','Step-up DC-DC','AC-DC converter','DC-AC converter'],0,'Buck: output voltage < input voltage.',10),
('power-quest','basic','What is a boost converter?',ARRAY['Step-up DC-DC converter','Step-down DC-DC','AC-DC converter','DC-AC converter'],0,'Boost: output voltage > input voltage.',10),
('power-quest','basic','What is a buck-boost converter?',ARRAY['Can step up or down','Step-up only','Step-down only','AC-DC only'],0,'Buck-boost: inverting output, up or down.',10),
('power-quest','basic','What is the duty cycle in a switching converter?',ARRAY['Ratio of on-time to total period','Ratio of off-time to period','Switching frequency','Output voltage'],0,'D = Ton / (Ton + Toff).',10),
('power-quest','basic','What is the output of a buck converter with D=0.5 and Vin=12V?',ARRAY['6V','12V','24V','3V'],0,'Vout = D × Vin = 0.5 × 12 = 6V.',10),
('power-quest','basic','What is the output of a boost converter with D=0.5 and Vin=5V?',ARRAY['10V','5V','2.5V','7.5V'],0,'Vout = Vin/(1-D) = 5/0.5 = 10V.',10),
('power-quest','basic','What is a battery?',ARRAY['Stores electrical energy','Generates AC','Converts DC to AC','Measures voltage'],0,'Batteries store energy chemically.',10),
('power-quest','basic','What is battery capacity measured in?',ARRAY['Ampere-hours (Ah)','Watts (W)','Volts (V)','Ohms (Ω)'],0,'Capacity = current × time, in Ah.',10),
('power-quest','basic','What is the energy stored in a battery?',ARRAY['Voltage × Capacity (Wh)','Capacity only','Current only','Voltage only'],0,'Energy = V × Ah = watt-hours.',10),
('power-quest','basic','What is a solar cell?',ARRAY['Converts light to electricity','Stores energy','Converts AC to DC','Measures light'],0,'Photovoltaic cells convert sunlight to DC.',10),
('power-quest','basic','What is the typical voltage of a silicon solar cell?',ARRAY['~0.5-0.6V','~1.5V','~12V','~5V'],0,'Single Si cell: ~0.5-0.6V open circuit.',10),
('power-quest','basic','What is a fuel cell?',ARRAY['Converts chemical energy to electricity','Stores solar energy','Converts AC to DC','Stores charge'],0,'Fuel cells use hydrogen + oxygen → electricity + water.',10),
('power-quest','basic','What is a generator?',ARRAY['Converts mechanical energy to electrical','Converts electrical to mechanical','Stores energy','Measures power'],0,'Generators convert mechanical rotation to electricity.',10),
('power-quest','basic','What is a motor?',ARRAY['Converts electrical energy to mechanical','Converts mechanical to electrical','Stores energy','Measures power'],0,'Motors convert electricity to mechanical rotation.',10),
('power-quest','basic','What is the difference between a motor and generator?',ARRAY['Motor: electric→mechanical; Generator: mechanical→electric','Same device','Motor generates power','Generator uses power'],0,'Same machine can work as either depending on direction.',10),
('power-quest','basic','What is AC power?',ARRAY['Alternating current power','Direct current power','Stored power','Reactive power'],0,'AC periodically reverses direction.',10),
('power-quest','basic','What is DC power?',ARRAY['Direct current power','Alternating current power','Reactive power','Apparent power'],0,'DC flows in one direction.',10),
('power-quest','basic','What is the frequency of AC power in the US?',ARRAY['60 Hz','50 Hz','100 Hz','120 Hz'],0,'US uses 60 Hz mains power.',10),
('power-quest','basic','What is the frequency of AC power in Europe?',ARRAY['50 Hz','60 Hz','100 Hz','120 Hz'],0,'Europe uses 50 Hz mains power.',10),
('power-quest','basic','What is the RMS voltage of US household AC?',ARRAY['120V','240V','170V','60V'],0,'US: 120V RMS, 60 Hz.',10);