INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('state-machine','basic','What is a state machine?',ARRAY['System that transitions between states','System with no states','System with one state','Analog circuit'],0,'A state machine has states and transitions.',10),
('state-machine','basic','What is a state in a state machine?',ARRAY['A condition or mode of the system','A clock cycle','A voltage level','A gate output'],0,'A state represents a unique configuration.',10),
('state-machine','basic','What is a transition?',ARRAY['Change from one state to another','A clock pulse','A reset signal','A gate delay'],0,'Transitions occur based on inputs and current state.',10),
('state-machine','basic','What are the two types of state machines?',ARRAY['Mealy and Moore','Combinational and sequential','Synchronous and asynchronous','Digital and analog'],0,'Mealy: output depends on state+input. Moore: output depends on state only.',10),
('state-machine','basic','What is a Moore machine?',ARRAY['Output depends only on current state','Output depends on input only','Output depends on state and input','No output'],0,'Moore: output = f(state).',10),
('state-machine','basic','What is a Mealy machine?',ARRAY['Output depends on state and input','Output depends on state only','Output depends on input only','No output'],0,'Mealy: output = f(state, input).',10),
('state-machine','basic','What is a state diagram?',ARRAY['Visual representation of states and transitions','Circuit diagram','Truth table','Timing diagram'],0,'State diagram: nodes = states, arrows = transitions.',10),
('state-machine','basic','What is a state table?',ARRAY['Tabular form of state transitions','Truth table','K-map','Timing diagram'],0,'State table lists next state and output for each input.',10),
('state-machine','basic','What is the initial state?',ARRAY['Starting state of the machine','Final state','Any state','Reset state'],0,'The initial state is entered on reset/power-up.',10),
('state-machine','basic','What is a reset state?',ARRAY['State entered on system reset','Final state','Error state','Idle state'],0,'Reset brings the machine to a known starting state.',10),
('state-machine','basic','What is a clock in a state machine?',ARRAY['Signal that triggers state transitions','Power signal','Reset signal','Input signal'],0,'State changes occur on clock edges.',10),
('state-machine','basic','What is a synchronous state machine?',ARRAY['Transitions on clock edges','Transitions anytime','No clock','Asynchronous'],0,'Synchronous: all flip-flops share the same clock.',10),
('state-machine','basic','What is an asynchronous state machine?',ARRAY['Transitions without a clock','Transitions on clock','Synchronous','No transitions'],0,'Asynchronous: transitions happen immediately on input change.',10),
('state-machine','basic','What is a flip-flop?',ARRAY['1-bit memory element','Logic gate','Counter','Multiplexer'],0,'Flip-flops store state bits.',10),
('state-machine','basic','What does D flip-flop do?',ARRAY['Stores D input on clock edge','Inverts input','ANDs inputs','ORs inputs'],0,'D-FF: Q follows D on clock edge.',10),
('state-machine','basic','What does JK flip-flop do?',ARRAY['J=K=0 hold, J=K=1 toggle, else set/reset','Stores D','Inverts clock','Counts only'],0,'JK-FF: versatile, can hold, set, reset, toggle.',10),
('state-machine','basic','What does T flip-flop do?',ARRAY['Toggles output on T=1','Stores T','Inverts T','ANDs inputs'],0,'T-FF: Q toggles when T=1 on clock edge.',10),
('state-machine','basic','What does SR flip-flop do?',ARRAY['S=1 set, R=1 reset, S=R=0 hold','Stores D','Toggles','Inverts'],0,'SR-FF: S sets, R resets, S=R=1 forbidden.',10),
('state-machine','basic','What is the forbidden state of SR flip-flop?',ARRAY['S=1 and R=1 simultaneously','S=0 and R=0','S=1 and R=0','S=0 and R=1'],0,'S=R=1 produces invalid output (both Q and Q'' high).',10),
('state-machine','basic','How many flip-flops are needed for 8 states?',ARRAY['3','2','4','8'],0,'2^n ≥ 8, so n = 3 flip-flops.',10),
('state-machine','basic','How many flip-flops are needed for 5 states?',ARRAY['3','2','4','5'],0,'2^n ≥ 5, so n = 3 (2^3 = 8 ≥ 5).',10),
('state-machine','basic','How many flip-flops are needed for 16 states?',ARRAY['4','3','5','16'],0,'2^4 = 16, so n = 4.',10),
('state-machine','basic','How many states can 4 flip-flops represent?',ARRAY['16','8','4','32'],0,'2^4 = 16 states.',10),
('state-machine','basic','What is a counter?',ARRAY['State machine that cycles through states','Adder circuit','Comparator','Multiplexer'],0,'Counters are a common type of state machine.',10),
('state-machine','basic','What is an up counter?',ARRAY['Counts 0, 1, 2, ..., max, 0, ...','Counts down only','Counts randomly','Stays at 0'],0,'Up counter increments on each clock.',10),
('state-machine','basic','What is a down counter?',ARRAY['Counts max, max-1, ..., 0, max, ...','Counts up only','Counts randomly','Stays at max'],0,'Down counter decrements on each clock.',10),
('state-machine','basic','What is an up/down counter?',ARRAY['Can count up or down based on control','Counts up only','Counts down only','Stays fixed'],0,'Up/down counter: direction controlled by input.',10),
('state-machine','basic','What is a modulo-N counter?',ARRAY['Counts 0 to N-1 then wraps','Counts to N','Counts 0 to infinity','Counts down only'],0,'Mod-N counter has N states (0 to N-1).',10),
('state-machine','basic','What is a mod-10 counter?',ARRAY['Counts 0-9 (decade counter)','Counts 0-10','Counts 0-99','Counts 0-100'],0,'Mod-10: 0,1,2,...,9,0,1,...',10),
('state-machine','basic','What is a ripple counter?',ARRAY['Flip-flops cascade, carry ripples','All FFs clocked simultaneously','No clock','Synchronous counter'],0,'Ripple (asynchronous) counter: each FF triggers the next.',10),
('state-machine','basic','What is a synchronous counter?',ARRAY['All flip-flops share same clock','Each FF triggers next','No clock','Ripple counter'],0,'Synchronous counter: all FFs update simultaneously.',10),
('state-machine','basic','What is the advantage of synchronous counter?',ARRAY['No ripple delay','Simpler design','Fewer gates','Lower power'],0,'Synchronous counters avoid cumulative propagation delay.',10),
('state-machine','basic','What is a ring counter?',ARRAY['Shift register with feedback','Binary counter','Ripple counter','Johnson counter'],0,'Ring counter: Q of last FF feeds D of first.',10),
('state-machine','basic','How many states does an n-bit ring counter have?',ARRAY['n','2^n','n-1','2n'],0,'Ring counter: n states (one-hot encoding).',10),
('state-machine','basic','What is a Johnson counter?',ARRAY['Ring counter with inverted feedback','Binary counter','Ripple counter','Decade counter'],0,'Johnson (twisted ring): inverted feedback doubles states.',10),
('state-machine','basic','How many states does an n-bit Johnson counter have?',ARRAY['2n','n','2^n','n²'],0,'Johnson counter: 2n states.',10),
('state-machine','basic','What is a shift register?',ARRAY['Chain of flip-flops shifting data','Counter','Adder','Comparator'],0,'Shift registers store and shift data bit-by-bit.',10),
('state-machine','basic','What is SISO shift register?',ARRAY['Serial In, Serial Out','Parallel In, Parallel Out','Serial In, Parallel Out','Parallel In, Serial Out'],0,'SISO: data enters and exits one bit at a time.',10),
('state-machine','basic','What is SIPO shift register?',ARRAY['Serial In, Parallel Out','SISO','PISO','PIPO'],0,'SIPO: serial input, read all bits in parallel.',10),
('state-machine','basic','What is PISO shift register?',ARRAY['Parallel In, Serial Out','SISO','SIPO','PIPO'],0,'PISO: load all bits, shift out serially.',10),
('state-machine','basic','What is PIPO shift register?',ARRAY['Parallel In, Parallel Out','SISO','SIPO','PISO'],0,'PIPO: parallel load and parallel read.',10),
('state-machine','basic','What is a finite state machine (FSM)?',ARRAY['State machine with finite number of states','State machine with infinite states','Analog state machine','No states'],0,'FSM: finite states, deterministic transitions.',10),
('state-machine','basic','What is a deterministic FSM?',ARRAY['Each input has exactly one transition','Multiple transitions per input','Random transitions','No transitions'],0,'Deterministic: one next state per (state, input).',10),
('state-machine','basic','What is a nondeterministic FSM (NFA)?',ARRAY['Multiple possible transitions per input','One transition per input','No transitions','Random states'],0,'NFA: can transition to multiple states simultaneously.',10),
('state-machine','basic','What is a Mealy output?',ARRAY['Associated with transitions','Associated with states','No output','Constant output'],0,'Mealy outputs appear on transition arcs.',10),
('state-machine','basic','What is a Moore output?',ARRAY['Associated with states','Associated with transitions','No output','Input-dependent output'],0,'Moore outputs appear inside state nodes.',10),
('state-machine','basic','Which machine type generally has fewer states?',ARRAY['Mealy','Moore','Same','Depends on input'],0,'Mealy often needs fewer states (output on transitions).',10),
('state-machine','basic','Which machine type is easier to design?',ARRAY['Moore (simpler output logic)','Mealy','Both equally','Neither'],0,'Moore: output depends only on state, simpler logic.',10),
('state-machine','basic','What is a state encoding?',ARRAY['Assigning binary codes to states','Encoding inputs','Encoding outputs','Encoding transitions'],0,'State encoding: binary, one-hot, Gray code.',10),
('state-machine','basic','What is one-hot encoding?',ARRAY['One bit per state','Binary encoding','Gray code','BCD encoding'],0,'One-hot: n states use n flip-flops, one bit high at a time.',10);