INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('cpu-boss','basic','What does CPU stand for?',ARRAY['Central Processing Unit','Computer Processing Unit','Central Power Unit','Computer Power Unit'],0,'CPU = Central Processing Unit.',10),
('cpu-boss','basic','What is the function of a CPU?',ARRAY['Executes instructions','Stores data','Displays output','Powers the computer'],0,'CPU fetches, decodes, and executes instructions.',10),
('cpu-boss','basic','What are the main parts of a CPU?',ARRAY['ALU, Control Unit, Registers','Cache and RAM','Hard drive and SSD','Input and output'],0,'CPU: ALU (compute), CU (control), Registers (storage).',10),
('cpu-boss','basic','What does ALU stand for?',ARRAY['Arithmetic Logic Unit','Advanced Logic Unit','Arithmetic Loading Unit','Active Logic Unit'],0,'ALU performs arithmetic and logical operations.',10),
('cpu-boss','basic','What does the Control Unit do?',ARRAY['Directs operation of the CPU','Performs calculations','Stores data','Manages memory'],0,'CU generates control signals for other components.',10),
('cpu-boss','basic','What are registers?',ARRAY['Small fast storage in CPU','Main memory','Cache memory','Disk storage'],0,'Registers: fastest, smallest storage in the CPU.',10),
('cpu-boss','basic','What is the program counter (PC)?',ARRAY['Holds address of next instruction','Counts programs','Counts clock cycles','Counts registers'],0,'PC points to the next instruction to fetch.',10),
('cpu-boss','basic','What is the instruction register (IR)?',ARRAY['Holds current instruction','Holds next instruction','Holds data','Holds address'],0,'IR stores the currently executing instruction.',10),
('cpu-boss','basic','What is the fetch-decode-execute cycle?',ARRAY['Basic CPU operation cycle','Memory cycle','I/O cycle','Cache cycle'],0,'Fetch: get instruction. Decode: interpret. Execute: perform.',10),
('cpu-boss','basic','What is a clock cycle?',ARRAY['One tick of the CPU clock','One instruction','One memory access','One I/O operation'],0,'Clock cycle = basic time unit for CPU operations.',10),
('cpu-boss','basic','What is clock speed measured in?',ARRAY['Hertz (Hz)','Bytes','Volts','Watts'],0,'Clock speed in Hz (GHz for modern CPUs).',10),
('cpu-boss','basic','What is the word size of a CPU?',ARRAY['Number of bits processed in one operation','Clock frequency','Cache size','Number of registers'],0,'Word size: 8, 16, 32, or 64 bits typically.',10),
('cpu-boss','basic','What is a 32-bit CPU?',ARRAY['Processes 32 bits at a time','Has 32 registers','Runs at 32 Hz','Has 32 pins'],0,'32-bit CPU: 32-bit data bus and registers.',10),
('cpu-boss','basic','What is a 64-bit CPU?',ARRAY['Processes 64 bits at a time','Has 64 registers','Runs at 64 Hz','Has 64 pins'],0,'64-bit CPU: 64-bit data bus and registers.',10),
('cpu-boss','basic','What is cache memory?',ARRAY['Fast memory between CPU and RAM','Slow memory','Disk storage','Flash memory'],0,'Cache: L1/L2/L3, faster than RAM, smaller.',10),
('cpu-boss','basic','What is L1 cache?',ARRAY['Closest and fastest cache to CPU','Largest cache','Disk cache','Network cache'],0,'L1: smallest, fastest, per-core.',10),
('cpu-boss','basic','What is the difference between L1 and L2 cache?',ARRAY['L1 is faster and smaller than L2','L2 is faster','Same speed','L1 is larger'],0,'L1 < L2 < L3 in size, L1 > L2 > L3 in speed.',10),
('cpu-boss','basic','What is a pipeline in a CPU?',ARRAY['Overlapping instruction execution','Memory pipeline','Cache pipeline','I/O pipeline'],0,'Pipelining: multiple instructions in different stages simultaneously.',10),
('cpu-boss','basic','What are the basic pipeline stages?',ARRAY['Fetch, Decode, Execute, Memory, Write-back','Read, Write','Input, Output','Load, Store'],0,'Classic 5-stage MIPS pipeline: IF, ID, EX, MEM, WB.',10),
('cpu-boss','basic','What is instruction latency?',ARRAY['Time to complete one instruction','Number of instructions','Clock speed','Cache size'],0,'Latency = cycles per individual instruction.',10),
('cpu-boss','basic','What is throughput in a CPU?',ARRAY['Instructions completed per unit time','Clock frequency','Memory size','Cache size'],0,'Throughput = IPC × clock frequency.',10),
('cpu-boss','basic','What is IPC?',ARRAY['Instructions Per Cycle','Instructions Per Clock-cycle','Internal Process Counter','Input Process Control'],0,'IPC: average instructions completed per clock cycle.',10),
('cpu-boss','basic','What is a register file?',ARRAY['Collection of registers in CPU','File in memory','Cache file','Disk file'],0,'Register file: small array of fast registers.',10),
('cpu-boss','basic','What is a bus?',ARRAY['Communication path between components','A type of memory','A cache type','A register'],0,'Buses transfer data between CPU, memory, I/O.',10),
('cpu-boss','basic','What is the data bus?',ARRAY['Carries data between components','Carries addresses','Carries control signals','Carries clock'],0,'Data bus width = word size.',10),
('cpu-boss','basic','What is the address bus?',ARRAY['Carries memory addresses','Carries data','Carries control signals','Carries clock'],0,'Address bus width determines addressable memory.',10),
('cpu-boss','basic','What is the control bus?',ARRAY['Carries control signals','Carries data','Carries addresses','Carries power'],0,'Control bus: read/write, interrupt, clock signals.',10),
('cpu-boss','basic','How many addressable locations with a 16-bit address bus?',ARRAY['65536','32768','16384','256'],0,'2^16 = 65536 locations.',10),
('cpu-boss','basic','How much memory can a 32-bit address bus address?',ARRAY['4 GB','2 GB','1 GB','8 GB'],0,'2^32 = 4,294,967,296 bytes = 4 GB.',10),
('cpu-boss','basic','What is RAM?',ARRAY['Random Access Memory','Read Access Memory','Rapid Access Memory','Random Active Memory'],0,'RAM: volatile, fast read/write memory.',10),
('cpu-boss','basic','What is ROM?',ARRAY['Read-Only Memory','Random Output Memory','Read-Only Module','Rapid Output Memory'],0,'ROM: non-volatile, permanent storage.',10),
('cpu-boss','basic','What is the difference between RAM and ROM?',ARRAY['RAM is volatile, ROM is non-volatile','RAM is faster','ROM is larger','No difference'],0,'RAM loses data on power off; ROM retains data.',10),
('cpu-boss','basic','What is an instruction set?',ARRAY['Set of all instructions a CPU can execute','Set of registers','Set of buses','Set of memories'],0,'ISA (Instruction Set Architecture) defines CPU operations.',10),
('cpu-boss','basic','What is an opcode?',ARRAY['Operation code specifying the instruction','Address of data','Register number','Memory location'],0,'Opcode: tells CPU what operation to perform.',10),
('cpu-boss','basic','What is an operand?',ARRAY['Data or address for the instruction','Operation code','Register name','Clock cycle'],0,'Operand: the data the instruction operates on.',10),
('cpu-boss','basic','What is assembly language?',ARRAY['Low-level programming using mnemonics','High-level language','Machine language','Natural language'],0,'Assembly: human-readable, one-to-one with machine code.',10),
('cpu-boss','basic','What is machine code?',ARRAY['Binary instructions executed by CPU','Assembly language','High-level code','Source code'],0,'Machine code: 1s and 0s, directly executed by hardware.',10),
('cpu-boss','basic','What is a RISC architecture?',ARRAY['Reduced Instruction Set Computer','Random Instruction Set Computer','Rapid Instruction Set Computer','Regular Instruction Set Computer'],0,'RISC: simple, fixed-length instructions, many registers.',10),
('cpu-boss','basic','What is a CISC architecture?',ARRAY['Complex Instruction Set Computer','Compact Instruction Set Computer','Complete Instruction Set Computer','Common Instruction Set Computer'],0,'CISC: complex, variable-length instructions (e.g., x86).',10),
('cpu-boss','basic','Which is a RISC architecture?',ARRAY['ARM','x86','Intel Core','AMD Ryzen'],0,'ARM is RISC; x86 is CISC.',10),
('cpu-boss','basic','Which is a CISC architecture?',ARRAY['x86','ARM','MIPS','RISC-V'],0,'x86 is CISC; ARM, MIPS, RISC-V are RISC.',10),
('cpu-boss','basic','What is a core in a CPU?',ARRAY['Independent processing unit','Cache unit','Memory unit','Bus unit'],0,'Multi-core CPUs have multiple independent processing units.',10),
('cpu-boss','basic','What is a multi-core CPU?',ARRAY['CPU with multiple processing cores','CPU with multiple caches','CPU with multiple buses','CPU with multiple registers'],0,'Multi-core: parallel execution on same chip.',10),
('cpu-boss','basic','What is hyper-threading?',ARRAY['Simulating two cores on one physical core','Doubling clock speed','Doubling cache','Doubling registers'],0,'SMT (Simultaneous Multi-Threading): 2 threads per core.',10),
('cpu-boss','basic','What is an interrupt?',ARRAY['Signal that pauses CPU execution','A type of instruction','A memory access','A clock signal'],0,'Interrupts allow external devices to request CPU attention.',10),
('cpu-boss','basic','What is an interrupt handler?',ARRAY['Routine that processes an interrupt','A type of register','A memory location','A bus signal'],0,'ISR (Interrupt Service Routine) handles the interrupt.',10),
('cpu-boss','basic','What is DMA?',ARRAY['Direct Memory Access','Direct Memory Address','Data Memory Access','Dynamic Memory Allocation'],0,'DMA: peripheral transfers data to memory without CPU.',10),
('cpu-boss','basic','What is the advantage of DMA?',ARRAY['CPU is free during data transfer','Faster clock','More memory','More registers'],0,'DMA offloads data transfer from CPU.',10),
('cpu-boss','basic','What is a flag register?',ARRAY['Holds status flags from operations','Holds data','Holds addresses','Holds instructions'],0,'Flags: zero, carry, sign, overflow, parity.',10),
('cpu-boss','basic','What is the zero flag?',ARRAY['Set when result is zero','Set when result is negative','Set when overflow occurs','Set when carry occurs'],0,'Zero flag = 1 when ALU result is 0.',10);