// circuit-builder question bank - 50 per level

// ===== BASIC (50) =====
const basic = [
  ["What is Ohm's Law?","V = IR","V = I/R","V = IR²","V = I²R",0,"Ohm's Law: Voltage = Current × Resistance."],
  ["What is the unit of resistance?","Ohm (Ω)","Volt (V)","Ampere (A)","Watt (W)",0,"Resistance is measured in ohms."],
  ["What is the unit of current?","Ampere (A)","Volt (V)","Ohm (Ω)","Farad (F)",0,"Current is measured in amperes."],
  ["What is the unit of voltage?","Volt (V)","Ampere (A)","Ohm (Ω)","Joule (J)",0,"Voltage is measured in volts."],
  ["What is the unit of power?","Watt (W)","Volt (V)","Ampere (A)","Ohm (Ω)",0,"Power is measured in watts."],
  ["What is the power formula?","P = VI","P = V/I","P = I/V","P = V+I",0,"Power = Voltage × Current."],
  ["What is the resistance of two 10Ω resistors in series?","20Ω","5Ω","10Ω","100Ω",0,"Series: R = R1 + R2 = 20Ω."],
  ["What is the resistance of two 10Ω resistors in parallel?","5Ω","20Ω","10Ω","100Ω",0,"Parallel: R = (R1×R2)/(R1+R2) = 5Ω."],
  ["What happens to current in a series circuit?","Same at all points","Splits at each component","Increases","Decreases",0,"Current is constant in a series circuit."],
  ["What happens to voltage in a parallel circuit?","Same across all branches","Splits across branches","Increases","Decreases",0,"Voltage is equal across parallel branches."],
  ["What is Kirchhoff's Voltage Law (KVL)?","Sum of voltages around a loop = 0","Sum of currents = 0","V = IR","P = VI",0,"KVL: algebraic sum of voltages in a loop is zero."],
  ["What is Kirchhoff's Current Law (KCL)?","Sum of currents at a node = 0","Sum of voltages = 0","I = V/R","P = I²R",0,"KCL: sum of currents entering a node equals sum leaving."],
  ["What is a short circuit?","Zero resistance path","High resistance path","Open circuit","Normal circuit",0,"Short circuit has near-zero resistance."],
  ["What is an open circuit?","Infinite resistance path","Zero resistance path","Low resistance path","Normal circuit",0,"Open circuit has infinite resistance."],
  ["What is the equivalent resistance of 5Ω and 15Ω in series?","20Ω","3.75Ω","10Ω","75Ω",0,"Series: 5 + 15 = 20Ω."],
  ["What is the equivalent resistance of 6Ω and 3Ω in parallel?","2Ω","9Ω","18Ω","3Ω",0,"Parallel: (6×3)/(6+3) = 2Ω."],
  ["What does a capacitor do in a DC circuit?","Blocks DC after charging","Passes DC freely","Acts as a short","Acts as a resistor",0,"Capacitor charges then blocks DC (open circuit)."],
  ["What does an inductor do in a DC circuit?","Acts as a short after steady state","Blocks DC","Acts as open circuit","Acts as a capacitor",0,"Inductor passes DC after transient (short circuit)."],
  ["What is the unit of capacitance?","Farad (F)","Henry (H)","Ohm (Ω)","Volt (V)",0,"Capacitance is measured in farads."],
  ["What is the unit of inductance?","Henry (H)","Farad (F)","Ohm (Ω)","Ampere (A)",0,"Inductance is measured in henries."],
  ["What is the formula for capacitive reactance?","Xc = 1/(2πfC)","Xc = 2πfC","Xc = 1/(2πfL)","Xc = 2πfL",0,"Capacitive reactance decreases with frequency."],
  ["What is the formula for inductive reactance?","Xl = 2πfL","Xl = 1/(2πfL)","Xl = 2πfC","Xl = 1/(2πfC)",0,"Inductive reactance increases with frequency."],
  ["What happens to a capacitor's reactance as frequency increases?","Decreases","Increases","Stays same","Becomes zero",0,"Xc = 1/(2πfC) → decreases with f."],
  ["What happens to an inductor's reactance as frequency increases?","Increases","Decreases","Stays same","Becomes zero",0,"Xl = 2πfL → increases with f."],
  ["What is the time constant of an RC circuit?","τ = RC","τ = R/C","τ = C/R","τ = R+C",0,"Time constant = R × C."],
  ["What is the time constant of an RL circuit?","τ = L/R","τ = R/L","τ = RL","τ = R+L",0,"Time constant = L / R."],
  ["What is the voltage across a capacitor after one time constant during charging?","63.2% of V","37% of V","100% of V","50% of V",0,"Capacitor charges to 63.2% after one τ."],
  ["What is the voltage across a capacitor after one time constant during discharging?","36.8% of V","63.2% of V","0% of V","50% of V",0,"Capacitor discharges to 36.8% after one τ."],
  ["How many time constants to fully charge a capacitor?","5","3","1","10",0,"~99.3% charged after 5 time constants."],
  ["What is a node in a circuit?","Junction of two or more elements","A single element","A loop","A battery",0,"A node is a connection point."],
  ["What is a mesh in a circuit?","A loop with no inner loops","Any loop","A node","A branch",0,"A mesh is the simplest loop."],
  ["What is a branch in a circuit?","A path between two nodes","A loop","A node","A source",0,"A branch is a single path between nodes."],
  ["What is the current through a 10Ω resistor with 20V across it?","2A","0.5A","200A","10A",0,"I = V/R = 20/10 = 2A."],
  ["What is the voltage across a 5Ω resistor with 3A through it?","15V","1.67V","8V","5V",0,"V = IR = 3×5 = 15V."],
  ["What is the power dissipated by a 10Ω resistor with 2A through it?","40W","20W","10W","4W",0,"P = I²R = 4×10 = 40W."],
  ["What is the power dissipated by a 10Ω resistor with 10V across it?","10W","1W","100W","0.1W",0,"P = V²/R = 100/10 = 10W."],
  ["What is the equivalent capacitance of two 10µF caps in series?","5µF","20µF","10µF","100µF",0,"Series caps: C = (C1×C2)/(C1+C2) = 5µF."],
  ["What is the equivalent capacitance of two 10µF caps in parallel?","20µF","5µF","10µF","100µF",0,"Parallel caps: C = C1 + C2 = 20µF."],
  ["What is the equivalent inductance of two 10mH inductors in series?","20mH","5mH","10mH","100mH",0,"Series inductors: L = L1 + L2 = 20mH."],
  ["What is the equivalent inductance of two 10mH inductors in parallel?","5mH","20mH","10mH","100mH",0,"Parallel inductors: L = (L1×L2)/(L1+L2) = 5mH."],
  ["What is a voltage divider?","Two resistors splitting voltage","Two resistors combining voltage","A capacitor divider","An inductor divider",0,"Voltage divider: Vout = Vin × R2/(R1+R2)."],
  ["What is the output of a voltage divider with R1=R2=10Ω and Vin=12V?","6V","12V","3V","0V",0,"Vout = 12 × 10/(10+10) = 6V."],
  ["What is a current divider?","Two parallel resistors splitting current","Two series resistors","A voltage divider","A transformer",0,"Current divides inversely to resistance in parallel."],
  ["What is the current through R1=2Ω in parallel with R2=4Ω with total current 6A?","4A","2A","3A","6A",0,"I1 = I × R2/(R1+R2) = 6 × 4/6 = 4A."],
  ["What does a diode do?","Allows current in one direction","Allows current both ways","Blocks all current","Amplifies current",0,"Diode conducts when forward-biased."],
  ["What is the forward voltage drop of a silicon diode?","~0.7V","~0.3V","~1.2V","~0V",0,"Silicon diode drops ~0.7V when conducting."],
  ["What is the forward voltage drop of a germanium diode?","~0.3V","~0.7V","~1.2V","~0V",0,"Germanium diode drops ~0.3V."],
  ["What is a Zener diode used for?","Voltage regulation","Rectification","Amplification","Filtering",0,"Zener diodes regulate voltage in reverse breakdown."],
  ["What is rectification?","Converting AC to DC","Converting DC to AC","Filtering signals","Amplifying signals",0,"Rectifiers convert AC to pulsating DC."],
  ["What does a half-wave rectifier use?","One diode","Two diodes","Four diodes","No diode",0,"Half-wave rectifier uses a single diode."],
  ["How many diodes does a full-wave bridge rectifier use?","4","2","1","6",0,"Bridge rectifier uses 4 diodes in a bridge configuration."],
];

// ===== INTERMEDIATE (50) =====
const intermediate = [
  ["What is Thevenin's theorem?","Any linear network = voltage source + series resistance","Any network = current source + parallel resistance","V = IR","P = VI",0,"Thevenin: Vth + Rth equivalent."],
  ["What is Norton's theorem?","Any linear network = current source + parallel resistance","Voltage source + series resistance","V = IR","I = V/R",0,"Norton: In || Rn equivalent."],
  ["How do you find Thevenin resistance?","Turn off all sources, find equivalent resistance","Measure voltage","Measure current","Short the output",0,"Deactivate sources, then calculate Rth."],
  ["How do you find Thevenin voltage?","Open-circuit voltage at terminals","Short-circuit current","Equivalent resistance","Source voltage",0,"Vth = open-circuit voltage."],
  ["How do you find Norton current?","Short-circuit current at terminals","Open-circuit voltage","Equivalent resistance","Source current",0,"In = short-circuit current."],
  ["What is the relationship between Thevenin and Norton equivalents?","Rth = Rn, Vth = In × Rn","Rth = 2×Rn","Vth = In","In = Vth",0,"Source transformation: Vth = In × Rn."],
  ["What is maximum power transfer?","Load R = source R for max power","Load R = 0","Load R = ∞","Load R = 2×source R",0,"Max power when RL = Rth."],
  ["What is the efficiency at maximum power transfer?","50%","100%","25%","75%",0,"Half the power is dissipated in source resistance."],
  ["What is superposition theorem?","Response = sum of responses from each source individually","Sum of all voltages","Sum of all currents","Sum of all powers",0,"Analyze each source separately, then add."],
  ["When can you use superposition?","Only in linear circuits","In any circuit","Only in DC circuits","Only in AC circuits",0,"Superposition requires linearity."],
  ["What is mesh analysis?","Using KVL around meshes","Using KCL at nodes","Using Ohm's law","Using Thevenin",0,"Mesh analysis applies KVL to each mesh."],
  ["What is nodal analysis?","Using KCL at nodes","Using KVL around meshes","Using Ohm's law","Using Norton",0,"Nodal analysis applies KCL at each node."],
  ["Which method is better for circuits with many nodes but few meshes?","Mesh analysis","Nodal analysis","Thevenin","Superposition",0,"Fewer meshes = fewer mesh equations."],
  ["Which method is better for circuits with many meshes but few nodes?","Nodal analysis","Mesh analysis","Thevenin","Superposition",0,"Fewer nodes = fewer nodal equations."],
  ["What is a dependent source?","Source controlled by another circuit variable","Independent voltage source","Battery","Current source",0,"Dependent sources depend on voltage/current elsewhere."],
  ["What are the four types of dependent sources?","VCVS, VCCS, CCVS, CCCS","VCVS only","Voltage and current","AC and DC",0,"Four types: voltage/current controlled voltage/current."],
  ["Can superposition be used with dependent sources?","Yes, but keep dependent sources active","No","Only with independent sources","Only with voltage sources",0,"Dependent sources are never deactivated."],
  ["What is a transfer function?","Output/Input in s-domain","Output × Input","Output + Input","Output - Input",0,"H(s) = Y(s)/X(s)."],
  ["What is the impedance of a resistor?","R","1/(sC)","sL","1/R",0,"Resistor impedance = R (frequency independent)."],
  ["What is the impedance of a capacitor in s-domain?","1/(sC)","sC","sL","R",0,"Capacitor: Z = 1/(sC)."],
  ["What is the impedance of an inductor in s-domain?","sL","1/(sL)","1/(sC)","R",0,"Inductor: Z = sL."],
  ["What is the impedance of a resistor at DC?","R","0","∞","1/R",0,"Resistor impedance is always R."],
  ["What is the impedance of a capacitor at DC?","∞ (open)","0 (short)","R","1/(sC)",0,"At DC (f=0), Xc → ∞."],
  ["What is the impedance of an inductor at DC?","0 (short)","∞ (open)","R","sL",0,"At DC (f=0), Xl → 0."],
  ["What is the impedance of a capacitor at very high frequency?","0 (short)","∞ (open)","R","1/(sC)",0,"At f→∞, Xc → 0."],
  ["What is the impedance of an inductor at very high frequency?","∞ (open)","0 (short)","R","sL",0,"At f→∞, Xl → ∞."],
  ["What is a low-pass filter?","Passes low frequencies, attenuates high","Passes high, attenuates low","Passes all","Attenuates all",0,"LPF cutoff: frequencies below fc pass."],
  ["What is a high-pass filter?","Passes high frequencies, attenuates low","Passes low, attenuates high","Passes all","Attenuates all",0,"HPF cutoff: frequencies above fc pass."],
  ["What is a band-pass filter?","Passes a range of frequencies","Passes all frequencies","Blocks all frequencies","Passes DC only",0,"BPF passes frequencies between f_low and f_high."],
  ["What is a band-stop filter?","Blocks a range of frequencies","Passes a range","Passes all","Blocks all",0,"BSF (notch filter) rejects a band."],
  ["What is the cutoff frequency of an RC low-pass filter?","f = 1/(2πRC)","f = 2πRC","f = RC","f = 1/(RC)",0,"Cutoff: fc = 1/(2πRC)."],
  ["What is the cutoff frequency of an RL high-pass filter?","f = R/(2πL)","f = 2πL/R","f = L/R","f = RL",0,"Cutoff: fc = R/(2πL)."],
  ["What is the roll-off rate of a first-order filter?","-20 dB/decade","-40 dB/decade","-10 dB/decade","-60 dB/decade",0,"First-order: -20 dB/decade or -6 dB/octave."],
  ["What is the roll-off rate of a second-order filter?","-40 dB/decade","-20 dB/decade","-60 dB/decade","-10 dB/decade",0,"Second-order: -40 dB/decade."],
  ["What is the Q factor of a filter?","Measure of selectivity/resonance sharpness","Quality of components","Power factor","Efficiency",0,"Q = fc/BW (center freq / bandwidth)."],
  ["What is bandwidth?","Range of frequencies passed","Single frequency","Maximum frequency","Minimum frequency",0,"BW = f_high - f_low."],
  ["What is resonance in an RLC circuit?","Xl = Xc, impedance is purely resistive","Maximum resistance","Minimum current","Maximum voltage",0,"At resonance, Xl = Xc, Z = R."],
  ["What is the resonant frequency of an RLC circuit?","f = 1/(2π√(LC))","f = 2π√(LC)","f = LC","f = 1/(LC)",0,"Resonance: fr = 1/(2π√(LC))."],
  ["What is the impedance at resonance in a series RLC circuit?","R (minimum)","∞","0","Xl",0,"At resonance, Z = R (minimum impedance)."],
  ["What is the impedance at resonance in a parallel RLC circuit?","R (maximum)","0","∞","Xc",0,"At parallel resonance, Z = R (maximum)."],
  ["What happens to current at series resonance?","Maximum","Minimum","Zero","Infinity",0,"Z is minimum, so current is maximum."],
  ["What happens to current at parallel resonance?","Minimum","Maximum","Zero","Infinity",0,"Z is maximum, so current is minimum."],
  ["What is a Bode plot?","Magnitude and phase vs frequency","Time vs voltage","Current vs voltage","Power vs time",0,"Bode plots show frequency response."],
  ["What is the gain margin in a Bode plot?","How much gain can increase before instability","Phase shift","Cutoff frequency","Bandwidth",0,"Gain margin measured at phase crossover."],
  ["What is the phase margin?","How much phase can change before instability","Gain at cutoff","Maximum phase","Minimum phase",0,"Phase margin measured at unity gain."],
  ["What is a decibel (dB)?","20 log₁₀(ratio) for voltage","10 log₁₀(ratio)","Linear ratio","Power ratio",0,"Voltage gain in dB: 20 log₁₀(Vout/Vin)."],
  ["What is the dB formula for power ratio?","10 log₁₀(Pout/Pin)","20 log₁₀(Pout/Pin)","Pout/Pin","log₂(Pout/Pin)",0,"Power gain in dB: 10 log₁₀(Pout/Pin)."],
  ["What is a coupling capacitor used for?","Blocking DC, passing AC","Blocking AC","Passing DC","Storing charge",0,"Coupling caps block DC between stages."],
  ["What is a bypass capacitor used for?","Shunting AC noise to ground","Blocking DC","Passing DC","Increasing voltage",0,"Bypass caps short AC noise to ground."],
  ["What is the input impedance of an ideal op-amp?","∞","0","1Ω","100Ω",0,"Ideal op-amp has infinite input impedance."],
  ["What is the gain of an inverting op-amp with Rf=10k, Rin=1k?","-10","10","-1","1",0,"Gain = -Rf/Rin = -10."],
  ["What is the gain of a non-inverting op-amp with Rf=10k, Rin=1k?","11","10","1","-11",0,"Gain = 1 + Rf/Rin = 11."],
];

// ===== ADVANCED (50) =====
const advanced = [
  ["What is the Miller effect?","Input capacitance multiplied by (1+Av)","Output capacitance doubled","Input resistance halved","Gain bandwidth product",0,"Miller: Cin_effective = Cin × (1 + |Av|)."],
  ["What is the gain-bandwidth product (GBW)?","Gain × Bandwidth = constant","Gain + Bandwidth","Gain / Bandwidth","Gain² × Bandwidth",0,"GBW is constant for an op-amp."],
  ["What is the slew rate of an op-amp?","Maximum rate of change of output voltage","Maximum gain","Maximum input voltage","Maximum frequency",0,"Slew rate in V/µs limits large-signal bandwidth."],
  ["What causes slew rate limiting?","Internal compensation capacitor charging","Input impedance","Power supply","Feedback resistor",0,"Compensation cap limits dV/dt."],
  ["What is the common-mode rejection ratio (CMRR)?","Differential gain / Common-mode gain","Open-loop gain","Slew rate","Input bias current",0,"CMRR = Adm/Acm, ideally ∞."],
  ["What is the input offset voltage?","Voltage needed to zero the output","Maximum input voltage","Minimum input voltage","Supply voltage",0,"Offset voltage nulls output when inputs are equal."],
  ["What is the input bias current?","DC current into op-amp inputs","AC input current","Output current","Supply current",0,"Bias current flows into both inputs."],
  ["What is the difference between inverting and non-inverting op-amp?","Non-inverting has positive gain and high input Z","Inverting has positive gain","No difference","Inverting has higher gain",0,"Non-inverting: +gain, high Zin; inverting: -gain, Zin = Rin."],
  ["Design a summing amplifier with 3 inputs. What is Vout?","-(Rf/R1·V1 + Rf/R2·V2 + Rf/R3·V3)","V1+V2+V3","Rf·(V1+V2+V3)","-(V1+V2+V3)",0,"Inverting summer: Vout = -Σ(Rf/Ri·Vi)."],
  ["Design a difference amplifier. What is Vout?","(R2/R1)×(V2-V1)","V2-V1","R2×(V1+V2)","(V1-V2)/R1",0,"Diff amp: Vout = (R2/R1)(V2-V1)."],
  ["What is an instrumentation amplifier?","High-precision differential amplifier with high CMRR","Buffer amplifier","Summing amplifier","Power amplifier",0,"Instrumentation amps have high CMRR and gain."],
  ["What is a Schmitt trigger using op-amp?","Comparator with hysteresis","Unity gain buffer","Integrator","Differentiator",0,"Positive feedback creates hysteresis."],
  ["Design an op-amp integrator. What component is in the feedback path?","Capacitor","Resistor","Inductor","Diode",0,"Integrator: capacitor in feedback."],
  ["Design an op-amp differentiator. What component is in the input path?","Capacitor","Resistor","Inductor","Diode",0,"Differentiator: capacitor at input, resistor in feedback."],
  ["What is a Wien bridge oscillator?","RC oscillator for sine waves","LC oscillator","Crystal oscillator","Relaxation oscillator",0,"Wien bridge uses RC network for sine wave generation."],
  ["What is the frequency of a Wien bridge oscillator?","f = 1/(2πRC)","f = 2πRC","f = RC","f = 1/(RC)",0,"Wien bridge: f = 1/(2πRC)."],
  ["What is the Barkhausen criterion for oscillation?","Loop gain ≥ 1 and phase shift = 360°","Gain > 0","Phase = 0","Gain = 0",0,"|Aβ| ≥ 1 and ∠Aβ = 2nπ."],
  ["What is a phase-shift oscillator?","RC network providing 180° phase shift","LC oscillator","Crystal oscillator","Wien bridge",0,"Three RC stages give 180°, plus op-amp inversion = 360°."],
  ["What is a Colpitts oscillator?","LC oscillator with capacitive divider","RC oscillator","Crystal oscillator","Relaxation oscillator",0,"Colpitts uses a capacitive voltage divider in the tank."],
  ["What is a Hartley oscillator?","LC oscillator with tapped inductor","RC oscillator","Crystal oscillator","Colpitts variant",0,"Hartley uses a tapped inductor in the tank circuit."],
  ["What is a crystal oscillator?","Uses piezoelectric crystal for high stability","Uses RC network","Uses LC tank","Uses op-amp",0,"Crystal oscillators are very stable (ppm range)."],
  ["What is the equivalent circuit of a crystal?","Series RLC with parallel C","Just a capacitor","Just an inductor","Just a resistor",0,"Crystal: series RLC branch with parallel capacitance."],
  ["What is a relaxation oscillator?","Uses charging/discharging of RC","Uses LC tank","Uses crystal","Uses op-amp integrator",0,"Relaxation oscillators use comparators + RC."],
  ["What is a multivibrator?","Two-state circuit generating square waves","Single amplifier","Filter circuit","Oscillator with crystal",0,"Astable, monostable, bistable multivibrators."],
  ["What is an astable multivibrator?","Free-running oscillator (no stable state)","One stable state","Two stable states","No output",0,"Astable continuously oscillates."],
  ["What is a monostable multivibrator?","One stable state, triggered to quasi-stable","No stable state","Two stable states","Free-running",0,"Monostable produces one pulse per trigger."],
  ["What is a bistable multivibrator?","Two stable states (flip-flop)","No stable state","One stable state","Free-running",0,"Bistable = SR flip-flop."],
  ["What is a 555 timer?","Versatile IC for timing and oscillation","Op-amp","Comparator","Logic gate",0,"555 timer: astable, monostable, PWM applications."],
  ["What is the output frequency of a 555 astable?","f = 1.44/((RA+2RB)C)","f = RC","f = 1/(RC)","f = RA+RB",0,"555 astable: f = 1.44/((RA+2RB)×C)."],
  ["What is the duty cycle of a 555 astable?","(RA+RB)/(RA+2RB) × 100%","50%","100%","RB/RA",0,"Duty cycle depends on RA and RB ratio."],
  ["What is a PLL (Phase-Locked Loop)?","Locks output phase to input reference","Phase shifter","Frequency multiplier only","Filter",0,"PLL: phase detector + VCO + loop filter."],
  ["What are the main blocks of a PLL?","Phase detector, VCO, loop filter","Op-amp, resistor, capacitor","Mixer, filter, amplifier","Counter, register, decoder",0,"PLL = PD + LPF + VCO."],
  ["What is the capture range of a PLL?","Range of frequencies PLL can lock onto","Output frequency range","Input voltage range","Loop bandwidth",0,"Capture range ⊆ lock range."],
  ["What is the lock range of a PLL?","Range of frequencies PLL can maintain lock","Capture range","VCO range","Filter bandwidth",0,"Lock range ≥ capture range."],
  ["What is a VCO?","Voltage-Controlled Oscillator","Voltage Comparator","Variable Current Output","Voltage Controlled Op-amp",0,"VCO frequency controlled by input voltage."],
  ["What is a sample-and-hold circuit?","Captures and holds analog voltage","Amplifies signal","Filters signal","Converts digital to analog",0,"S/H uses a capacitor to hold sampled voltage."],
  ["What is a DAC?","Digital-to-Analog Converter","Data Acquisition Circuit","Direct Current Amplifier","Digital Arithmetic Circuit",0,"DAC converts digital codes to analog voltage."],
  ["What is an ADC?","Analog-to-Digital Converter","Amplifier with Digital Control","Active Differential Comparator","Analog Data Converter",0,"ADC converts analog voltage to digital code."],
  ["What is the resolution of an 8-bit ADC?","256 levels","128 levels","64 levels","512 levels",0,"2^8 = 256 levels."],
  ["What is the quantization error of an n-bit ADC?","±(1/2) LSB","±1 LSB","±2 LSB","±(1/4) LSB",0,"Quantization error is ±½ LSB."],
  ["What is a flash ADC?","Fastest ADC using 2^n-1 comparators","Slowest ADC","Uses a single comparator","Uses a DAC",0,"Flash ADC: parallel comparison, 1 clock cycle."],
  ["What is a successive approximation ADC?","Uses binary search with DAC","Uses parallel comparators","Uses single slope","Uses dual slope",0,"SAR ADC: binary search, n clock cycles."],
  ["What is a dual-slope ADC?","Integrates signal for fixed time, then deintegrates","Uses parallel comparators","Uses binary search","Fastest ADC",0,"Dual-slope: high accuracy, slow speed."],
  ["What is a sigma-delta ADC?","Oversampling + noise shaping + decimation","Parallel conversion","Binary search","Dual slope",0,"Σ-Δ ADC: high resolution, moderate speed."],
  ["What is the Nyquist rate?","Minimum sampling rate = 2 × signal bandwidth","Sampling rate = signal bandwidth","Sampling rate = 4 × bandwidth","Sampling rate = bandwidth/2",0,"Nyquist: fs ≥ 2 × fmax to avoid aliasing."],
  ["What is aliasing?","High frequencies fold back as low frequencies","Signal attenuation","Signal amplification","Phase distortion",0,"Aliasing occurs when fs < 2 × fmax."],
  ["What is an anti-aliasing filter?","Low-pass filter before ADC","High-pass filter after ADC","Band-pass filter","Notch filter",0,"Anti-aliasing filter limits bandwidth before sampling."],
  ["What is oversampling?","Sampling at much higher than Nyquist rate","Sampling at Nyquist rate","Sampling below Nyquist","Sampling once",0,"Oversampling improves SNR and resolution."],
  ["What is a switched-capacitor filter?","Uses capacitors and switches to simulate resistors","Uses op-amps only","Uses inductors","Uses crystals",0,"SC filters: R = 1/(fC), tunable by clock frequency."],
  ["What is the advantage of active filters over passive filters?","Can provide gain, no inductors needed","Cheaper","Smaller size","Higher frequency",0,"Active filters use op-amps, avoid bulky inductors."],
  ["What is a Sallen-Key filter?","Second-order active filter topology","Passive filter","Crystal filter","Digital filter",0,"Sallen-Key: popular active LPF/HPF topology."],
];

module.exports = { basic, intermediate, advanced };
