// cpu-boss question bank - 50 per level

// ===== BASIC (50) =====
const basic = [
  ["What does CPU stand for?","Central Processing Unit","Computer Processing Unit","Central Power Unit","Computer Power Unit",0,"CPU = Central Processing Unit."],
  ["What is the function of a CPU?","Executes instructions","Stores data","Displays output","Powers the computer",0,"CPU fetches, decodes, and executes instructions."],
  ["What are the main parts of a CPU?","ALU, Control Unit, Registers","Cache and RAM","Hard drive and SSD","Input and output",0,"CPU: ALU (compute), CU (control), Registers (storage)."],
  ["What does ALU stand for?","Arithmetic Logic Unit","Advanced Logic Unit","Arithmetic Loading Unit","Active Logic Unit",0,"ALU performs arithmetic and logical operations."],
  ["What does the Control Unit do?","Directs operation of the CPU","Performs calculations","Stores data","Manages memory",0,"CU generates control signals for other components."],
  ["What are registers?","Small fast storage in CPU","Main memory","Cache memory","Disk storage",0,"Registers: fastest, smallest storage in the CPU."],
  ["What is the program counter (PC)?","Holds address of next instruction","Counts programs","Counts clock cycles","Counts registers",0,"PC points to the next instruction to fetch."],
  ["What is the instruction register (IR)?","Holds current instruction","Holds next instruction","Holds data","Holds address",0,"IR stores the currently executing instruction."],
  ["What is the fetch-decode-execute cycle?","Basic CPU operation cycle","Memory cycle","I/O cycle","Cache cycle",0,"Fetch: get instruction. Decode: interpret. Execute: perform."],
  ["What is a clock cycle?","One tick of the CPU clock","One instruction","One memory access","One I/O operation",0,"Clock cycle = basic time unit for CPU operations."],
  ["What is clock speed measured in?","Hertz (Hz)","Bytes","Volts","Watts",0,"Clock speed in Hz (GHz for modern CPUs)."],
  ["What is the word size of a CPU?","Number of bits processed in one operation","Clock frequency","Cache size","Number of registers",0,"Word size: 8, 16, 32, or 64 bits typically."],
  ["What is a 32-bit CPU?","Processes 32 bits at a time","Has 32 registers","Runs at 32 Hz","Has 32 pins",0,"32-bit CPU: 32-bit data bus and registers."],
  ["What is a 64-bit CPU?","Processes 64 bits at a time","Has 64 registers","Runs at 64 Hz","Has 64 pins",0,"64-bit CPU: 64-bit data bus and registers."],
  ["What is cache memory?","Fast memory between CPU and RAM","Slow memory","Disk storage","Flash memory",0,"Cache: L1/L2/L3, faster than RAM, smaller."],
  ["What is L1 cache?","Closest and fastest cache to CPU","Largest cache","Disk cache","Network cache",0,"L1: smallest, fastest, per-core."],
  ["What is the difference between L1 and L2 cache?","L1 is faster and smaller than L2","L2 is faster","Same speed","L1 is larger",0,"L1 < L2 < L3 in size, L1 > L2 > L3 in speed."],
  ["What is a pipeline in a CPU?","Overlapping instruction execution","Memory pipeline","Cache pipeline","I/O pipeline",0,"Pipelining: multiple instructions in different stages simultaneously."],
  ["What are the basic pipeline stages?","Fetch, Decode, Execute, Memory, Write-back","Read, Write","Input, Output","Load, Store",0,"Classic 5-stage MIPS pipeline: IF, ID, EX, MEM, WB."],
  ["What is instruction latency?","Time to complete one instruction","Number of instructions","Clock speed","Cache size",0,"Latency = cycles per individual instruction."],
  ["What is throughput in a CPU?","Instructions completed per unit time","Clock frequency","Memory size","Cache size",0,"Throughput = IPC × clock frequency."],
  ["What is IPC?","Instructions Per Cycle","Instructions Per Clock-cycle","Internal Process Counter","Input Process Control",0,"IPC: average instructions completed per clock cycle."],
  ["What is a register file?","Collection of registers in CPU","File in memory","Cache file","Disk file",0,"Register file: small array of fast registers."],
  ["What is a bus?","Communication path between components","A type of memory","A cache type","A register",0,"Buses transfer data between CPU, memory, I/O."],
  ["What is the data bus?","Carries data between components","Carries addresses","Carries control signals","Carries clock",0,"Data bus width = word size."],
  ["What is the address bus?","Carries memory addresses","Carries data","Carries control signals","Carries clock",0,"Address bus width determines addressable memory."],
  ["What is the control bus?","Carries control signals","Carries data","Carries addresses","Carries power",0,"Control bus: read/write, interrupt, clock signals."],
  ["How many addressable locations with a 16-bit address bus?","65536","32768","16384","256",0,"2^16 = 65536 locations."],
  ["How much memory can a 32-bit address bus address?","4 GB","2 GB","1 GB","8 GB",0,"2^32 = 4,294,967,296 bytes = 4 GB."],
  ["What is RAM?","Random Access Memory","Read Access Memory","Rapid Access Memory","Random Active Memory",0,"RAM: volatile, fast read/write memory."],
  ["What is ROM?","Read-Only Memory","Random Output Memory","Read-Only Module","Rapid Output Memory",0,"ROM: non-volatile, permanent storage."],
  ["What is the difference between RAM and ROM?","RAM is volatile, ROM is non-volatile","RAM is faster","ROM is larger","No difference",0,"RAM loses data on power off; ROM retains data."],
  ["What is an instruction set?","Set of all instructions a CPU can execute","Set of registers","Set of buses","Set of memories",0,"ISA (Instruction Set Architecture) defines CPU operations."],
  ["What is an opcode?","Operation code specifying the instruction","Address of data","Register number","Memory location",0,"Opcode: tells CPU what operation to perform."],
  ["What is an operand?","Data or address for the instruction","Operation code","Register name","Clock cycle",0,"Operand: the data the instruction operates on."],
  ["What is assembly language?","Low-level programming using mnemonics","High-level language","Machine language","Natural language",0,"Assembly: human-readable, one-to-one with machine code."],
  ["What is machine code?","Binary instructions executed by CPU","Assembly language","High-level code","Source code",0,"Machine code: 1s and 0s, directly executed by hardware."],
  ["What is a RISC architecture?","Reduced Instruction Set Computer","Random Instruction Set Computer","Rapid Instruction Set Computer","Regular Instruction Set Computer",0,"RISC: simple, fixed-length instructions, many registers."],
  ["What is a CISC architecture?","Complex Instruction Set Computer","Compact Instruction Set Computer","Complete Instruction Set Computer","Common Instruction Set Computer",0,"CISC: complex, variable-length instructions (e.g., x86)."],
  ["Which is a RISC architecture?","ARM","x86","Intel Core","AMD Ryzen",0,"ARM is RISC; x86 is CISC."],
  ["Which is a CISC architecture?","x86","ARM","MIPS","RISC-V",0,"x86 is CISC; ARM, MIPS, RISC-V are RISC."],
  ["What is a core in a CPU?","Independent processing unit","Cache unit","Memory unit","Bus unit",0,"Multi-core CPUs have multiple independent processing units."],
  ["What is a multi-core CPU?","CPU with multiple processing cores","CPU with multiple caches","CPU with multiple buses","CPU with multiple registers",0,"Multi-core: parallel execution on same chip."],
  ["What is hyper-threading?","Simulating two cores on one physical core","Doubling clock speed","Doubling cache","Doubling registers",0,"SMT (Simultaneous Multi-Threading): 2 threads per core."],
  ["What is an interrupt?","Signal that pauses CPU execution","A type of instruction","A memory access","A clock signal",0,"Interrupts allow external devices to request CPU attention."],
  ["What is an interrupt handler?","Routine that processes an interrupt","A type of register","A memory location","A bus signal",0,"ISR (Interrupt Service Routine) handles the interrupt."],
  ["What is DMA?","Direct Memory Access","Direct Memory Address","Data Memory Access","Dynamic Memory Allocation",0,"DMA: peripheral transfers data to memory without CPU."],
  ["What is the advantage of DMA?","CPU is free during data transfer","Faster clock","More memory","More registers",0,"DMA offloads data transfer from CPU."],
  ["What is a flag register?","Holds status flags from operations","Holds data","Holds addresses","Holds instructions",0,"Flags: zero, carry, sign, overflow, parity."],
  ["What is the zero flag?","Set when result is zero","Set when result is negative","Set when overflow occurs","Set when carry occurs",0,"Zero flag = 1 when ALU result is 0."],
  ["What is the carry flag?","Set when arithmetic operation overflows","Set when result is zero","Set when sign is negative","Set when parity is odd",0,"Carry flag = 1 on unsigned overflow/underflow."],
];

// ===== INTERMEDIATE (50) =====
const intermediate = [
  ["What is a pipeline hazard?","Situation preventing next instruction from executing","Pipeline overflow","Cache miss","Bus error",0,"Hazards: structural, data, control."],
  ["What is a structural hazard?","Resource conflict (same hardware needed)","Data dependency","Branch instruction","Cache miss",0,"Structural: two instructions need same hardware simultaneously."],
  ["What is a data hazard?","Dependence between instructions","Resource conflict","Branch prediction","Cache miss",0,"Data hazards: RAW, WAW, WAR dependencies."],
  ["What is a RAW hazard?","Read After Write: need result of previous instruction","Read After Write conflict","Random Access Write","Register Address Write",0,"RAW: instruction reads before previous write completes."],
  ["What is a WAW hazard?","Write After Write: two writes to same register","Write After Write conflict","Write After Wait","Word Address Write",0,"WAW: out-of-order execution can cause wrong final value."],
  ["What is a WAR hazard?","Write After Read: write before previous read","Write After Read conflict","Word After Read","Write Access Register",0,"WAR: writing before previous instruction reads old value."],
  ["How do you resolve data hazards?","Forwarding/bypassing or stalling","Adding more registers","Increasing clock","Adding cache",0,"Forwarding: pass result directly to next instruction."],
  ["What is forwarding (bypassing)?","Passing result directly without waiting for writeback","Adding more cache","Increasing clock speed","Adding pipelines",0,"Forwarding: ALU result sent directly to next instruction."],
  ["What is a pipeline stall (bubble)?","Inserting NOP cycles to resolve hazards","Adding more instructions","Removing instructions","Increasing clock",0,"Stall: pause pipeline until hazard resolves."],
  ["What is a control hazard?","Branch/change in control flow","Data dependency","Resource conflict","Cache miss",0,"Control hazards: branches change flow, pipeline unsure."],
  ["How do you reduce control hazards?","Branch prediction and delay slots","More cache","More registers","Higher clock",0,"Prediction: guess branch direction to keep pipeline full."],
  ["What is branch prediction?","Guessing branch outcome before resolution","Counting branches","Removing branches","Adding branches",0,"Prediction: minimize stalls from control hazards."],
  ["What is static branch prediction?","Fixed prediction (e.g., always not taken)","Prediction based on history","Prediction based on cache","No prediction",0,"Static: simple heuristic (backward = taken)."],
  ["What is dynamic branch prediction?","Prediction based on execution history","Fixed prediction","No prediction","Random prediction",0,"Dynamic: BHT, BTB, perceptron predictors."],
  ["What is a branch target buffer (BTB)?","Cache storing branch target addresses","Branch predictor cache","Data cache","Instruction cache",0,"BTB: stores target address for recent branches."],
  ["What is a branch history table (BHT)?","Table storing branch outcome history","Target addresses","Instruction cache","Data cache",0,"BHT: 1-bit or 2-bit saturating counters per branch."],
  ["What is a 2-bit saturating counter predictor?","Strong/weak taken/not-taken states","1-bit predictor","No prediction","Random",0,"2-bit: more stable, tolerates one misprediction."],
  ["What is a branch delay slot?","Instruction after branch always executes","Instruction before branch","Skipped instruction","NOP instruction",0,"Delay slot: MIPS executes next instruction regardless."],
  ["What is speculative execution?","Executing instructions before knowing if needed","Executing after branch resolves","Not executing","Random execution",0,"Speculation: execute predicted path, flush if wrong."],
  ["What is out-of-order execution?","Executing instructions when ready, not in order","Executing in order","Not executing","Random order",0,"OoO: improves ILP by using available resources."],
  ["What is instruction-level parallelism (ILP)?","Executing multiple instructions simultaneously","Parallel cores","Parallel threads","Parallel cache",0,"ILP: pipelining + superscalar + OoO + speculation."],
  ["What is a superscalar CPU?","Multiple execution units per cycle","Single execution unit","No pipeline","Single core",0,"Superscalar: >1 instruction per cycle (multiple ALUs)."],
  ["What is VLIW?","Very Long Instruction Word","Very Large Internal Word","Variable Length Instruction Word","Virtual Linear Instruction Word",0,"VLIW: compiler packs multiple ops into one wide instruction."],
  ["What is the difference between VLIW and superscalar?","VLIW: compiler schedules; superscalar: hardware schedules","No difference","VLIW is faster","Superscalar is simpler",0,"VLIW relies on compiler; superscalar has dynamic scheduling."],
  ["What is SIMD?","Single Instruction Multiple Data","Single Input Multiple Devices","Simple Instruction Multiple Data","Single Instruction Memory Data",0,"SIMD: one instruction operates on multiple data elements."],
  ["What is an example of SIMD?","Intel SSE/AVX","Hyper-threading","Multi-core","Pipeline",0,"SSE/AVX: vector operations on multiple data."],
  ["What is vector processing?","Operating on arrays of data with one instruction","Scalar processing","Branch prediction","Cache optimization",0,"Vector: GPU and CPU SIMD extensions."],
  ["What is SMT?","Simultaneous Multi-Threading","Single Multi-Thread","Synchronous Multi-Threading","Sequential Multi-Thread",0,"SMT: multiple threads share one core's resources."],
  ["What is a thread in CPU context?","Independent sequence of instructions","A core","A cache line","A register",0,"Threads share core resources but have independent state."],
  ["What is a context switch?","Saving and restoring CPU state for thread/process","Switching cache","Switching clock","Switching bus",0,"Context switch: save PC, registers, switch to new thread."],
  ["What is virtual memory?","Using disk as extended RAM","Cache memory","Register memory","ROM memory",0,"Virtual memory: page table maps virtual to physical addresses."],
  ["What is a page table?","Maps virtual to physical addresses","Maps cache to memory","Maps registers to memory","Maps buses to devices",0,"Page table: OS-managed, translates virtual addresses."],
  ["What is a TLB?","Translation Lookaside Buffer","Table Lookaside Buffer","Translation Logic Buffer","Table Logic Buffer",0,"TLB: cache for page table entries (speeds translation)."],
  ["What is a TLB miss?","Translation not found in TLB","Cache miss","Page fault","Bus error",0,"TLB miss: walk page table to find translation."],
  ["What is a page fault?","Access to page not in physical memory","TLB miss","Cache miss","Bus error",0,"Page fault: OS must load page from disk."],
  ["What is cache coherence?","Multiple caches agree on memory values","Cache speed","Cache size","Cache replacement",0,"Coherence: ensures all cores see consistent data."],
  ["What is MESI protocol?","Cache coherence protocol (Modified, Exclusive, Shared, Invalid)","Memory protocol","Bus protocol","Clock protocol",0,"MESI: 4-state protocol for multi-core cache coherence."],
  ["What is a cache hit?","Requested data found in cache","Data not in cache","Data in memory","Data in disk",0,"Cache hit: data available without accessing main memory."],
  ["What is a cache miss?","Requested data not in cache","Data in cache","Data in register","Data in TLB",0,"Cache miss: must fetch from lower memory hierarchy."],
  ["What are the three types of cache misses?","Compulsory, Capacity, Conflict","Read, Write, Execute","L1, L2, L3","Data, Instruction, TLB",0,"3Cs: Compulsory (cold), Capacity, Conflict."],
  ["What is a compulsory miss?","First access to data (never cached)","Cache full","Multiple map to same set","Cache too small",0,"Compulsory: unavoidable first-time miss."],
  ["What is a capacity miss?","Cache cannot hold all active data","First access","Conflict in set","Coherence",0,"Capacity: cache too small for working set."],
  ["What is a conflict miss?","Multiple addresses map to same cache set","First access","Cache too small","Coherence issue",0,"Conflict: limited associativity causes evictions."],
  ["What is cache associativity?","Number of locations data can be placed","Cache size","Cache speed","Cache replacement",0,"Direct-mapped, set-associative, fully-associative."],
  ["What is a direct-mapped cache?","Each address maps to one cache line","Multiple locations per address","Any location","No mapping",0,"Direct-mapped: simple, fast, more conflict misses."],
  ["What is a fully-associative cache?","Data can go in any cache line","One location per address","Fixed location","No mapping",0,"Fully-associative: flexible, fewer misses, more complex."],
  ["What is a set-associative cache?","Data maps to a set of N lines","One line per address","Any line","No mapping",0,"N-way set-associative: compromise between direct and full."],
  ["What is a cache line (block)?","Minimum unit of cache transfer","Single byte","Single word","Cache set",0,"Cache line: typically 32-64 bytes, fetched together."],
  ["What is a write-through cache?","Writes to cache and memory simultaneously","Writes to cache only","Writes to memory only","No writes",0,"Write-through: simple, consistent, more memory traffic."],
  ["What is a write-back cache?","Writes to cache, memory updated later","Writes to both","Writes to memory only","No writes",0,"Write-back: efficient, dirty bit tracks changes."],
  ["What is a write-allocate policy?","Load block into cache on write miss","Write directly to memory","No allocation","Skip cache",0,"Write-allocate: bring block to cache, then write."],
  ["What is a no-write-allocate policy?","Write directly to memory on write miss","Load block to cache","Write to cache","Skip memory",0,"No-write-allocate: write to memory, don't cache."],
  ["What is memory hierarchy?","Faster/smaller to slower/larger storage","All same speed","Only cache","Only RAM",0,"Registers → Cache → RAM → SSD → HDD."],
  ["What is the principle of locality?","Programs access nearby/recent data","Random access","Sequential only","No pattern",0,"Locality: spatial (nearby) + temporal (recently used)."],
  ["What is spatial locality?","Accessing nearby memory locations","Accessing recent locations","Random access","No pattern",0,"Spatial: sequential access, prefetching helps."],
  ["What is temporal locality?","Reaccessing recently used data","Accessing nearby data","Random access","No pattern",0,"Temporal: recently used data likely reused soon."],
];

// ===== ADVANCED (50) =====
const advanced = [
  ["What is Tomasulo's algorithm?","Dynamic scheduling with reservation stations","Branch prediction","Cache coherence","Pipeline stalling",0,"Tomasulo: register renaming, RS, common data bus."],
  ["What is register renaming?","Mapping architectural to physical registers","Removing registers","Adding registers","Cache mapping",0,"Renaming eliminates WAW and WAR hazards."],
  ["What is a reorder buffer (ROB)?","Enables in-order commit of OoO instructions","Branch predictor","Cache buffer","Memory buffer",0,"ROB: instructions execute OoO but commit in order."],
  ["What is a reservation station?","Holds instruction until operands ready","Cache line","Register file","Memory buffer",0,"RS: waiting area for instructions in Tomasulo."],
  ["What is a common data bus (CDB)?","Broadcasts results to all reservation stations","Memory bus","Address bus","Control bus",0,"CDB: results broadcast to waiting RS in one cycle."],
  ["What is the difference between scoreboarding and Tomasulo?","Tomasulo uses renaming; scoreboarding uses stalls","No difference","Scoreboarding is faster","Tomasulo is simpler",0,"Scoreboarding: stalls on WAW/WAR. Tomasulo: renaming avoids them."],
  ["What is a load-store queue (LSQ)?","Manages memory operations in OoO execution","Cache queue","Bus queue","Register queue",0,"LSQ: handles load/store ordering, memory disambiguation."],
  ["What is memory disambiguation?","Determining if load/store access same address","Cache replacement","TLB management","Bus arbitration",0,"Disambiguation: can load bypass earlier store?"],
  ["What is a store buffer?","Holds stores until commit","Cache buffer","Register buffer","Bus buffer",0,"Store buffer: stores commit in order, not visible until retired."],
  ["What is speculative load execution?","Executing loads before branch resolves","Cache loading","Register loading","Bus loading",0,"Speculative loads: may need rollback if path wrong."],
  ["What is a micro-op (µop)?","Simple operations decomposing complex instructions","Macro instruction","Cache operation","Bus operation",0,"CISC instructions decoded into µops (like RISC)."],
  ["What is a trace cache?","Cache storing decoded µops","Data cache","Instruction cache","TLB cache",0,"Trace cache: stores decoded instruction sequences (P4)."],
  ["What is microcode?","Low-level code implementing complex instructions","Assembly code","Machine code","High-level code",0,"Microcode: ROM-based routines for complex instructions."],
  ["What is the difference between hardwired and microcoded control?","Hardwired: fast, fixed; microcoded: slow, flexible","No difference","Hardwired is slower","Microcoded is faster",0,"Hardwired: FSM logic. Microcoded: ROM lookup."],
  ["What is a superscalar issue width?","Number of instructions issued per cycle","Number of pipelines","Number of cores","Number of registers",0,"Issue width: 2, 4, 6, 8 instructions per cycle."],
  ["What is an instruction window?","Set of instructions available for OoO execution","Cache window","Register window","Bus window",0,"Larger window = more ILP exploited."],
  ["What is the difference between issue and dispatch?","Issue: send to RS; dispatch: execute when ready","No difference","Issue is execution","Dispatch is fetch",0,"Issue: to reservation station. Dispatch: to execution unit."],
  ["What is commit (retire)?","Permanently updating state after execution","Fetching instructions","Decoding instructions","Executing instructions",0,"Commit: in-order, updates registers/memory."],
  ["What is a precise exception?","All prior instructions committed, none after","All instructions committed","No instructions committed","Random state",0,"Precise: clean state for interrupt handling."],
  ["What is instruction fusion?","Combining two instructions into one µop","Splitting instructions","Removing instructions","Adding instructions",0,"Fusion: e.g., compare+branch fused into one op."],
  ["What is macro-operation fusion?","Combining macro-instructions at decode","Combining µops","Removing µops","Splitting µops",0,"Macro-fusion: e.g., CMP + JCC → one µop (Intel)."],
  ["What is a µop cache?","Cache of decoded µops before decode stage","Data cache","Instruction cache","TLB",0,"µop cache: skips decode for repeated code (Intel Sandy Bridge+)."],
  ["What is the front-end of a CPU pipeline?","Fetch + decode stages","Execute stage","Memory stage","Writeback stage",0,"Front-end: fetch, decode, branch prediction."],
  ["What is the back-end of a CPU pipeline?","Execute + memory + writeback","Fetch + decode","Branch prediction","Cache only",0,"Back-end: execution units, memory, commit."],
  ["What is a decode queue?","Buffer between decode and rename stages","Cache queue","Bus queue","Memory queue",0,"Decode queue: smooths front-end to back-end flow."],
  ["What is the rename stage?","Maps architectural to physical registers","Decode stage","Fetch stage","Execute stage",0,"Rename: allocates physical registers, removes false deps."],
  ["What is a physical register file?","Actual storage with more registers than ISA defines","ISA registers only","Cache","Memory",0,"PRF: e.g., 128-256 physical vs 16-32 architectural."],
  ["What is a free list?","Pool of available physical registers","List of free cache lines","List of free buses","List of free instructions",0,"Free list: physical registers not currently in use."],
  ["What is an architectural register file?","Registers visible to the programmer","Physical registers","Cache","Memory",0,"ARF: ISA-defined registers (e.g., 32 GPRs in MIPS)."],
  ["What is the difference between PRF and ARF?","PRF has more for renaming; ARF is ISA-visible","No difference","PRF is smaller","ARF is larger",0,"PRF: many physical. ARF: architectural (ISA-defined)."],
  ["What is a checkpoint in speculative execution?","Saved state for rollback on misprediction","Cache checkpoint","Memory checkpoint","Bus checkpoint",0,"Checkpoint: save PRF mapping for branch recovery."],
  ["What is a misprediction penalty?","Cycles lost when branch predicted wrong","Cache miss penalty","TLB miss penalty","Bus penalty",0,"Misprediction: flush pipeline, restart from correct path."],
  ["What is the branch misprediction rate of a good predictor?","< 1%","~50%","~10%","~25%",0,"Modern predictors: 95-99% accuracy."],
  ["What is a perceptron branch predictor?","ML-based predictor using weighted history","Simple counter","Random","Static",0,"Perceptron: learns correlations, high accuracy."],
  ["What is a tournament predictor?","Chooses between global and local predictors","Single predictor","No prediction","Random",0,"Tournament: meta-predictor selects best predictor."],
  ["What is a return address stack (RAS)?","Predicts return targets for function calls","Branch predictor","Cache predictor","Data predictor",0,"RAS: push on call, pop on return, predicts return address."],
  ["What is a hardware prefetcher?","Predicts and fetches data before needed","Branch predictor","Cache predictor","TLB predictor",0,"Prefetcher: spatial/stride/stream pattern detection."],
  ["What is a stride prefetcher?","Prefetches at constant address stride","Random prefetch","No prefetch","Sequential only",0,"Stride: detects linear access patterns (e.g., a[i])."],
  ["What is a stream prefetcher?","Prefetches sequential cache lines","Stride prefetch","No prefetch","Random prefetch",0,"Stream: detects sequential access, prefetches ahead."],
  ["What is a memory-level parallelism (MLP)?","Multiple outstanding memory requests","Instruction parallelism","Thread parallelism","Data parallelism",0,"MLP: number of cache misses served simultaneously."],
  ["What is a non-blocking cache?","Serves other requests during a miss","Blocks on miss","No cache","Write-only cache",0,"Non-blocking (lockup-free): continues on miss."],
  ["What is a hardware prefetching for instruction fetch?","Prefetches next instruction cache lines","Data prefetch","No prefetch","Random prefetch",0,"Instruction prefetch: sequential fetch pattern."],
  ["What is a power gating in CPU?","Cutting power to idle components","Clock gating only","Bus gating","Cache gating",0,"Power gating: reduces leakage power in idle units."],
  ["What is dynamic voltage and frequency scaling (DVFS)?","Adjusting V/f for power-performance trade-off","Fixed voltage","Fixed frequency","No scaling",0,"DVFS: lower V/f when performance not needed."],
  ["What is turbo boost?","Temporarily increasing frequency above base","Permanent overclock","Reducing frequency","Disabling cores",0,"Turbo: uses thermal headroom for burst performance."],
  ["What is a NUMA architecture?","Non-Uniform Memory Access","Uniform Memory Access","No Memory Access","Network Memory Access",0,"NUMA: each CPU has local memory, faster than remote."],
  ["What is a SMP system?","Symmetric Multiprocessing","Sequential Multiprocessing","Synchronous Multi-Processing","Shared Memory Protocol",0,"SMP: all cores share same memory uniformly."],
  ["What is a chiplet architecture?","Multiple dies on one package","Single die","No die","Multi-chip module only",0,"Chiplets: smaller dies connected by high-speed links."],
  ["What is a 3D stacked cache (V-Cache)?","SRAM stacked on CPU die","Cache on PCB","Cache in memory","No cache",0,"3D V-Cache: AMD's stacked L3 for larger cache."],
  ["What is a systolic array?","Grid of processing elements for matrix ops","Single ALU","Cache array","Register array",0,"Systolic arrays: used in TPUs for ML acceleration."],
  ["What is a tensor processing unit (TPU)?","Specialized for matrix multiplication","General CPU","GPU","DSP",0,"TPU: ASIC for ML workloads, uses systolic arrays."],
  ["What is a neuromorphic processor?","Mimics brain-like neural computation","Standard CPU","Standard GPU","Standard DSP",0,"Neuromorphic: spiking neural networks, event-driven."],
  ["What is a quantum processing unit (QPU)?","Uses quantum bits (qubits) for computation","Classical CPU","GPU","TPU",0,"QPU: superposition and entanglement for quantum algorithms."],
];

module.exports = { basic, intermediate, advanced };
