// gate-puzzler question bank - 50 per level
const G = [];

// ===== BASIC (50) =====
const basic = [
  ["What does a NOT gate do?","Inverts the input","Buffers the input","Adds two inputs","Multiplies inputs",0,"A NOT gate outputs the inverse of its input."],
  ["Which gate outputs 1 only when both inputs are 1?","AND","OR","XOR","NAND",0,"AND requires both inputs high."],
  ["How many inputs does a standard NOT gate have?","1","2","3","4",0,"NOT is a single-input gate."],
  ["What is the output of OR gate when both inputs are 0?","0","1","High impedance","Undefined",0,"OR outputs 0 only when all inputs are 0."],
  ["NAND gate is the combination of which two gates?","AND + NOT","OR + NOT","XOR + NOT","NOR + NOT",0,"NAND is AND followed by NOT."],
  ["Which gate outputs 0 only when both inputs are 1?","NAND","AND","OR","XOR",0,"NAND outputs 0 only when all inputs are 1."],
  ["What does XOR output when both inputs are the same?","0","1","High-Z","Depends on input",0,"XOR outputs 0 when inputs are equal."],
  ["How many input combinations does a 2-input truth table have?","4","2","8","16",0,"2^2 = 4 combinations."],
  ["Which symbol represents an AND gate?","D-shaped","Shield-shaped","Triangle","Oval",0,"AND gates use a D-shaped symbol."],
  ["What is the output of a NOR gate with inputs 1 and 0?","0","1","High-Z","Undefined",0,"NOR outputs 0 if any input is 1."],
  ["A buffer gate does what?","Passes input unchanged","Inverts input","ANDs inputs","ORs inputs",0,"A buffer passes the signal through."],
  ["Which gate is known as the universal gate?","NAND","XOR","OR","NOT",0,"NAND can implement any logic function."],
  ["What is the truth table output for AND(1,1)?","1","0","Both","Neither",0,"AND(1,1) = 1."],
  ["How many rows in a 3-input truth table?","8","4","16","32",0,"2^3 = 8 rows."],
  ["Which gate gives 1 when inputs differ?","XOR","AND","OR","NAND",0,"XOR outputs 1 when inputs differ."],
  ["What is De Morgan's first law?","NOT(A AND B) = NOT A OR NOT B","A AND B = A OR B","NOT(A OR B) = A AND B","A XOR B = A NAND B",0,"De Morgan: complement of AND equals OR of complements."],
  ["Which gate has a bubble at its output?","NAND","AND","OR","XOR",0,"The bubble indicates inversion."],
  ["What does the bubble on a gate symbol represent?","Inversion","Amplification","Buffering","Ground",0,"A bubble means logical NOT."],
  ["Which gate is OR followed by NOT?","NOR","NAND","XOR","AND",0,"NOR = OR + NOT."],
  ["What is the output of NAND(0,0)?","1","0","High-Z","Undefined",0,"NAND(0,0) = NOT(0 AND 0) = NOT(0) = 1."],
  ["How many transistors does a basic CMOS NOT gate use?","2","4","6","8",0,"CMOS NOT uses one PMOS and one NMOS."],
  ["Which logic family uses complementary pairs?","CMOS","TTL","ECL","DTL",0,"CMOS uses complementary MOSFET pairs."],
  ["What is the output of NOT(1)?","0","1","High-Z","Undefined",0,"NOT(1) = 0."],
  ["Which gate can be used to build any other gate?","NAND","XOR","OR","Buffer",0,"NAND is functionally complete."],
  ["What is the Boolean expression for OR gate?","A + B","A · B","A ⊕ B","A · B'",0,"OR is represented by +."],
  ["What is the Boolean expression for AND gate?","A · B","A + B","A ⊕ B","A'",0,"AND is represented by ·."],
  ["Which gate outputs 1 when at least one input is 1?","OR","AND","NAND","NOR",0,"OR outputs 1 if any input is high."],
  ["What is the dual of AND?","OR","NOT","XOR","NAND",0,"The dual of AND is OR."],
  ["In Boolean algebra, what is A + 1?","1","A","0","A'",0,"A OR 1 = 1 (absorption)."],
  ["In Boolean algebra, what is A · 0?","0","A","1","A'",0,"A AND 0 = 0."],
  ["In Boolean algebra, what is A + 0?","A","0","1","A'",0,"A OR 0 = A (identity)."],
  ["In Boolean algebra, what is A · 1?","A","0","1","A'",0,"A AND 1 = A (identity)."],
  ["What is A + A in Boolean algebra?","A","0","1","A'",0,"A OR A = A (idempotent)."],
  ["What is A · A in Boolean algebra?","A","0","1","A'",0,"A AND A = A (idempotent)."],
  ["What is NOT(NOT A)?","A","0","1","A'",0,"Double negation cancels out."],
  ["Which gate has a truth table with only one 0 output?","NAND","AND","OR","XOR",0,"NAND has one 0 row (both inputs 1)."],
  ["Which gate has a truth table with only one 1 output?","AND","NAND","NOR","XOR",0,"AND has one 1 row (both inputs 1)."],
  ["What is the output of XOR(1,0)?","1","0","High-Z","Undefined",0,"XOR(1,0) = 1."],
  ["What is the output of XNOR(1,1)?","1","0","High-Z","Undefined",0,"XNOR outputs 1 when inputs are equal."],
  ["How many 2-input gates are needed to build a NAND from NOR gates?","4","2","3","1",0,"NAND from NOR requires 4 NOR gates."],
  ["What does a logic 1 typically represent?","HIGH/True","LOW/False","Ground","High impedance",0,"Logic 1 = HIGH = True."],
  ["What does a logic 0 typically represent?","LOW/False","HIGH/True","VCC","High impedance",0,"Logic 0 = LOW = False."],
  ["Which gate is used for parity checking?","XOR","AND","OR","NAND",0,"XOR is used for parity generation/checking."],
  ["What is the output of NOR(0,0)?","1","0","High-Z","Undefined",0,"NOR(0,0) = NOT(0 OR 0) = NOT(0) = 1."],
  ["Which gate's output is the complement of XOR?","XNOR","NAND","NOR","AND",0,"XNOR is the complement of XOR."],
  ["What is A · A' in Boolean algebra?","0","1","A","A'",0,"A AND NOT A = 0 (complementarity)."],
  ["What is A + A' in Boolean algebra?","1","0","A","A'",0,"A OR NOT A = 1 (complementarity)."],
  ["Which two gates are called universal gates?","NAND and NOR","AND and OR","XOR and XNOR","NOT and Buffer",0,"Both NAND and NOR are functionally complete."],
  ["What is the output of AND(1,0)?","0","1","High-Z","Undefined",0,"AND(1,0) = 0."],
  ["What is the output of OR(1,0)?","1","0","High-Z","Undefined",0,"OR(1,0) = 1."],
];

// ===== INTERMEDIATE (50) =====
const intermediate = [
  ["Simplify: A + AB","A","B","A+B","AB",0,"A + AB = A(1+B) = A (absorption)."],
  ["Simplify: A(A+B)","A","B","AB","A+B",0,"A(A+B) = AA + AB = A + AB = A."],
  ["Simplify: (A+B)(A+B')","A","B","A+B","AB",0,"(A+B)(A+B') = A + BB' = A."],
  ["What is the consensus theorem?","AB + A'C + BC = AB + A'C","AB + AC = AB","A+B = A","AB = A",0,"Consensus: AB + A'C + BC = AB + A'C."],
  ["Simplify: AB + AB'","A","B","A+B","0",0,"AB + AB' = A(B+B') = A."],
  ["How many minterms does a 3-variable function have?","8","4","16","6",0,"2^3 = 8 minterms."],
  ["How many maxterms does a 4-variable function have?","16","8","4","32",0,"2^4 = 16 maxterms."],
  ["What is the minterm for A=1, B=0, C=1?","m5","m2","m7","m3",0,"101 binary = 5, so m5."],
  ["What is the maxterm for A=0, B=1, C=0?","M2","M5","M4","M1",0,"010 binary = 2, so M2."],
  ["How many cells in a 4-variable K-map?","16","8","4","32",0,"2^4 = 16 cells."],
  ["In a K-map, adjacent cells differ by how many variables?","1","2","3","0",0,"Adjacent cells differ by exactly one variable."],
  ["What is the minimum number of variables for a K-map to be useful?","2","1","3","4",0,"K-maps work for 2-6 variables."],
  ["What does SOP stand for?","Sum of Products","Set of Pairs","Standard Operating Procedure","Series of Products",0,"SOP = Sum of Products."],
  ["What does POS stand for?","Product of Sums","Position","Post-Operation Set","Pair of Sums",0,"POS = Product of Sums."],
  ["Which is the canonical form for minterms?","SOP","POS","Both","Neither",0,"Minterms are expressed in SOP form."],
  ["Which is the canonical form for maxterms?","POS","SOP","Both","Neither",0,"Maxterms are expressed in POS form."],
  ["What is a hazard in combinational logic?","A momentary false output","A permanent error","A short circuit","A power fault",0,"Hazards cause brief glitches during transitions."],
  ["What causes a static-1 hazard?","Single variable change causing a 1→0→1 glitch","Two variables changing","Clock skew","Power noise",0,"A single input change can cause a brief 0 glitch."],
  ["How do you eliminate a static hazard?","Add redundant consensus terms","Add more gates","Increase voltage","Add a clock",0,"Consensus terms cover the hazard gap."],
  ["What is a multiplexer?","A data selector","A data distributor","A counter","A register",0,"A MUX selects one of many inputs."],
  ["How many select lines does a 16:1 MUX need?","4","3","2","5",0,"2^4 = 16 inputs need 4 select lines."],
  ["How many inputs does a 4:1 MUX have?","4","2","8","16",0,"4:1 means 4 data inputs."],
  ["What is a demultiplexer?","Routes one input to many outputs","Combines many inputs","Counts pulses","Stores data",0,"A DEMUX distributes one input to selected output."],
  ["How many output lines does a 3-to-8 decoder have?","8","3","5","16",0,"3 inputs decode to 8 outputs."],
  ["What is an encoder?","Converts many inputs to fewer output lines","Converts few inputs to many","Amplifies signals","Buffers data",0,"Encoder = opposite of decoder."],
  ["How many output lines does an 8-to-3 priority encoder have?","3","8","5","4",0,"8 inputs encode to 3-bit output."],
  ["What does a priority encoder do?","Outputs the highest-priority active input","Outputs all active inputs","Counts inputs","Buffers data",0,"Priority encoders handle multiple active inputs."],
  ["What is a half adder?","Adds 2 bits, outputs sum and carry","Adds 4 bits","Adds 2 numbers","Subtracts bits",0,"Half adder: 2 inputs, sum + carry outputs."],
  ["What is a full adder?","Adds 3 bits including carry-in","Adds 2 bits","Adds 4 bits","Adds with overflow",0,"Full adder includes carry-in."],
  ["How many full adders are needed for a 4-bit ripple carry adder?","4","3","2","8",0,"One per bit position."],
  ["What is the main disadvantage of ripple carry?","Propagation delay","Power consumption","Area","Cost",0,"Carry ripples through each stage sequentially."],
  ["Which adder is fastest for large bit widths?","Carry-lookahead","Ripple carry","Serial adder","Half adder",0,"CLA computes carries in advance."],
  ["What does a comparator circuit do?","Compares two binary numbers","Compares voltages","Compares frequencies","Compares currents",0,"Comparators output equality/inequality."],
  ["How many outputs does a 4-bit magnitude comparator have?","3","2","4","1",0,"A>B, A<B, A=B outputs."],
  ["What is a parity generator?","Adds a parity bit for error detection","Generates clock signals","Generates random numbers","Generates addresses",0,"Parity bits detect single-bit errors."],
  ["What is even parity?","Total number of 1s is even","Total 1s is odd","All bits are 1","All bits are 0",0,"Even parity means even count of 1s."],
  ["What is odd parity?","Total number of 1s is odd","Total 1s is even","Half are 1","None are 1",0,"Odd parity means odd count of 1s."],
  ["Which gate is used in a parity checker?","XOR","AND","OR","NAND",0,"XOR toggles for each 1, giving parity."],
  ["What is a BCD to 7-segment decoder?","Converts BCD to segment signals","Converts binary to BCD","Converts hex to decimal","Converts analog to digital",0,"Drives 7-segment displays from BCD input."],
  ["How many segment outputs does a 7-segment decoder have?","7","4","8","10",0,"7 segments: a-g."],
  ["What is a tristate buffer?","Buffer with high-impedance state","Buffer with 3 inputs","Buffer with 3 outputs","Triple buffer",0,"Tristate adds a high-Z (disable) state."],
  ["What is the purpose of tristate buffers on a bus?","Allow multiple drivers to share a bus","Increase speed","Reduce power","Add inversion",0,"Only one driver is active at a time."],
  ["What is an open-collector output?","Output that can sink but not source current","Output with 3 states","Output with amplification","Output with inversion",0,"Open-collector needs a pull-up resistor."],
  ["What is wired-OR using open-collector?","Multiple open-collector outputs share a pull-up","OR gate with wires","Wired connection","Bus arbitration",0,"Active-low outputs on shared line act as NOR."],
  ["What does a Schmitt trigger do?","Provides hysteresis for noise immunity","Triggers on clock","Amplifies signals","Buffers data",0,"Hysteresis prevents oscillation near threshold."],
  ["What is the difference between latch and flip-flop?","Flip-flop is edge-triggered, latch is level-sensitive","Latch is faster","Flip-flop uses less power","No difference",0,"Latches are transparent when enabled; FFs sample on edge."],
  ["What is a setup time?","Time data must be stable before clock edge","Time after clock","Clock period","Propagation delay",0,"Setup time ensures correct sampling."],
  ["What is hold time?","Time data must be stable after clock edge","Time before clock","Clock high duration","Reset time",0,"Hold time ensures data is captured correctly."],
  ["What is metastability?","Flip-flop output is unstable between 0 and 1","Flip-flop is reset","Flip-flop is stuck at 1","Flip-flop is too fast",0,"Caused by setup/hold violation."],
  ["How do you reduce metastability?","Use synchronizer flip-flops","Increase clock speed","Add more gates","Reduce voltage",0,"Two-stage synchronizers reduce failure rate."],
  ["What is fan-out in logic gates?","Number of inputs a gate output can drive","Number of inputs","Number of outputs","Speed of gate",0,"Fan-out = drive capability."],
  ["What is fan-in?","Number of inputs to a gate","Number of outputs","Drive capability","Gate speed",0,"Fan-in = input count."],
];

// ===== ADVANCED (50) =====
const advanced = [
  ["Prove that NAND is functionally complete","NAND can build NOT, AND, OR","NAND is fast","NAND uses few transistors","NAND is cheap",0,"NOT: NAND(A,A); AND: NOT(NAND(A,B)); OR: NAND(NOT A, NOT B)."],
  ["Implement XOR using only NAND gates. How many NAND gates are needed?","4","2","3","5",0,"XOR = NAND(A,NAND(A,B)) XOR NAND(B,NAND(A,B)) — 4 NANDs."],
  ["Implement a 2:1 MUX using only NAND. How many NAND gates?","4","3","2","5",0,"MUX: Y = AS + B S' needs 4 NAND gates."],
  ["What is the minimal SOP for F(A,B,C) = Σm(0,1,2,5,6,7)?","A'C' + AB + BC' + B'C","A + B + C","ABC + A'B'C'","A'B' + AB",0,"K-map minimization yields A'C' + AB + BC' + B'C."],
  ["What is the minimal POS for F(A,B,C) = Σm(0,1,2,5,6,7)?","(A+B'+C)(A'+B+C')","(A+B+C)(A+B'+C')","(A'+B'+C)(A+B+C)","(A+B)(B+C)",0,"Group zeros in K-map for POS form."],
  ["Design a 4-bit carry-lookahead adder. What is C4 in terms of G and P?","G3 + P3·G2 + P3·P2·G1 + P3·P2·P1·G0","C0 + G3","P3·G3","G3·P2",0,"CLA carry: C4 = G3 + P3G2 + P3P2G1 + P3P2P1G0."],
  ["What is the group generate G for a 4-bit CLA block?","G3 + P3G2 + P3P2G1 + P3P2P1G0","G0+G1+G2+G3","P0P1P2P3","G3P3",0,"Group generate combines individual generates."],
  ["What is the group propagate P for a 4-bit CLA block?","P3·P2·P1·P0","P0+P1+P2+P3","G0G1G2G3","P3+P0",0,"Group propagate = AND of all individual propagates."],
  ["How many gate delays does a 4-bit CLA adder have?","2 levels of logic","4 levels","8 levels","16 levels",0,"CLA carry is computed in 2 gate levels."],
  ["What is the Quine-McCluskey method used for?","Minimizing Boolean functions","Designing counters","Testing circuits","Simulating gates",0,"Tabular method for Boolean minimization."],
  ["What is a prime implicant?","An implicant that cannot be covered by a larger one","The largest minterm","The smallest maxterm","Any implicant",0,"Prime implicants are maximal groups in K-map."],
  ["What is an essential prime implicant?","A prime implicant covering a minterm no other PI covers","Any prime implicant","The largest PI","The smallest PI",0,"Essential PIs must be included in the minimal form."],
  ["How many prime implicants can a 4-variable function have at most?","8","4","16","32",0,"Maximum 2^(n-1) = 8 for n=4."],
  ["What is a don't-care condition in K-maps?","A combination that can be 0 or 1","An error condition","A forbidden state","A reset state",0,"Don't-cares help simplify logic."],
  ["What are Petrick's method and iterated consensus used for?","Finding minimal covers of prime implicants","Designing adders","Testing circuits","Clock generation",0,"Petrick's method finds all minimal SOP covers."],
  ["Design a 3:8 decoder using two 2:4 decoders. What additional gate is needed?","1 AND gate for enable","1 OR gate","1 NOT gate","1 XOR gate",0,"The MSB selects which 2:4 decoder is active."],
  ["How many 2:4 decoders are needed to build a 4:16 decoder?","5","2","3","4",0,"Four for the outputs plus one for enable selection."],
  ["Implement F = A'B' + AB using a 2:1 MUX. What connects to the select line?","A","B","A'","Ground",0,"With A on select: I0 = B', I1 = B gives F = A'B' + AB."],
  ["How many 4:1 MUXes are needed to implement a 3-variable function?","1","2","3","4",0,"One 4:1 MUX with 2 variables on select lines suffices."],
  ["What is the Shannon expansion theorem?","F = S·F(1) + S'·F(0)","F = A + B","F = AB","F = A⊕B",0,"Shannon expansion decomposes functions around a variable."],
  ["What is a transmission gate?","Parallel NMOS and PMOS passing signals in both directions","A series switch","A buffer","An inverter",0,"TG = NMOS || PMOS, bidirectional switch."],
  ["How do you build a D latch using transmission gates?","2 TGs + inverter feedback","4 NAND gates","6 NOR gates","1 multiplexer",0,"TG-based latches are compact and fast."],
  ["What is the difference between static and dynamic CMOS logic?","Static uses pull-up/pull-down networks; dynamic uses clocks","Static is faster","Dynamic uses less area","No difference",0,"Dynamic logic uses clocked evaluation; static is always on."],
  ["What is domino logic?","Dynamic CMOS with a static inverter per stage","Static CMOS variant","Clocked latch","Bipolar logic",0,"Domino cascades dynamic stages with inverters."],
  ["What is the main advantage of domino logic?","High speed and compact area","Low power","High noise margin","Easy to design",0,"Domino logic is faster and smaller than static CMOS."],
  ["What is the main disadvantage of domino logic?","Charge leakage and clock overhead","Slow speed","Large area","Low noise margin",0,"Dynamic nodes leak charge between clock phases."],
  ["What is NORA logic?","No Race Conditions dynamic logic","Static CMOS","Bipolar logic","ECL logic",0,"NORA uses alternating n-blocks and p-blocks to avoid races."],
  ["What is the difference between ripple-carry and carry-skip adders?","Carry-skip bypasses carry through groups","Carry-skip is slower","Ripple is faster","No difference",0,"Carry-skip adds bypass logic for faster carry propagation."],
  ["What is a carry-select adder?","Precomputes both carry=0 and carry=1, selects later","Adds in parallel","Uses CLA only","Is a multiplier",0,"CSA precomputes both cases and muxes the result."],
  ["What is a Wallace tree multiplier?","Parallel multiplier using carry-save adders","Sequential multiplier","Shift-add multiplier","Array multiplier",0,"Wallace tree compresses partial products in parallel."],
  ["What is a Booth multiplier?","Encodes multipliers to reduce partial products","Uses Wallace tree","Is an adder","Is a divider",0,"Booth encoding reduces the number of partial products."],
  ["What is the advantage of radix-4 Booth encoding?","Halves the number of partial products","Doubles speed","Reduces power","Increases area",0,"Radix-4 Booth processes 2 bits at a time."],
  ["What is a barrel shifter?","Combinational shifter that shifts any amount in one cycle","Sequential shifter","Single-bit shifter","Rotate-only circuit",0,"Barrel shifters use a crossbar of multiplexers."],
  ["How many muxes does an 8-bit barrel shifter use?","8","4","16","2",0,"One 8:1 MUX per output bit = 8 muxes."],
  ["What is an ALU?","Arithmetic Logic Unit performing multiple operations","Adder only","Multiplier","Comparator",0,"ALU performs arithmetic and logic operations."],
  ["How many select lines does a 16-operation ALU need?","4","3","2","5",0,"2^4 = 16 operations."],
  ["What is the difference between structural and behavioral HDL?","Structural describes gate-level; behavioral describes function","Structural is faster","Behavioral uses more area","No difference",0,"Structural = netlist; behavioral = algorithm."],
  ["What is gate-level netlist?","List of gates and their interconnections","RTL code","Test bench","Timing report",0,"Gate-level netlist is post-synthesis."],
  ["What is the difference between blocking and non-blocking assignments in Verilog?","Blocking (=) executes in order; non-blocking (<=) schedules simultaneously","Blocking is faster","Non-blocking is slower","No difference",0,"Use non-blocking for sequential, blocking for combinational."],
  ["What is a testbench in HDL?","Code that applies stimulus and checks outputs","Synthesis tool","Timing analyzer","Place and route tool",0,"Testbenches verify design correctness."],
  ["What is assertion-based verification?","Checking design properties at runtime","Code coverage","Gate-level simulation","Power analysis",0,"Assertions check temporal properties automatically."],
  ["What is formal verification?","Mathematically proves design equivalence","Simulation-based check","Visual inspection","Manual review",0,"Formal verification proves two designs are equivalent."],
  ["What is STA?","Static Timing Analysis","Sequential Timing Analyzer","Standard Test Architecture","Static Test Analyzer",0,"STA checks all timing paths without simulation."],
  ["What is the critical path in a circuit?","Longest delay path limiting clock frequency","Shortest path","Power supply path","Reset path",0,"Critical path determines max operating frequency."],
  ["What is slack in timing analysis?","Difference between required and actual arrival time","Extra gates","Unused inputs","Clock period",0,"Positive slack = meets timing; negative = violates."],
  ["What is clock skew?","Difference in clock arrival times at different FFs","Clock frequency","Clock duty cycle","Clock jitter",0,"Skew can help or hurt timing depending on direction."],
  ["What is useful skew?","Intentionally delaying clock to relax setup constraints","Accidental skew","Clock jitter","Clock drift",0,"Useful skew borrows time from next stage."],
  ["What is power dissipation in CMOS?","Dynamic (switching) + static (leakage) power","Dynamic only","Static only","Short-circuit only",0,"P = P_dynamic + P_leakage + P_short_circuit."],
  ["What is the formula for dynamic power?","P = CV²f","P = IR","P = V²/R","P = VI",0,"Dynamic power = capacitance × voltage² × frequency."],
  ["What is clock gating for?","Reducing dynamic power by disabling clocks to idle blocks","Increasing speed","Adding latency","Improving noise margin",0,"Clock gating saves power by stopping unnecessary switching."],
  ["What is body effect in MOSFETs?","Threshold voltage changes with source-body voltage","Channel length modulation","Velocity saturation","DIBL",0,"Body effect increases Vt when source rises above body."],
];

module.exports = { basic, intermediate, advanced };
