// power-quest question bank - 50 per level

// ===== BASIC (50) =====
const basic = [
  ["What is electrical power?","Rate of energy transfer","Amount of charge","Resistance to flow","Voltage level",0,"Power = energy/time, measured in watts."],
  ["What is the formula for DC power?","P = VI","P = V/I","P = I/V","P = V+I",0,"DC power = voltage × current."],
  ["What is the unit of electrical energy?","Joule (J)","Watt (W)","Volt (V)","Ampere (A)",0,"Energy measured in joules (or watt-hours)."],
  ["What is 1 kWh in joules?","3.6 MJ","3600 J","1 J","1000 J",0,"1 kWh = 1000 × 3600 = 3.6 × 10⁶ J."],
  ["What is the efficiency of a system?","Output power / Input power × 100%","Input / Output × 100%","Output × Input","Output + Input",0,"Efficiency = Pout/Pin × 100%."],
  ["What is power factor?","cos(φ) = R/Z","R/X","X/R","Z/R",0,"Power factor = cos(phase angle) = R/Z."],
  ["What is the ideal power factor?","1","0","0.5","0.8",0,"Unity power factor = 1 (purely resistive)."],
  ["What does a power factor of 0.8 lagging mean?","Current lags voltage by 36.87°","Current leads voltage","Current in phase","No phase difference",0,"cos⁻¹(0.8) = 36.87° lagging."],
  ["What is real power?","Power actually consumed","Power stored in reactive elements","Total apparent power","Power lost in wires",0,"Real power P = VI cos(φ), measured in watts."],
  ["What is reactive power?","Power oscillating in reactive elements","Power consumed by resistors","Total power","Power lost",0,"Reactive power Q = VI sin(φ), measured in VAR."],
  ["What is apparent power?","VI (total power)","VI cos(φ)","VI sin(φ)","V/I",0,"Apparent power S = VI, measured in VA."],
  ["What is the unit of reactive power?","VAR","Watt","VA","Joule",0,"Reactive power measured in VAR (volt-ampere reactive)."],
  ["What is the unit of apparent power?","VA","Watt","VAR","Joule",0,"Apparent power measured in VA (volt-ampere)."],
  ["What is the power triangle?","P, Q, S relationship","Voltage triangle","Current triangle","Resistance triangle",0,"S² = P² + Q², S = √(P²+Q²)."],
  ["What is the relationship between P, Q, and S?","S² = P² + Q²","S = P + Q","S = P × Q","S = P - Q",0,"Power triangle: S = √(P² + Q²)."],
  ["What is a transformer?","Device that changes voltage levels","Device that generates power","Device that stores energy","Device that measures power",0,"Transformer transfers AC power between voltage levels."],
  ["What does a step-up transformer do?","Increases voltage, decreases current","Decreases voltage, increases current","Increases both","Decreases both",0,"Step-up: V₂ > V₁, I₂ < I₁."],
  ["What does a step-down transformer do?","Decreases voltage, increases current","Increases voltage, decreases current","Decreases both","Increases both",0,"Step-down: V₂ < V₁, I₂ > I₁."],
  ["What is the turns ratio of a transformer?","N2/N1","N1/N2","N1+N2","N1×N2",0,"Turns ratio a = N2/N1 = V2/V1 = I1/I2."],
  ["What is an ideal transformer's power relationship?","V1I1 = V2I2","V1I2 = V2I1","V1 = V2","I1 = I2",0,"Ideal: input power = output power."],
  ["What is the efficiency of an ideal transformer?","100%","50%","90%","99%",0,"Ideal transformer has no losses."],
  ["What are transformer losses?","Copper losses + core losses","Only copper losses","Only core losses","No losses",0,"Copper (I²R) + core (hysteresis + eddy current)."],
  ["What are copper losses?","I²R losses in windings","Losses in the core","Losses in the air","Losses in insulation",0,"Copper losses = current² × winding resistance."],
  ["What are core losses?","Hysteresis + eddy current losses","Copper losses","Friction losses","Windage losses",0,"Core losses are constant (independent of load)."],
  ["What is hysteresis loss?","Energy lost in magnetizing/demagnetizing core","Loss in windings","Loss in oil","Loss in insulation",0,"Hysteresis: area of B-H loop × frequency × volume."],
  ["What is eddy current loss?","Loss from circulating currents in core","Loss in windings","Loss in air gap","Loss in connections",0,"Eddy currents induced in core; reduced by laminations."],
  ["How are eddy currents reduced?","Using laminated cores","Using thicker wire","Using more turns","Using oil",0,"Laminations break eddy current paths."],
  ["What is a rectifier?","Converts AC to DC","Converts DC to AC","Changes voltage","Stores energy",0,"Rectifier converts AC to DC."],
  ["What is an inverter?","Converts DC to AC","Converts AC to DC","Changes voltage","Stores energy",0,"Inverter converts DC to AC."],
  ["What is a converter?","Changes voltage/current form","Stores energy","Measures power","Generates power",0,"Converters change electrical form (AC/DC, voltage)."],
  ["What is a buck converter?","Step-down DC-DC converter","Step-up DC-DC","AC-DC converter","DC-AC converter",0,"Buck: output voltage < input voltage."],
  ["What is a boost converter?","Step-up DC-DC converter","Step-down DC-DC","AC-DC converter","DC-AC converter",0,"Boost: output voltage > input voltage."],
  ["What is a buck-boost converter?","Can step up or down","Step-up only","Step-down only","AC-DC only",0,"Buck-boost: inverting output, up or down."],
  ["What is the duty cycle in a switching converter?","Ratio of on-time to total period","Ratio of off-time to period","Switching frequency","Output voltage",0,"D = Ton / (Ton + Toff)."],
  ["What is the output of a buck converter with D=0.5 and Vin=12V?","6V","12V","24V","3V",0,"Vout = D × Vin = 0.5 × 12 = 6V."],
  ["What is the output of a boost converter with D=0.5 and Vin=5V?","10V","5V","2.5V","7.5V",0,"Vout = Vin/(1-D) = 5/0.5 = 10V."],
  ["What is a battery?","Stores electrical energy","Generates AC","Converts DC to AC","Measures voltage",0,"Batteries store energy chemically."],
  ["What is battery capacity measured in?","Ampere-hours (Ah)","Watts (W)","Volts (V)","Ohms (Ω)",0,"Capacity = current × time, in Ah."],
  ["What is the energy stored in a battery?","Voltage × Capacity (Wh)","Capacity only","Current only","Voltage only",0,"Energy = V × Ah = watt-hours."],
  ["What is a solar cell?","Converts light to electricity","Stores energy","Converts AC to DC","Measures light",0,"Photovoltaic cells convert sunlight to DC."],
  ["What is the typical voltage of a silicon solar cell?","~0.5-0.6V","~1.5V","~12V","~5V",0,"Single Si cell: ~0.5-0.6V open circuit."],
  ["What is a fuel cell?","Converts chemical energy to electricity","Stores solar energy","Converts AC to DC","Stores charge",0,"Fuel cells use hydrogen + oxygen → electricity + water."],
  ["What is a generator?","Converts mechanical energy to electrical","Converts electrical to mechanical","Stores energy","Measures power",0,"Generators convert mechanical rotation to electricity."],
  ["What is a motor?","Converts electrical energy to mechanical","Converts mechanical to electrical","Stores energy","Measures power",0,"Motors convert electricity to mechanical rotation."],
  ["What is the difference between a motor and generator?","Motor: electric→mechanical; Generator: mechanical→electric","Same device","Motor generates power","Generator uses power",0,"Same machine can work as either depending on direction."],
  ["What is AC power?","Alternating current power","Direct current power","Stored power","Reactive power",0,"AC periodically reverses direction."],
  ["What is DC power?","Direct current power","Alternating current power","Reactive power","Apparent power",0,"DC flows in one direction."],
  ["What is the frequency of AC power in the US?","60 Hz","50 Hz","100 Hz","120 Hz",0,"US uses 60 Hz mains power."],
  ["What is the frequency of AC power in Europe?","50 Hz","60 Hz","100 Hz","120 Hz",0,"Europe uses 50 Hz mains power."],
  ["What is the RMS voltage of US household AC?","120V","240V","170V","60V",0,"US: 120V RMS, 60 Hz."],
  ["What is the peak voltage of 120V RMS AC?","170V","120V","240V","60V",0,"Vpeak = Vrms × √2 = 120 × 1.414 ≈ 170V."],
];

// ===== INTERMEDIATE (50) =====
const intermediate = [
  ["What is a three-phase system?","Three AC voltages 120° apart","Three DC voltages","Single-phase with three wires","Three batteries in series",0,"Three-phase: balanced 120° phase separation."],
  ["What is the advantage of three-phase power?","More efficient for power transmission","Higher voltage","Lower frequency","Better power factor",0,"Three-phase delivers constant instantaneous power."],
  ["What is the line voltage in a Y-connected system?","√3 × phase voltage","Same as phase voltage","2 × phase voltage","Phase voltage / √3",0,"Y-connection: Vline = √3 × Vphase."],
  ["What is the line current in a Δ-connected system?","√3 × phase current","Same as phase current","2 × phase current","Phase current / √3",0,"Δ-connection: Iline = √3 × Iphase."],
  ["What is the total power in a balanced three-phase system?","√3 × Vline × Iline × cos(φ)","Vline × Iline","3 × Vphase × Iphase","√3 × Vline × Iline",0,"3-phase power: P = √3 × VL × IL × cos(φ)."],
  ["What is the relationship between line and phase voltage in Y?","Vline = √3 × Vphase","Vline = Vphase","Vline = 2 × Vphase","Vline = Vphase/√3",0,"Y: line voltage = √3 × phase voltage."],
  ["What is the relationship between line and phase current in Y?","Iline = Iphase","Iline = √3 × Iphase","Iline = 2 × Iphase","Iline = Iphase/√3",0,"Y: line current = phase current."],
  ["What is the relationship between line and phase voltage in Δ?","Vline = Vphase","Vline = √3 × Vphase","Vline = 2 × Vphase","Vline = Vphase/√3",0,"Δ: line voltage = phase voltage."],
  ["What is the relationship between line and phase current in Δ?","Iline = √3 × Iphase","Iline = Iphase","Iline = 2 × Iphase","Iline = Iphase/√3",0,"Δ: line current = √3 × phase current."],
  ["What is power factor correction?","Adding capacitors to improve PF","Adding inductors","Adding resistors","Adding transformers",0,"PFC capacitors cancel inductive reactive power."],
  ["Why improve power factor?","Reduce current and losses","Increase voltage","Increase power","Reduce frequency",0,"Better PF → lower current → lower I²R losses."],
  ["What is the capacitance needed for PFC?","C = Q/(2πfV²)","C = Q/V","C = V/Q","C = Q×V",0,"Required C = reactive power / (2πf × V²)."],
  ["What is the maximum efficiency of a transformer?","At load where copper loss = core loss","At full load","At no load","At half load",0,"Max efficiency when variable losses = constant losses."],
  ["What is per-unit system?","Normalizing values to a base","Unit system for power","SI units","Percentage system",0,"Per-unit simplifies calculations by normalizing."],
  ["What is the base value in per-unit system?","Reference for normalization","Maximum value","Minimum value","Average value",0,"Base values: Vbase, Ibase, Sbase, Zbase."],
  ["What is a synchronous generator?","Generator with rotor at synchronous speed","Generator with variable speed","DC generator","Induction generator",0,"Alternator: rotor speed = synchronous speed."],
  ["What is synchronous speed?","Ns = 120f/P","Ns = 60f/P","Ns = f/P","Ns = 120P/f",0,"Ns = 120 × frequency / poles."],
  ["What is the synchronous speed of a 4-pole machine at 60 Hz?","1800 RPM","3600 RPM","900 RPM","1200 RPM",0,"Ns = 120 × 60 / 4 = 1800 RPM."],
  ["What is the synchronous speed of a 2-pole machine at 50 Hz?","3000 RPM","1500 RPM","1000 RPM","750 RPM",0,"Ns = 120 × 50 / 2 = 3000 RPM."],
  ["What is an induction motor?","Motor where rotor speed < synchronous speed","Motor at synchronous speed","DC motor","Universal motor",0,"Induction motor: rotor runs below synchronous speed."],
  ["What is slip in an induction motor?","(Ns - Nr) / Ns × 100%","Ns / Nr","Nr / Ns","Ns - Nr",0,"Slip s = (Ns - Nr) / Ns."],
  ["What is the slip of an induction motor at no load?","~0%","100%","50%","10%",0,"At no load, rotor nearly reaches synchronous speed."],
  ["What is the slip at motor startup?","100% (or 1)","0%","50%","10%",0,"At start, rotor is stationary, so slip = 1."],
  ["What is the typical slip at full load?","2-5%","0%","50%","100%",0,"Full load slip is small (2-5%)."],
  ["What is the torque-slip characteristic?","Torque varies with slip","Torque is constant","Torque decreases with slip","No relationship",0,"Torque increases with slip up to maximum torque."],
  ["What is the starting torque of an induction motor?","Torque at slip = 1","Torque at slip = 0","Maximum torque","Rated torque",0,"Starting torque = torque at standstill (s=1)."],
  ["What is the maximum torque called?","Pull-out (breakdown) torque","Starting torque","Rated torque","Full-load torque",0,"Pull-out torque is the maximum the motor can produce."],
  ["How do you start a large induction motor?","Star-delta or auto-transformer starter","Direct online","Always direct","Series resistor",0,"Large motors need reduced-voltage starting to limit current."],
  ["What is a star-delta starter?","Starts in Y, runs in Δ","Starts in Δ, runs in Y","Always Y","Always Δ",0,"Y-Δ starter reduces starting voltage by 1/√3."],
  ["What is the starting current reduction in Y-Δ starting?","1/3 of DOL current","1/2 of DOL","2/3 of DOL","Same as DOL",0,"Y starting: current = 1/3 of direct-on-line."],
  ["What is a VFD?","Variable Frequency Drive","Voltage Frequency Detector","Variable Force Drive","Voltage Feedback Device",0,"VFD controls motor speed by varying frequency/voltage."],
  ["How does a VFD control motor speed?","By varying frequency and voltage","By varying current only","By varying resistance","By varying load",0,"VFD: ns = 120f/P, so speed ∝ frequency."],
  ["What is PWM in power electronics?","Pulse Width Modulation","Power Wave Modulation","Pulse Wave Management","Phase Width Modulation",0,"PWM varies duty cycle to control average voltage."],
  ["What is the purpose of PWM in inverters?","Control output voltage and reduce harmonics","Increase frequency","Reduce voltage","Increase current",0,"PWM synthesizes sinusoidal output from DC."],
  ["What is SPWM?","Sinusoidal PWM","Synchronous PWM","Simple PWM","Symmetric PWM",0,"SPWM: sine reference compared with triangular carrier."],
  ["What is the THD of an ideal sine wave inverter?","0%","5%","10%","3%",0,"Ideal sine wave has no harmonics."],
  ["What is a snubber circuit?","Protects switches from voltage spikes","Increases switching speed","Reduces power","Measures voltage",0,"Snubbers absorb transients from parasitic inductance."],
  ["What is a flyback diode?","Protects against inductive kickback","Rectifies AC","Filters noise","Stores charge",0,"Flyback diode provides path for inductor current."],
  ["What is soft switching?","Zero voltage or zero current switching","Low voltage switching","Slow switching","Low power switching",0,"Soft switching reduces switching losses."],
  ["What is ZVS?","Zero Voltage Switching","Zero Voltage Source","Zero Value Switch","Zener Voltage Switching",0,"ZVS: switch transitions at zero voltage."],
  ["What is ZCS?","Zero Current Switching","Zero Current Source","Zero Circuit Switch","Zener Current Switching",0,"ZCS: switch transitions at zero current."],
  ["What is a power MOSFET?","Voltage-controlled switching device","Current-controlled device","Bipolar device","Passive device",0,"MOSFET: gate voltage controls drain-source current."],
  ["What is an IGBT?","Insulated Gate Bipolar Transistor","Integrated Gate Bipolar Transistor","Insulated Gate Buffered Transistor","Internal Gate Bipolar Transistor",0,"IGBT combines MOSFET gate and BJT power handling."],
  ["What is the advantage of IGBT over MOSFET?","Higher voltage and current handling","Faster switching","Lower voltage","Lower cost",0,"IGBT handles high power; MOSFET is faster."],
  ["What is the advantage of MOSFET over IGBT?","Faster switching at lower voltages","Higher voltage","Higher current","Better efficiency at high power",0,"MOSFETs switch faster, better for low voltage."],
  ["What is a thyristor?","Latching semiconductor switch","Always-on switch","Voltage regulator","Current source",0,"Thyristor: SCR, latches on until current stops."],
  ["What triggers a thyristor?","Gate pulse","Voltage at anode","Current at cathode","Removing gate signal",0,"SCR turns on with gate pulse, off when current < holding."],
  ["What is a TRIAC?","Bidirectional thyristor","Unidirectional thyristor","DC switch","AC rectifier",0,"TRIAC conducts in both directions (AC switch)."],
  ["What is a DIAC?","Bidirectional trigger diode","Unidirectional diode","Zener diode","Schottky diode",0,"DIAC triggers TRIACs when voltage reaches breakover."],
  ["What is the difference between linear and switching regulators?","Linear dissipates excess; switching chops","Linear is more efficient","Switching has more noise","No difference",0,"Linear: simple, low noise, less efficient. Switching: efficient, noisy."],
  ["What is the efficiency of a linear regulator?","30-50% (depends on dropout)","90%","100%","10%",0,"Linear: efficiency ≈ Vout/Vin, often low."],
  ["What is the efficiency of a switching regulator?","80-95%","30-50%","100%","10%",0,"Switching regulators are highly efficient."],
  ["What is LDO?","Low Dropout Regulator","Low Duty Oscillator","Linear Drive Output","Low Distortion Output",0,"LDO: linear regulator with small input-output voltage difference."],
];

// ===== ADVANCED (50) =====
const advanced = [
  ["What is the maximum power point of a solar cell?","Operating point of maximum P = V×I","Maximum voltage point","Maximum current point","Open circuit voltage",0,"MPP: dP/dV = 0 on the IV curve."],
  ["What is MPPT?","Maximum Power Point Tracking","Maximum Power Point Transfer","Multi-Power Point Tracking","Maximum Power Phase Tracking",0,"MPPT dynamically adjusts load to stay at maximum power point."],
  ["What algorithm is commonly used for MPPT?","Perturb and Observe (P&O)","Newton-Raphson","Binary search","Kalman filter",0,"P&O: perturb voltage, observe power change direction."],
  ["What is the incremental conductance MPPT method?","dP/dV = 0 → dI/dV = -I/V","dI/dV = I/V","dV/dI = 0","dP/dI = V",0,"At MPP: dI/dV = -I/V (incremental = negative conductance)."],
  ["What is the fill factor of a solar cell?","FF = (Vm × Im) / (Voc × Isc)","Voc / Isc","Vm / Voc","Im / Isc",0,"FF measures how 'square' the IV curve is."],
  ["What is the efficiency of a typical commercial solar cell?","15-22%","5-10%","30-40%","50-60%",0,"Commercial Si cells: 15-22% efficiency."],
  ["What is the Shockley-Queisser limit?","~33.7% max efficiency for single-junction cell","~50%","~10%","~100%",0,"Theoretical max for single-junction Si under AM1.5G."],
  ["How do you exceed the Shockley-Queisser limit?","Multi-junction (tandem) cells","Thicker cells","More sunlight","Higher voltage",0,"Tandem cells stack different bandgap materials."],
  ["What is a battery management system (BMS)?","Monitors and protects battery cells","Charges batteries","Discharges batteries","Measures voltage only",0,"BMS: balancing, protection, SOC estimation."],
  ["What is state of charge (SOC)?","Remaining capacity as percentage","Total capacity","Voltage level","Current level",0,"SOC = remaining energy / full capacity × 100%."],
  ["What is depth of discharge (DOD)?","Percentage of capacity used","Percentage remaining","Total capacity","Charging level",0,"DOD = 100% - SOC."],
  ["What is Coulomb counting for SOC?","Integrating current over time","Measuring voltage","Measuring temperature","Measuring impedance",0,"SOC = SOC₀ - ∫I dt / capacity."],
  ["What is cell balancing?","Equalizing charge across battery cells","Charging cells faster","Discharging cells","Measuring cell voltage",0,"Balancing prevents overcharge/overdischarge of cells."],
  ["What is the difference between active and passive balancing?","Active transfers energy; passive dissipates","Active is slower","Passive is more efficient","No difference",0,"Passive: bleed resistors. Active: transfer between cells."],
  ["What is a supercapacitor?","High-capacity electrochemical capacitor","Small capacitor","DC-DC converter","Battery type",0,"Supercapacitors: high energy density, fast charge/discharge."],
  ["What is the energy density comparison: battery vs supercapacitor?","Battery higher energy, supercap higher power","Supercap higher energy","Same","Battery higher power",0,"Batteries: high Wh/kg. Supercaps: high W/kg."],
  ["What is a smart grid?","Grid with two-way communication and control","Traditional grid","Off-grid system","Microgrid",0,"Smart grid: sensors, meters, automated control."],
  ["What is demand response?","Adjusting load based on grid conditions","Generating more power","Reducing voltage","Increasing frequency",0,"Demand response shifts load to reduce peak demand."],
  ["What is load shedding?","Disconnecting loads during overload","Adding more loads","Increasing generation","Reducing frequency",0,"Load shedding prevents grid collapse."],
  ["What is the purpose of a grid-tie inverter?","Synchronize with grid and feed power","Convert AC to DC","Store energy","Isolate from grid",0,"Grid-tie inverter: phase-locked to grid, anti-islanding."],
  ["What is anti-islanding?","Detecting grid failure and disconnecting","Connecting to grid","Generating more power","Reducing output",0,"Anti-islanding protects lineworkers during outages."],
  ["What is a microgrid?","Localized grid that can operate independently","Large grid","National grid","Off-grid only",0,"Microgrid: can disconnect from main grid and self-supply."],
  ["What is distributed generation?","Small-scale generation near load","Centralized generation","Nuclear power","Grid-scale solar",0,"DG: solar panels, wind turbines, fuel cells near consumers."],
  ["What is net metering?","Feeding excess generation back to grid","Measuring total consumption","Measuring total generation","Fixed-rate billing",0,"Net metering credits prosumers for excess energy."],
  ["What is the capacity factor of a power plant?","Actual output / Rated capacity × 100%","Efficiency","Power factor","Load factor",0,"Capacity factor = average output / maximum output."],
  ["What is base load?","Minimum continuous demand on grid","Peak demand","Average demand","Off-peak demand",0,"Base load plants run continuously (nuclear, coal)."],
  ["What is peak load?","Maximum demand period","Minimum demand","Average demand","Off-peak",0,"Peaking plants handle short-term high demand."],
  ["What is load following?","Adjusting generation to match demand","Adjusting demand to match generation","Fixed generation","Fixed demand",0,"Load following: plants ramp output with demand changes."],
  ["What is spinning reserve?","Ready-to-deliver extra capacity","Off-line reserve","Long-term reserve","Maintenance reserve",0,"Spinning reserve: synchronized, ready in minutes."],
  ["What is FACTS?","Flexible AC Transmission System","Fast AC Transfer System","Flexible Alternative Current System","Full AC Transmission Standard",0,"FACTS: power electronic devices for grid control."],
  ["What is a STATCOM?","Static Synchronous Compensator","Static Switching Compensator","Synchronous Static Converter","Static System Compensator",0,"STATCOM: voltage-source inverter for reactive power."],
  ["What is an SVC?","Static Var Compensator","Static Voltage Compensator","Switching Var Converter","Static Variable Compensator",0,"SVC: thyristor-controlled reactive power compensation."],
  ["What is HVDC?","High Voltage DC transmission","High Voltage Direct Current","High Voltage Distribution Control","High Voltage DC Converter",0,"HVDC: efficient long-distance power transmission."],
  ["What is the advantage of HVDC over HVAC?","Lower losses for long distances","Higher losses","Same losses","No advantage",0,"HVDC: no skin effect, no reactive losses, lower line loss."],
  ["What is a DC-DC converter efficiency typically?","85-98%","50-60%","30-40%","100%",0,"Modern DC-DC converters: 85-98% efficient."],
  ["What is synchronous rectification?","Using MOSFETs instead of diodes","Using diodes only","Using IGBTs","Using thyristors",0,"Synchronous rectification: MOSFETs reduce conduction losses."],
  ["What is interleaving in converters?","Running multiple phases in parallel","Running at higher frequency","Using more inductors","Adding more capacitors",0,"Interleaving reduces ripple and increases effective frequency."],
  ["What is the benefit of multiphase converters?","Lower ripple, better thermal distribution","Higher voltage","Lower frequency","Simpler design",0,"Multiphase: ripple cancellation, shared current, less stress."],
  ["What is a resonant converter?","Uses LC resonance for soft switching","Uses resistors","Uses diodes only","Hard switching",0,"Resonant converters achieve ZVS/ZCS for high efficiency."],
  ["What is an LLC resonant converter?","L-L-C tank for ZVS","RLC circuit","LC circuit","RC circuit",0,"LLC: two inductors + capacitor, high efficiency at varied loads."],
  ["What is active power factor correction?","Boost converter for PF ≈ 1","Capacitor only","Inductor only","Transformer",0,"Active PFC: boost pre-regulator shapes input current."],
  ["What is the THD target for active PFC?","< 5%","< 50%","< 20%","< 10%",0,"Active PFC achieves THD < 5% and PF > 0.99."],
  ["What is a UPS?","Uninterruptible Power Supply","Universal Power Source","Underground Power System","Unified Power Supply",0,"UPS provides backup power during outages."],
  ["What are the types of UPS?","Online, line-interactive, offline","AC and DC","Single and three-phase","Small and large",0,"Online: double conversion. Line-interactive: AVR. Offline: standby."],
  ["What is double conversion in online UPS?","AC→DC→AC for clean output","AC→DC only","DC→AC only","AC→AC",0,"Online UPS: always converts through DC link for isolation."],
  ["What is galvanic isolation?","No direct electrical connection between circuits","Direct connection","Shared ground","Shared neutral",0,"Isolation via transformer prevents ground loops."],
  ["What is creepage distance?","Shortest path along insulator surface","Air gap distance","Insulator thickness","Conductor length",0,"Creepage: surface path for safety standards."],
  ["What is clearance distance?","Shortest air gap between conductors","Surface distance","Insulator length","Wire length",0,"Clearance: air gap for dielectric strength."],
  ["What is the function of an optocoupler in power supplies?","Signal isolation between primary and secondary","Amplification","Rectification","Filtering",0,"Optocouplers provide feedback isolation in isolated supplies."],
  ["What is a flyback converter?","Isolated buck-boost using transformer","Non-isolated buck","Non-isolated boost","Forward converter",0,"Flyback: energy stored in transformer during on-time, released during off-time."],
  ["What is a forward converter?","Isolated buck using transformer during on-time","Isolated buck-boost","Non-isolated","Flyback variant",0,"Forward converter: transfers energy during switch on-time, needs reset winding."],
];

module.exports = { basic, intermediate, advanced };
