// state-machine question bank - 50 per level

// ===== BASIC (50) =====
const basic = [
  ["What is a state machine?","System that transitions between states","System with no states","System with one state","Analog circuit",0,"A state machine has states and transitions."],
  ["What is a state in a state machine?","A condition or mode of the system","A clock cycle","A voltage level","A gate output",0,"A state represents a unique configuration."],
  ["What is a transition?","Change from one state to another","A clock pulse","A reset signal","A gate delay",0,"Transitions occur based on inputs and current state."],
  ["What are the two types of state machines?","Mealy and Moore","Combinational and sequential","Synchronous and asynchronous","Digital and analog",0,"Mealy: output depends on state+input. Moore: output depends on state only."],
  ["What is a Moore machine?","Output depends only on current state","Output depends on input only","Output depends on state and input","No output",0,"Moore: output = f(state)."],
  ["What is a Mealy machine?","Output depends on state and input","Output depends on state only","Output depends on input only","No output",0,"Mealy: output = f(state, input)."],
  ["What is a state diagram?","Visual representation of states and transitions","Circuit diagram","Truth table","Timing diagram",0,"State diagram: nodes = states, arrows = transitions."],
  ["What is a state table?","Tabular form of state transitions","Truth table","K-map","Timing diagram",0,"State table lists next state and output for each input."],
  ["What is the initial state?","Starting state of the machine","Final state","Any state","Reset state",0,"The initial state is entered on reset/power-up."],
  ["What is a reset state?","State entered on system reset","Final state","Error state","Idle state",0,"Reset brings the machine to a known starting state."],
  ["What is a clock in a state machine?","Signal that triggers state transitions","Power signal","Reset signal","Input signal",0,"State changes occur on clock edges."],
  ["What is a synchronous state machine?","Transitions on clock edges","Transitions anytime","No clock","Asynchronous",0,"Synchronous: all flip-flops share the same clock."],
  ["What is an asynchronous state machine?","Transitions without a clock","Transitions on clock","Synchronous","No transitions",0,"Asynchronous: transitions happen immediately on input change."],
  ["What is a flip-flop?","1-bit memory element","Logic gate","Counter","Multiplexer",0,"Flip-flops store state bits."],
  ["What does D flip-flop do?","Stores D input on clock edge","Inverts input","ANDs inputs","ORs inputs",0,"D-FF: Q follows D on clock edge."],
  ["What does JK flip-flop do?","J=K=0 hold, J=K=1 toggle, else set/reset","Stores D","Inverts clock","Counts only",0,"JK-FF: versatile, can hold, set, reset, toggle."],
  ["What does T flip-flop do?","Toggles output on T=1","Stores T","Inverts T","ANDs inputs",0,"T-FF: Q toggles when T=1 on clock edge."],
  ["What does SR flip-flop do?","S=1 set, R=1 reset, S=R=0 hold","Stores D","Toggles","Inverts",0,"SR-FF: S sets, R resets, S=R=1 forbidden."],
  ["What is the forbidden state of SR flip-flop?","S=1 and R=1 simultaneously","S=0 and R=0","S=1 and R=0","S=0 and R=1",0,"S=R=1 produces invalid output (both Q and Q' high)."],
  ["How many flip-flops are needed for 8 states?","3","2","4","8",0,"2^n ≥ 8, so n = 3 flip-flops."],
  ["How many flip-flops are needed for 5 states?","3","2","4","5",0,"2^n ≥ 5, so n = 3 (2^3 = 8 ≥ 5)."],
  ["How many flip-flops are needed for 16 states?","4","3","5","16",0,"2^4 = 16, so n = 4."],
  ["How many states can 4 flip-flops represent?","16","8","4","32",0,"2^4 = 16 states."],
  ["What is a counter?","State machine that cycles through states","Adder circuit","Comparator","Multiplexer",0,"Counters are a common type of state machine."],
  ["What is an up counter?","Counts 0, 1, 2, ..., max, 0, ...","Counts down only","Counts randomly","Stays at 0",0,"Up counter increments on each clock."],
  ["What is a down counter?","Counts max, max-1, ..., 0, max, ...","Counts up only","Counts randomly","Stays at max",0,"Down counter decrements on each clock."],
  ["What is an up/down counter?","Can count up or down based on control","Counts up only","Counts down only","Stays fixed",0,"Up/down counter: direction controlled by input."],
  ["What is a modulo-N counter?","Counts 0 to N-1 then wraps","Counts to N","Counts 0 to infinity","Counts down only",0,"Mod-N counter has N states (0 to N-1)."],
  ["What is a mod-10 counter?","Counts 0-9 (decade counter)","Counts 0-10","Counts 0-99","Counts 0-100",0,"Mod-10: 0,1,2,...,9,0,1,..."],
  ["What is a ripple counter?","Flip-flops cascade, carry ripples","All FFs clocked simultaneously","No clock","Synchronous counter",0,"Ripple (asynchronous) counter: each FF triggers the next."],
  ["What is a synchronous counter?","All flip-flops share same clock","Each FF triggers next","No clock","Ripple counter",0,"Synchronous counter: all FFs update simultaneously."],
  ["What is the advantage of synchronous counter?","No ripple delay","Simpler design","Fewer gates","Lower power",0,"Synchronous counters avoid cumulative propagation delay."],
  ["What is a ring counter?","Shift register with feedback","Binary counter","Ripple counter","Johnson counter",0,"Ring counter: Q of last FF feeds D of first."],
  ["How many states does an n-bit ring counter have?","n","2^n","n-1","2n",0,"Ring counter: n states (one-hot encoding)."],
  ["What is a Johnson counter?","Ring counter with inverted feedback","Binary counter","Ripple counter","Decade counter",0,"Johnson (twisted ring): inverted feedback doubles states."],
  ["How many states does an n-bit Johnson counter have?","2n","n","2^n","n²",0,"Johnson counter: 2n states."],
  ["What is a shift register?","Chain of flip-flops shifting data","Counter","Adder","Comparator",0,"Shift registers store and shift data bit-by-bit."],
  ["What is SISO shift register?","Serial In, Serial Out","Parallel In, Parallel Out","Serial In, Parallel Out","Parallel In, Serial Out",0,"SISO: data enters and exits one bit at a time."],
  ["What is SIPO shift register?","Serial In, Parallel Out","SISO","PISO","PIPO",0,"SIPO: serial input, read all bits in parallel."],
  ["What is PISO shift register?","Parallel In, Serial Out","SISO","SIPO","PIPO",0,"PISO: load all bits, shift out serially."],
  ["What is PIPO shift register?","Parallel In, Parallel Out","SISO","SIPO","PISO",0,"PIPO: parallel load and parallel read."],
  ["What is a finite state machine (FSM)?","State machine with finite number of states","State machine with infinite states","Analog state machine","No states",0,"FSM: finite states, deterministic transitions."],
  ["What is a deterministic FSM?","Each input has exactly one transition","Multiple transitions per input","Random transitions","No transitions",0,"Deterministic: one next state per (state, input)."],
  ["What is a nondeterministic FSM (NFA)?","Multiple possible transitions per input","One transition per input","No transitions","Random states",0,"NFA: can transition to multiple states simultaneously."],
  ["What is a Mealy output?","Associated with transitions","Associated with states","No output","Constant output",0,"Mealy outputs appear on transition arcs."],
  ["What is a Moore output?","Associated with states","Associated with transitions","No output","Input-dependent output",0,"Moore outputs appear inside state nodes."],
  ["Which machine type generally has fewer states?","Mealy","Moore","Same","Depends on input",0,"Mealy often needs fewer states (output on transitions)."],
  ["Which machine type is easier to design?","Moore (simpler output logic)","Mealy","Both equally","Neither",0,"Moore: output depends only on state, simpler logic."],
  ["What is a state encoding?","Assigning binary codes to states","Encoding inputs","Encoding outputs","Encoding transitions",0,"State encoding: binary, one-hot, Gray code."],
  ["What is one-hot encoding?","One bit per state","Binary encoding","Gray code","BCD encoding",0,"One-hot: n states use n flip-flops, one bit high at a time."],
  ["What is the advantage of one-hot encoding?","Simple next-state logic","Fewer flip-flops","Less power","Smaller area",0,"One-hot: simpler decode logic, but more FFs."],
];

// ===== INTERMEDIATE (50) =====
const intermediate = [
  ["What is state minimization?","Merging equivalent states","Adding more states","Removing inputs","Reducing outputs",0,"Equivalent states produce same outputs and transitions."],
  ["What are equivalent states?","States with same outputs and next states for all inputs","States with same name","States with same encoding","Adjacent states",0,"Two states are equivalent if they behave identically."],
  ["What is the state minimization algorithm?","Partition refinement","Binary search","Bubble sort","Dijkstra's",0,"Partition refinement merges equivalent states."],
  ["What is a partition in state minimization?","Group of states that may be equivalent","Group of inputs","Group of outputs","Group of transitions",0,"Partitions are iteratively refined to find equivalents."],
  ["What is state assignment?","Assigning binary codes to states","Assigning inputs","Assigning outputs","Assigning transitions",0,"State assignment affects circuit complexity."],
  ["What are common state assignment strategies?","Binary, Gray, one-hot, random","Sequential, parallel","Ascending, descending","Odd, even",0,"Different encodings optimize different metrics."],
  ["What is a Mealy-to-Moore conversion?","Adding states to move outputs from arcs to nodes","Removing states","Adding inputs","Removing outputs",0,"Mealy→Moore: split states so output depends only on state."],
  ["What is a Moore-to-Mealy conversion?","Moving outputs from states to transitions","Adding states","Removing transitions","Adding inputs",0,"Moore→Mealy: move output to incoming transition arc."],
  ["What is a sequence detector?","FSM that recognizes a specific input pattern","FSM that counts","FSM that adds","FSM that divides",0,"Sequence detectors find specific bit patterns."],
  ["How many states for a Mealy sequence detector for '101'?","4","3","5","2",0,"Mealy '101' detector: S0, S1, S2, S3 (found)."],
  ["How many states for a Moore sequence detector for '101'?","5","4","3","2",0,"Moore needs one extra state for output delay."],
  ["What is a Mealy sequence detector advantage?","Fewer states than Moore","More states","Faster clock","Less logic",0,"Mealy uses fewer states but output can glitch."],
  ["What is a glitch in Mealy machines?","Brief incorrect output during state transition","Permanent error","Clock error","Reset error",0,"Mealy output can change mid-transition (asynchronous)."],
  ["How to avoid Mealy glitches?","Register the output or use Moore machine","Add more states","Increase clock","Remove inputs",0,"Registered Mealy or Moore avoids glitches."],
  ["What is a traffic light controller?","FSM controlling light sequences","Analog circuit","Combinational logic","Counter only",0,"Traffic lights cycle: green→yellow→red→green."],
  ["How many states does a simple traffic light controller have?","4 (G, Y, R in two directions)","2","3","6",0,"Two directions: NS-green, NS-yellow, EW-green, EW-yellow."],
  ["What is a vending machine controller?","FSM accepting coins and dispensing products","Counter","Adder","Comparator",0,"Vending machines track credit and product selection."],
  ["What is an elevator controller?","FSM managing floor and door states","Counter","Timer","Comparator",0,"Elevator: states for idle, moving, door open/closed."],
  ["What is a deadlock state?","State with no exit transitions","Initial state","Final state","Error state",0,"Deadlock: machine stuck, cannot progress."],
  ["What is a livelock in an FSM?","Machine cycles without making progress","Machine is stuck","Machine resets","Machine stops",0,"Livelock: active but no useful work done."],
  ["What is a reachability analysis?","Finding all states reachable from initial","Counting states","Minimizing states","Encoding states",0,"Reachability: BFS/DFS from initial state."],
  ["What is an unreachable state?","State never entered from initial state","State with no inputs","State with no outputs","Final state",0,"Unreachable states can be removed."],
  ["What is a state transition table?","Maps (state, input) → (next state, output)","Maps inputs to outputs","Maps states to codes","Maps clocks to transitions",0,"Transition table fully specifies FSM behavior."],
  ["What is the next-state equation?","Boolean function for each flip-flop input","Clock equation","Output equation","Reset equation",0,"Next-state eq: D_i = f(current state, inputs)."],
  ["What is the output equation?","Boolean function for FSM outputs","Next-state function","Clock function","Reset function",0,"Output eq: Y = f(state) [Moore] or f(state, input) [Mealy]."],
  ["What is a D flip-flop input equation?","D = next-state function","D = current state","D = clock","D = output",0,"For D-FF: D input = desired next state."],
  ["What is a JK flip-flop input equation?","J and K derived from next-state table","D = next state","T = toggle","S = set",0,"JK: J=1 set, K=1 reset, J=K=1 toggle, J=K=0 hold."],
  ["What is a T flip-flop input equation?","T = 1 when state should change","T = 0 always","T = clock","T = output",0,"T-FF: T=1 toggles, T=0 holds."],
  ["What is excitation table?","Table showing FF inputs needed for each transition","Truth table","State table","K-map",0,"Excitation tables give required inputs for state changes."],
  ["What is the D-FF excitation table?","D = next state (always)","D = 0","D = 1","D = current state",0,"D-FF: D = Q(next), regardless of current."],
  ["What is the JK-FF excitation for Q→Q'?","J=1, K=1","J=0, K=0","J=1, K=0","J=0, K=1",0,"Toggle: J=K=1."],
  ["What is the JK-FF excitation for Q→Q (hold)?","J=0, K=0","J=1, K=1","J=1, K=0","J=0, K=1",0,"Hold: J=K=0."],
  ["What is the T-FF excitation for Q→Q'?","T=1","T=0","T=Q","T=Q'",0,"Toggle: T=1."],
  ["What is the T-FF excitation for Q→Q (hold)?","T=0","T=1","T=Q","T=Q'",0,"Hold: T=0."],
  ["What is a K-map for state machine design?","Minimizes next-state and output equations","Counts states","Encodes states","Tests states",0,"K-maps simplify Boolean expressions for FF inputs."],
  ["What is a binary counter with parallel load?","Counter that can be preset to any value","Counter that only counts up","Counter that only counts down","Ripple counter",0,"Parallel load: load arbitrary value, then count."],
  ["What is a self-starting counter?","Eventually reaches valid counting sequence from any state","Starts at 0","Starts at max","Never starts",0,"Self-starting: all unused states lead to valid states."],
  ["What is a non-self-starting counter?","May get stuck in unused states","Always starts correctly","Counts backwards","Never counts",0,"Non-self-starting: unused states may form deadlock cycles."],
  ["How do you make a counter self-starting?","Map unused states to valid states","Add more flip-flops","Remove flip-flops","Increase clock speed",0,"Design next-state logic to redirect unused states."],
  ["What is a Gray code counter?","Counter using Gray code encoding","Binary counter","One-hot counter","BCD counter",0,"Gray code: one bit changes per transition, no glitches."],
  ["What is the advantage of Gray code in state machines?","Only one bit changes per transition","Fewer states","Less power","Higher speed",0,"Single bit change avoids decoding glitches."],
  ["What is a clock divider?","Circuit that divides clock frequency","Amplifies clock","Generates clock","Buffers clock",0,"Clock divider: toggle FF divides by 2."],
  ["What division ratio does a single toggle FF give?","Divide by 2","Divide by 4","Divide by 8","Divide by 10",0,"One T-FF with T=1 divides clock by 2."],
  ["How many FFs for divide-by-16?","4","2","3","8",0,"2^4 = 16, so 4 toggle FFs."],
  ["What is a digital clock manager (DCM)?","PLL/DLL for clock synthesis and phase shifting","Counter","Divider","Buffer",0,"DCM: phase shifting, frequency synthesis, deskew."],
  ["What is clock domain crossing?","Transferring data between different clock domains","Clock division","Clock buffering","Clock generation",0,"CDC requires synchronizers to prevent metastability."],
  ["What is a two-flop synchronizer?","Two flip-flops in series for CDC","Two flip-flops in parallel","Two flip-flops with feedback","Single flip-flop",0,"Two-stage synchronizer reduces metastability probability."],
  ["What is the MTBF of a synchronizer?","Mean Time Between Failures from metastability","Maximum Time Before Failure","Minimum Time Between Fixes","Mean Toggle Bit Frequency",0,"MTBF depends on clock frequency, data rate, and FF parameters."],
  ["What is asynchronous reset?","Reset independent of clock","Reset synchronized with clock","No reset","Clock-dependent reset",0,"Async reset: immediate effect, but may cause metastability."],
  ["What is synchronous reset?","Reset only takes effect on clock edge","Reset is immediate","No reset needed","Reset is asynchronous",0,"Sync reset: safer, avoids reset deassertion metastability."],
  ["What is a debounce circuit?","Removes contact bounce from switches","Amplifies signal","Filters noise","Generates clock",0,"Debounce: FSM or timer ignores rapid transitions."],
  ["How many states does a simple debounce FSM have?","3 (wait, press, release)","2","4","5",0,"Debounce FSM: stable, transitioning, stable."],
  ["What is a one-pulse circuit?","Generates single pulse for button press","Generates continuous pulses","Counts pulses","Delays pulses",0,"One-pulse: edge detect + state prevents multiple triggers."],
  ["What is a sequence generator?","FSM that produces a specific output sequence","FSM that detects sequences","Counter","Comparator",0,"Sequence generators output predetermined bit patterns."],
];

// ===== ADVANCED (50) =====
const advanced = [
  ["What is a Huffman encoding for FSM design?","Minimal state assignment method","Compression algorithm","State encoding type","Gate-level optimization",0,"Huffman: minimal logic via state assignment heuristics."],
  ["What is the difference between Mealy and Moore delay?","Mealy: same-cycle output; Moore: next-cycle output","Moore: same-cycle","No difference","Mealy: delayed",0,"Mealy output appears in the same cycle as input."],
  ["What is a UML statechart?","Hierarchical state machine notation","Truth table","K-map","Timing diagram",0,"UML statecharts support nested/orthogonal states."],
  ["What is a hierarchical state machine?","States can contain sub-states","States are all flat","States have no hierarchy","States are parallel only",0,"HSM: nested states, shared transitions at parent level."],
  ["What is an orthogonal (concurrent) state machine?","Multiple independent state regions","Single state region","No states","Hierarchical states",0,"Orthogonal regions run concurrently and independently."],
  ["What is a history state in HSM?","Remembers last active sub-state","Initial state","Final state","Error state",0,"History pseudo-state restores previous sub-state on re-entry."],
  ["What is a guard condition on a transition?","Condition that must be true for transition","Clock condition","Reset condition","Output condition",0,"Guard: boolean expression on transition arc."],
  ["What is an action in a state machine?","Activity executed during transition or state","Input signal","Output signal","Clock signal",0,"Actions: entry, exit, transition, or internal actions."],
  ["What is a transition action vs state action?","Transition action: on arc; state action: in state","Both same","Transition action only","State action only",0,"Mealy-like: transition actions. Moore-like: state actions."],
  ["What is a Petri net?","Concurrent state machine with tokens","Sequential FSM","Truth table","K-map",0,"Petri nets model concurrency with places, transitions, tokens."],
  ["What is a marked place in a Petri net?","Place indicating completion","Initial place","Token-free place","Transition place",0,"Marked places represent final/accepting states."],
  ["What is a Timed Automaton?","State machine with clock constraints","State machine with no clock","Analog state machine","Digital counter",0,"Timed automata: transitions have time guards (real-time systems)."],
  ["What is a Buchi automaton?","Automaton accepting infinite sequences","Accepts finite sequences","No acceptance","Single state",0,"Buchi: accepts if some state visited infinitely often."],
  ["What is a regular expression equivalent to?","Finite automaton (DFA/NFA)","Pushdown automaton","Turing machine","Infinite state machine",0,"Regular expressions = regular languages = finite automata."],
  ["What is the pumping lemma for regular languages?","All regular languages can be 'pumped'","All languages are regular","No pumping needed","Infinite pumping",0,"Pumping lemma: used to prove non-regularity."],
  ["What is the Myhill-Nerode theorem?","Language is regular iff finite equivalence classes","All languages are regular","DFA minimization","State encoding",0,"Myhill-Nerode: regularity via distinguishable string pairs."],
  ["What is the difference between DFA and NFA?","NFA allows multiple transitions; DFA has one","DFA has multiple transitions","No difference","NFA is deterministic",0,"DFA: one transition per (state, input). NFA: zero or more."],
  ["What is epsilon (λ) transition in NFA?","Transition without consuming input","Transition consuming input","No transition","Error transition",0,"Epsilon transitions allow state changes without input."],
  ["What is the subset construction?","Converts NFA to DFA","Converts DFA to NFA","Minimizes DFA","Encodes states",0,"Subset construction: DFA states = sets of NFA states."],
  ["What is the worst-case DFA size from NFA with n states?","2^n","n","n²","n!",0,"Subset construction can produce up to 2^n DFA states."],
  ["What is Hopcroft's algorithm?","DFA minimization in O(n log n)","NFA to DFA","State encoding","DFA construction",0,"Hopcroft: partition-based DFA minimization."],
  ["What is Brzozowski's algorithm?","DFA minimization via reversal and determinization","DFA construction","NFA simulation","State encoding",0,"Brzozowski: reverse + determinize + reverse + determinize."],
  ["What is a pushdown automaton (PDA)?","Automaton with a stack","Automaton with no memory","DFA with output","NFA with output",0,"PDA recognizes context-free languages."],
  ["What is a Turing machine?","Automaton with infinite tape","DFA","NFA","PDA",0,"Turing machines recognize recursively enumerable languages."],
  ["What is the Church-Turing thesis?","Turing machines capture effective computation","All problems are decidable","All languages are regular","All machines are equivalent",0,"Church-Turing: TM = universal model of computation."],
  ["What is the halting problem?","Undecidable whether a TM halts","Always halts","Never halts","Sometimes halts",0,"Halting problem: proven undecidable by Turing."],
  ["What is a Mealy machine conversion to state diagram?","Outputs on transition arcs","Outputs in state nodes","No outputs","Outputs separate",0,"Mealy: output labels on arcs between states."],
  ["What is a Moore machine conversion to state diagram?","Outputs in state nodes","Outputs on arcs","No outputs","Outputs separate",0,"Moore: output labels inside state circles."],
  ["What is state encoding for FPGA optimization?","One-hot preferred for FPGAs","Binary preferred","Gray preferred","Random preferred",0,"FPGAs have many flip-flops, making one-hot efficient."],
  ["What is state encoding for ASIC optimization?","Binary or Gray preferred","One-hot preferred","Random","Sequential",0,"ASICs: minimize flip-flops, prefer compact encoding."],
  ["What is a redundant state?","State that can be merged with another","State with no inputs","State with no outputs","Final state",0,"Redundant states are equivalent and can be merged."],
  ["What is the implication chart method?","State minimization technique","State encoding method","State diagram method","State table method",0,"Implication chart: pairwise state equivalence testing."],
  ["What is a state graph traversal for verification?","Model checking all reachable states","Simulation only","Testing only","Formal proof only",0,"Model checking: exhaustively verify FSM properties."],
  ["What is SPIN model checker?","Tool for verifying FSM properties","Circuit simulator","State encoder","K-map tool",0,"SPIN: verifies LTL/never-claims on Promela models."],
  ["What is LTL (Linear Temporal Logic)?","Logic for expressing time-dependent properties","Logic for circuits","Logic for gates","Logic for states",0,"LTL: □ (always), ◇ (eventually), ○ (next), U (until)."],
  ["What is CTL (Computation Tree Logic)?","Logic for branching time properties","Linear time logic","No temporal logic","State logic",0,"CTL: A (all paths), E (exists path), G (globally), F (future)."],
  ["What is the difference between LTL and CTL?","LTL: linear time; CTL: branching time","No difference","LTL is stronger","CTL is weaker",0,"LTL: one path at a time. CTL: quantifies over paths."],
  ["What is a fairness constraint?","Condition that must hold infinitely often","Condition that holds once","No condition","Reset condition",0,"Fairness: e.g., 'request always eventually granted.'"],
  ["What is a deadlock-free FSM?","No state with no outgoing transitions","All states have inputs","All states have outputs","All states reachable",0,"Deadlock-free: every state has at least one valid transition."],
  ["What is a liveness property?","Something good eventually happens","Something bad never happens","System is stable","System is fast",0,"Liveness: 'eventually reach goal state' (progress)."],
  ["What is a safety property?","Something bad never happens","Something good eventually happens","System is fast","System is stable",0,"Safety: 'never enter error state' (invariance)."],
  ["What is a hazard-free FSM design?","No glitches in output or state","Fast FSM","Small FSM","Low-power FSM",0,"Hazard-free: Gray code + Moore outputs avoid glitches."],
  ["What is a clock-gated FSM?","Clock disabled for idle states to save power","Faster clock","More states","Fewer states",0,"Clock gating: disable FF clock when state is idle."],
  ["What is a power-aware state encoding?","Minimizes bit transitions between frequent states","Maximizes transitions","Random encoding","Binary encoding",0,"Power-aware: assign codes to minimize switching activity."],
  ["What is a scan chain in FSM testing?","Flip-flops chained for test access","Gate-level testing","Power testing","Timing testing",0,"Scan chain: serial shift in/out for testability (DFT)."],
  ["What is ATPG?","Automatic Test Pattern Generation","Automatic Timing Pattern Generator","Analog Test Power Generator","Automatic Transition Path Generator",0,"ATPG: generates test vectors for fault coverage."],
  ["What is stuck-at fault model?","Line stuck at 0 or 1","Line is floating","Line is delayed","Line is inverted",0,"Stuck-at-0/1: classic digital fault model for testing."],
  ["What is fault coverage?","Percentage of detectable faults covered by tests","Percentage of states","Percentage of transitions","Percentage of inputs",0,"Fault coverage = detected faults / total faults × 100%."],
  ["What is a BIST (Built-In Self-Test)?","On-chip test circuitry","External tester","Manual testing","Simulation only",0,"BIST: LFSR generates test patterns, MISR compresses responses."],
  ["What is an LFSR (Linear Feedback Shift Register)?","Pseudo-random sequence generator","Counter","Adder","Comparator",0,"LFSR: shift register with XOR feedback, used in BIST."],
  ["What is formal equivalence checking?","Proves two designs are functionally identical","Proves timing is met","Proves power is low","Proves area is minimal",0,"Equivalence checking: compares RTL vs gate-level netlist."],
];

module.exports = { basic, intermediate, advanced };
