INSERT INTO module_questions (module_id, level, question, options, correct_index, explanation, xp_reward) VALUES
('gate-puzzler','basic','What does a NOT gate do?',ARRAY['Inverts the input','Buffers the input','Adds two inputs','Multiplies inputs'],0,'A NOT gate outputs the inverse of its input.',10),
('gate-puzzler','basic','Which gate outputs 1 only when both inputs are 1?',ARRAY['AND','OR','XOR','NAND'],0,'AND requires both inputs high.',10),
('gate-puzzler','basic','How many inputs does a standard NOT gate have?',ARRAY['1','2','3','4'],0,'NOT is a single-input gate.',10),
('gate-puzzler','basic','What is the output of OR gate when both inputs are 0?',ARRAY['0','1','High impedance','Undefined'],0,'OR outputs 0 only when all inputs are 0.',10),
('gate-puzzler','basic','NAND gate is the combination of which two gates?',ARRAY['AND + NOT','OR + NOT','XOR + NOT','NOR + NOT'],0,'NAND is AND followed by NOT.',10),
('gate-puzzler','basic','Which gate outputs 0 only when both inputs are 1?',ARRAY['NAND','AND','OR','XOR'],0,'NAND outputs 0 only when all inputs are 1.',10),
('gate-puzzler','basic','What does XOR output when both inputs are the same?',ARRAY['0','1','High-Z','Depends on input'],0,'XOR outputs 0 when inputs are equal.',10),
('gate-puzzler','basic','How many input combinations does a 2-input truth table have?',ARRAY['4','2','8','16'],0,'2^2 = 4 combinations.',10),
('gate-puzzler','basic','Which symbol represents an AND gate?',ARRAY['D-shaped','Shield-shaped','Triangle','Oval'],0,'AND gates use a D-shaped symbol.',10),
('gate-puzzler','basic','What is the output of a NOR gate with inputs 1 and 0?',ARRAY['0','1','High-Z','Undefined'],0,'NOR outputs 0 if any input is 1.',10),
('gate-puzzler','basic','A buffer gate does what?',ARRAY['Passes input unchanged','Inverts input','ANDs inputs','ORs inputs'],0,'A buffer passes the signal through.',10),
('gate-puzzler','basic','Which gate is known as the universal gate?',ARRAY['NAND','XOR','OR','NOT'],0,'NAND can implement any logic function.',10),
('gate-puzzler','basic','What is the truth table output for AND(1,1)?',ARRAY['1','0','Both','Neither'],0,'AND(1,1) = 1.',10),
('gate-puzzler','basic','How many rows in a 3-input truth table?',ARRAY['8','4','16','32'],0,'2^3 = 8 rows.',10),
('gate-puzzler','basic','Which gate gives 1 when inputs differ?',ARRAY['XOR','AND','OR','NAND'],0,'XOR outputs 1 when inputs differ.',10),
('gate-puzzler','basic','What is De Morgan''s first law?',ARRAY['NOT(A AND B) = NOT A OR NOT B','A AND B = A OR B','NOT(A OR B) = A AND B','A XOR B = A NAND B'],0,'De Morgan: complement of AND equals OR of complements.',10),
('gate-puzzler','basic','Which gate has a bubble at its output?',ARRAY['NAND','AND','OR','XOR'],0,'The bubble indicates inversion.',10),
('gate-puzzler','basic','What does the bubble on a gate symbol represent?',ARRAY['Inversion','Amplification','Buffering','Ground'],0,'A bubble means logical NOT.',10),
('gate-puzzler','basic','Which gate is OR followed by NOT?',ARRAY['NOR','NAND','XOR','AND'],0,'NOR = OR + NOT.',10),
('gate-puzzler','basic','What is the output of NAND(0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'NAND(0,0) = NOT(0 AND 0) = NOT(0) = 1.',10),
('gate-puzzler','basic','How many transistors does a basic CMOS NOT gate use?',ARRAY['2','4','6','8'],0,'CMOS NOT uses one PMOS and one NMOS.',10),
('gate-puzzler','basic','Which logic family uses complementary pairs?',ARRAY['CMOS','TTL','ECL','DTL'],0,'CMOS uses complementary MOSFET pairs.',10),
('gate-puzzler','basic','What is the output of NOT(1)?',ARRAY['0','1','High-Z','Undefined'],0,'NOT(1) = 0.',10),
('gate-puzzler','basic','Which gate can be used to build any other gate?',ARRAY['NAND','XOR','OR','Buffer'],0,'NAND is functionally complete.',10),
('gate-puzzler','basic','What is the Boolean expression for OR gate?',ARRAY['A + B','A · B','A ⊕ B','A · B'''],0,'OR is represented by +.',10),
('gate-puzzler','basic','What is the Boolean expression for AND gate?',ARRAY['A · B','A + B','A ⊕ B','A'''],0,'AND is represented by ·.',10),
('gate-puzzler','basic','Which gate outputs 1 when at least one input is 1?',ARRAY['OR','AND','NAND','NOR'],0,'OR outputs 1 if any input is high.',10),
('gate-puzzler','basic','What is the dual of AND?',ARRAY['OR','NOT','XOR','NAND'],0,'The dual of AND is OR.',10),
('gate-puzzler','basic','In Boolean algebra, what is A + 1?',ARRAY['1','A','0','A'''],0,'A OR 1 = 1 (absorption).',10),
('gate-puzzler','basic','In Boolean algebra, what is A · 0?',ARRAY['0','A','1','A'''],0,'A AND 0 = 0.',10),
('gate-puzzler','basic','In Boolean algebra, what is A + 0?',ARRAY['A','0','1','A'''],0,'A OR 0 = A (identity).',10),
('gate-puzzler','basic','In Boolean algebra, what is A · 1?',ARRAY['A','0','1','A'''],0,'A AND 1 = A (identity).',10),
('gate-puzzler','basic','What is A + A in Boolean algebra?',ARRAY['A','0','1','A'''],0,'A OR A = A (idempotent).',10),
('gate-puzzler','basic','What is A · A in Boolean algebra?',ARRAY['A','0','1','A'''],0,'A AND A = A (idempotent).',10),
('gate-puzzler','basic','What is NOT(NOT A)?',ARRAY['A','0','1','A'''],0,'Double negation cancels out.',10),
('gate-puzzler','basic','Which gate has a truth table with only one 0 output?',ARRAY['NAND','AND','OR','XOR'],0,'NAND has one 0 row (both inputs 1).',10),
('gate-puzzler','basic','Which gate has a truth table with only one 1 output?',ARRAY['AND','NAND','NOR','XOR'],0,'AND has one 1 row (both inputs 1).',10),
('gate-puzzler','basic','What is the output of XOR(1,0)?',ARRAY['1','0','High-Z','Undefined'],0,'XOR(1,0) = 1.',10),
('gate-puzzler','basic','What is the output of XNOR(1,1)?',ARRAY['1','0','High-Z','Undefined'],0,'XNOR outputs 1 when inputs are equal.',10),
('gate-puzzler','basic','How many 2-input gates are needed to build a NAND from NOR gates?',ARRAY['4','2','3','1'],0,'NAND from NOR requires 4 NOR gates.',10),
('gate-puzzler','basic','What does a logic 1 typically represent?',ARRAY['HIGH/True','LOW/False','Ground','High impedance'],0,'Logic 1 = HIGH = True.',10),
('gate-puzzler','basic','What does a logic 0 typically represent?',ARRAY['LOW/False','HIGH/True','VCC','High impedance'],0,'Logic 0 = LOW = False.',10),
('gate-puzzler','basic','Which gate is used for parity checking?',ARRAY['XOR','AND','OR','NAND'],0,'XOR is used for parity generation/checking.',10),
('gate-puzzler','basic','What is the output of NOR(0,0)?',ARRAY['1','0','High-Z','Undefined'],0,'NOR(0,0) = NOT(0 OR 0) = NOT(0) = 1.',10),
('gate-puzzler','basic','Which gate''s output is the complement of XOR?',ARRAY['XNOR','NAND','NOR','AND'],0,'XNOR is the complement of XOR.',10),
('gate-puzzler','basic','What is A · A'' in Boolean algebra?',ARRAY['0','1','A','A'''],0,'A AND NOT A = 0 (complementarity).',10),
('gate-puzzler','basic','What is A + A'' in Boolean algebra?',ARRAY['1','0','A','A'''],0,'A OR NOT A = 1 (complementarity).',10),
('gate-puzzler','basic','Which two gates are called universal gates?',ARRAY['NAND and NOR','AND and OR','XOR and XNOR','NOT and Buffer'],0,'Both NAND and NOR are functionally complete.',10),
('gate-puzzler','basic','What is the output of AND(1,0)?',ARRAY['0','1','High-Z','Undefined'],0,'AND(1,0) = 0.',10),
('gate-puzzler','basic','What is the output of OR(1,0)?',ARRAY['1','0','High-Z','Undefined'],0,'OR(1,0) = 1.',10),
('gate-puzzler','intermediate','Simplify: A + AB',ARRAY['A','B','A+B','AB'],0,'A + AB = A(1+B) = A (absorption).',15),
('gate-puzzler','intermediate','Simplify: A(A+B)',ARRAY['A','B','AB','A+B'],0,'A(A+B) = AA + AB = A + AB = A.',15),
('gate-puzzler','intermediate','Simplify: (A+B)(A+B'')',ARRAY['A','B','A+B','AB'],0,'(A+B)(A+B'') = A + BB'' = A.',15),
('gate-puzzler','intermediate','What is the consensus theorem?',ARRAY['AB + A''C + BC = AB + A''C','AB + AC = AB','A+B = A','AB = A'],0,'Consensus: AB + A''C + BC = AB + A''C.',15),
('gate-puzzler','intermediate','Simplify: AB + AB''',ARRAY['A','B','A+B','0'],0,'AB + AB'' = A(B+B'') = A.',15),
('gate-puzzler','intermediate','How many minterms does a 3-variable function have?',ARRAY['8','4','16','6'],0,'2^3 = 8 minterms.',15),
('gate-puzzler','intermediate','How many maxterms does a 4-variable function have?',ARRAY['16','8','4','32'],0,'2^4 = 16 maxterms.',15),
('gate-puzzler','intermediate','What is the minterm for A=1, B=0, C=1?',ARRAY['m5','m2','m7','m3'],0,'101 binary = 5, so m5.',15),
('gate-puzzler','intermediate','What is the maxterm for A=0, B=1, C=0?',ARRAY['M2','M5','M4','M1'],0,'010 binary = 2, so M2.',15),
('gate-puzzler','intermediate','How many cells in a 4-variable K-map?',ARRAY['16','8','4','32'],0,'2^4 = 16 cells.',15),
('gate-puzzler','intermediate','In a K-map, adjacent cells differ by how many variables?',ARRAY['1','2','3','0'],0,'Adjacent cells differ by exactly one variable.',15),
('gate-puzzler','intermediate','What is the minimum number of variables for a K-map to be useful?',ARRAY['2','1','3','4'],0,'K-maps work for 2-6 variables.',15),
('gate-puzzler','intermediate','What does SOP stand for?',ARRAY['Sum of Products','Set of Pairs','Standard Operating Procedure','Series of Products'],0,'SOP = Sum of Products.',15),
('gate-puzzler','intermediate','What does POS stand for?',ARRAY['Product of Sums','Position','Post-Operation Set','Pair of Sums'],0,'POS = Product of Sums.',15),
('gate-puzzler','intermediate','Which is the canonical form for minterms?',ARRAY['SOP','POS','Both','Neither'],0,'Minterms are expressed in SOP form.',15),
('gate-puzzler','intermediate','Which is the canonical form for maxterms?',ARRAY['POS','SOP','Both','Neither'],0,'Maxterms are expressed in POS form.',15),
('gate-puzzler','intermediate','What is a hazard in combinational logic?',ARRAY['A momentary false output','A permanent error','A short circuit','A power fault'],0,'Hazards cause brief glitches during transitions.',15),
('gate-puzzler','intermediate','What causes a static-1 hazard?',ARRAY['Single variable change causing a 1→0→1 glitch','Two variables changing','Clock skew','Power noise'],0,'A single input change can cause a brief 0 glitch.',15),
('gate-puzzler','intermediate','How do you eliminate a static hazard?',ARRAY['Add redundant consensus terms','Add more gates','Increase voltage','Add a clock'],0,'Consensus terms cover the hazard gap.',15),
('gate-puzzler','intermediate','What is a multiplexer?',ARRAY['A data selector','A data distributor','A counter','A register'],0,'A MUX selects one of many inputs.',15),
('gate-puzzler','intermediate','How many select lines does a 16:1 MUX need?',ARRAY['4','3','2','5'],0,'2^4 = 16 inputs need 4 select lines.',15),
('gate-puzzler','intermediate','How many inputs does a 4:1 MUX have?',ARRAY['4','2','8','16'],0,'4:1 means 4 data inputs.',15),
('gate-puzzler','intermediate','What is a demultiplexer?',ARRAY['Routes one input to many outputs','Combines many inputs','Counts pulses','Stores data'],0,'A DEMUX distributes one input to selected output.',15),
('gate-puzzler','intermediate','How many output lines does a 3-to-8 decoder have?',ARRAY['8','3','5','16'],0,'3 inputs decode to 8 outputs.',15),
('gate-puzzler','intermediate','What is an encoder?',ARRAY['Converts many inputs to fewer output lines','Converts few inputs to many','Amplifies signals','Buffers data'],0,'Encoder = opposite of decoder.',15),
('gate-puzzler','intermediate','How many output lines does an 8-to-3 priority encoder have?',ARRAY['3','8','5','4'],0,'8 inputs encode to 3-bit output.',15),
('gate-puzzler','intermediate','What does a priority encoder do?',ARRAY['Outputs the highest-priority active input','Outputs all active inputs','Counts inputs','Buffers data'],0,'Priority encoders handle multiple active inputs.',15),
('gate-puzzler','intermediate','What is a half adder?',ARRAY['Adds 2 bits, outputs sum and carry','Adds 4 bits','Adds 2 numbers','Subtracts bits'],0,'Half adder: 2 inputs, sum + carry outputs.',15),
('gate-puzzler','intermediate','What is a full adder?',ARRAY['Adds 3 bits including carry-in','Adds 2 bits','Adds 4 bits','Adds with overflow'],0,'Full adder includes carry-in.',15),
('gate-puzzler','intermediate','How many full adders are needed for a 4-bit ripple carry adder?',ARRAY['4','3','2','8'],0,'One per bit position.',15),
('gate-puzzler','intermediate','What is the main disadvantage of ripple carry?',ARRAY['Propagation delay','Power consumption','Area','Cost'],0,'Carry ripples through each stage sequentially.',15),
('gate-puzzler','intermediate','Which adder is fastest for large bit widths?',ARRAY['Carry-lookahead','Ripple carry','Serial adder','Half adder'],0,'CLA computes carries in advance.',15),
('gate-puzzler','intermediate','What does a comparator circuit do?',ARRAY['Compares two binary numbers','Compares voltages','Compares frequencies','Compares currents'],0,'Comparators output equality/inequality.',15),
('gate-puzzler','intermediate','How many outputs does a 4-bit magnitude comparator have?',ARRAY['3','2','4','1'],0,'A>B, A<B, A=B outputs.',15),
('gate-puzzler','intermediate','What is a parity generator?',ARRAY['Adds a parity bit for error detection','Generates clock signals','Generates random numbers','Generates addresses'],0,'Parity bits detect single-bit errors.',15),
('gate-puzzler','intermediate','What is even parity?',ARRAY['Total number of 1s is even','Total 1s is odd','All bits are 1','All bits are 0'],0,'Even parity means even count of 1s.',15),
('gate-puzzler','intermediate','What is odd parity?',ARRAY['Total number of 1s is odd','Total 1s is even','Half are 1','None are 1'],0,'Odd parity means odd count of 1s.',15),
('gate-puzzler','intermediate','Which gate is used in a parity checker?',ARRAY['XOR','AND','OR','NAND'],0,'XOR toggles for each 1, giving parity.',15),
('gate-puzzler','intermediate','What is a BCD to 7-segment decoder?',ARRAY['Converts BCD to segment signals','Converts binary to BCD','Converts hex to decimal','Converts analog to digital'],0,'Drives 7-segment displays from BCD input.',15),
('gate-puzzler','intermediate','How many segment outputs does a 7-segment decoder have?',ARRAY['7','4','8','10'],0,'7 segments: a-g.',15),
('gate-puzzler','intermediate','What is a tristate buffer?',ARRAY['Buffer with high-impedance state','Buffer with 3 inputs','Buffer with 3 outputs','Triple buffer'],0,'Tristate adds a high-Z (disable) state.',15),
('gate-puzzler','intermediate','What is the purpose of tristate buffers on a bus?',ARRAY['Allow multiple drivers to share a bus','Increase speed','Reduce power','Add inversion'],0,'Only one driver is active at a time.',15),
('gate-puzzler','intermediate','What is an open-collector output?',ARRAY['Output that can sink but not source current','Output with 3 states','Output with amplification','Output with inversion'],0,'Open-collector needs a pull-up resistor.',15),
('gate-puzzler','intermediate','What is wired-OR using open-collector?',ARRAY['Multiple open-collector outputs share a pull-up','OR gate with wires','Wired connection','Bus arbitration'],0,'Active-low outputs on shared line act as NOR.',15),
('gate-puzzler','intermediate','What does a Schmitt trigger do?',ARRAY['Provides hysteresis for noise immunity','Triggers on clock','Amplifies signals','Buffers data'],0,'Hysteresis prevents oscillation near threshold.',15),
('gate-puzzler','intermediate','What is the difference between latch and flip-flop?',ARRAY['Flip-flop is edge-triggered, latch is level-sensitive','Latch is faster','Flip-flop uses less power','No difference'],0,'Latches are transparent when enabled; FFs sample on edge.',15),
('gate-puzzler','intermediate','What is a setup time?',ARRAY['Time data must be stable before clock edge','Time after clock','Clock period','Propagation delay'],0,'Setup time ensures correct sampling.',15),
('gate-puzzler','intermediate','What is hold time?',ARRAY['Time data must be stable after clock edge','Time before clock','Clock high duration','Reset time'],0,'Hold time ensures data is captured correctly.',15),
('gate-puzzler','intermediate','What is metastability?',ARRAY['Flip-flop output is unstable between 0 and 1','Flip-flop is reset','Flip-flop is stuck at 1','Flip-flop is too fast'],0,'Caused by setup/hold violation.',15),
('gate-puzzler','intermediate','How do you reduce metastability?',ARRAY['Use synchronizer flip-flops','Increase clock speed','Add more gates','Reduce voltage'],0,'Two-stage synchronizers reduce failure rate.',15),
('gate-puzzler','advanced','Prove that NAND is functionally complete',ARRAY['NAND can build NOT, AND, OR','NAND is fast','NAND uses few transistors','NAND is cheap'],0,'NOT: NAND(A,A); AND: NOT(NAND(A,B)); OR: NAND(NOT A, NOT B).',20),
('gate-puzzler','advanced','Implement XOR using only NAND gates. How many NAND gates are needed?',ARRAY['4','2','3','5'],0,'XOR = NAND(A,NAND(A,B)) XOR NAND(B,NAND(A,B)) — 4 NANDs.',20),
('gate-puzzler','advanced','Implement a 2:1 MUX using only NAND. How many NAND gates?',ARRAY['4','3','2','5'],0,'MUX: Y = AS + B S'' needs 4 NAND gates.',20),
('gate-puzzler','advanced','What is the minimal SOP for F(A,B,C) = Σm(0,1,2,5,6,7)?',ARRAY['A''C'' + AB + BC'' + B''C','A + B + C','ABC + A''B''C''','A''B'' + AB'],0,'K-map minimization yields A''C'' + AB + BC'' + B''C.',20),
('gate-puzzler','advanced','What is the minimal POS for F(A,B,C) = Σm(0,1,2,5,6,7)?',ARRAY['(A+B''+C)(A''+B+C'')','(A+B+C)(A+B''+C'')','(A''+B''+C)(A+B+C)','(A+B)(B+C)'],0,'Group zeros in K-map for POS form.',20),
('gate-puzzler','advanced','Design a 4-bit carry-lookahead adder. What is C4 in terms of G and P?',ARRAY['G3 + P3·G2 + P3·P2·G1 + P3·P2·P1·G0','C0 + G3','P3·G3','G3·P2'],0,'CLA carry: C4 = G3 + P3G2 + P3P2G1 + P3P2P1G0.',20),
('gate-puzzler','advanced','What is the group generate G for a 4-bit CLA block?',ARRAY['G3 + P3G2 + P3P2G1 + P3P2P1G0','G0+G1+G2+G3','P0P1P2P3','G3P3'],0,'Group generate combines individual generates.',20),
('gate-puzzler','advanced','What is the group propagate P for a 4-bit CLA block?',ARRAY['P3·P2·P1·P0','P0+P1+P2+P3','G0G1G2G3','P3+P0'],0,'Group propagate = AND of all individual propagates.',20),
('gate-puzzler','advanced','How many gate delays does a 4-bit CLA adder have?',ARRAY['2 levels of logic','4 levels','8 levels','16 levels'],0,'CLA carry is computed in 2 gate levels.',20),
('gate-puzzler','advanced','What is the Quine-McCluskey method used for?',ARRAY['Minimizing Boolean functions','Designing counters','Testing circuits','Simulating gates'],0,'Tabular method for Boolean minimization.',20),
('gate-puzzler','advanced','What is a prime implicant?',ARRAY['An implicant that cannot be covered by a larger one','The largest minterm','The smallest maxterm','Any implicant'],0,'Prime implicants are maximal groups in K-map.',20),
('gate-puzzler','advanced','What is an essential prime implicant?',ARRAY['A prime implicant covering a minterm no other PI covers','Any prime implicant','The largest PI','The smallest PI'],0,'Essential PIs must be included in the minimal form.',20),
('gate-puzzler','advanced','How many prime implicants can a 4-variable function have at most?',ARRAY['8','4','16','32'],0,'Maximum 2^(n-1) = 8 for n=4.',20),
('gate-puzzler','advanced','What is a don''t-care condition in K-maps?',ARRAY['A combination that can be 0 or 1','An error condition','A forbidden state','A reset state'],0,'Don''t-cares help simplify logic.',20),
('gate-puzzler','advanced','What are Petrick''s method and iterated consensus used for?',ARRAY['Finding minimal covers of prime implicants','Designing adders','Testing circuits','Clock generation'],0,'Petrick''s method finds all minimal SOP covers.',20),
('gate-puzzler','advanced','Design a 3:8 decoder using two 2:4 decoders. What additional gate is needed?',ARRAY['1 AND gate for enable','1 OR gate','1 NOT gate','1 XOR gate'],0,'The MSB selects which 2:4 decoder is active.',20),
('gate-puzzler','advanced','How many 2:4 decoders are needed to build a 4:16 decoder?',ARRAY['5','2','3','4'],0,'Four for the outputs plus one for enable selection.',20),
('gate-puzzler','advanced','Implement F = A''B'' + AB using a 2:1 MUX. What connects to the select line?',ARRAY['A','B','A''','Ground'],0,'With A on select: I0 = B'', I1 = B gives F = A''B'' + AB.',20),
('gate-puzzler','advanced','How many 4:1 MUXes are needed to implement a 3-variable function?',ARRAY['1','2','3','4'],0,'One 4:1 MUX with 2 variables on select lines suffices.',20),
('gate-puzzler','advanced','What is the Shannon expansion theorem?',ARRAY['F = S·F(1) + S''·F(0)','F = A + B','F = AB','F = A⊕B'],0,'Shannon expansion decomposes functions around a variable.',20),
('gate-puzzler','advanced','What is a transmission gate?',ARRAY['Parallel NMOS and PMOS passing signals in both directions','A series switch','A buffer','An inverter'],0,'TG = NMOS || PMOS, bidirectional switch.',20),
('gate-puzzler','advanced','How do you build a D latch using transmission gates?',ARRAY['2 TGs + inverter feedback','4 NAND gates','6 NOR gates','1 multiplexer'],0,'TG-based latches are compact and fast.',20),
('gate-puzzler','advanced','What is the difference between static and dynamic CMOS logic?',ARRAY['Static uses pull-up/pull-down networks; dynamic uses clocks','Static is faster','Dynamic uses less area','No difference'],0,'Dynamic logic uses clocked evaluation; static is always on.',20),
('gate-puzzler','advanced','What is domino logic?',ARRAY['Dynamic CMOS with a static inverter per stage','Static CMOS variant','Clocked latch','Bipolar logic'],0,'Domino cascades dynamic stages with inverters.',20),
('gate-puzzler','advanced','What is the main advantage of domino logic?',ARRAY['High speed and compact area','Low power','High noise margin','Easy to design'],0,'Domino logic is faster and smaller than static CMOS.',20),
('gate-puzzler','advanced','What is the main disadvantage of domino logic?',ARRAY['Charge leakage and clock overhead','Slow speed','Large area','Low noise margin'],0,'Dynamic nodes leak charge between clock phases.',20),
('gate-puzzler','advanced','What is NORA logic?',ARRAY['No Race Conditions dynamic logic','Static CMOS','Bipolar logic','ECL logic'],0,'NORA uses alternating n-blocks and p-blocks to avoid races.',20),
('gate-puzzler','advanced','What is the difference between ripple-carry and carry-skip adders?',ARRAY['Carry-skip bypasses carry through groups','Carry-skip is slower','Ripple is faster','No difference'],0,'Carry-skip adds bypass logic for faster carry propagation.',20),
('gate-puzzler','advanced','What is a carry-select adder?',ARRAY['Precomputes both carry=0 and carry=1, selects later','Adds in parallel','Uses CLA only','Is a multiplier'],0,'CSA precomputes both cases and muxes the result.',20),
('gate-puzzler','advanced','What is a Wallace tree multiplier?',ARRAY['Parallel multiplier using carry-save adders','Sequential multiplier','Shift-add multiplier','Array multiplier'],0,'Wallace tree compresses partial products in parallel.',20),
('gate-puzzler','advanced','What is a Booth multiplier?',ARRAY['Encodes multipliers to reduce partial products','Uses Wallace tree','Is an adder','Is a divider'],0,'Booth encoding reduces the number of partial products.',20),
('gate-puzzler','advanced','What is the advantage of radix-4 Booth encoding?',ARRAY['Halves the number of partial products','Doubles speed','Reduces power','Increases area'],0,'Radix-4 Booth processes 2 bits at a time.',20),
('gate-puzzler','advanced','What is a barrel shifter?',ARRAY['Combinational shifter that shifts any amount in one cycle','Sequential shifter','Single-bit shifter','Rotate-only circuit'],0,'Barrel shifters use a crossbar of multiplexers.',20),
('gate-puzzler','advanced','How many muxes does an 8-bit barrel shifter use?',ARRAY['8','4','16','2'],0,'One 8:1 MUX per output bit = 8 muxes.',20),
('gate-puzzler','advanced','What is an ALU?',ARRAY['Arithmetic Logic Unit performing multiple operations','Adder only','Multiplier','Comparator'],0,'ALU performs arithmetic and logic operations.',20),
('gate-puzzler','advanced','How many select lines does a 16-operation ALU need?',ARRAY['4','3','2','5'],0,'2^4 = 16 operations.',20),
('gate-puzzler','advanced','What is the difference between structural and behavioral HDL?',ARRAY['Structural describes gate-level; behavioral describes function','Structural is faster','Behavioral uses more area','No difference'],0,'Structural = netlist; behavioral = algorithm.',20),
('gate-puzzler','advanced','What is gate-level netlist?',ARRAY['List of gates and their interconnections','RTL code','Test bench','Timing report'],0,'Gate-level netlist is post-synthesis.',20),
('gate-puzzler','advanced','What is the difference between blocking and non-blocking assignments in Verilog?',ARRAY['Blocking (=) executes in order; non-blocking (<=) schedules simultaneously','Blocking is faster','Non-blocking is slower','No difference'],0,'Use non-blocking for sequential, blocking for combinational.',20),
('gate-puzzler','advanced','What is a testbench in HDL?',ARRAY['Code that applies stimulus and checks outputs','Synthesis tool','Timing analyzer','Place and route tool'],0,'Testbenches verify design correctness.',20),
('gate-puzzler','advanced','What is assertion-based verification?',ARRAY['Checking design properties at runtime','Code coverage','Gate-level simulation','Power analysis'],0,'Assertions check temporal properties automatically.',20),
('gate-puzzler','advanced','What is formal verification?',ARRAY['Mathematically proves design equivalence','Simulation-based check','Visual inspection','Manual review'],0,'Formal verification proves two designs are equivalent.',20),
('gate-puzzler','advanced','What is STA?',ARRAY['Static Timing Analysis','Sequential Timing Analyzer','Standard Test Architecture','Static Test Analyzer'],0,'STA checks all timing paths without simulation.',20),
('gate-puzzler','advanced','What is the critical path in a circuit?',ARRAY['Longest delay path limiting clock frequency','Shortest path','Power supply path','Reset path'],0,'Critical path determines max operating frequency.',20),
('gate-puzzler','advanced','What is slack in timing analysis?',ARRAY['Difference between required and actual arrival time','Extra gates','Unused inputs','Clock period'],0,'Positive slack = meets timing; negative = violates.',20),
('gate-puzzler','advanced','What is clock skew?',ARRAY['Difference in clock arrival times at different FFs','Clock frequency','Clock duty cycle','Clock jitter'],0,'Skew can help or hurt timing depending on direction.',20),
('gate-puzzler','advanced','What is useful skew?',ARRAY['Intentionally delaying clock to relax setup constraints','Accidental skew','Clock jitter','Clock drift'],0,'Useful skew borrows time from next stage.',20),
('gate-puzzler','advanced','What is power dissipation in CMOS?',ARRAY['Dynamic (switching) + static (leakage) power','Dynamic only','Static only','Short-circuit only'],0,'P = P_dynamic + P_leakage + P_short_circuit.',20),
('gate-puzzler','advanced','What is the formula for dynamic power?',ARRAY['P = CV²f','P = IR','P = V²/R','P = VI'],0,'Dynamic power = capacitance × voltage² × frequency.',20),
('gate-puzzler','advanced','What is clock gating for?',ARRAY['Reducing dynamic power by disabling clocks to idle blocks','Increasing speed','Adding latency','Improving noise margin'],0,'Clock gating saves power by stopping unnecessary switching.',20);
